# -*- coding: utf-8 -*-
# Pagine tipologie di stand (uso: python3 build_tipi.py)
from nuove_common import *
BASE_REL=[("Allestimenti fieristici",PILLAR),("Calendario fiere 2026–2027",CAL),("Quanto costa uno stand","/quanto-costa-uno-stand-fieristico/"),("Montaggio stand","/montaggio-stand-fieristici/")]
def T(P,title,desc,ey,h1,lead,secs,qa,offers,stype,rel,ogd):
    m=hero(ey,h1,lead,"Richiedi un preventivo","#richiesta","Scopri di più","#cosa")
    for s in secs: m+=s
    name=strip_tags(h1).rstrip('.').split(':')[0]
    node=svc(P,name,stype,ogd,offers)
    pagina(P,title,desc,f"{name} — Danova Tech",ogd,crumbs(name),m,qa,[node],rel+BASE_REL+TIPI_LINKS)
    print(len(title),len(desc),P)

# ---------------- PREALLESTITI
T("/stand-preallestiti/","Stand preallestiti per fiere: chiavi in mano | Danova Tech",
 "Stand fieristici preallestiti a noleggio: pareti, moquette, luci, insegna e arredi, personalizzati con la tua grafica e montati in fiera. Ideali per la prima fiera e per spazi piccoli.",
 "Stand preallestiti",'Stand preallestiti: <span class="grad">pronti in fiera</span>, con la tua immagine.',
 "Lo stand preallestito è la soluzione più rapida per esporre: pareti, moquette, illuminazione, insegna e arredi base, a noleggio, montati nel tuo spazio prima dell'apertura. Noi lo rendiamo tuo con grafiche, arredi e qualche dettaglio che fa la differenza rispetto ai pacchetti standard.",
 [cards("cosa","Cosa comprende uno stand preallestito","Il pacchetto base si può arricchire voce per voce, senza passare a uno stand su misura.",
   [("Pareti e struttura","Pannelli bianchi o colorati su telaio modulare, alti di solito 2,5–3 metri, con eventuale ripostiglio chiuso."),
    ("Moquette","Pavimentazione in moquette nel colore scelto, con eventuale pedana per nascondere i cavi."),
    ("Illuminazione","Faretti o bracci luce sulle pareti e quadro elettrico, con dichiarazione di conformità."),
    ("Insegna","Fascione frontale con nome e logo, anche retroilluminato."),
    ("Arredi base","Banco reception, tavolo e sedie, mensole, cestino, appendiabiti."),
    ("Grafica personalizzata","Pannelli stampati o tessuto teso al posto delle pareti bianche: lo stand diventa riconoscibile.")]),
  testo("quando","Quando conviene lo stand preallestito",None,
   ["Il preallestito è la scelta giusta per la prima fiera, per spazi piccoli in linea o ad angolo, per chi deve decidere in fretta o vuole tenere sotto controllo il budget. Si noleggia, non si conserva in magazzino, non richiede progettazione lunga.",
    "Molti organizzatori offrono un proprio pacchetto preallestito: è comodo, ma tutti gli stand del padiglione si somigliano. Con il nostro servizio partiamo dalla stessa logica ma personalizziamo grafica, arredi e luci, e se cresci possiamo trasformarlo in uno <a href=\"/stand-modulari/\">stand modulare</a> riutilizzabile."],
   [("Tempi rapidi.","Si organizza anche a poche settimane dalla fiera."),("Costo prevedibile.","Pacchetto chiaro, extra voce per voce."),
    ("Nessun magazzino.","A fine fiera smontiamo e ritiriamo tutto."),("Personalizzabile.","Grafica, arredi, luci, schermi.")])],
 [("Quanto costa uno stand preallestito?","Dipende da metratura, arredi e grafiche. È la soluzione più economica per esporre; ti facciamo un preventivo voce per voce sul tuo spazio."),
  ("Che differenza c'è con il preallestito dell'organizzatore?","Il principio è lo stesso, ma noi personalizziamo grafica, arredi e illuminazione e seguiamo tutto con un unico referente, anche nelle fiere successive."),
  ("Si può avere un preallestito a isola o ad angolo?","Sì, la struttura si adatta a spazi in linea, ad angolo, a penisola e a isola."),
  ("In quanto tempo si organizza?","Anche in poche settimane: il preallestito è la soluzione ideale per le richieste urgenti.")],
 ["Stand preallestiti a noleggio","Grafica personalizzata per stand preallestiti","Arredi e illuminazione","Montaggio e smontaggio in fiera"],"Noleggio di stand fieristici preallestiti",
 [("Noleggio stand","/noleggio-stand-fieristici/"),("Stand modulari","/stand-modulari/")],
 "Stand preallestiti a noleggio con pareti, moquette, luci, insegna e arredi, personalizzati con la tua grafica e montati in fiera.")

# ---------------- ISOLA
T("/stand-a-isola/","Stand a isola: progetto e allestimento | Danova Tech",
 "Stand fieristici a isola, aperti su quattro lati: progetto 3D a 360°, strutture sospese, magazzino centrale, sale riunioni e montaggio in fiera.",
 "Stand a isola",'Stand a isola: <span class="grad">visibili da ogni lato</span> del padiglione.',
 "Lo stand a isola è aperto su quattro lati e si vede da tutti i corridoi: è la forma più visibile e più impegnativa da progettare, perché non ha pareti di confine a cui appoggiarsi. Lo progettiamo a 360°, con percorsi, magazzino e sale riunioni al posto giusto.",
 [cards("cosa","Come si progetta uno stand a isola",None,
   [("Progetto a 360°","Ogni lato è un fronte: grafica, prodotto e accoglienza devono funzionare da tutte le direzioni."),
    ("Nucleo centrale","Magazzino, ripostiglio e locale tecnico raccolti al centro, così il perimetro resta libero e aperto."),
    ("Strutture sospese","Americane e insegne appese al soffitto del padiglione, dove il regolamento lo consente, per farsi vedere da lontano."),
    ("Percorsi e soglie","Ingressi chiari, banco di accoglienza visibile, flussi che non si incrociano con le zone di lavoro."),
    ("Sale riunioni","Salette chiuse o semichiuse, anche su un secondo livello, per le trattative riservate."),
    ("Pratiche e approvazioni","Altezze massime, distanze dai confini, appendimenti e calcoli strutturali da far approvare all'ente fiera.")]),
  testo("regole","Le regole da conoscere",None,
   ["Ogni quartiere fieristico ha un regolamento tecnico che fissa altezze massime, distanze dei muri pieni dai confini, percentuale di lati che devono restare aperti e condizioni per gli appendimenti a soffitto. Per uno stand a isola queste regole pesano più che per uno in linea, perché lo stand è visibile da tutti e confina con quattro corridoi.",
    "Ce ne occupiamo noi: leggiamo il regolamento della manifestazione, progettiamo nei limiti e presentiamo all'ente fiera disegni, calcoli e certificazioni. Così il progetto approvato è quello che poi montiamo, senza modifiche dell'ultimo minuto."],
   [("Altezze.","Variano da fiera a fiera e da padiglione a padiglione: le verifichiamo prima di disegnare."),
    ("Appendimenti.","Americane e insegne sospese richiedono punti di aggancio e approvazioni specifiche."),
    ("Due piani.","Possibili in molte fiere, con calcoli strutturali e collaudo. Vedi <a href=\"/stand-a-due-piani/\">stand a due piani</a>.")])],
 [("Quanto è grande uno stand a isola?","Di solito parte da 50–60 mq e può superare diverse centinaia di metri quadri. La forma dipende dallo spazio assegnato dall'organizzatore."),
  ("Si possono appendere insegne al soffitto?","In molti padiglioni sì, con punti di aggancio forniti dall'ente fiera e un progetto approvato. Lo verifichiamo per la tua fiera."),
  ("Lo stand a isola si può riutilizzare?","Sì, se progettato in modo modulare: alcuni elementi si riconfigurano anche per spazi ad angolo o a penisola."),
  ("Fate stand a isola anche all'estero?","Sì, in Germania, Francia, Spagna e nel resto d'Europa. Vedi <a href=\"/allestimenti-fieristici-estero/\">stand all'estero</a>.")],
 ["Progettazione stand a isola","Strutture sospese e americane","Sale riunioni e magazzini","Pratiche con l'ente fiera"],"Progettazione e allestimento di stand fieristici a isola",
 [("Stand su misura","/stand-fieristici-su-misura/"),("Stand a due piani","/stand-a-due-piani/"),("Progettazione stand","/progettazione-stand-fieristici/")],
 "Stand fieristici a isola progettati a 360°: strutture sospese, magazzino centrale, sale riunioni, grafica e montaggio in fiera.")

# ---------------- ANGOLO / PENISOLA
T("/stand-ad-angolo/","Stand ad angolo e a penisola per fiere | Danova Tech",
 "Stand fieristici ad angolo (due lati aperti) e a penisola (tre lati aperti): progetto, grafica, arredi e montaggio in fiera. Come sfruttare al meglio i lati liberi.",
 "Stand ad angolo e a penisola",'Stand ad angolo e a penisola: <span class="grad">due o tre lati</span> da sfruttare.',
 "Lo stand ad angolo ha due lati aperti, quello a penisola tre: più visibilità di uno stand in linea, con il vantaggio di avere ancora una o due pareti a cui appoggiare magazzino, grafica e arredi. Progettiamo il layout per far lavorare ogni lato libero.",
 [cards("cosa","Come si sfrutta uno spazio ad angolo",None,
   [("Il lato più trafficato","Studiamo i flussi del padiglione: il fronte principale va sul corridoio con più passaggio."),
    ("Pareti piene utili","Le pareti di confine ospitano magazzino, grafica grande e prodotto in parete."),
    ("Angolo aperto","L'angolo libero è il punto più visibile: lì va l'elemento che attira, un prodotto, un ledwall, un banco."),
    ("Penisola: tre fronti","Con tre lati aperti lo stand si comporta quasi come un'isola, con una sola parete di fondo."),
    ("Accoglienza","Banco e zona incontri posizionati per non bloccare l'ingresso."),
    ("Insegna","Fascioni o insegne su entrambi i fronti, per essere letti da due corridoi.")]),
  testo("confronto","In linea, angolo, penisola o isola?",None,
   ["Il tipo di spazio lo assegna l'organizzatore e incide sul costo dell'area. In linea hai un solo fronte e tre pareti; ad angolo due fronti; a penisola tre; a isola quattro. Più lati aperti significano più visibilità, ma anche più superficie da curare e meno pareti per il magazzino.",
    "Se puoi scegliere, l'angolo è spesso il miglior compromesso fra visibilità e costo, soprattutto fra i 16 e i 50 metri quadri. Ti aiutiamo a valutarlo con la planimetria del padiglione."],
   [("In linea.","Un fronte: semplice ed economico, ma bisogna farsi notare. Vedi <a href=\"/stand-fieristici-piccoli/\">stand piccoli</a>."),
    ("Angolo.","Due fronti: più visibilità, magazzino sulle pareti."),("Penisola.","Tre fronti: quasi un'isola, con una parete di fondo."),
    ("Isola.","Quattro fronti: massima visibilità. Vedi <a href=\"/stand-a-isola/\">stand a isola</a>.")])],
 [("Conviene uno stand ad angolo?","Spesso sì: costa poco più di uno in linea e si vede da due corridoi. Dipende dalla posizione nel padiglione."),
  ("Che differenza c'è fra angolo e penisola?","L'angolo ha due lati aperti, la penisola tre: la penisola ha una sola parete di fondo."),
  ("Potete aiutarmi a scegliere lo spazio?","Sì, con la planimetria del padiglione valutiamo flussi, posizione e forma prima che tu confermi l'area."),
  ("Lo stesso stand va bene in linea e ad angolo?","Con una struttura modulare sì: si riconfigura aprendo o chiudendo i lati.")],
 ["Stand ad angolo","Stand a penisola","Progettazione del layout","Montaggio in fiera"],"Progettazione e allestimento di stand fieristici ad angolo e a penisola",
 [("Stand a isola","/stand-a-isola/"),("Stand modulari","/stand-modulari/")],
 "Stand fieristici ad angolo e a penisola: progetto del layout, grafica sui fronti aperti, arredi e montaggio in fiera.")

# ---------------- PICCOLI
T("/stand-fieristici-piccoli/","Stand fieristici piccoli (9–24 mq) che si notano | Danova Tech",
 "Idee e soluzioni per stand fieristici piccoli, da 9 a 24 mq: verticalità, grafica, luci, arredi multifunzione e magazzino nascosto. Progetto e montaggio con budget sotto controllo.",
 "Stand piccoli",'Stand piccoli, da 9 a 24 mq, <span class="grad">che si notano</span>.',
 "In fiera la maggior parte degli espositori ha uno spazio piccolo, spesso in linea. Si può fare molto anche con 9, 12 o 16 metri quadri: serve un progetto che lavori in altezza, una grafica che si legga dal corridoio e arredi che non rubino spazio.",
 [cards("cosa","Come far rendere uno stand piccolo",None,
   [("Sfruttare l'altezza","Grafica e insegna in alto, sopra le teste: il corridoio ti vede da lontano anche se lo stand è piccolo."),
    ("Un messaggio solo","Una frase chiara e un'immagine forte valgono più di dieci testi: chi passa ha tre secondi."),
    ("Prodotto in primo piano","Il prodotto vicino al corridoio, non in fondo allo stand."),
    ("Arredi multifunzione","Banco con magazzino integrato, sgabelli impilabili, mensole a scomparsa."),
    ("Magazzino nascosto","Anche un metro quadro chiuso cambia la giornata: borse, scatole e cappotti spariscono."),
    ("Luce","Uno stand piccolo ben illuminato sembra più grande e più curato di uno grande in penombra.")]),
  testo("idee","Idee per uno stand da 9, 12 o 16 mq",None,
   ["Con 9 metri quadri (3×3) bastano una parete grafica a tutta altezza, un banco con ripostiglio e un espositore: semplice, leggibile, economico. A 12–16 mq si può aggiungere un tavolino per gli incontri e un ledwall o un monitor. Fra 18 e 24 mq si comincia a dividere lo spazio fra esposizione e accoglienza.",
    "La struttura più adatta è spesso un preallestito personalizzato o un modulare in tessuto teso: leggero, veloce da montare e riutilizzabile se fai più fiere. Te lo proponiamo con un render prima di decidere."],
   [("Tessuto teso.","Grafica a tutta parete, senza giunture: il modo più efficace per farsi notare in pochi metri."),
    ("Preallestito personalizzato.","La soluzione più rapida ed economica. Vedi <a href=\"/stand-preallestiti/\">stand preallestiti</a>."),
    ("Modulare riutilizzabile.","Conviene se fai più fiere l'anno. Vedi <a href=\"/stand-modulari/\">stand modulari</a>.")])],
 [("Cosa si può fare con uno stand di 9 mq?","Molto: una parete grafica a tutta altezza, un banco con magazzino integrato e un espositore per il prodotto. L'importante è un messaggio chiaro e una buona luce."),
  ("Quanto costa uno stand piccolo?","Dipende da struttura, grafica e arredi; un preallestito personalizzato è la soluzione più economica. Ti facciamo un preventivo voce per voce."),
  ("Fate il render anche per stand piccoli?","Sì, anche per 9 mq: vedere lo stand prima di produrlo evita errori di proporzione e di grafica."),
  ("Accettate richieste urgenti?","Sì, gli stand piccoli si organizzano anche a poche settimane dalla fiera.")],
 ["Stand fieristici piccoli","Grafica in tessuto teso","Arredi multifunzione","Montaggio in fiera"],"Progettazione e allestimento di stand fieristici di piccole dimensioni",
 [("Stand preallestiti","/stand-preallestiti/"),("Grafica per stand","/grafica-per-stand-fieristici/")],
 "Stand fieristici piccoli da 9 a 24 mq: grafica a tutta altezza, luce, arredi multifunzione e magazzino nascosto, montati in fiera.")

# ---------------- DUE PIANI
T("/stand-a-due-piani/","Stand a due piani: soppalco e sale riunioni | Danova Tech",
 "Stand fieristici a due piani con soppalco: sale riunioni e lounge al piano superiore, calcoli strutturali, collaudo e approvazione dell'ente fiera, montaggio in Italia e all'estero.",
 "Stand a due piani",'Stand a due piani: <span class="grad">raddoppiare lo spazio</span> senza raddoppiare l\'area.',
 "Quando l'area è cara e gli incontri sono tanti, salire al piano di sopra è la soluzione: sale riunioni, lounge o uffici sul soppalco, esposizione e accoglienza al piano terra. Uno stand a due piani richiede però calcoli, certificazioni e un montaggio più lungo: ce ne occupiamo noi, dal progetto al collaudo.",
 [cards("cosa","Cosa serve per uno stand a due piani",None,
   [("Progetto strutturale","Calcoli statici firmati da un tecnico abilitato, con carichi d'uso, scale e parapetti dimensionati."),
    ("Approvazione dell'ente fiera","Non tutte le fiere e non tutti i padiglioni ammettono i due piani: verifichiamo il regolamento e presentiamo il progetto."),
    ("Collaudo in fiera","A montaggio finito il soppalco va collaudato prima dell'apertura, secondo le procedure della manifestazione."),
    ("Scale e sicurezza","Scale comode, parapetti, illuminazione di sicurezza e vie di esodo."),
    ("Spazi al piano superiore","Sale riunioni, lounge, uffici, terrazze affacciate sul padiglione."),
    ("Tempi di montaggio","Servono più giorni di un allestimento normale: li pianifichiamo con l'ente fiera.")]),
  testo("quando","Quando conviene salire di un piano",None,
   ["Lo stand a due piani conviene nelle grandi fiere internazionali, dove il costo dell'area è alto e servono molti incontri riservati: si raddoppiano le superfici utili senza raddoppiare i metri quadri pagati all'organizzatore. È anche un segnale di presenza forte, visibile da lontano.",
    "Ha costi e tempi superiori a uno stand su un piano, per struttura, certificazioni e montaggio. Per questo lo valutiamo insieme partendo da quanti incontri prevedi e da quanto costa l'area in quella fiera."],
   [("Grandi fiere.","Salone del Mobile, EIMA, EICMA, fiere tedesche: dove l'area costa e gli incontri sono tanti."),
    ("Stand a isola.","La forma più adatta. Vedi <a href=\"/stand-a-isola/\">stand a isola</a>."),
    ("Strutture riutilizzabili.","Alcuni sistemi di soppalco modulari si riusano in più fiere.")])],
 [("Tutte le fiere permettono stand a due piani?","No: dipende dal regolamento tecnico della manifestazione e dal padiglione. Lo verifichiamo prima di progettare."),
  ("Chi firma i calcoli strutturali?","Un tecnico abilitato, che segue anche il collaudo in fiera. Pensiamo noi a coordinare tutto."),
  ("Quanto costa uno stand a due piani?","Più di uno su un piano, per struttura, certificazioni e montaggio; ma spesso meno che raddoppiare l'area. Ti facciamo un preventivo dettagliato."),
  ("Quanto tempo serve per montarlo?","Più giorni di un allestimento normale: lo pianifichiamo con l'ente fiera in base ai giorni di montaggio disponibili.")],
 ["Stand a due piani con soppalco","Calcoli strutturali e collaudo","Sale riunioni e lounge in quota","Montaggio in fiera"],"Progettazione e allestimento di stand fieristici a due piani",
 [("Stand a isola","/stand-a-isola/"),("Stand su misura","/stand-fieristici-su-misura/")],
 "Stand fieristici a due piani con soppalco: calcoli strutturali, approvazione dell'ente fiera, collaudo e montaggio.")

# ---------------- ECOSOSTENIBILI
T("/stand-fieristici-ecosostenibili/","Stand fieristici ecosostenibili e riutilizzabili | Danova Tech",
 "Stand fieristici sostenibili: strutture riutilizzabili in alluminio, tessuti riciclabili, legno certificato, LED, meno trasporti e magazzino per il riuso. Senza promesse vaghe.",
 "Stand ecosostenibili",'Stand ecosostenibili: <span class="grad">riusare</span> prima di tutto.',
 "Lo stand più sostenibile è quello che non si butta dopo quattro giorni. Progettiamo stand che si smontano, si conservano e si rimontano, con materiali riciclabili, illuminazione a basso consumo e trasporti ridotti. E ti diciamo con chiarezza cosa è riutilizzabile e cosa no.",
 [cards("cosa","Le scelte che fanno davvero la differenza",None,
   [("Strutture riutilizzabili","Telai modulari in alluminio che durano anni e si riconfigurano su metrature diverse."),
    ("Grafiche in tessuto","Tessuti stampati leggeri, lavabili e, dove possibile, riciclabili, al posto di pannelli rigidi monouso."),
    ("Legno certificato","Quando serve il legno, pannelli e listelli da filiere certificate e progettati per il riuso."),
    ("LED e consumi","Illuminazione LED e impianti dimensionati sul reale fabbisogno."),
    ("Meno trasporti","Imballi compatti, carichi ottimizzati, magazzino vicino alle fiere che fai più spesso."),
    ("Arredi a noleggio","Arredi noleggiati e riutilizzati invece di comprati per una sola fiera.")]),
  testo("onesta","Sostenibile, ma senza slogan",None,
   ["Ogni stand ha un impatto: materiali, trasporti, energia. Il modo più efficace per ridurlo è usare la stessa struttura per più fiere e più anni, e scegliere materiali che si possano recuperare. Per questo partiamo dal riuso, non dalle etichette.",
    "Se partecipi a fiere su ambiente ed energia, come Ecomondo, KEY o Klimahouse, lo stand è anche parte del messaggio: ti aiutiamo a raccontare le scelte fatte in modo concreto e verificabile."],
   [("Riuso.","Struttura e arredi conservati nel nostro magazzino e riportati alla fiera successiva."),
    ("Riciclo.","Separazione dei materiali a fine vita dello stand."),
    ("Trasparenza.","Ti diciamo quali elementi sono riutilizzabili e quali no.")])],
 [("Uno stand sostenibile costa di più?","Al primo utilizzo può costare un po' di più, ma il riuso abbassa il costo delle fiere successive. Facciamo il conto sulle fiere che prevedi."),
  ("Quante volte si può riusare uno stand modulare?","Per anni, se ben conservato: cambiano grafiche e configurazione, la struttura resta."),
  ("Potete fornire documentazione sui materiali?","Sì, per i materiali certificati forniamo le schede e le certificazioni dei produttori."),
  ("Fate stand per Ecomondo e Klimahouse?","Sì. Vedi <a href=\"/stand-ecomondo/\">stand per Ecomondo</a> e <a href=\"/allestimenti-fieristici-bolzano/\">allestimenti a Bolzano</a>.")],
 ["Stand riutilizzabili","Grafiche in tessuto","Illuminazione LED","Magazzino e riuso"],"Progettazione di stand fieristici sostenibili e riutilizzabili",
 [("Stand modulari","/stand-modulari/"),("Stand Ecomondo","/stand-ecomondo/")],
 "Stand fieristici sostenibili: strutture riutilizzabili, tessuti riciclabili, legno certificato, LED e magazzino per il riuso.")

# ---------------- PROGETTAZIONE 3D
T("/progettazione-stand-fieristici/","Progettazione stand fieristici e render 3D | Danova Tech",
 "Progettazione di stand fieristici: brief, layout, render 3D fotorealistici, disegni esecutivi e pratiche con l'ente fiera. Anche solo il progetto, da realizzare con noi o con altri.",
 "Progettazione stand",'Progettazione stand fieristici: <span class="grad">vederlo prima</span> di costruirlo.',
 "Uno stand si decide meglio guardandolo che immaginandolo. Partiamo da obiettivi, prodotto e planimetria, disegniamo il layout e te lo mostriamo in render 3D fotorealistico, con materiali, grafica e luci. Poi prepariamo gli esecutivi e le pratiche per l'ente fiera.",
 [passi("cosa","Il percorso","Dal brief <span class=\"grad\">agli esecutivi.</span>",None,
   [("Brief","Obiettivi, prodotto, visitatori attesi, budget, fiera e planimetria del padiglione."),
    ("Layout","Distribuzione degli spazi: accoglienza, esposizione, incontri, magazzino, flussi."),
    ("Render 3D","Immagini fotorealistiche da più punti di vista, con materiali, grafica e luci."),
    ("Revisioni","Modifichiamo il progetto finché non ti convince, prima di produrre qualsiasi cosa."),
    ("Esecutivi","Disegni costruttivi, schema elettrico, dettagli per la produzione."),
    ("Pratiche","Progetto presentato all'ente fiera secondo il regolamento tecnico.")]),
  testo("perche","Perché il render cambia il risultato",None,
   ["Nel render si vedono subito le cose che in fiera costerebbero care: una grafica illeggibile da lontano, un banco che chiude l'ingresso, un magazzino troppo piccolo, una luce che appiattisce il prodotto. Correggerle su un file costa minuti; in padiglione, ore e soldi.",
    "Il render serve anche dopo: per far approvare il progetto internamente, per i social e la comunicazione prima della fiera, per il materiale da inviare ai clienti che inviti allo stand."],
   [("Anche solo il progetto.","Puoi affidarci la progettazione e realizzarlo con il fornitore che preferisci."),
    ("Anche su progetti altrui.","Partiamo dal disegno del tuo architetto e lo rendiamo costruibile."),
    ("Riutilizzo.","Progettiamo pensando a configurazioni diverse per fiere diverse.")])],
 [("Posso commissionare solo il progetto dello stand?","Sì, ti consegniamo render ed esecutivi; se poi vuoi, lo realizziamo e montiamo noi."),
  ("Quante revisioni sono comprese?","Lavoriamo finché il progetto non ti convince, nei limiti concordati nel preventivo; di solito bastano due o tre giri."),
  ("Il costo del progetto si scala dalla realizzazione?","Se realizziamo noi lo stand, la progettazione è parte del preventivo complessivo."),
  ("Cosa vi serve per iniziare?","Planimetria del padiglione con la posizione dello spazio, metratura, tipo di spazio, logo e materiali del marchio, prodotti da esporre e budget indicativo.")],
 ["Progettazione stand fieristici","Render 3D fotorealistici","Disegni esecutivi","Pratiche con l'ente fiera"],"Progettazione di stand fieristici con render 3D",
 [("Stand su misura","/stand-fieristici-su-misura/"),("Grafica per stand","/grafica-per-stand-fieristici/")],
 "Progettazione di stand fieristici: layout, render 3D fotorealistici, disegni esecutivi e pratiche con l'ente fiera.")

# ---------------- GRAFICA
T("/grafica-per-stand-fieristici/","Grafica per stand fieristici: stampa e posa | Danova Tech",
 "Grafica per stand fieristici: progetto, impaginazione e stampa su tessuto teso, forex, dibond, prespaziati e vetrofanie, con posa in fiera. Messaggi leggibili da lontano.",
 "Grafica per stand",'Grafica per stand fieristici: <span class="grad">leggibile da dieci metri</span>.',
 "La grafica è la prima cosa che il visitatore vede, spesso da un corridoio di distanza. Progettiamo messaggi che si leggono camminando, impaginiamo i file di stampa e stampiamo sul supporto giusto, dal tessuto teso ai pannelli rigidi, con posa in fiera.",
 [cards("cosa","Supporti e lavorazioni",None,
   [("Tessuto teso","Stampa su tessuto con bordo in silicone inserito nei telai: grandi superfici senza giunture, anche retroilluminate."),
    ("Pannelli rigidi","Forex, dibond, legno stampato: per pareti, banchi e totem."),
    ("Prespaziati e lettere 3D","Loghi e scritte in vinile prespaziato o in rilievo, anche illuminati."),
    ("Vetrofanie e pavimenti","Pellicole per vetri, grafiche calpestabili, segnaletica a terra."),
    ("Insegne sospese","Bandiere, cubi e cilindri appesi per farsi trovare nel padiglione."),
    ("Posa in fiera","Montaggio delle grafiche insieme allo stand, con controllo di allineamenti e colori.")]),
  testo("regole","Tre regole per una grafica che funziona in fiera",None,
   ["Primo: un messaggio, non dieci. Chi cammina in fiera legge cinque o sei parole, poi decide se fermarsi. Secondo: in alto quello che deve vedersi da lontano (marchio, cosa fai), all'altezza degli occhi quello che si legge da vicino. Terzo: colori e contrasti pensati per la luce del padiglione, che è diversa da quella dello schermo.",
    "Prepariamo noi i file di stampa nei formati, nelle risoluzioni e con le abbondanze giuste; oppure controlliamo quelli del tuo grafico prima di stampare, così in fiera non ci sono bande bianche, loghi sgranati o colori sbagliati."],
   [("File controllati.","Verifica di risoluzione, colore, abbondanze e testi prima della stampa."),
    ("Grafiche riutilizzabili.","Il tessuto si conserva e si rimonta nella fiera successiva."),
    ("Anche solo la stampa.","Se la grafica ce l'hai, ci occupiamo di stampa e posa.")])],
 [("Che risoluzione serve per la grafica di uno stand?","Dipende dalla distanza di lettura: per grandi superfici viste da lontano bastano risoluzioni più basse di quelle di una brochure. Controlliamo noi i file prima della stampa."),
  ("Meglio tessuto teso o pannelli rigidi?","Il tessuto è leggero, senza giunture e riutilizzabile; i pannelli rigidi sono adatti a banchi, totem e superfici che si toccano. Spesso si usano insieme."),
  ("Potete stampare grafiche fornite dal nostro grafico?","Sì, le verifichiamo e le stampiamo sul supporto giusto, con posa in fiera."),
  ("Le grafiche si possono riutilizzare?","Sì, soprattutto quelle in tessuto: le conserviamo in magazzino insieme allo stand.")],
 ["Progetto grafico per stand","Stampa su tessuto teso","Pannelli, prespaziati e vetrofanie","Posa grafiche in fiera"],"Grafica, stampa e posa per stand fieristici",
 [("Progettazione stand","/progettazione-stand-fieristici/"),("Ledwall e illuminazione","/ledwall-e-illuminazione-stand/")],
 "Grafica per stand fieristici: progetto, impaginazione, stampa su tessuto teso e pannelli rigidi, posa in fiera.")

# ---------------- LEDWALL E LUCI
T("/ledwall-e-illuminazione-stand/","Ledwall e illuminazione per stand fieristici | Danova Tech",
 "Ledwall, monitor e illuminazione per stand fieristici a noleggio o in acquisto: progetto luci, impianto elettrico certificato, potenze per l'ente fiera e contenuti video.",
 "Ledwall e luci",'Ledwall e illuminazione: <span class="grad">lo stand che si accende</span>.',
 "Luce e schermi fanno la differenza fra uno stand che si vede e uno che si nota. Progettiamo l'illuminazione sul prodotto, forniamo ledwall e monitor a noleggio, realizziamo l'impianto elettrico certificato e calcoliamo la potenza da richiedere all'ente fiera.",
 [cards("cosa","Cosa forniamo",None,
   [("Ledwall","Pareti LED modulari di varie dimensioni, per video e immagini visibili anche da lontano."),
    ("Monitor e totem","Schermi per presentazioni, video prodotto, cataloghi interattivi."),
    ("Luce sul prodotto","Faretti d'accento, luce diffusa, temperatura colore e resa cromatica scelte sul materiale."),
    ("Grafiche retroilluminate","Tessuto teso con LED all'interno dei telai: superfici luminose e uniformi."),
    ("Impianto elettrico","Quadro, linee e dichiarazione di conformità richiesta dall'ente fiera."),
    ("Contenuti","Se serve, prepariamo i video e le grafiche animate da mostrare sugli schermi.")]),
  testo("potenza","Potenza elettrica e pratiche",None,
   ["Ogni fiera chiede di dichiarare in anticipo la potenza elettrica necessaria allo stand: luci, ledwall, frigoriferi, macchine. Se la richiesta è sottodimensionata, in fiera scatta l'interruttore; se è sovradimensionata, si paga di più. Facciamo il calcolo sulle schede tecniche e richiediamo la potenza giusta.",
    "A montaggio finito rilasciamo la dichiarazione di conformità dell'impianto elettrico richiesta dall'ente fiera."],
   [("Ledwall a noleggio.","Nessun investimento: lo portiamo, lo montiamo, lo riprendiamo."),
    ("LED a basso consumo.","Più luce, meno calore e meno potenza richiesta."),
    ("Luce per settore.","Pietra, gioielli, cosmetica e moda chiedono luci diverse: la scegliamo sul prodotto.")])],
 [("Si può noleggiare un ledwall per una fiera?","Sì, con montaggio, collegamento e smontaggio inclusi; scegliamo dimensioni e passo dei LED in base alla distanza di visione."),
  ("Chi rilascia la dichiarazione di conformità dell'impianto?","La rilasciamo noi a fine montaggio, come richiesto dall'ente fiera."),
  ("Quanta potenza elettrica serve allo stand?","Dipende da luci, schermi e apparecchi: facciamo il calcolo e la richiesta all'ente fiera."),
  ("Preparate anche i contenuti video?","Sì, se serve: video prodotto, loop di immagini e grafiche animate pensate per lo schermo in fiera.")],
 ["Noleggio ledwall e monitor","Progetto illuminotecnico per stand","Impianto elettrico certificato","Contenuti video per schermi"],"Ledwall, illuminazione e impianti elettrici per stand fieristici",
 [("Grafica per stand","/grafica-per-stand-fieristici/"),("Noleggio stand","/noleggio-stand-fieristici/")],
 "Ledwall, monitor, illuminazione e impianto elettrico certificato per stand fieristici, a noleggio o in acquisto.")
