# -*- coding: utf-8 -*-
# Contenuti delle pagine /stand-<fiera>/ . exp=True solo per le fiere in cui Danova Tech ha gia' allestito stand.
P=[
dict(k="vinitaly",cal=["vinitaly"],nome="Vinitaly",citta="Verona",cs="verona",q="Veronafiere",sett="vino",cad="Annuale, in primavera",exp=True,
 lead="Stand per Vinitaly chiavi in mano: banchi di degustazione, frigoriferi, magazzino bottiglie, aree incontri, grafica e montaggio a Veronafiere. Abbiamo già allestito stand al Vinitaly e sappiamo quanto contano tempi e dettagli.",
 intro=["Vinitaly è il salone internazionale dei vini e dei distillati di Verona: quattro giorni in cui cantine, consorzi e distillerie incontrano importatori, distributori, ristoratori ed enotecari da tutto il mondo. Per molte aziende vinicole è l'appuntamento commerciale più importante dell'anno, quello in cui si chiudono listini e nuove distribuzioni.",
  "Lo stand di una cantina al Vinitaly è insieme sala degustazione, ufficio commerciale e biglietto da visita. Deve far sedere le persone giuste, permettere di degustare con calma e tenere a portata di mano bottiglie, bicchieri e ghiaccio senza che il retro si veda. E deve farsi notare in padiglioni dove ogni metro è occupato da un'altra etichetta."],
 esig=[("Banco di mescita e degustazione.","Piani di lavoro all'altezza giusta, sputavino, lavabicchieri e spazio per le bottiglie aperte, separati dall'area in cui si siede il buyer."),
  ("Frigoriferi e cantinette.","Bianchi, bollicine e rosati vanno serviti alla temperatura giusta per quattro giorni: prevediamo frigoriferi, cantinette e la potenza elettrica necessaria."),
  ("Magazzino nascosto.","Un ripostiglio chiuso per cartoni, bicchieri di scorta, borse e cappotti: è la differenza fra uno stand ordinato e uno che sembra un deposito."),
  ("Tavoli per gli appuntamenti.","Al Vinitaly si lavora su appuntamento: tavoli e sedute per incontri riservati, anche separati da pareti o tende."),
  ("Grafica per denominazioni ed etichette.","Nome della cantina leggibile da lontano, territorio e denominazioni ben visibili, bottiglie retroilluminate su mensole o in nicchia."),
  ("Stand collettivi.","Per consorzi e collettive progettiamo postazioni uguali per più cantine, con un'area comune per degustazioni guidate.")],
 tempi="Vinitaly è la fiera più richiesta dell'anno a Verona: squadre di montaggio, frigoriferi e arredi a noleggio vanno bloccati con largo anticipo. L'ideale è sentirci appena hai la conferma dello spazio, di solito fra l'autunno e l'inverno. Se ti accorgi tardi che ti serve una mano, scrivici comunque: valutiamo subito cosa è possibile fare.",
 qa=[("Con quanto anticipo prenotare lo stand per Vinitaly?","Prima possibile: le squadre e i materiali per Veronafiere ad aprile sono molto richiesti. Con 3–4 mesi di margine hai piena scelta su progetto e finiture; con meno tempo lavoriamo su soluzioni modulari o a noleggio, che si organizzano più in fretta."),
  ("Potete fornire frigoriferi, lavabicchieri e attrezzature per la degustazione?","Sì, a noleggio insieme allo stand: frigoriferi e cantinette, lavabicchieri, sputavino, banchi di mescita, ghiacciaie. Calcoliamo anche la potenza elettrica da richiedere all'ente fiera."),
  ("Allestite anche stand collettivi per consorzi?","Sì. Progettiamo postazioni coordinate per più cantine, con grafica comune, aree di degustazione condivise e un magazzino centrale.")],
 off=["Stand per cantine al Vinitaly","Banchi di degustazione e frigoriferi a noleggio","Stand collettivi per consorzi","Montaggio e smontaggio a Veronafiere"]),

dict(k="marmomac",cal=["marmomac"],nome="Marmomac",citta="Verona",cs="verona",q="Veronafiere",sett="edilizia",cad="Annuale, a fine settembre",exp=True,
 lead="Stand per Marmomac progettati per reggere pietra, lastre e macchinari: pavimenti e pareti portanti, illuminazione per le venature, logistica di carico e scarico e montaggio a Veronafiere. Abbiamo già allestito stand al Marmomac.",
 intro=["Marmomac è la fiera internazionale della pietra naturale, del design litico e delle tecnologie di lavorazione: cave, laboratori, distributori di lastre e costruttori di macchine si ritrovano a Verona davanti a un pubblico di architetti, progettisti e buyer da tutto il mondo.",
  "È una fiera in cui lo stand non è solo immagine ma ingegneria. Lastre e blocchi pesano centinaia di chili, a volte tonnellate; le macchine sono spesso in funzione; e la pietra va illuminata in modo che venature, colori e finiture si leggano davvero. Un errore di progetto qui non è estetico: è di portata e di sicurezza."],
 esig=[("Pavimenti e pedane portanti.","Calcoliamo i carichi e prevediamo pavimentazioni e pedane adatte al peso di lastre, blocchi e macchinari."),
  ("Pareti e rastrelliere per lastre.","Strutture dimensionate per esporre lastre in verticale in sicurezza, con ancoraggi verificati."),
  ("Luce radente e fedele al colore.","Illuminazione studiata per far emergere venature, lucidature e texture senza falsare i colori del materiale."),
  ("Carico e scarico con mezzi di sollevamento.","Coordinamento dei tempi di consegna dei materiali pesanti con gli orari dell'ente fiera e i mezzi disponibili in padiglione."),
  ("Macchine in funzione.","Allacci elettrici adeguati, protezioni e spazi di sicurezza per le dimostrazioni.")],
 tempi="Marmomac si tiene a fine settembre, ma le lastre da esporre si scelgono e si preparano mesi prima. Conviene impostare il progetto dello stand insieme alla selezione dei materiali, in primavera o all'inizio dell'estate, così strutture e logistica nascono già dimensionate sul peso reale.",
 qa=[("Le pareti dello stand reggono lastre di pietra?","Sì, se progettate per farlo: dimensioniamo strutture, ancoraggi e pavimenti sui materiali che vuoi esporre. Per questo ci servono in anticipo misure e pesi delle lastre."),
  ("Vi occupate del carico e scarico dei materiali pesanti?","Coordiniamo noi consegne, orari e mezzi di sollevamento con l'ente fiera, così le lastre arrivano quando la struttura è pronta a riceverle."),
  ("Potete allestire uno stand con macchinari in funzione?","Sì: prevediamo allacci elettrici, protezioni e distanze di sicurezza, e presentiamo il progetto all'ente fiera secondo il regolamento tecnico.")],
 off=["Stand per Marmomac","Pavimenti e pedane portanti","Strutture per esposizione lastre","Logistica materiali pesanti in fiera"]),

dict(k="salone-del-mobile",cal=["salone-del-mobile"],nome="Salone del Mobile",citta="Milano",cs="milano",q="Fiera Milano Rho",sett="arredo",cad="Annuale, in aprile (con biennali alternate)",exp=True,
 lead="Stand per il Salone del Mobile.Milano progettati come un pezzo d'arredo: finiture di livello, luce, ambientazioni complete e montaggio a Fiera Milano Rho. Abbiamo già allestito stand al Salone del Mobile.",
 intro=["Il Salone del Mobile.Milano è l'appuntamento di riferimento mondiale per l'arredo e il design. Ad aprile, a Fiera Milano Rho, aziende di arredamento, complemento e illuminazione presentano le novità a progettisti, rivenditori, contract e stampa. Accanto al Salone si alternano le biennali: nel 2027 c'è Euroluce, dedicata all'illuminazione.",
  "Qui lo stand viene giudicato con gli stessi occhi con cui si giudica un prodotto: proporzioni, materiali, giunzioni, luce. Un pannello non allineato o un bordo grezzo si notano subito. Per questo al Salone conta poco la quantità di metri quadri e molto la cura del dettaglio, dalla laccatura delle pareti alla temperatura colore dei faretti."],
 esig=[("Ambientazioni complete.","Pareti, controsoffitti, pavimenti e quinte che trasformano lo stand in una casa, un ufficio o un hotel in cui il prodotto si vede in uso."),
  ("Finiture di livello.","Laccature, impiallacciati, tessuti e metalli scelti come per un interno di pregio; campionature approvate prima della produzione."),
  ("Luce progettata.","Illuminazione d'accento, luce diffusa e temperatura colore pensate sui materiali. Per chi espone a Euroluce, integrazione delle lampade nel progetto."),
  ("Materiali certificati.","Il regolamento tecnico chiede materiali con adeguata reazione al fuoco e strutture verificate: prepariamo noi la documentazione per l'ente fiera."),
  ("Tempi di allestimento rigidi.","Accessi, orari e scarichi a Rho sono regolati con precisione: pianifichiamo squadre e consegne giorno per giorno.")],
 tempi="Per uno stand su misura al Salone del Mobile il lavoro comincia molti mesi prima: concept e render in autunno, campionature e produzione in inverno, montaggio nei giorni concessi prima dell'apertura. Se il progetto è già pronto e ti mancano produzione e montatori, possiamo entrare anche più tardi.",
 qa=[("Fate stand anche per Euroluce?","Sì. Nel 2027 Euroluce si tiene insieme al Salone: progettiamo stand in cui la luce è il prodotto, con controsoffitti, schermature e impianti dimensionati sulle lampade esposte."),
  ("Usate materiali certificati per la reazione al fuoco?","Sì, scegliamo materiali con le certificazioni richieste dal regolamento tecnico e consegniamo all'ente fiera la documentazione necessaria, insieme alla dichiarazione di conformità dell'impianto elettrico."),
  ("Allestite anche showroom ed eventi durante il Fuorisalone?","Sì, oltre allo stand in fiera allestiamo spazi in città, showroom ed eventi. Vedi <a href=\"/allestimenti-eventi-showroom-negozi/\">allestimenti per eventi e showroom</a>.")],
 off=["Stand per il Salone del Mobile","Stand per Euroluce","Ambientazioni e finiture su misura","Montaggio a Fiera Milano Rho"]),

dict(k="eicma",cal=["eicma"],nome="EICMA",citta="Milano",cs="milano",q="Fiera Milano Rho",sett="auto",cad="Annuale, a novembre",exp=True,
 lead="Stand per EICMA a Fiera Milano Rho: pedane portanti per moto e scooter, grafiche di grande formato, ledwall, percorsi per un pubblico numeroso e montaggio nei tempi della fiera. Abbiamo già allestito stand a EICMA.",
 intro=["EICMA è l'esposizione internazionale delle due ruote: moto, scooter, e-bike, abbigliamento tecnico, componenti e accessori. A novembre, a Fiera Milano Rho, si alternano giornate riservate a stampa e operatori e giornate aperte a un pubblico di appassionati molto numeroso.",
  "Due pubblici diversi chiedono uno stand che funzioni in due modi: ordinato e accogliente per i dealer e i giornalisti, spettacolare e resistente per i visitatori. I mezzi vanno esposti in sicurezza, le grafiche devono vedersi da lontano sopra la folla e gli spazi devono reggere migliaia di persone che si fermano, fotografano e salgono in sella."],
 esig=[("Pedane portanti e rampe.","Pedane dimensionate sul peso dei mezzi, con rampe di carico, bordi protetti e finiture resistenti al passaggio."),
  ("Impatto visivo in alto.","Grafiche in tessuto teso, insegne sospese e ledwall visibili sopra le teste del pubblico."),
  ("Percorsi e zone foto.","Layout che lascia scorrere il pubblico senza intasare lo stand, con punti dedicati a prove in sella e foto."),
  ("Area riservata per dealer e stampa.","Un salottino o una sala chiusa per gli incontri commerciali, separata dal flusso del pubblico."),
  ("Banco merchandising.","Postazione vendita o distribuzione gadget con magazzino retrostante.")],
 tempi="EICMA è a novembre e lo stand si progetta di solito in estate. Se esponi quest'anno e ti manca ancora il fornitore, scrivici subito: con strutture modulari, pedane e grafiche in tessuto teso riusciamo a lavorare anche a poche settimane dall'apertura.",
 qa=[("Le pedane reggono moto e scooter esposti?","Sì, le dimensioniamo sul peso e sul numero dei mezzi, con rampe per la movimentazione e finiture antiscivolo dove serve."),
  ("Potete allestire uno stand per EICMA con poco preavviso?","Sì, valutiamo anche richieste urgenti: con soluzioni modulari e grafiche in tessuto teso i tempi di produzione si accorciano molto."),
  ("Gestite ledwall e schermi?","Sì, a noleggio o in acquisto, con l'impianto elettrico certificato e la regia dei contenuti se ti serve.")],
 off=["Stand per EICMA","Pedane portanti per moto","Ledwall e grafiche di grande formato","Montaggio a Fiera Milano Rho"]),

dict(k="host",cal=["host"],nome="HostMilano",citta="Milano",cs="milano",q="Fiera Milano Rho",sett="food",cad="Biennale, a ottobre (anni dispari)",exp=True,
 lead="Stand per HostMilano con attrezzature in funzione: allacci elettrici e idrici, scarichi, banchi per dimostrazioni e assaggi, grafica e montaggio a Fiera Milano Rho. Abbiamo già allestito stand a Host.",
 intro=["HostMilano è la fiera internazionale dell'ospitalità professionale: macchine per caffè, forni, attrezzature per ristorazione, gelateria e pasticceria, arredi per hotel e locali, tavola e servizio. Si tiene ogni due anni a Fiera Milano Rho e riunisce produttori e operatori del fuori casa da tutto il mondo.",
  "A Host le macchine non si guardano: si provano. Caffè estratti al momento, impasti, cotture e dimostrazioni dal vivo chiedono uno stand che sia prima di tutto un laboratorio funzionante, con potenze elettriche importanti, acqua, scarichi e piani di lavoro igienici, senza rinunciare all'immagine del marchio."],
 esig=[("Impianti per macchine in funzione.","Potenza elettrica, prese dedicate, carico e scarico dell'acqua, previsti nel progetto e richiesti per tempo all'ente fiera."),
  ("Banchi dimostrativi e show cooking.","Piani di lavoro, isole e banconi su misura per dimostrazioni dal vivo, con spazio per il pubblico."),
  ("Aree assaggio.","Bancone o tavoli dove degustare caffè, gelato o piatti, con stoviglie e lavaggio retrostanti."),
  ("Magazzino e retro tecnico.","Spazio chiuso per materie prime, ricambi e attrezzature di servizio."),
  ("Arredi e ambientazioni.","Per chi espone arredo per hotel e locali, ambientazioni realistiche: una camera, una sala, un bancone bar.")],
 tempi="Host si tiene negli anni dispari, a ottobre. Le richieste di potenza elettrica e di allacci idrici vanno presentate entro le scadenze dell'ente fiera, quindi il progetto impiantistico va chiuso con mesi di anticipo: conviene iniziare in primavera.",
 qa=[("Potete portare acqua e scarichi nello stand?","Sì, prevediamo nel progetto gli allacci idrici e gli scarichi richiesti dalle macchine e li coordiniamo con i servizi tecnici della fiera."),
  ("Quanta potenza elettrica serve per uno stand con macchine in funzione?","Dipende dalle attrezzature: facciamo il calcolo con le schede tecniche delle macchine e richiediamo all'ente fiera la potenza corretta, così in fiera non salta niente."),
  ("Fate anche arredi su misura per bar e ristoranti esposti?","Sì, banconi, retrobanchi e ambientazioni costruiti su misura e integrati nello stand.")],
 off=["Stand per HostMilano","Impianti elettrici e idrici per macchine in funzione","Banchi per dimostrazioni e show cooking","Montaggio a Fiera Milano Rho"]),

dict(k="cosmoprof",cal=["cosmoprof"],nome="Cosmoprof",citta="Bologna",cs="bologna",q="BolognaFiere",sett="beauty",cad="Annuale, a marzo",exp=True,
 lead="Stand per Cosmoprof Worldwide Bologna: espositori illuminati, vetrine, postazioni per trattamenti e dimostrazioni, magazzino campioni, grafica e montaggio a BolognaFiere. Abbiamo già allestito stand al Cosmoprof.",
 intro=["Cosmoprof Worldwide Bologna è la fiera internazionale della bellezza: cosmetica, profumeria, prodotti per capelli, unghie ed estetica professionale, packaging e conto terzi. È organizzata in più saloni (Cosmopack, Cosmo Perfumery & Cosmetics, Cosmo Hair Nail & Beauty Salon) con buyer, distributori e professionisti da tutto il mondo.",
  "In un padiglione con migliaia di marchi, il prodotto cosmetico vince se è illuminato bene e se si può provare. Flaconi e confezioni hanno bisogno di luce fedele al colore e di espositori ordinati; le linee professionali chiedono postazioni per trattamenti, piega o manicure; il conto terzi chiede salottini dove parlare di formulazioni e volumi."],
 esig=[("Espositori e vetrine illuminate.","Mensole retroilluminate, teche e banchi espositivi con luce ad alta resa cromatica, perché il colore del prodotto in fiera sia quello vero."),
  ("Postazioni per dimostrazioni.","Postazioni trucco, lavatesta e poltrone per piega, tavoli manicure: con acqua, scarichi ed elettricità dove servono."),
  ("Magazzino campioni.","Ripostiglio chiuso per campionature, tester e materiale da distribuire."),
  ("Area B2B riservata.","Tavoli per incontri con buyer e distributori, separati dallo spazio espositivo."),
  ("Grafica pulita e coerente.","Packaging e brand al centro: grafiche essenziali, fondali neutri e loghi leggibili da lontano.")],
 tempi="Cosmoprof è a marzo: per uno stand su misura conviene partire in autunno. Le aziende che espongono anche alle edizioni estere di Cosmoprof possono valutare uno stand modulare di proprietà, da riconfigurare di volta in volta.",
 qa=[("Potete realizzare postazioni con lavatesta e acqua per dimostrazioni?","Sì, prevediamo allacci idrici e scarichi e li coordiniamo con i servizi tecnici di BolognaFiere."),
  ("Che luce usate per esporre cosmetici?","Illuminazione LED ad alta resa cromatica, con temperatura colore scelta sul prodotto, per evitare che il colore di rossetti, fondotinta e packaging risulti falsato."),
  ("Allestite stand per Cosmopack e il conto terzi?","Sì: lì contano spazi per incontri, campionari e schermi per presentare impianti e lavorazioni.")],
 off=["Stand per Cosmoprof","Espositori illuminati per cosmetica","Postazioni per dimostrazioni con allacci idrici","Montaggio a BolognaFiere"]),

dict(k="cersaie",cal=["cersaie"],nome="Cersaie",citta="Bologna",cs="bologna",q="BolognaFiere",sett="edilizia",cad="Annuale, a fine settembre",exp=True,
 lead="Stand per Cersaie con pareti portanti, ambientazioni bagno e pavimenti posati: progetto, materiali, componentistica e montaggio a BolognaFiere. Abbiamo già allestito stand al Cersaie.",
 intro=["Cersaie è il salone internazionale della ceramica per l'architettura e dell'arredobagno. A Bologna, a fine settembre, produttori di piastrelle, lastre, sanitari, rubinetteria e arredo bagno presentano le collezioni ad architetti, rivenditori e posatori.",
  "Allo stand di Cersaie la ceramica deve essere vista posata, non appoggiata: pavimenti e rivestimenti montati come in un vero ambiente, grandi lastre a parete, bagni completi con sanitari e rubinetteria. Significa strutture capaci di reggere pesi importanti e tempi di montaggio che includono una vera e propria posa."],
 esig=[("Pareti portanti per rivestimenti.","Strutture dimensionate per piastrelle e lastre di grande formato, anche in verticale e a tutta altezza."),
  ("Pavimenti posati nello stand.","Pavimentazioni sopraelevate o posate a secco, per mostrare il materiale come sarà a casa del cliente."),
  ("Ambientazioni bagno complete.","Sanitari, rubinetteria, docce e arredi installati in ambientazioni realistiche, con gli allacci necessari se devono funzionare."),
  ("Espositori per collezioni.","Pannelli scorrevoli, cassettiere e campionari che permettono di vedere decine di finiture in poco spazio."),
  ("Tempi di montaggio adeguati.","La posa richiede più giorni di un allestimento normale: pianifichiamo squadre e consegne di conseguenza.")],
 tempi="Cersaie è a fine settembre e le collezioni da esporre si definiscono spesso in primavera. Conviene progettare lo stand insieme alla scelta dei prodotti, così strutture e pesi sono già calcolati quando arrivano i materiali.",
 qa=[("Lo stand può reggere lastre ceramiche di grande formato?","Sì, progettiamo pareti e ancoraggi sui formati e sui pesi delle lastre che vuoi esporre."),
  ("Potete posare pavimenti e rivestimenti dentro lo stand?","Sì, con pavimenti sopraelevati o posa a secco, e rivestimenti a parete montati su strutture dedicate."),
  ("Allestite anche showroom di ceramica e arredobagno?","Sì, oltre alla fiera progettiamo spazi espositivi permanenti. Vedi <a href=\"/allestimenti-eventi-showroom-negozi/\">allestimenti per showroom</a>.")],
 off=["Stand per Cersaie","Pareti portanti per ceramica","Ambientazioni bagno","Montaggio a BolognaFiere"]),

dict(k="eima",cal=["eima"],nome="EIMA International",short="EIMA",citta="Bologna",cs="bologna",q="BolognaFiere",sett="agri",cad="Biennale, a novembre (anni pari)",exp=True,
 lead="Stand per EIMA International a BolognaFiere: grandi superfici per trattori e macchine agricole, pedane portanti, aree incontro per i dealer, grafica e montaggio. Abbiamo già allestito stand all'EIMA.",
 intro=["EIMA International è l'esposizione internazionale delle macchine per l'agricoltura e il giardinaggio: trattori, attrezzature, componenti, irrigazione, macchine per la manutenzione del verde. Si tiene a Bologna ogni due anni, a novembre, con un pubblico di agricoltori, contoterzisti, dealer e importatori.",
  "Gli stand dell'EIMA sono spesso grandi, a isola, con mezzi di dimensioni e pesi importanti. Il progetto deve tenere insieme la movimentazione delle macchine, la sicurezza dei visitatori che ci salgono sopra e gli spazi per accogliere la rete commerciale, che in fiera fissa decine di appuntamenti al giorno."],
 esig=[("Pavimenti e pedane per mezzi pesanti.","Pedane portanti e pavimentazioni resistenti, con rampe per la movimentazione delle macchine."),
  ("Stand a isola di grandi dimensioni.","Layout aperto su più lati, con percorsi chiari fra i mezzi esposti e un punto di accoglienza riconoscibile."),
  ("Sala incontri per dealer.","Uffici e salottini chiusi, a volte su un secondo livello, per trattative e riunioni della rete vendita."),
  ("Grafica e segnaletica.","Insegne alte e visibili nei grandi padiglioni, schede prodotto vicino a ogni macchina."),
  ("Logistica dei mezzi.","Coordinamento con l'ente fiera per l'ingresso e il posizionamento delle macchine nei giorni di allestimento.")],
 tempi="EIMA si tiene negli anni pari, a novembre. Se partecipi all'edizione di quest'anno e non hai ancora chiuso l'allestimento, contattaci subito: valutiamo strutture modulari e soluzioni a noleggio montabili in tempi brevi.",
 qa=[("Le pedane reggono trattori e macchine agricole?","Sì, le dimensioniamo sul peso dei mezzi e prevediamo rampe e protezioni per la movimentazione."),
  ("Potete realizzare uno stand a due piani all'EIMA?","Sì, nel rispetto del regolamento tecnico e con calcoli strutturali e collaudo. Vedi <a href=\"/stand-a-due-piani/\">stand a due piani</a>."),
  ("Fate anche stand per Agritechnica e altre fiere agricole all'estero?","Sì, lavoriamo anche nelle fiere estere. Trovi le date nel <a href=\"/calendario-fiere/\">calendario fiere</a>.")],
 off=["Stand per EIMA International","Pedane per macchine agricole","Stand a isola di grandi dimensioni","Montaggio a BolognaFiere"]),

dict(k="sicam",cal=["sicam"],nome="Sicam",citta="Pordenone",cs="pordenone",q="Pordenone Fiere",sett="arredo",cad="Annuale, a ottobre",exp=True,
 lead="Stand per Sicam a Pordenone Fiere: pareti attrezzate per campionari, espositori per ferramenta e finiture, aree incontri e montaggio. Abbiamo già allestito stand al Sicam e la nostra sede è a pochi chilometri dalla fiera.",
 intro=["Sicam è il salone internazionale dei componenti, accessori e semilavorati per l'industria del mobile. A Pordenone, ogni ottobre, produttori di ferramenta, maniglie, sistemi di movimento, pannelli, finiture, tessuti e illuminazione per mobili incontrano gli uffici acquisti e i progettisti delle aziende di arredamento.",
  "È una fiera molto tecnica: i visitatori vogliono toccare il prodotto, aprire un cassetto, provare una cerniera, confrontare finiture. Lo stand deve essere un campionario ordinato e consultabile, con spazi per sedersi e discutere di forniture, e deve stare nei tempi stretti di allestimento di un quartiere fieristico compatto."],
 esig=[("Pareti attrezzate per campionari.","Pannelli forati, mensole, cassettiere e sistemi a binario per esporre componenti e finiture in modo ordinato."),
  ("Prodotti funzionanti da provare.","Mobili campione e meccanismi montati in modo che il visitatore possa aprirli e muoverli."),
  ("Tavoli per gli uffici acquisti.","Aree per incontri tecnici con cataloghi, schede e campioni a portata di mano."),
  ("Grafica tecnica e leggibile.","Codici, famiglie di prodotto e applicazioni spiegati con chiarezza, anche in inglese per i buyer stranieri."),
  ("Siamo a pochi chilometri.","Sede a Mansuè (TV): sopralluoghi, consegne e interventi rapidissimi, anche durante la fiera.")],
 tempi="Sicam si tiene a ottobre. Se esponi quest'anno e serve ancora una mano per materiali o montaggio, scrivici subito: essendo vicini a Pordenone Fiere possiamo intervenire anche a ridosso dell'apertura.",
 qa=[("Siete vicini a Pordenone Fiere?","Sì, la nostra sede è a Mansuè, in provincia di Treviso, a pochi chilometri dal quartiere fieristico: per Sicam riusciamo a seguire sopralluoghi e urgenze in tempi brevissimi."),
  ("Potete progettare pareti per esporre ferramenta e componenti?","Sì, con pannelli attrezzati, binari, mensole e cassettiere progettati sui tuoi prodotti e sul numero di referenze da esporre."),
  ("Lo stand si può riusare per altre fiere del mobile?","Sì: con una struttura modulare di proprietà lo stand torna a Sicam l'anno successivo e può essere riconfigurato per interzum o altre fiere estere.")],
 off=["Stand per Sicam","Pareti attrezzate per campionari","Montaggio a Pordenone Fiere","Interventi rapidi in Friuli e Veneto"]),

dict(k="samuexpo",cal=["samuexpo"],nome="Samuexpo",citta="Pordenone",cs="pordenone",q="Pordenone Fiere",sett="industria",cad="Biennale, a febbraio",exp=True,
 lead="Stand per Samuexpo a Pordenone Fiere: pedane per macchinari, allacci elettrici, aree per incontri tecnici, grafica e montaggio. Abbiamo già allestito stand al Samuexpo e la nostra sede è a pochi chilometri.",
 intro=["Samuexpo è la fiera di Pordenone dedicata alle tecnologie per la lavorazione dei metalli e delle materie plastiche, alla subfornitura meccanica e alla produzione industriale. Riunisce costruttori di macchine, terzisti e fornitori di tecnologia del Nord Est e non solo.",
  "Agli stand di Samuexpo i visitatori sono tecnici e responsabili di produzione: vogliono vedere la macchina, il pezzo lavorato, la tolleranza raggiunta. Il progetto deve mettere in sicurezza macchinari spesso pesanti e in funzione, e dare spazio a campioni e schermi che spieghino lavorazioni e capacità produttive."],
 esig=[("Pedane e allacci per macchinari.","Basamenti portanti, potenza elettrica adeguata ed eventuale aria compressa per le macchine in funzione."),
  ("Vetrine per pezzi lavorati.","Teche e banchi per esporre particolari e campioni di lavorazione, con illuminazione che ne mostri le finiture."),
  ("Schermi e video.","Monitor e ledwall per mostrare impianti, reparti e lavorazioni che non si possono portare in fiera."),
  ("Spazi per incontri tecnici.","Tavoli per discutere disegni, lotti e tempi con i clienti."),
  ("Vicinanza.","Sede a pochi chilometri da Pordenone Fiere: sopralluoghi e assistenza durante la fiera senza costi di trasferta.")],
 tempi="La prossima edizione di Samuexpo è a febbraio 2028. È un ottimo momento per impostare uno stand modulare di proprietà, da usare anche nelle altre fiere della meccanica in Italia e all'estero.",
 qa=[("Potete esporre macchinari in funzione allo stand?","Sì, con basamenti dimensionati, protezioni, potenza elettrica e, se serve, aria compressa, nel rispetto del regolamento tecnico."),
  ("Fate stand riutilizzabili per più fiere della meccanica?","Sì, gli stand modulari si riconfigurano su metrature diverse: lo stesso stand può andare a Samuexpo, MECSPE o fiere estere."),
  ("Siete vicini a Pordenone?","Sì, la nostra sede è a Mansuè (TV), a pochi chilometri dal quartiere fieristico.")],
 off=["Stand per Samuexpo","Pedane e allacci per macchinari","Stand modulari per fiere della meccanica","Montaggio a Pordenone Fiere"]),

dict(k="sigep",cal=["sigep"],nome="Sigep World",citta="Rimini",cs="rimini",q="Rimini Expo Centre",sett="food",cad="Annuale, a gennaio",exp=False,
 lead="Stand per Sigep World a Rimini: laboratori a vista, vetrine per gelato e pasticceria, allacci elettrici e idrici, aree assaggio, grafica e montaggio al Rimini Expo Centre.",
 intro=["Sigep World è la fiera internazionale del foodservice dolce: gelateria, pasticceria, panificazione, cioccolato e caffè. A gennaio, al Rimini Expo Centre, produttori di ingredienti, macchine, vetrine e arredi incontrano artigiani, catene e distributori da tutto il mondo.",
  "Al Sigep si lavora dal vivo: il gelato si manteca davanti al pubblico, i pasticceri fanno dimostrazioni, il caffè si estrae in continuazione. Lo stand è un laboratorio aperto, con macchine assetate di potenza elettrica, acqua e scarichi, e deve restare pulito e attraente per cinque giorni di lavoro intenso."],
 esig=[("Laboratorio a vista.","Piani di lavoro, lavelli e attrezzature disposti perché il pubblico veda le lavorazioni senza intralciare chi lavora."),
  ("Vetrine refrigerate.","Vetrine per gelato e pasticceria integrate nel bancone, con potenza elettrica e ventilazione previste nel progetto."),
  ("Allacci idrici e scarichi.","Acqua e scarichi per macchine, lavaggio e laboratorio, coordinati con i servizi tecnici della fiera."),
  ("Aree assaggio e palco demo.","Spazi dove il pubblico assaggia e segue le dimostrazioni, con microfoni e schermi se servono."),
  ("Superfici facili da pulire.","Materiali resistenti a zucchero, latte e acqua: lo stand deve restare in ordine fino all'ultimo giorno.")],
 tempi="Sigep è a gennaio: le richieste di allacci e potenze elettriche vanno chiuse entro le scadenze dell'ente fiera, di solito in autunno. Se esponi al prossimo Sigep, è il momento di definire il layout del laboratorio.",
 qa=[("Potete portare acqua e scarichi in uno stand al Sigep?","Sì, li prevediamo nel progetto e li coordiniamo con i servizi tecnici del Rimini Expo Centre."),
  ("Integrate vetrine per gelato già di nostra proprietà?","Sì, progettiamo banconi e retrobanchi sulle misure delle tue vetrine e calcoliamo le potenze necessarie."),
  ("Quanto prima bisogna iniziare?","Per uno stand con laboratorio, almeno 3 mesi prima: gli impianti richiedono pratiche con l'ente fiera entro scadenze precise.")],
 off=["Stand per Sigep World","Laboratori a vista e banconi su misura","Allacci elettrici e idrici","Montaggio al Rimini Expo Centre"]),

dict(k="cibus",cal=["cibus","cibus-tec"],nome="Cibus",citta="Parma",cs="parma",q="Fiere di Parma",sett="food",cad="Cibus a maggio; Cibus Tec a ottobre",exp=False,
 lead="Stand per Cibus e Cibus Tec a Fiere di Parma: banchi refrigerati, aree assaggio, magazzino, salottini per i buyer della distribuzione, grafica e montaggio.",
 intro=["Cibus è la fiera internazionale dell'agroalimentare italiano: a Parma, nel cuore della food valley, produttori di salumi, formaggi, pasta, conserve, dolci e bevande incontrano i buyer della grande distribuzione, del canale horeca e dell'export. Cibus Tec, dedicata alle tecnologie per l'industria alimentare, completa il calendario di Fiere di Parma.",
  "Lo stand di un'azienda alimentare a Cibus deve far assaggiare e far parlare di numeri: banchi refrigerati per conservare il prodotto, spazi per tagliare e servire in sicurezza, e salottini dove i buyer discutono assortimenti, listini e private label. Un layout sbagliato mescola le due cose e fa perdere appuntamenti."],
 esig=[("Banchi refrigerati e frigoriferi.","Esposizione del prodotto fresco alla temperatura giusta, con potenze elettriche calcolate."),
  ("Zona taglio e assaggio.","Piani di lavoro, lavelli e attrezzature per servire assaggi in modo igienico."),
  ("Salottini per i buyer.","Aree riservate per le trattative con la distribuzione e gli importatori."),
  ("Magazzino e celle.","Spazio chiuso per scorte, packaging e materiale promozionale."),
  ("Grafica per il retail.","Prodotto in primo piano, packaging leggibili, origine e certificazioni ben visibili.")],
 tempi="Cibus si tiene a maggio. Per stand con frigoriferi e zone assaggio conviene definire layout e impianti in inverno, quando si chiudono le richieste tecniche con l'ente fiera.",
 qa=[("Potete fornire banchi frigo e attrezzature per gli assaggi?","Sì, a noleggio insieme allo stand, con il calcolo della potenza elettrica necessaria."),
  ("Fate anche stand per Cibus Tec?","Sì: per le tecnologie alimentari servono pedane per macchinari, allacci e schermi per spiegare gli impianti."),
  ("Avete soluzioni per chi fa molte fiere food in Europa?","Sì, uno stand modulare di proprietà si riusa a Cibus, Anuga, SIAL e nelle altre fiere del settore. Le date sono nel <a href=\"/calendario-fiere/\">calendario fiere</a>.")],
 off=["Stand per Cibus","Stand per Cibus Tec","Banchi refrigerati a noleggio","Montaggio a Fiere di Parma"]),

dict(k="vicenzaoro",cal=["vicenzaoro"],nome="VicenzaOro",citta="Vicenza",cs="vicenza",q="Vicenza Expo Centre",sett="gioielli",cad="A gennaio e a settembre",exp=False,
 lead="Stand per VicenzaOro: vetrine e teche di sicurezza, illuminazione per preziosi, salottini riservati, grafica e montaggio al Vicenza Expo Centre, con un fornitore veneto.",
 intro=["VicenzaOro è uno degli appuntamenti internazionali di riferimento per gioielleria e oreficeria. Al Vicenza Expo Centre, a gennaio e a settembre, produttori, designer e grossisti incontrano buyer da tutto il mondo; accanto si tengono T.Gold, dedicata alle tecnologie per la lavorazione dei preziosi, e VO Vintage.",
  "Lo stand per la gioielleria è uno degli allestimenti più delicati: deve proteggere merce di grande valore, esaltare metalli e pietre con una luce precisa e offrire riservatezza alle trattative. Il visitatore deve sentirsi in una boutique, non in un padiglione."],
 esig=[("Vetrine e teche di sicurezza.","Teche con vetri adeguati e serrature, integrate negli arredi dello stand."),
  ("Luce per metalli e pietre.","Faretti puntuali e temperatura colore scelta per far brillare oro, argento e gemme senza riflessi fastidiosi."),
  ("Salottini riservati.","Aree chiuse o semichiuse per mostrare le collezioni e trattare con i buyer in tranquillità."),
  ("Finiture da boutique.","Materiali, tessuti e colori coerenti con il posizionamento del marchio."),
  ("Fornitore veneto.","Siamo in regione: sopralluoghi e assistenza rapidi a Vicenza.")],
 tempi="L'edizione di gennaio arriva subito dopo le feste: progetto e produzione vanno chiusi entro novembre. Per l'edizione di settembre conviene partire in primavera.",
 qa=[("Potete realizzare vetrine di sicurezza per gioielli?","Sì, progettiamo teche e vetrine integrate nello stand, con le caratteristiche di sicurezza richieste dal tuo assicuratore."),
  ("Fate stand anche per T.Gold?","Sì, per le tecnologie orafe servono pedane e allacci per macchinari e spazi per le dimostrazioni."),
  ("Siete vicini a Vicenza?","Sì, siamo in Veneto, in provincia di Treviso: per VicenzaOro seguiamo sopralluoghi e assistenza in fiera senza trasferte lunghe.")],
 off=["Stand per VicenzaOro","Vetrine e teche per gioielleria","Illuminazione per preziosi","Montaggio al Vicenza Expo Centre"]),

dict(k="ecomondo",cal=["ecomondo"],nome="Ecomondo",citta="Rimini",cs="rimini",q="Rimini Expo Centre",sett="ambiente",cad="Annuale, a novembre",exp=False,
 lead="Stand per Ecomondo a Rimini, anche riutilizzabili e a basso impatto: strutture modulari, tessuti riciclabili, illuminazione LED, aree incontri e montaggio al Rimini Expo Centre.",
 intro=["Ecomondo è la fiera della green technology e dell'economia circolare: gestione dei rifiuti, riciclo, trattamento delle acque, bonifiche, bioeconomia. A novembre, al Rimini Expo Centre, imprese, utility, enti pubblici e tecnici si confrontano sulle tecnologie per l'ambiente.",
  "Per chi espone a Ecomondo lo stand è anche un messaggio: difficile parlare di economia circolare da uno stand costruito per essere buttato dopo quattro giorni. Strutture riutilizzabili, materiali riciclabili e consumi ridotti sono una scelta coerente, oltre che un risparmio sulle edizioni successive."],
 esig=[("Strutture riutilizzabili.","Telai modulari in alluminio che si smontano, si conservano e si rimontano per anni."),
  ("Materiali riciclabili.","Grafiche su tessuto riciclabile, pannelli recuperabili, arredi a noleggio invece che usa e getta."),
  ("Consumi ridotti.","Illuminazione LED e impianti dimensionati sul reale fabbisogno."),
  ("Impianti e macchinari.","Pedane e allacci per chi espone tecnologie per il trattamento di acque e rifiuti."),
  ("Sale riunioni.","Spazi per incontri con enti, utility e partner industriali.")],
 tempi="Ecomondo si tiene a novembre. Se esponi quest'anno e cerchi ancora chi monti lo stand, scrivici subito; per l'edizione successiva conviene impostare in primavera uno stand modulare di proprietà.",
 qa=[("Potete realizzare uno stand riutilizzabile per Ecomondo?","Sì, con strutture modulari in alluminio e grafiche in tessuto che si conservano nel nostro magazzino e si riusano. Vedi <a href=\"/stand-fieristici-ecosostenibili/\">stand ecosostenibili</a>."),
  ("Avete pedane per esporre macchinari?","Sì, dimensionate sul peso e con gli allacci necessari."),
  ("Lavorate con poco preavviso?","Sì, valutiamo anche richieste urgenti, soprattutto con soluzioni modulari.")],
 off=["Stand per Ecomondo","Stand riutilizzabili e a basso impatto","Pedane per impianti e macchinari","Montaggio al Rimini Expo Centre"]),

dict(k="pitti-uomo",cal=["pitti-uomo","pitti-uomo-giugno"],nome="Pitti Uomo",citta="Firenze",cs="firenze",q="Fortezza da Basso",sett="moda",cad="Due edizioni l'anno, a gennaio e a giugno",exp=False,
 lead="Stand per Pitti Uomo alla Fortezza da Basso di Firenze: allestimenti da boutique, appendiabiti e mensole, luce per tessuti, grafica e montaggio nel rispetto delle regole di uno spazio storico.",
 intro=["Pitti Uomo è il salone internazionale della moda maschile: due edizioni l'anno, a gennaio e a giugno, nella Fortezza da Basso di Firenze. Marchi di abbigliamento e accessori presentano le collezioni a buyer, stampa e influencer, in un contesto che è anche un evento di stile.",
  "La Fortezza da Basso è un complesso storico, con padiglioni e spazi molto diversi fra loro. Gli allestimenti devono essere leggeri, rispettosi dei vincoli e veloci da montare, ma allo stesso tempo curati come un negozio: chi visita Pitti giudica il marchio anche da come è vestito lo stand."],
 esig=[("Stand come una boutique.","Appendiabiti, mensole, tavoli espositivi e manichini disposti per raccontare la collezione."),
  ("Luce per i tessuti.","Illuminazione che restituisce colori e texture dei capi, senza ombre dure."),
  ("Spazi per buyer e stampa.","Tavolo per ordini e un angolo per interviste e contenuti social."),
  ("Allestimenti leggeri.","Strutture autoportanti e facili da montare, compatibili con le regole di uno spazio storico."),
  ("Regolamento della manifestazione.","Alcune sezioni hanno regole di allestimento proprie: le verifichiamo noi prima di progettare.")],
 tempi="Con due edizioni l'anno, conviene progettare uno stand che si riallestisce: struttura e arredi di proprietà, conservati in magazzino, e grafiche nuove a ogni stagione.",
 qa=[("Potete allestire stand alla Fortezza da Basso?","Sì, con strutture leggere e autoportanti, rispettando le regole dell'organizzatore e i vincoli degli spazi storici."),
  ("Lo stesso stand si può usare a gennaio e a giugno?","Sì: struttura e arredi restano, cambiano grafiche e disposizione in base alla collezione."),
  ("Fate stand anche per Pitti Bimbo, Pitti Filati e Taste?","Sì, le date di tutte le manifestazioni sono nel <a href=\"/calendario-fiere/\">calendario fiere</a>.")],
 off=["Stand per Pitti Uomo","Allestimenti boutique per la moda","Strutture leggere per spazi storici","Montaggio alla Fortezza da Basso"]),

dict(k="micam",cal=["micam-feb","micam-set"],nome="MICAM Milano",citta="Milano",cs="milano",q="Fiera Milano Rho",sett="moda",cad="Due edizioni l'anno, a febbraio e a settembre",exp=False,
 lead="Stand per MICAM Milano a Fiera Milano Rho: espositori per calzature, mensole illuminate, sedute per la prova, magazzino campionario, grafica e montaggio.",
 intro=["MICAM Milano è il salone internazionale della calzatura: due edizioni l'anno, a febbraio e a settembre, a Fiera Milano Rho, in contemporanea con altre manifestazioni della filiera moda e pelle. Calzaturifici e marchi presentano le collezioni a buyer e negozi da tutto il mondo.",
  "Le scarpe si vendono quando si vedono bene e si toccano: lo stand deve esporre decine di modelli in poco spazio, con luce che valorizzi pellami e colori, e offrire ai buyer un tavolo dove sfogliare il campionario e scrivere l'ordine."],
 esig=[("Mensole e pareti espositive.","Mensole illuminate, nicchie e pareti attrezzate per mostrare molti modelli in modo ordinato."),
  ("Luce per pellami.","Illuminazione che restituisce texture e colori di pelle, scamosciato e tessuti."),
  ("Tavoli ordini.","Postazioni per i buyer, con spazio per campionario e listini."),
  ("Magazzino campionario.","Retro chiuso per scatole, paia di scorta e materiali."),
  ("Stand riallestibile.","Struttura riutilizzata a ogni edizione, con grafiche aggiornate sulla collezione.")],
 tempi="Con due edizioni l'anno, la soluzione più conveniente è spesso uno stand modulare di proprietà conservato in magazzino: si progetta una volta e si riallestisce a ogni stagione.",
 qa=[("Potete conservare lo stand fra un MICAM e l'altro?","Sì, lo teniamo nel nostro magazzino e lo riportiamo in fiera, aggiornando grafiche e disposizione."),
  ("Quanti modelli si possono esporre in uno stand piccolo?","Dipende dal layout: con pareti attrezzate e mensole su più livelli anche 16–24 mq ospitano un campionario ampio. Vedi <a href=\"/stand-fieristici-piccoli/\">stand piccoli</a>."),
  ("Fate stand anche per Expo Riva Schuh?","Sì, vedi la pagina <a href=\"/stand-expo-riva-schuh/\">stand per Expo Riva Schuh</a>.")],
 off=["Stand per MICAM","Espositori per calzature","Stand riallestibili per due edizioni l'anno","Montaggio a Fiera Milano Rho"]),

dict(k="mido",cal=["mido"],nome="MIDO",citta="Milano",cs="milano",q="Fiera Milano Rho",sett="moda",cad="Annuale, a febbraio",exp=False,
 lead="Stand per MIDO, la fiera dell'occhialeria a Fiera Milano Rho: teche ed espositori per montature, specchi e postazioni prova, luce dedicata, grafica e montaggio.",
 intro=["MIDO è la fiera internazionale dell'occhialeria: montature, occhiali da sole, lenti, macchinari per l'ottica e arredi per negozi. Ogni febbraio, a Fiera Milano Rho, produttori e marchi incontrano ottici, catene e distributori da tutto il mondo.",
  "Un occhiale si sceglie provandolo: lo stand deve avere espositori ordinati e sicuri, specchi ben illuminati e postazioni comode per i buyer, che passano molto tempo seduti a selezionare modelli. Le sezioni della fiera hanno identità molto diverse, dal design di ricerca ai grandi gruppi."],
 esig=[("Teche ed espositori sicuri.","Espositori con chiusura per le montature, ordinati per collezione."),
  ("Postazioni prova con specchi.","Tavoli e specchi con illuminazione frontale uniforme, che non crea ombre sul viso."),
  ("Luce controllata.","Illuminazione che evita riflessi sulle lenti e valorizza materiali come acetato e metallo."),
  ("Spazi per ordini.","Tavoli e sedute comode per sessioni di selezione lunghe."),
  ("Arredi per l'ottica.","Per chi espone arredi per negozi, ambientazioni che mostrano un punto vendita completo.")],
 tempi="MIDO è a febbraio: progetto e produzione vanno chiusi entro dicembre, prima della pausa natalizia.",
 qa=[("Che illuminazione serve per esporre occhiali?","Luce diffusa e uniforme sulle postazioni prova e faretti mirati sugli espositori, con schermature per evitare riflessi sulle lenti."),
  ("Potete realizzare espositori con chiusura?","Sì, teche ed espositori su misura con serrature, integrati negli arredi dello stand."),
  ("Lo stand si può riutilizzare per Silmo o altre fiere estere?","Sì, con una struttura modulare si adatta a metrature diverse. Trovi le date nel <a href=\"/calendario-fiere/\">calendario fiere</a>.")],
 off=["Stand per MIDO","Espositori e teche per occhialeria","Postazioni prova illuminate","Montaggio a Fiera Milano Rho"]),

dict(k="macfrut",cal=["macfrut"],nome="Macfrut",citta="Rimini",cs="rimini",q="Rimini Expo Centre",sett="agri",cad="Annuale, in primavera",exp=False,
 lead="Stand per Macfrut, la fiera dell'ortofrutta al Rimini Expo Centre: esposizione del prodotto fresco, refrigerazione, pedane per macchinari, aree incontri e montaggio.",
 intro=["Macfrut è la fiera internazionale della filiera ortofrutticola: produttori, consorzi, aziende di sementi, tecnologie per la raccolta e il confezionamento, logistica e distribuzione. Si tiene in primavera al Rimini Expo Centre, con una forte presenza di buyer esteri.",
  "Esporre frutta e verdura significa lavorare con un prodotto vivo, che deve restare bello per tre giorni. Accanto al fresco ci sono macchine per selezione e confezionamento, imballaggi e servizi: lo stand deve tenere insieme colore, freschezza e tecnica."],
 esig=[("Esposizione del fresco.","Banchi, cassette e vetrine refrigerate che mantengono il prodotto in condizioni perfette."),
  ("Pedane per macchinari.","Basamenti portanti e allacci per macchine di selezione, lavaggio e confezionamento."),
  ("Salottini per buyer esteri.","Spazi riservati per trattative, con grafica e materiali anche in inglese."),
  ("Grafica di territorio.","Origine, varietà e certificazioni raccontate in modo chiaro."),
  ("Stand collettivi.","Postazioni coordinate per consorzi, regioni e organizzazioni di produttori.")],
 tempi="Macfrut è in primavera: per stand con refrigerazione e macchinari conviene impostare il progetto in inverno.",
 qa=[("Potete fornire vetrine refrigerate per la frutta?","Sì, a noleggio insieme allo stand, con il calcolo della potenza elettrica."),
  ("Allestite stand collettivi per consorzi e regioni?","Sì, con postazioni coordinate, grafica comune e aree condivise."),
  ("Fate stand anche per Fruit Logistica e Fruit Attraction?","Sì, le date sono nel <a href=\"/calendario-fiere/\">calendario fiere</a>; vedi anche <a href=\"/allestimenti-fieristici-estero/\">stand all'estero</a>.")],
 off=["Stand per Macfrut","Vetrine refrigerate a noleggio","Stand collettivi per consorzi","Montaggio al Rimini Expo Centre"]),

dict(k="expo-riva-schuh",cal=["expo-riva-schuh","expo-riva-schuh-giugno"],nome="Expo Riva Schuh",citta="Riva del Garda",cs="riva-del-garda",q="Riva del Garda Fierecongressi",sett="moda",cad="Due edizioni l'anno, a gennaio e a giugno",exp=False,
 lead="Stand per Expo Riva Schuh & Gardabags a Riva del Garda: espositori per calzature e borse, tavoli ordini, magazzino campionario, grafica e montaggio, con stand riallestibili a ogni edizione.",
 intro=["Expo Riva Schuh & Gardabags è la fiera internazionale dedicata alla calzatura e alla pelletteria di volume. Due volte l'anno, a gennaio e a giugno, a Riva del Garda, produttori e importatori da tutto il mondo incontrano catene, grossisti e grande distribuzione.",
  "È una fiera molto commerciale: i buyer arrivano con agende fitte e budget da allocare. Lo stand deve mostrare tanti articoli in modo ordinato, far lavorare bene i venditori e farsi riconoscere in un quartiere fieristico con molti espositori su metrature simili."],
 esig=[("Pareti espositive ad alta densità.","Mensole e pareti attrezzate per esporre molti modelli di scarpe e borse."),
  ("Tavoli ordini.","Postazioni per i buyer, con campionario e listini a portata di mano."),
  ("Magazzino.","Retro chiuso per scatole, campionari e materiali."),
  ("Insegna riconoscibile.","Grafica alta e leggibile per farsi trovare nei corridoi."),
  ("Stand riallestibile.","Due edizioni l'anno: struttura e arredi di proprietà, grafiche aggiornate.")],
 tempi="Con due edizioni l'anno e molti espositori esteri, la soluzione più pratica è affidarci stand, magazzino e montaggio: lo conserviamo noi e lo riportiamo a Riva a ogni edizione.",
 qa=[("Potete conservare lo stand tra un'edizione e l'altra?","Sì, lo teniamo in magazzino e lo rimontiamo a ogni edizione, cambiando le grafiche."),
  ("Lavorate con aziende estere che espongono a Riva del Garda?","Sì, seguiamo anche espositori stranieri, con un unico referente in Italia."),
  ("Fate stand anche per MICAM?","Sì, vedi la pagina <a href=\"/stand-micam/\">stand per MICAM Milano</a>.")],
 off=["Stand per Expo Riva Schuh","Espositori per calzature e borse","Magazzino e riallestimento","Montaggio a Riva del Garda"]),

dict(k="fieracavalli",cal=["fieracavalli"],nome="Fieracavalli",citta="Verona",cs="verona",q="Veronafiere",sett="agri",cad="Annuale, a novembre",exp=False,
 lead="Stand per Fieracavalli a Veronafiere: stand commerciali per selleria, abbigliamento e attrezzature equestri, aree espositive, grafica e montaggio, con un fornitore veneto.",
 intro=["Fieracavalli è la manifestazione internazionale dedicata al mondo del cavallo: sport equestri, allevamento, turismo a cavallo, selleria, abbigliamento, mangimi e attrezzature. Ogni novembre a Veronafiere unisce un pubblico di appassionati molto numeroso e una parte professionale per allevatori e operatori.",
  "Per le aziende commerciali lo stand deve funzionare come un negozio: tanti articoli esposti, possibilità di provare e acquistare, magazzino per rifornire durante la giornata. Per allevamenti e associazioni conta l'immagine e lo spazio per incontrare clienti e soci."],
 esig=[("Stand-negozio.","Pareti attrezzate, banchi vendita e camerini per abbigliamento e selleria."),
  ("Magazzino di rifornimento.","Retro chiuso per le scorte, accessibile senza attraversare lo stand."),
  ("Pavimenti resistenti.","Pavimentazioni adatte a un grande afflusso di pubblico."),
  ("Immagine e accoglienza.","Grafica e arredi per allevamenti, associazioni e turismo equestre."),
  ("Fornitore veneto.","Siamo in Veneto: sopralluoghi e assistenza rapidi a Verona.")],
 tempi="Fieracavalli è a novembre. Se esponi quest'anno e hai bisogno di una mano per l'allestimento, contattaci subito: lavoriamo anche con poco preavviso.",
 qa=[("Potete realizzare uno stand con area vendita?","Sì, con banchi cassa, pareti attrezzate, camerini e magazzino di rifornimento."),
  ("Siete vicini a Verona?","Sì, siamo in Veneto e lavoriamo a Veronafiere da anni."),
  ("Accettate richieste urgenti?","Sì, valutiamo subito materiali e squadre disponibili.")],
 off=["Stand per Fieracavalli","Stand con area vendita","Montaggio a Veronafiere","Allestimenti per allevamenti e associazioni"]),
]
