# -*- coding: utf-8 -*-
# Nuove pagine /allestimenti-fieristici-<citta>/ (ottobre 2026). Nessuna esperienza dichiarata dove non c'e'.
C=[
dict(s="firenze",c="Firenze",q="Firenze Fiera",venue="firenze",sedi="Fortezza da Basso, Palazzo dei Congressi e Palazzo degli Affari",
 fiere=[("Pitti Uomo","pitti-uomo"),("Pitti Bimbo",None),("Pitti Filati",None),("Taste",None),("Congressi medici e scientifici",None)],
 lead="Allestimenti fieristici a Firenze: stand per Pitti Immagine alla Fortezza da Basso, congressi e mostre. Strutture leggere adatte agli spazi storici, grafica, luci e montatori, con un unico referente.",
 intro=["Firenze ospita fiere e congressi in spazi che non hanno eguali in Italia: la Fortezza da Basso, fortificazione cinquecentesca trasformata in quartiere espositivo, il Palazzo dei Congressi e il Palazzo degli Affari. È la casa di Pitti Immagine, con Pitti Uomo, Pitti Bimbo, Pitti Filati e Taste, e di molti congressi internazionali.",
  "Allestire in uno spazio storico significa rispettare regole precise su ancoraggi, carichi, altezze e accessi dei mezzi. Gli stand devono essere autoportanti, leggeri e veloci da montare, ma curati come una boutique, perché il pubblico di Pitti guarda lo stand con gli occhi di chi lavora nella moda."],
 sapere=[("Spazi storici, regole precise.","Niente forature, carichi limitati, accessi regolati: progettiamo strutture autoportanti compatibili con i vincoli della Fortezza."),
  ("Moda: lo stand è una vetrina.","Appendiabiti, mensole, manichini e luce sui tessuti: lo spazio racconta la collezione come in negozio."),
  ("Due stagioni l'anno.","Gennaio e giugno: struttura e arredi di proprietà, grafiche nuove a ogni edizione, magazzino fra una e l'altra."),
  ("Congressi e sponsor.","Desk, fondali e stand sponsor per i congressi al Palazzo dei Congressi e al Palazzo degli Affari.")],
 qa=[("Potete allestire stand alla Fortezza da Basso?","Sì, con strutture leggere e autoportanti, nel rispetto delle regole dell'organizzatore e dei vincoli degli spazi storici."),
  ("Fate allestimenti per congressi a Firenze?","Sì: stand per sponsor, desk di accoglienza, fondali, segnaletica, luci e schermi.")]),
dict(s="torino",c="Torino",q="Lingotto Fiere",venue="torino",sedi="Lingotto Fiere, Oval e centri congressi cittadini",
 fiere=[("Salone Internazionale del Libro",None),("Automation & Testing",None),("Fiere di settore e congressi",None)],
 lead="Allestimenti fieristici a Torino: stand per Lingotto Fiere e Oval, dal Salone del Libro alle fiere dell'automazione e dell'industria. Progetto, materiali, grafica, impianti e montatori in fiera.",
 intro=["A Torino il polo fieristico è il Lingotto, l'ex stabilimento automobilistico trasformato in centro espositivo e congressuale, affiancato dall'Oval. Ospita il Salone Internazionale del Libro, fiere dedicate all'automazione, all'industria e all'automotive, e congressi di respiro nazionale.",
  "La tradizione industriale della città si sente anche in fiera: molti espositori portano macchine, componenti e tecnologie da mostrare in funzione. Accanto, il Salone del Libro porta un pubblico enorme e stand che devono reggere flussi continui di visitatori e scaffalature cariche."],
 sapere=[("Editoria: scaffali e flussi.","Librerie e banchi vendita robusti, casse, magazzino e percorsi che reggono migliaia di visitatori al giorno."),
  ("Industria e automazione.","Pedane, allacci elettrici e aria compressa per macchine in funzione, schermi per spiegare processi e impianti."),
  ("Stand riutilizzabili.","Per chi espone più volte l'anno, una struttura modulare di proprietà riduce costi e tempi."),
  ("Dal Veneto al Piemonte.","Organizziamo trasporto, squadre e pass per lavorare a Torino come nelle fiere più vicine a noi.")],
 qa=[("Allestite stand per il Salone del Libro?","Sì: scaffalature, banchi vendita, aree incontri con autori, grafica e montaggio al Lingotto."),
  ("Potete esporre macchinari in funzione a Lingotto Fiere?","Sì, con basamenti, allacci e protezioni previsti nel progetto e approvati dall'ente fiera.")]),
dict(s="roma",c="Roma",q="Fiera di Roma",venue="roma",sedi="Fiera di Roma, La Nuvola all'EUR e centri congressi",
 fiere=[("Fiere di settore e B2B",None),("Romics",None),("Congressi nazionali e internazionali",None)],
 lead="Allestimenti fieristici a Roma: stand per la Fiera di Roma, congressi alla Nuvola dell'EUR ed eventi aziendali. Progetto, materiali, grafica, impianti e montatori, con un unico referente.",
 intro=["Roma ha un quartiere fieristico moderno, la Fiera di Roma, sulla via Portuense verso l'aeroporto di Fiumicino, e uno dei centri congressi più riconoscibili d'Europa, La Nuvola all'EUR. Fiere di settore, manifestazioni per il pubblico e grandi congressi si alternano tutto l'anno.",
  "Nella capitale molte occasioni espositive sono legate a congressi, istituzioni e associazioni: stand per sponsor, aree espositive accanto alle sale plenarie, eventi di presentazione. Servono allestimenti curati, veloci da montare e smontare, spesso in finestre di poche ore."],
 sapere=[("Congressi e sponsor.","Stand sponsor, desk di accoglienza, fondali per palchi e segnaletica per congressi e convention."),
  ("Tempi stretti.","Nei centri congressi le finestre di montaggio sono brevi: strutture modulari e grafiche in tessuto teso si montano in fretta."),
  ("Pubblico numeroso.","Per le fiere aperte al pubblico, percorsi, banchi vendita e magazzino."),
  ("Logistica a distanza.","Trasporto, squadre, pass e orari organizzati da noi, con un referente presente in fiera.")],
 qa=[("Allestite stand per congressi alla Nuvola dell'EUR?","Sì: stand sponsor, desk, fondali e segnaletica, nei tempi di montaggio previsti dal centro congressi."),
  ("Lavorate anche nel centro e sud Italia?","Sì, organizziamo trasporto, squadre e pass per lavorare in tutta Italia con la stessa organizzazione.")]),
dict(s="napoli",c="Napoli",q="Mostra d'Oltremare",venue=None,sedi="Mostra d'Oltremare, Stazione Marittima e centri congressi",
 fiere=[("Comicon",None),("Fiere della nautica",None),("Fiere di settore, congressi ed eventi",None)],
 lead="Allestimenti fieristici a Napoli: stand per la Mostra d'Oltremare, fiere della nautica, congressi ed eventi. Progetto, materiali, grafica, impianti e montatori, con un unico referente.",
 intro=["A Napoli la principale area espositiva è la Mostra d'Oltremare, nel quartiere di Fuorigrotta: padiglioni storici e spazi all'aperto che ospitano manifestazioni come il Comicon, fiere della nautica, fiere di settore e grandi eventi. Accanto, la Stazione Marittima e i centri congressi cittadini accolgono convegni ed eventi aziendali.",
  "Molte manifestazioni napoletane usano anche spazi esterni e banchine, con esigenze diverse da un padiglione chiuso: strutture che resistono al vento, coperture, pavimentazioni su terreni non perfettamente piani, impianti elettrici protetti."],
 sapere=[("Spazi interni ed esterni.","Strutture autoportanti per padiglioni storici e allestimenti all'aperto con coperture e zavorre."),
  ("Nautica.","Stand a terra e in banchina per cantieri, accessoristica e servizi."),
  ("Eventi e congressi.","Fondali, desk e stand sponsor per convegni ed eventi aziendali."),
  ("Logistica organizzata.","Trasporto, squadre e pass gestiti da noi, con un unico referente.")],
 qa=[("Fate allestimenti all'aperto per fiere ed eventi a Napoli?","Sì, con strutture zavorrate, coperture e impianti protetti, nel rispetto delle prescrizioni dell'organizzatore."),
  ("Lavorate anche nel sud Italia?","Sì, organizziamo trasporto e squadre per lavorare in tutta Italia.")]),
dict(s="bari",c="Bari",q="Fiera del Levante",venue="bari",sedi="Fiera del Levante, sul lungomare",
 fiere=[("Fiera del Levante (campionaria)",None),("LUV – uva da tavola",None),("Promessi Sposi",None),("Smart Building Levante",None)],
 lead="Allestimenti fieristici a Bari: stand per la Fiera del Levante, dalle fiere agroalimentari a quelle dell'edilizia e degli eventi. Progetto, materiali, grafica, impianti e montatori in fiera.",
 intro=["La Fiera del Levante, affacciata sul lungomare di Bari, è il principale quartiere fieristico del sud Italia e un ponte verso i mercati del Mediterraneo e dei Balcani. Oltre alla storica campionaria di settembre ospita fiere agroalimentari come LUV, dedicata all'uva da tavola, manifestazioni sull'edilizia e l'impiantistica e fiere per il pubblico.",
  "Il calendario barese mescola eventi B2B e manifestazioni per il grande pubblico. Per un'azienda che arriva da fuori regione la sfida è logistica: materiali, squadre e pratiche devono arrivare organizzati, senza sorprese il giorno dell'allestimento."],
 sapere=[("Agroalimentare.","Banchi refrigerati, aree assaggio e salottini per buyer, anche esteri."),
  ("Edilizia e impianti.","Pareti attrezzate e pedane per materiali e macchinari."),
  ("Fiere per il pubblico.","Stand-negozio con area vendita e magazzino di rifornimento."),
  ("Organizzazione a distanza.","Trasporto, squadre, pass e pratiche con l'ente fiera gestiti da noi.")],
 qa=[("Allestite stand alla Fiera del Levante?","Sì: progetto, materiali, grafica, impianti e montaggio, con trasporto e squadre organizzati da noi."),
  ("Avete soluzioni per fiere agroalimentari come LUV?","Sì: banchi refrigerati, aree assaggio e spazi per incontri con i buyer.")]),
dict(s="genova",c="Genova",q="Fiera di Genova",venue="genova",sedi="Fiera di Genova e Waterfront di Levante",
 fiere=[("Salone Nautico Internazionale",None),("Fiere di settore ed eventi",None)],
 lead="Allestimenti fieristici a Genova: stand per il Salone Nautico, a terra e in banchina, e per le fiere del quartiere fieristico. Strutture per esterni, grafica, impianti e montatori.",
 intro=["Genova è la città del Salone Nautico Internazionale, l'appuntamento di riferimento per la nautica da diporto, che si svolge fra il quartiere fieristico e il Waterfront di Levante, con padiglioni, aree a terra e pontili in acqua.",
  "Gli stand per la nautica vivono spesso all'aperto: devono resistere a vento, sole e umidità, essere zavorrati e non forati, garantire impianti elettrici protetti e accoglienza di alto livello per armatori e clienti. Un tipo di allestimento con regole tutte sue."],
 sapere=[("All'aperto, vicino al mare.","Strutture zavorrate e resistenti al vento, coperture, materiali che sopportano sole e salsedine."),
  ("Accoglienza di livello.","Lounge, bar e salottini per clienti e armatori, con arredi da esterno di qualità."),
  ("Impianti protetti.","Impianto elettrico adatto agli spazi esterni, con dichiarazione di conformità."),
  ("Accessoristica e servizi.","Stand in padiglione con pareti attrezzate per componenti, elettronica e accessori nautici.")],
 qa=[("Allestite stand per il Salone Nautico di Genova?","Sì, a terra e nelle aree esterne: strutture zavorrate, coperture, lounge, grafica e impianti."),
  ("Fate stand anche per altre fiere della nautica?","Sì, in Italia e all'estero, come boot Düsseldorf e METSTRADE: le date sono nel <a href=\"/calendario-fiere/\">calendario fiere</a>.")]),
dict(s="bergamo",c="Bergamo",q="Fiera di Bergamo",venue=None,sedi="Fiera di Bergamo e centri congressi",
 fiere=[("Fiere di settore e per il pubblico",None),("Congressi ed eventi aziendali",None)],
 lead="Allestimenti fieristici a Bergamo: stand per la Fiera di Bergamo, eventi aziendali e congressi, a pochi chilometri da Milano e dall'aeroporto. Progetto, materiali, grafica e montatori in fiera.",
 intro=["Bergamo ha un quartiere fieristico moderno a ridosso della città e dell'aeroporto di Orio al Serio, con un calendario di fiere di settore, manifestazioni per il pubblico ed eventi aziendali. È anche il territorio di un tessuto industriale fra i più dinamici d'Italia, che espone in fiera in Italia e all'estero.",
  "Per le aziende bergamasche lavoriamo spesso su due fronti: lo stand per la fiera di casa e lo stand che gira l'Italia e l'Europa. Ha senso progettarli insieme, con una struttura modulare di proprietà che si adatta a metrature e fiere diverse."],
 sapere=[("Fiera di casa e fiere in trasferta.","Uno stand modulare di proprietà che si adatta a Bergamo, Milano e alle fiere estere."),
  ("Eventi aziendali.","Convention, presentazioni di prodotto e open day allestiti in fiera o in azienda."),
  ("Vicino a Milano.","Sinergie con le fiere di Rho per squadre, trasporti e magazzino."),
  ("Industria e tecnologia.","Pedane e allacci per macchinari, schermi per spiegare processi.")],
 qa=[("Allestite stand per la Fiera di Bergamo?","Sì: progetto, materiali, grafica, impianti e montaggio, con un unico referente."),
  ("Potete usare lo stesso stand a Bergamo e nelle fiere di Milano?","Sì, una struttura modulare si riconfigura su spazi diversi e la conserviamo in magazzino fra una fiera e l'altra.")]),
dict(s="brescia",c="Brescia",q="Brixia Forum e Centro Fiera Montichiari",venue=None,sedi="Brixia Forum a Brescia e Centro Fiera del Garda a Montichiari",
 fiere=[("Fiere agricole e zootecniche",None),("Fiere della meccanica e dell'industria",None),("Eventi e congressi",None)],
 lead="Allestimenti fieristici a Brescia e Montichiari: stand per il Brixia Forum e il Centro Fiera del Garda, dalle fiere agricole a quelle della meccanica. Progetto, materiali, grafica e montatori.",
 intro=["Il bresciano ha due poli espositivi: il Brixia Forum in città e il Centro Fiera del Garda a Montichiari, con un calendario che riflette l'economia del territorio, fatta di meccanica, metallurgia, agricoltura e zootecnia, oltre a manifestazioni per il pubblico ed eventi.",
  "Le fiere della meccanica e dell'agricoltura hanno esigenze simili: mezzi e macchinari pesanti, pedane portanti, allacci elettrici importanti, spazi per incontri tecnici con clienti e rivenditori. Il nostro lavoro è far arrivare tutto in sicurezza e in tempo."],
 sapere=[("Macchinari e mezzi.","Pedane portanti, protezioni e allacci per macchine in esposizione o in funzione."),
  ("Agricoltura e zootecnia.","Stand per attrezzature, mangimi e servizi, con aree incontro per allevatori e dealer."),
  ("Stand che viaggiano.","Le aziende bresciane espongono in tutta Europa: uno stand modulare di proprietà riduce i costi per fiera."),
  ("Eventi aziendali.","Convention e presentazioni allestite in fiera o negli spazi aziendali.")],
 qa=[("Allestite stand al Centro Fiera di Montichiari?","Sì: progetto, materiali, grafica, impianti e montaggio, anche per mezzi e macchinari."),
  ("Fate stand anche per fiere estere della meccanica?","Sì, come EMO, Hannover Messe e LIGNA: le date sono nel <a href=\"/calendario-fiere/\">calendario fiere</a>.")]),
dict(s="venezia",c="Venezia",q="Venezia e Mestre",venue=None,sedi="spazi congressuali ed espositivi di Venezia, del Lido e di Mestre",
 fiere=[("Congressi ed eventi aziendali",None),("Mostre ed eventi culturali",None),("Fiere ed eventi a Mestre",None)],
 lead="Allestimenti per fiere, congressi, mostre ed eventi a Venezia e Mestre: logistica anche via acqua, strutture leggere per spazi storici, grafica e montatori. Siamo in Veneto, a un'ora di strada.",
 intro=["Venezia non ha un grande quartiere fieristico, ma ospita ogni anno congressi internazionali, eventi aziendali, presentazioni di prodotto e mostre in palazzi storici, ex spazi industriali e centri congressi, al Lido come in città. Mestre e la terraferma completano l'offerta con spazi più facili da raggiungere su gomma.",
  "Allestire a Venezia è un mestiere a parte: i materiali arrivano in barca, si spostano a mano lungo calli e ponti, entrano in edifici vincolati dove non si fora e non si appoggia nulla senza permesso. Per questo progetto e logistica vanno pensati insieme fin dal primo giorno."],
 sapere=[("Logistica via acqua.","Trasporto su barca, trasbordi e consegne a mano organizzati in base agli orari e agli accessi."),
  ("Edifici vincolati.","Strutture autoportanti, niente forature, protezioni per pavimenti e pareti storiche."),
  ("Elementi leggeri e modulari.","Pezzi maneggevoli, montaggio rapido, grafiche in tessuto teso."),
  ("Siamo a un'ora.","La nostra sede è in provincia di Treviso: sopralluoghi e assistenza in tempi rapidi.")],
 qa=[("Organizzate il trasporto via acqua per gli allestimenti a Venezia?","Sì, coordiniamo barche, trasbordi e consegne in base agli accessi e agli orari della sede."),
  ("Potete allestire in palazzi storici e spazi vincolati?","Sì, con strutture autoportanti e protezioni, senza forature, nel rispetto delle prescrizioni della sede.")]),
dict(s="treviso",c="Treviso",q="Treviso e provincia",venue=None,sedi="la nostra sede di Mansuè, in provincia di Treviso",
 fiere=[("Stand per le aziende trevigiane in tutta Italia",None),("Eventi aziendali e open day",None),("Showroom e negozi",None)],
 lead="Allestimenti fieristici a Treviso: siamo in provincia, a Mansuè. Progettiamo, prepariamo e montiamo gli stand delle aziende trevigiane per le fiere in Italia e all'estero, con sopralluoghi in azienda e magazzino vicino.",
 intro=["Treviso è casa nostra: la sede di Danova Tech è a Mansuè, in provincia. La Marca è una delle aree manifatturiere più vivaci d'Italia, fra arredo, meccanica, calzatura, vino e agroalimentare, e le sue aziende espongono ogni anno nelle grandi fiere italiane ed europee.",
  "Lavorare con un fornitore vicino ha vantaggi concreti: il sopralluogo si fa in azienda per vedere i prodotti da esporre, lo stand si può provare montato prima di partire, il magazzino è a pochi chilometri e se serve un intervento dell'ultimo minuto non ci sono trasferte da organizzare."],
 sapere=[("Sopralluogo in azienda.","Vediamo prodotti, campionari e materiali dal vivo prima di progettare lo stand."),
  ("Prova di montaggio.","Per gli stand su misura possiamo premontare le parti principali prima della fiera."),
  ("Magazzino vicino.","Lo stand resta a pochi chilometri dall'azienda fra una fiera e l'altra."),
  ("Dalla Marca a tutta Europa.","Verona, Milano, Bologna, Pordenone e le fiere estere con lo stesso referente.")],
 qa=[("Dove siete?","A Mansuè (TV), in via Rigole 48: seguiamo le aziende di Treviso e provincia e lavoriamo in tutte le fiere italiane ed europee."),
  ("Allestite anche eventi aziendali e showroom in provincia?","Sì: open day, convention, showroom e negozi. Vedi <a href=\"/allestimenti-eventi-showroom-negozi/\">allestimenti per eventi e showroom</a>.")]),
dict(s="udine",c="Udine",q="Udine e Gorizia Fiere",venue="udine",sedi="quartiere fieristico di Torreano di Martignacco",
 fiere=[("Casa Moderna",None),("Fiere agricole e di settore",None),("Eventi e manifestazioni per il pubblico",None)],
 lead="Allestimenti fieristici a Udine: stand per Udine e Gorizia Fiere a Martignacco, da Casa Moderna alle fiere di settore. Siamo a meno di un'ora: progetto, materiali, grafica e montatori.",
 intro=["Il quartiere fieristico di Udine e Gorizia Fiere, a Torreano di Martignacco, ospita manifestazioni come Casa Moderna, dedicata a casa, arredo e abitare, fiere agricole e di settore ed eventi per il pubblico. È la vetrina di un territorio di aziende manifatturiere, del mobile e dell'agroalimentare.",
  "Per noi il Friuli è territorio di casa: siamo a Mansuè, al confine fra Veneto e Friuli, e lavoriamo regolarmente anche a Pordenone Fiere. Sopralluoghi, consegne e interventi durante la fiera sono rapidi e senza costi di trasferta importanti."],
 sapere=[("Casa e arredo.","Ambientazioni, pareti attrezzate e luci per chi espone mobili, serramenti e finiture."),
  ("Fiere per il pubblico.","Stand-negozio con area vendita, magazzino e percorsi."),
  ("Vicinanza.","Meno di un'ora dalla nostra sede: assistenza rapida anche durante la fiera."),
  ("Friuli e Veneto orientale.","Conosciamo il distretto del mobile, la meccanica e l'agroalimentare locali.")],
 qa=[("Allestite stand per Casa Moderna?","Sì: ambientazioni, pareti attrezzate, grafica, luci e montaggio a Martignacco."),
  ("Quanto siete distanti da Udine?","La nostra sede è a Mansuè (TV), a meno di un'ora dal quartiere fieristico.")]),
dict(s="bolzano",c="Bolzano",q="Fiera Bolzano",venue=None,sedi="Fiera Bolzano",
 fiere=[("Klimahouse",None),("Interpoma",None),("Hotel",None),("Prowinter",None),("Fiere agricole e per il pubblico",None)],
 lead="Allestimenti fieristici a Bolzano: stand per Fiera Bolzano, da Klimahouse a Interpoma e Hotel. Grafiche bilingui italiano-tedesco, progetto, materiali, impianti e montatori in fiera.",
 intro=["Fiera Bolzano ospita fiere specializzate che sono riferimenti nei rispettivi settori: Klimahouse per l'edilizia efficiente e sostenibile, Interpoma per la coltivazione e la filiera della mela, Hotel per l'ospitalità alpina, Prowinter per gli sport invernali, accanto a fiere agricole e per il pubblico.",
  "In Alto Adige la comunicazione è bilingue e il pubblico internazionale arriva da Austria, Germania e Svizzera: grafiche, materiali e accoglienza vanno pensati in italiano e tedesco. E molti espositori parlano di sostenibilità, quindi anche lo stand deve esserlo."],
 sapere=[("Grafiche bilingui.","Testi in italiano e tedesco impaginati con cura, senza affollare le pareti."),
  ("Edilizia efficiente.","Per Klimahouse, materiali e soluzioni costruttive mostrati in sezione, campioni da toccare."),
  ("Stand sostenibili.","Strutture riutilizzabili, legno certificato, LED: coerenti con i temi delle fiere altoatesine."),
  ("Ospitalità alpina.","Ambientazioni per hotel e rifugi, con arredi in legno e materiali naturali.")],
 qa=[("Preparate grafiche in italiano e tedesco?","Sì, impaginiamo testi bilingui e se serve ti aiutiamo a organizzare traduzioni e revisioni."),
  ("Potete realizzare uno stand ecosostenibile per Klimahouse?","Sì, con strutture riutilizzabili e materiali certificati. Vedi <a href=\"/stand-fieristici-ecosostenibili/\">stand ecosostenibili</a>.")]),
dict(s="riva-del-garda",c="Riva del Garda",q="Riva del Garda Fierecongressi",venue="riva",sedi="Riva del Garda Fierecongressi e Palazzo dei Congressi",
 fiere=[("Expo Riva Schuh & Gardabags","expo-riva-schuh"),("Hospitality – Il Salone dell'Accoglienza",None),("Congressi ed eventi",None)],
 lead="Allestimenti fieristici a Riva del Garda: stand per Expo Riva Schuh, Hospitality, congressi ed eventi. Progetto, materiali, grafica, impianti e montatori, con stand conservati in magazzino fra un'edizione e l'altra.",
 intro=["Riva del Garda, sulla punta nord del lago, ha un polo fieristico e congressuale con appuntamenti di livello internazionale: Expo Riva Schuh & Gardabags per calzatura e pelletteria, due volte l'anno, e Hospitality, il salone dell'accoglienza dedicato a hotel, ristorazione e turismo. A questi si aggiungono congressi ed eventi.",
  "Molti espositori arrivano dall'estero e tornano a ogni edizione: per loro conta avere un fornitore in Italia che conservi lo stand, lo riporti a Riva e lo rimonti, aggiornando solo grafiche e prodotti. Per Hospitality, invece, servono ambientazioni realistiche di hotel e locali."],
 sapere=[("Calzature e borse.","Pareti espositive ad alta densità, tavoli ordini e magazzino campionario."),
  ("Hospitality.","Ambientazioni di camere, sale e bar per chi espone arredi e forniture per l'accoglienza."),
  ("Espositori esteri.","Un unico referente in Italia per stand, magazzino, trasporto e montaggio."),
  ("Due edizioni l'anno.","Lo stand resta nel nostro magazzino e torna a Riva a ogni edizione.")],
 qa=[("Potete conservare lo stand fra due edizioni di Expo Riva Schuh?","Sì, lo teniamo in magazzino e lo rimontiamo a ogni edizione con grafiche aggiornate."),
  ("Allestite stand per Hospitality?","Sì: ambientazioni per hotel e ristorazione, arredi, luci e impianti.")]),
dict(s="carrara",c="Carrara",q="CarraraFiere",venue=None,sedi="CarraraFiere, a Marina di Carrara",
 fiere=[("Seatec – nautica",None),("Fiere della pietra e delle tecnologie",None),("Tirreno CT – ristorazione",None),("Fiere ed eventi per il pubblico",None)],
 lead="Allestimenti fieristici a Carrara: stand per CarraraFiere a Marina di Carrara, dalla nautica alla pietra e alla ristorazione. Pedane portanti, pareti per lastre, grafica, impianti e montatori.",
 intro=["CarraraFiere, a Marina di Carrara, è il quartiere fieristico della costa apuana: ospita manifestazioni legate alla nautica e alla componentistica navale, alla pietra e alle sue tecnologie, alla ristorazione e all'ospitalità, oltre a fiere ed eventi per il pubblico.",
  "Il territorio parla da sé: marmo e cantieristica. Le fiere che li rappresentano chiedono stand capaci di reggere materiali pesanti e componenti tecnici, con pareti e pavimenti portanti, illuminazione per le superfici e allacci per macchinari."],
 sapere=[("Pietra e lastre.","Strutture portanti e luce radente per esporre marmi e lavorazioni."),
  ("Nautica e componentistica.","Pareti attrezzate e pedane per componenti, arredi navali e tecnologie."),
  ("Ristorazione.","Banchi per dimostrazioni con allacci elettrici e idrici."),
  ("Esperienza nella pietra.","Abbiamo allestito stand al Marmomac di Verona: conosciamo pesi e logistica dei materiali lapidei.")],
 qa=[("Potete esporre lastre di marmo in uno stand a Carrara?","Sì, progettando strutture e pavimenti sul peso reale dei materiali. Vedi anche <a href=\"/stand-marmomac/\">stand per Marmomac</a>."),
  ("Allestite stand per fiere della nautica?","Sì, a Carrara, Genova e nelle fiere estere del settore.")]),
dict(s="longarone",c="Longarone",q="Longarone Fiere Dolomiti",venue="longarone",sedi="Longarone Fiere Dolomiti, in provincia di Belluno",
 fiere=[("Arredamont",None),("Agrimont",None),("Dolomiti HoReCa",None),("MIG – Mostra Internazionale del Gelato",None),("Caccia, Pesca, Natura",None)],
 lead="Allestimenti fieristici a Longarone: stand per Longarone Fiere Dolomiti, da Arredamont ad Agrimont, Dolomiti HoReCa e MIG. Siamo in Veneto: progetto, materiali, grafica, impianti e montatori.",
 intro=["Longarone Fiere Dolomiti è il quartiere fieristico della montagna veneta: Arredamont dedicata all'arredo e all'abitare in montagna, Agrimont per agricoltura e zootecnia di montagna, Dolomiti HoReCa per l'ospitalità, la storica Mostra Internazionale del Gelato e fiere per il pubblico come Caccia, Pesca, Natura.",
  "Il pubblico è fatto di artigiani, albergatori, allevatori e famiglie, spesso del territorio: gli stand devono essere concreti, mostrare il prodotto da vicino e invogliare all'acquisto. Siamo in Veneto, a poco più di un'ora: sopralluoghi e assistenza sono semplici."],
 sapere=[("Arredo di montagna.","Ambientazioni in legno, stube, cucine e camere ricostruite nello stand."),
  ("Gelato e HoReCa.","Vetrine refrigerate, banchi dimostrativi e allacci elettrici e idrici."),
  ("Agricoltura di montagna.","Pedane per mezzi e attrezzature, spazi per incontri con allevatori."),
  ("Siamo vicini.","Sede in provincia di Treviso: sopralluoghi e assistenza rapidi.")],
 qa=[("Allestite stand per Arredamont?","Sì: ambientazioni, pareti attrezzate, luci, grafica e montaggio a Longarone."),
  ("Potete realizzare stand con vetrine per il gelato?","Sì, con banconi su misura, allacci e potenze elettriche calcolate. Vedi anche <a href=\"/stand-sigep/\">stand per Sigep</a>.")]),
]
