# -*- coding: utf-8 -*-
D={}
D['tr']=dict(path='/tr/italya-fuar-standi/',
 title='İtalya ve Avrupa’da fuar standı tasarım ve kurulumu | Danova Tech',
 desc='İtalya ve Avrupa’da fuar standı: 3D tasarım, malzeme, bileşenler, grafik, elektrik ve fuar alanında kurulum ekipleri. Milano, Verona, Bologna ve daha fazlası.',
 ogt='İtalya’da fuar standı — Danova Tech',ogd='İtalya ve Avrupa’da anahtar teslim fuar standları: tasarım, malzeme, bileşenler ve yerinde kurulum.',
 crumbs=[('Ana sayfa','/en/'),('Fuar standı',None)],
 eyebrow='Fuar standı · İtalya ve Avrupa',
 h1='İtalya’da fuar standı: <span class="grad">anahtar teslim</span> tasarım ve kurulum.',
 lead='İtalya’da ve Avrupa’da fuara katılan her ülkeden ve her sektörden firmalar için fuar standları tasarlıyor, tedarik ediyor ve kuruyoruz. Gerekli tüm malzemeyi ve bileşenleri biz buluyoruz; kurulum ekiplerimiz standınızı doğrudan fuar alanında inşa ediyor. 25 yılı aşkın deneyim, ilk çizimden söküme kadar tek bir muhatap.',
 cta='Standınız için teklif isteyin',cta2='Nasıl çalışıyoruz',
 c_t='Standınızın ihtiyacı olan her şey, tek bir tedarikçide',c_l='Yurt dışında fuara katılmak, bilinmeyen kurallar, tedarikçiler ve lojistik demektir. İtalya’da her şeyi biz yönetiyoruz.',
 cards=[('Tasarım ve 3D görsel','Alan, hol içindeki konum ve hedeflerinizden yola çıkıyor, standı inşa etmeden önce 3D olarak gösteriyoruz.'),
  ('Malzeme ve bileşenler','Yapılar, profiller, bağlantı parçaları, duvarlar, zeminler ve mobilyalar: projenin ve fuarın teknik kurallarının gerektirdiği her şey.'),
  ('Grafik ve baskı','Paneller, afişler, baskılı kumaşlar ve yönlendirmeler; üretilip fuar alanında monte edilir.'),
  ('Elektrik, aydınlatma ve LED','İtalyan fuarlarının istediği uygunluk beyanıyla elektrik tesisatı, aydınlatma, halı, ekranlar ve LED duvarlar.'),
  ('Kurulum ve söküm','Kendi ekiplerimiz ve iş ortağı ekipler standı resmi kurulum süresinde kurar, fuar sonunda söker.'),
  ('Lojistik, depolama ve işlemler','Nakliye, fuarlar arasında depolama, proje onayı, giriş kartları ve organizatörle yükleme saatleri.')],
 t_t='Neden İtalya’da yerel bir iş ortağı',
 paras=['İtalyan fuar merkezlerinin kendi teknik kuralları, son tarihleri ve prosedürleri vardır ve bunlar sıkı şekilde uygulanır. Bu kuralları bilen yerel bir ortak zaman ve para kazandırır, son dakika sürprizlerini önler.',
  'Alüminyum modüler sistemler, gergi kumaş standlar, hazır standlar ve ahşap özel tasarım standlarla çalışıyoruz; kiralık veya satın alma seçenekleriyle. Her yıl İtalya’da fuara katılıyorsanız standınızı iki fuar arasında depomuzda saklayabiliriz.'],
 lista=[('Kendi dilinizde yazın.','Her talebe Türkçe veya İngilizce yanıt veriyoruz.'),
  ('Acil talepleri kabul ediyoruz.','Açılışa günler kalsa bile neyin mümkün olduğunu hemen değerlendiriyoruz.'),
  ('Kiralama veya satın alma.','Hazır, modüler, kumaş ve özel tasarım standlar.'),
  ('İtalya ve Avrupa.','İtalyan fuarlarında ve Almanya, Fransa, İspanya ile Avrupa’nın geri kalanında aynı organizasyon.')],
 f_t='Stand kurduğumuz yerler',f_l='İtalya’nın tüm büyük fuar merkezlerinde ve Avrupa genelindeki fuarlarda.',
 places=['Milano · Fiera Milano Rho','Verona · Veronafiere','Bologna · BolognaFiere','Rimini · Expo Centre','Parma · Fiere di Parma','Vicenza','Padova','Pordenone','Almanya','Fransa','İspanya','Avrupa’nın geri kalanı'],
 e_t='Stand kurduğumuz fuarlardan bazıları',
 p_ey='Nasıl çalışıyoruz',p_t='Hol planından <span class="grad">hazır standa.</span>',
 steps=[('Brif','Fuar, tarihler, alan, stand tipi, hedefler ve bütçe.'),('3D tasarım ve teklif','İnşaattan önce 3D görsel ve kalem kalem teklif.'),
  ('Onaylar','Projeyi teknik kurallara göre organizatöre sunuyoruz.'),('Üretim ve nakliye','Yapılar, bileşenler, grafikler ve mobilyalar yola çıkmadan kontrol edilir.'),
  ('Kurulum ve söküm','Ekiplerimiz standı fuar alanında kurar ve fuar sonunda söker.')],
 faq_ey='SSS',faq_t='Sık sorulan <span class="grad">sorular.</span>',
 qa=[('İtalya’da bir fuar standı ne kadar tutar?','Alan, yapı tipi, kaplamalar, elektrik, lojistik ve fuar şehrine bağlıdır. Sabit fiyat listesi yayınlamıyoruz; projeniz için kalem kalem teklif hazırlıyoruz.'),
  ('Başka bir firmanın tasarladığı standı kurabilir misiniz?','Evet. Tasarımcınızın çizimlerine göre yalnızca malzeme, bileşen ve kurulumu üstlenebiliriz.'),
  ('Son dakika taleplerini kabul ediyor musunuz?','Evet. Kendi ekiplerimiz ve iş ortaklarımızla açılıştan kısa süre önce bile stand hazırlayabiliyoruz.'),
  ('Stand başka fuarlarda tekrar kullanılabilir mi?','Evet. Modüler ve kumaş standlar tekrar kullanım için tasarlanır; fuarlar arasında depolayabiliriz.'),
  ('Organizatörle işlemleri siz mi yapıyorsunuz?','Evet: proje onayı, belgeler, giriş kartları ve yükleme saatleri.'),
  ('Hangi dilde yazabilirim?','Türkçe veya İngilizce: her talebe yanıt veriyoruz.')],
 k_t='İtalya’da veya Avrupa’da fuara mı katılıyorsunuz?',k_p='Fuarı, tarihleri ve alanı bize bildirin. Neye ihtiyacınız olduğunu ve maliyetini yanıtlayalım.',
 mail='Bize yazın',wa='WhatsApp',more='Daha fazla',
 svc_name='Fuar standı tasarım ve kurulumu',svc_desc='İtalya ve Avrupa’da anahtar teslim fuar standları: 3D tasarım, malzeme ve bileşenler, grafik, elektrik, aydınlatma ve LED, fuar alanında kurulum ve söküm, lojistik, depolama ve işlemler. Hazır, modüler, kumaş ve özel standlar, kiralık veya satın alma.',
 offers=['Stand tasarımı','Modüler standlar','Özel tasarım standlar','Stand kurulumu ve sökümü','Stand kiralama'])
