# -*- coding: utf-8 -*-
D={}
D['en']=dict(path='/en/exhibition-stand-builder-italy/',
 title='Exhibition stand builder in Italy and Europe | Danova Tech',
 desc='Exhibition stand design and build in Italy and Europe: 3D design, graphics, electrics and on-site installers at Milan, Verona, Bologna and more.',
 ogt='Exhibition stand builder in Italy — Danova Tech',ogd='Turnkey trade fair stands in Italy and Europe: design, materials, components and installers on site.',
 crumbs=[('Home','/en/'),('Services','/en/#servizi'),('Exhibition stands',None)],
 eyebrow='Exhibition stands · Italy & Europe',
 h1='Exhibition stand builder in Italy: <span class="grad">turnkey stands</span> for your trade fair.',
 lead='We design, supply and build trade fair stands for companies from every country and industry exhibiting in Italy and across Europe. We source the materials and every component required, and our installation crews build your stand right at the fair. Over 25 years of experience, one contact person from the first sketch to dismantling.',
 cta='Request a quote for your stand',cta2='How we work',
 c_t='Everything your stand needs, from one supplier',c_l='Exhibiting abroad means dealing with unfamiliar rules, suppliers and logistics. We handle all of it on the ground, so you can focus on your customers.',
 cards=[('Design and 3D renders','We start from your floor space, hall position and goals, and show you the stand in 3D before it is built.'),
  ('Materials and components','Structures, profiles, fittings, walls, flooring and furniture: everything the project and the fair’s technical rules require.'),
  ('Graphics and printing','Panels, banners, printed fabrics and signage, produced and installed on site.'),
  ('Electrics, lighting and LED','Electrical installation with the certificate of conformity Italian fairs require, lighting, carpet, screens and LED walls.'),
  ('Installation and dismantling','Our own crews and trusted partner crews build the stand within the official set-up times and dismantle it after the show.'),
  ('Logistics, storage and paperwork','Transport, storage between fairs, project approval, passes and loading times with the fair organiser.')],
 t_t='Why work with a local partner in Italy',
 paras=['Italian exhibition centres have their own technical regulations, deadlines and procedures, and they are strict about them. A local partner who knows them saves you time, money and last-minute surprises.',
  'We work with modular aluminium and stretched-fabric systems, preassembled stands and custom-built wooden stands, all available to rent or to buy. If you exhibit in Italy every year, we can store your stand between shows and have it ready for the next one.'],
 lista=[('Write in your language.','Our team replies to every request, in your language or in English.'),
  ('Urgent requests accepted.','Even close to the opening day, we check right away what can be done.'),
  ('Rent or buy.','Preassembled, modular, fabric and custom stands, rented or owned.'),
  ('Italy and Europe.','The same organisation at Italian fairs and at shows in Germany, France, Spain and the rest of Europe.')],
 f_t='Where we build stands',f_l='We work at all major Italian exhibition centres and at trade fairs across Europe.',
 places=['Milan · Fiera Milano Rho','Verona · Veronafiere','Bologna · BolognaFiere','Rimini · Expo Centre','Parma · Fiere di Parma','Vicenza','Padua','Pordenone','Germany','France','Spain','Rest of Europe'],
 e_t='Some fairs where we have built stands',
 p_ey='How we work',p_t='From your floor plan <span class="grad">to a finished stand.</span>',
 steps=[('Brief','Fair, dates, floor space, stand type, goals and budget.'),('3D design and quote','A 3D render and an itemised quote before anything is built.'),
  ('Approvals','We submit the project to the fair organiser according to the technical regulations.'),('Production and transport','Structures, components, graphics and furniture, checked before departure.'),
  ('Installation and dismantling','Our crews build the stand on site and dismantle it after the show.')],
 faq_ey='FAQ',faq_t='Questions we are <span class="grad">often asked.</span>',
 qa=[('How much does an exhibition stand in Italy cost?','It depends on floor space, type of structure, finishes, electrics, logistics and the city of the fair. We do not publish a price list: we send you an itemised quote for your project.'),
  ('Can you build a stand designed by another company?','Yes. We can handle only materials, components and installation, following your designer’s drawings.'),
  ('Do you accept last-minute requests?','Yes. With our own crews and partner crews we can often organise a stand close to the opening day.'),
  ('Can the stand be reused at other fairs?','Yes. Modular aluminium and fabric stands are built to be reused, and we can store them between shows.'),
  ('Do you deal with the fair organiser?','Yes: project approval, documents, passes and loading times.'),
  ('Which language can I write in?','Your own language or English: we reply to every request.')],
 k_t='Exhibiting in Italy or Europe?',k_p='Tell us the fair, the dates and your floor space. We will reply with what you need and what it costs.',
 mail='Write to us',wa='WhatsApp',more='More',
 svc_name='Exhibition stand design and build',svc_desc='Turnkey exhibition stands in Italy and Europe: 3D design, materials and components, graphics, electrics, lighting and LED, installation and dismantling on site, logistics, storage and paperwork. Preassembled, modular, fabric and custom stands, rented or bought.',
 offers=['Exhibition stand design','Modular exhibition stands','Custom exhibition stands','Stand installation and dismantling','Exhibition stand rental'])
D['de']=dict(path='/de/messebau-italien/',
 title='Messebau in Italien und Europa: Messestände schlüsselfertig',
 desc='Messebau in Italien und Europa: 3D-Planung, Material, Komponenten, Grafik, Elektrik und Monteure direkt auf der Messe in Mailand, Verona, Bologna und mehr.',
 ogt='Messebau in Italien — Danova Tech',ogd='Schlüsselfertige Messestände in Italien und Europa: Planung, Material, Komponenten und Monteure vor Ort.',
 crumbs=[('Home','/de/'),('Leistungen','/de/#servizi'),('Messebau',None)],
 eyebrow='Messebau · Italien & Europa',
 h1='Messebau in Italien: Ihr Messestand <span class="grad">schlüsselfertig</span>.',
 lead='Wir planen, liefern und bauen Messestände für Unternehmen aller Länder und Branchen, die in Italien und in ganz Europa ausstellen. Wir besorgen das Material und alle geforderten Komponenten, und unsere Montageteams bauen Ihren Stand direkt auf der Messe auf. Über 25 Jahre Erfahrung, ein Ansprechpartner von der ersten Skizze bis zum Abbau.',
 cta='Angebot für Ihren Stand anfragen',cta2='So arbeiten wir',
 c_t='Alles für Ihren Messestand aus einer Hand',c_l='Wer im Ausland ausstellt, hat es mit fremden Regeln, Lieferanten und Logistik zu tun. Wir kümmern uns vor Ort um alles.',
 cards=[('Planung und 3D-Rendering','Wir gehen von Fläche, Hallenposition und Zielen aus und zeigen Ihnen den Stand in 3D, bevor er gebaut wird.'),
  ('Material und Komponenten','Systeme, Profile, Verbinder, Wände, Böden und Möbel: alles, was Projekt und technische Richtlinien der Messe verlangen.'),
  ('Grafik und Druck','Paneele, Banner, bedruckte Textilien und Beschilderung, produziert und vor Ort montiert.'),
  ('Elektrik, Licht und LED','Elektroinstallation mit der in Italien geforderten Konformitätserklärung, Beleuchtung, Teppich, Bildschirme und LED-Wände.'),
  ('Aufbau und Abbau','Eigene Teams und Partnerteams bauen den Stand in den offiziellen Aufbauzeiten auf und nach der Messe wieder ab.'),
  ('Logistik, Lager und Formalitäten','Transport, Einlagerung zwischen den Messen, Projektfreigabe, Ausweise und Anlieferzeiten mit dem Veranstalter.')],
 t_t='Warum ein Partner vor Ort in Italien',
 paras=['Italienische Messegelände haben eigene technische Richtlinien, Fristen und Abläufe, und sie werden streng angewendet. Ein lokaler Partner, der sie kennt, spart Zeit, Geld und böse Überraschungen in letzter Minute.',
  'Wir arbeiten mit modularen Aluminium- und Textilsystemen, Komplettständen und individuellem Holzbau, zur Miete oder zum Kauf. Wenn Sie jedes Jahr in Italien ausstellen, lagern wir Ihren Stand zwischen den Messen ein.'],
 lista=[('Schreiben Sie in Ihrer Sprache.','Wir antworten auf jede Anfrage, auf Deutsch oder Englisch.'),
  ('Auch kurzfristig.','Selbst kurz vor Messebeginn prüfen wir sofort, was möglich ist.'),
  ('Miete oder Kauf.','Komplett-, System-, Textil- und individuelle Stände.'),
  ('Italien und Europa.','Dieselbe Organisation auf italienischen Messen und in Deutschland, Frankreich, Spanien und ganz Europa.')],
 f_t='Wo wir Messestände bauen',f_l='Auf allen großen italienischen Messegeländen und auf Messen in ganz Europa.',
 places=['Mailand · Fiera Milano Rho','Verona · Veronafiere','Bologna · BolognaFiere','Rimini · Expo Centre','Parma · Fiere di Parma','Vicenza','Padua','Pordenone','Deutschland','Frankreich','Spanien','Ganz Europa'],
 e_t='Einige Messen, auf denen wir Stände gebaut haben',
 p_ey='So arbeiten wir',p_t='Vom Hallenplan <span class="grad">zum fertigen Stand.</span>',
 steps=[('Briefing','Messe, Termine, Fläche, Standtyp, Ziele und Budget.'),('3D-Planung und Angebot','Rendering und detailliertes Angebot, bevor gebaut wird.'),
  ('Freigaben','Einreichung beim Veranstalter nach den technischen Richtlinien.'),('Produktion und Transport','Systeme, Komponenten, Grafik und Möbel, vor der Abfahrt geprüft.'),
  ('Aufbau und Abbau','Unsere Teams bauen den Stand vor Ort auf und nach der Messe ab.')],
 faq_ey='FAQ',faq_t='Häufige <span class="grad">Fragen.</span>',
 qa=[('Was kostet ein Messestand in Italien?','Das hängt von Fläche, Bauweise, Ausstattung, Elektrik, Logistik und Messestadt ab. Wir veröffentlichen keine Preisliste, sondern erstellen ein detailliertes Angebot für Ihr Projekt.'),
  ('Bauen Sie auch Stände nach fremden Entwürfen?','Ja. Wir können nur Material, Komponenten und Montage nach den Plänen Ihres Designers übernehmen.'),
  ('Sind kurzfristige Aufträge möglich?','Ja. Mit eigenen Teams und Partnerteams organisieren wir oft auch kurz vor Messebeginn einen Stand.'),
  ('Kann der Stand wiederverwendet werden?','Ja. System- und Textilstände sind für die Wiederverwendung gebaut, und wir lagern sie zwischen den Messen ein.'),
  ('Kümmern Sie sich um den Veranstalter?','Ja: Projektfreigabe, Unterlagen, Ausweise und Anlieferzeiten.'),
  ('In welcher Sprache kann ich schreiben?','Auf Deutsch, Englisch oder in Ihrer Sprache: Wir antworten auf jede Anfrage.')],
 k_t='Sie stellen in Italien oder Europa aus?',k_p='Nennen Sie uns Messe, Termine und Fläche. Wir antworten mit dem, was Sie brauchen, und was es kostet.',
 mail='Schreiben Sie uns',wa='WhatsApp',more='Mehr',
 svc_name='Messebau',svc_desc='Schlüsselfertiger Messebau in Italien und Europa: 3D-Planung, Material und Komponenten, Grafik, Elektrik, Licht und LED, Auf- und Abbau vor Ort, Logistik, Lager und Formalitäten. Komplett-, System-, Textil- und individuelle Stände zur Miete oder zum Kauf.',
 offers=['Messestandplanung','Systemstände','Individueller Messebau','Auf- und Abbau','Messestand mieten'])
