# -*- coding: utf-8 -*-
D={}
D['fr']=dict(path='/fr/standiste-salon-italie/',
 title='Standiste en Italie et en Europe : stands clés en main | Danova Tech',
 desc='Conception et montage de stands de salon en Italie et en Europe : projet 3D, graphisme, électricité et monteurs sur place à Milan, Vérone, Bologne.',
 ogt='Standiste en Italie — Danova Tech',ogd='Stands de salon clés en main en Italie et en Europe : projet, matériaux, composants et monteurs sur place.',
 crumbs=[('Accueil','/fr/'),('Services','/fr/#servizi'),('Stands de salon',None)],
 eyebrow='Stands de salon · Italie & Europe',
 h1='Standiste en Italie : votre stand de salon <span class="grad">clés en main</span>.',
 lead="Nous concevons, fournissons et montons des stands de salon pour les entreprises de tous pays et de tous secteurs qui exposent en Italie et partout en Europe. Nous trouvons les matériaux et tous les composants nécessaires, et nos équipes de monteurs construisent votre stand directement sur le salon. Plus de 25 ans d'expérience, un seul interlocuteur du premier croquis au démontage.",
 cta='Demander un devis pour votre stand',cta2='Notre méthode',
 c_t='Tout ce dont votre stand a besoin, chez un seul fournisseur',c_l="Exposer à l'étranger, c'est composer avec des règles, des fournisseurs et une logistique inconnus. Nous nous occupons de tout sur place.",
 cards=[('Projet et rendu 3D',"Nous partons de la surface, de l'emplacement dans le hall et de vos objectifs, et vous montrons le stand en 3D avant de le construire."),
  ('Matériaux et composants','Structures, profilés, raccords, cloisons, sols et mobilier : tout ce que demandent le projet et le règlement technique du salon.'),
  ('Graphisme et impression','Panneaux, bâches, tissus imprimés et signalétique, produits et posés sur place.'),
  ('Électricité, éclairage et LED',"Installation électrique avec la déclaration de conformité exigée en Italie, éclairage, moquette, écrans et murs LED."),
  ('Montage et démontage','Nos équipes et des équipes partenaires montent le stand dans les délais officiels et le démontent après le salon.'),
  ('Logistique, stockage et formalités',"Transport, stockage entre deux salons, validation du projet, badges et horaires de livraison avec l'organisateur.")],
 t_t='Pourquoi un partenaire sur place en Italie',
 paras=["Les parcs d'exposition italiens ont leurs propres règlements techniques, délais et procédures, appliqués avec rigueur. Un partenaire local qui les connaît vous fait gagner du temps, de l'argent et vous évite les mauvaises surprises.",
  "Nous travaillons avec des systèmes modulaires en aluminium et en tissu tendu, des stands pré-équipés et des stands sur mesure en bois, à la location ou à l'achat. Si vous exposez chaque année en Italie, nous stockons votre stand entre deux salons."],
 lista=[('Écrivez dans votre langue.','Nous répondons à chaque demande, en français ou en anglais.'),
  ('Urgences acceptées.',"Même à quelques jours de l'ouverture, nous vérifions tout de suite ce qui est possible."),
  ('Location ou achat.','Stands pré-équipés, modulaires, en tissu et sur mesure.'),
  ('Italie et Europe.','La même organisation dans les salons italiens et en Allemagne, en France, en Espagne et dans toute l’Europe.')],
 f_t='Où nous montons des stands',f_l="Dans tous les grands parcs d'exposition italiens et dans les salons de toute l'Europe.",
 places=['Milan · Fiera Milano Rho','Vérone · Veronafiere','Bologne · BolognaFiere','Rimini · Expo Centre','Parme · Fiere di Parma','Vicence','Padoue','Pordenone','Allemagne','France','Espagne',"Toute l'Europe"],
 e_t='Quelques salons où nous avons monté des stands',
 p_ey='Notre méthode',p_t='Du plan du hall <span class="grad">au stand terminé.</span>',
 steps=[('Brief','Salon, dates, surface, type de stand, objectifs et budget.'),('Projet 3D et devis','Rendu 3D et devis détaillé avant toute construction.'),
  ('Validations',"Dépôt du projet auprès de l'organisateur selon le règlement technique."),('Production et transport','Structures, composants, graphismes et mobilier, vérifiés avant le départ.'),
  ('Montage et démontage','Nos équipes montent le stand sur place et le démontent après le salon.')],
 faq_ey='FAQ',faq_t='Les questions <span class="grad">fréquentes.</span>',
 qa=[('Combien coûte un stand de salon en Italie ?',"Cela dépend de la surface, du type de structure, des finitions, de l'électricité, de la logistique et de la ville. Nous ne publions pas de tarifs : nous établissons un devis détaillé pour votre projet."),
  ("Montez-vous des stands conçus par d'autres ?","Oui. Nous pouvons nous charger uniquement des matériaux, des composants et du montage d'après les plans de votre designer."),
  ('Acceptez-vous les demandes de dernière minute ?',"Oui. Avec nos équipes et nos partenaires, nous organisons souvent un stand peu avant l'ouverture."),
  ('Le stand est-il réutilisable ?','Oui. Les stands modulaires et en tissu sont conçus pour être réutilisés, et nous pouvons les stocker entre deux salons.'),
  ("Vous occupez-vous de l'organisateur ?",'Oui : validation du projet, documents, badges et horaires de livraison.'),
  ('Dans quelle langue puis-je écrire ?','En français, en anglais ou dans votre langue : nous répondons à chaque demande.')],
 k_t='Vous exposez en Italie ou en Europe ?',k_p="Indiquez-nous le salon, les dates et la surface. Nous vous répondons avec ce qu'il faut et ce que cela coûte.",
 mail='Écrivez-nous',wa='WhatsApp',more='Plus',
 svc_name='Conception et montage de stands de salon',svc_desc="Stands de salon clés en main en Italie et en Europe : projet 3D, matériaux et composants, graphisme, électricité, éclairage et LED, montage et démontage sur place, logistique, stockage et formalités. Stands pré-équipés, modulaires, en tissu et sur mesure, à la location ou à l'achat.",
 offers=['Conception de stands','Stands modulaires','Stands sur mesure','Montage et démontage de stands','Location de stands'])
D['es']=dict(path='/es/montaje-stands-feriales-italia/',
 title='Montaje de stands feriales en Italia y Europa | Danova Tech',
 desc='Diseño y montaje de stands feriales en Italia y Europa: proyecto 3D, materiales, gráfica, electricidad y montadores en la feria en Milán, Verona, Bolonia.',
 ogt='Montaje de stands en Italia — Danova Tech',ogd='Stands feriales llave en mano en Italia y Europa: proyecto, materiales, componentes y montadores en la feria.',
 crumbs=[('Inicio','/es/'),('Servicios','/es/#servizi'),('Stands feriales',None)],
 eyebrow='Stands feriales · Italia y Europa',
 h1='Montaje de stands feriales en Italia: <span class="grad">llave en mano</span>.',
 lead='Diseñamos, suministramos y montamos stands feriales para empresas de cualquier país y sector que exponen en Italia y en toda Europa. Encontramos los materiales y todos los componentes necesarios, y nuestros equipos de montadores construyen tu stand directamente en la feria. Más de 25 años de experiencia y un único interlocutor desde el primer boceto hasta el desmontaje.',
 cta='Pide presupuesto para tu stand',cta2='Cómo trabajamos',
 c_t='Todo lo que necesita tu stand, en un solo proveedor',c_l='Exponer en el extranjero significa lidiar con normas, proveedores y logística desconocidos. Nosotros nos encargamos de todo sobre el terreno.',
 cards=[('Proyecto y render 3D','Partimos de la superficie, la posición en el pabellón y tus objetivos, y te mostramos el stand en 3D antes de construirlo.'),
  ('Materiales y componentes','Estructuras, perfiles, uniones, paredes, suelos y mobiliario: todo lo que exigen el proyecto y la normativa técnica de la feria.'),
  ('Gráfica e impresión','Paneles, lonas, tejidos impresos y señalética, producidos e instalados en la feria.'),
  ('Electricidad, iluminación y LED','Instalación eléctrica con la declaración de conformidad que exigen las ferias italianas, iluminación, moqueta, pantallas y pantallas LED.'),
  ('Montaje y desmontaje','Equipos propios y colaboradores montan el stand en los plazos oficiales y lo desmontan al terminar la feria.'),
  ('Logística, almacén y trámites','Transporte, almacenaje entre ferias, aprobación del proyecto, acreditaciones y horarios de carga con el organizador.')],
 t_t='Por qué un socio local en Italia',
 paras=['Los recintos feriales italianos tienen sus propias normas técnicas, plazos y procedimientos, y los aplican con rigor. Un socio local que los conoce te ahorra tiempo, dinero y sorpresas de última hora.',
  'Trabajamos con sistemas modulares de aluminio y tejido tensado, stands modulares básicos y stands a medida en madera, en alquiler o en propiedad. Si expones en Italia cada año, guardamos tu stand entre una feria y otra.'],
 lista=[('Escríbenos en tu idioma.','Respondemos a cada solicitud, en español o en inglés.'),
  ('Aceptamos urgencias.','Incluso a pocos días de la apertura, comprobamos enseguida qué se puede hacer.'),
  ('Alquiler o compra.','Stands básicos, modulares, de tejido y a medida.'),
  ('Italia y Europa.','La misma organización en las ferias italianas y en Alemania, Francia, España y el resto de Europa.')],
 f_t='Dónde montamos stands',f_l='En todos los grandes recintos feriales italianos y en ferias de toda Europa.',
 places=['Milán · Fiera Milano Rho','Verona · Veronafiere','Bolonia · BolognaFiere','Rímini · Expo Centre','Parma · Fiere di Parma','Vicenza','Padua','Pordenone','Alemania','Francia','España','Resto de Europa'],
 e_t='Algunas ferias en las que hemos montado stands',
 p_ey='Cómo trabajamos',p_t='Del plano del pabellón <span class="grad">al stand terminado.</span>',
 steps=[('Briefing','Feria, fechas, superficie, tipo de stand, objetivos y presupuesto.'),('Proyecto 3D y presupuesto','Render 3D y presupuesto detallado antes de construir.'),
  ('Aprobaciones','Presentamos el proyecto al organizador según la normativa técnica.'),('Producción y transporte','Estructuras, componentes, gráfica y mobiliario, revisados antes de salir.'),
  ('Montaje y desmontaje','Nuestros equipos montan el stand en la feria y lo desmontan al final.')],
 faq_ey='Preguntas frecuentes',faq_t='Lo que más nos <span class="grad">preguntan.</span>',
 qa=[('¿Cuánto cuesta un stand en una feria en Italia?','Depende de la superficie, el tipo de estructura, los acabados, la electricidad, la logística y la ciudad. No publicamos tarifas: te enviamos un presupuesto detallado para tu proyecto.'),
  ('¿Montáis stands diseñados por otros?','Sí. Podemos encargarnos solo de materiales, componentes y montaje siguiendo los planos de tu diseñador.'),
  ('¿Aceptáis encargos de última hora?','Sí. Con equipos propios y colaboradores a menudo organizamos un stand poco antes de la apertura.'),
  ('¿Se puede reutilizar el stand?','Sí. Los stands modulares y de tejido están pensados para reutilizarse, y podemos almacenarlos entre ferias.'),
  ('¿Os encargáis de los trámites con la feria?','Sí: aprobación del proyecto, documentos, acreditaciones y horarios de carga.'),
  ('¿En qué idioma puedo escribir?','En español, inglés o en tu idioma: respondemos a cada solicitud.')],
 k_t='¿Expones en Italia o en Europa?',k_p='Dinos la feria, las fechas y la superficie. Te respondemos con lo que necesitas y lo que cuesta.',
 mail='Escríbenos',wa='WhatsApp',more='Más',
 svc_name='Diseño y montaje de stands feriales',svc_desc='Stands feriales llave en mano en Italia y Europa: proyecto 3D, materiales y componentes, gráfica, electricidad, iluminación y LED, montaje y desmontaje en la feria, logística, almacenaje y trámites. Stands básicos, modulares, de tejido y a medida, en alquiler o en propiedad.',
 offers=['Diseño de stands','Stands modulares','Stands a medida','Montaje y desmontaje de stands','Alquiler de stands'])
