# -*- coding: utf-8 -*-
"""Pagine nuove del 9 ottobre 2026 (quarto giro): lacune emerse dai suggerimenti
   di ricerca di Google (autocomplete) e dai dati Keyword Planner.
   Si modifica qui, poi:  python3 seo-tools/pagine-build-2.py pagine-dati-4.py
   ATTENZIONE: le due pagine sui bandi contengono date e importi. Ricontrollarle
   ogni 2-3 mesi (fonti ufficiali: simest.it, tb.camcom.gov.it, regione.veneto.it)."""
OGGI = "2026-10-09"
IT = [{"@type":"Country","name":"Italia"}]
VEN = [{"@type":"AdministrativeArea","name":"Veneto"},{"@type":"AdministrativeArea","name":"Friuli-Venezia Giulia"}]
PAGINE = []

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/contributi-fiere-2026/",
 "title":"Contributi per le fiere 2026: SIMEST e Camere di Commercio",
 "desc":"Contributi e finanziamenti per partecipare alle fiere nel 2026: SIMEST Fiere ed Eventi, bandi delle Camere di Commercio, collettive ICE. Cosa copre lo stand.",
 "ogtitle":"Contributi per le fiere 2026 — Danova Tech",
 "ogdesc":"Chi paga una parte dello stand: SIMEST, Camere di Commercio, Regioni e collettive ICE. Cosa si può finanziare e come preparare i preventivi.",
 "crumbs":[("Allestimenti fieristici","/servizi/allestimenti-fieristici/"),("Contributi per le fiere",None)],
 "eyebrow":"Fiere · finanziamenti · aggiornato a ottobre 2026",
 "h1":"Contributi per le fiere 2026: <span class=\"grad\">chi paga una parte dello stand.</span>",
 "lead":"Area espositiva, allestimento, grafica, trasporto: una fiera internazionale pesa sul bilancio di una PMI. In Italia esistono tre strade per farsene coprire una parte: il finanziamento agevolato SIMEST, i bandi delle Camere di Commercio e le collettive regionali e ICE. Qui trovate come funzionano, cosa coprono e come preparare preventivi che superino il controllo.",
 "cta1":"Chiedi un preventivo stand", "cta2":"Le tre strade",
 "sezioni":[
  {"id":"strade","tipo":"cards","eyebrow":"Le tre strade",
   "h2":"Da dove arrivano<br>i <span class=\"grad\">soldi per la fiera</span>",
   "lead":"Non sono alternative fra loro in tutti i casi: spesso un'impresa usa la collettiva per la prima fiera e SIMEST quando il programma diventa annuale.",
   "corpo":[
    ("SIMEST Fiere ed Eventi","Finanziamento agevolato del Fondo 394/81, gestito da SIMEST (gruppo CDP), per fiere, mostre ed eventi internazionali anche in Italia. Arriva fino a 500.000 euro, entro il 20% dei ricavi, durata 4 anni di cui 2 di preammortamento. Una quota fino al 10% può essere a fondo perduto per alcune categorie di PMI."),
    ("Bandi delle Camere di Commercio","Contributi a fondo perduto, di solito da 2.000 a 5.000 euro per impresa, a rimborso di una parte delle spese di area e stand. Escono una o due volte l'anno, con finestre brevi e fondi che finiscono in fretta. Esempio: la Camera di Vicenza ha messo 545.000 euro sull'ultimo bando fiere internazionali, con contributo di 2.500 euro per impresa."),
    ("Collettive regionali e padiglioni ICE","La Regione, la Camera di Commercio o ICE Agenzia prendono un padiglione e lo dividono fra più imprese. Voi pagate una quota ridotta e ricevete uno spazio già allestito. Si aderisce con mesi di anticipo e lo stand è uguale per tutti: comodo per la prima volta, stretto quando volete distinguervi.")]},
  {"id":"simest","tipo":"testo","eyebrow":"La misura più grande",
   "h2":"SIMEST Fiere ed Eventi:<br><span class=\"grad\">cosa sapere prima</span>",
   "corpo":[
    "È la misura con più risorse ed è aperta per tutto il 2026, a sportello: le domande si istruiscono in ordine di arrivo. Finanzia fino a tre iniziative, anche in paesi diversi, con un tasso agevolato che SIMEST aggiorna periodicamente. La parte a fondo perduto, fino al 10% e fino a 100.000 euro, è riservata ad alcune categorie: PMI giovanili, femminili o innovative, PMI che esportano almeno il 20% del fatturato, con certificazioni di sostenibilità o con sede operativa al Sud.",
    "<b>Spese ammesse:</b> area espositiva, allestimento e logistica, promozione, consulenze collegate alla fiera, spese digitali connesse all'evento. Devono essere sostenute dopo l'assegnazione del CUP ed entro 24 mesi dalla stipula. Il finanziamento arriva in due tranche: un anticipo fino al 25% e il saldo sulle spese rendicontate.",
    "<b>Requisiti:</b> sede legale e operativa in Italia e almeno un bilancio depositato; sopra i 150.000 euro servono due bilanci e una buona classe di rating. Possono essere chieste garanzie sulla parte che supera il margine operativo. Prima di presentare la domanda conviene una verifica con il vostro commercialista o con l'associazione di categoria.",
    "Fonti e condizioni aggiornate: <a href=\"https://www.simest.it\" rel=\"noopener\" target=\"_blank\">simest.it</a>. I numeri di questa pagina sono aggiornati a ottobre 2026 e possono cambiare."]},
  {"id":"preventivi","tipo":"passi","eyebrow":"Il lato pratico",
   "h2":"Come preparare lo stand<br>perché il <span class=\"grad\">contributo regga.</span>",
   "lead":"I contributi si perdono più spesso per un preventivo scritto male che per un requisito mancante. Ecco cosa prepariamo per chi partecipa con un bando.",
   "corpo":[
    ("Preventivo a voci separate","Area, struttura, grafica, impianto elettrico, arredi, trasporto e montaggio su righe distinte. I bandi ammettono alcune voci e non altre: se è tutto in un'unica cifra, il controllo non sa cosa riconoscervi."),
    ("Date coerenti con il bando","Molti bandi ammettono solo spese fatturate dopo la domanda o dopo la concessione. Concordiamo con voi quando ordinare e quando fatturare, così l'acconto non cade fuori dal periodo valido."),
    ("Documentazione fotografica","Foto dello stand montato, con la fiera riconoscibile. Le chiedono quasi tutti i bandi in fase di rendicontazione e le facciamo noi a fine montaggio."),
    ("Stand riutilizzabile se il bando è annuale","Con un programma di più fiere, uno stand modulare o un noleggio pesa meno sul finanziamento e lascia budget per area e promozione.")]},
  {"id":"attenzione","tipo":"testo","eyebrow":"Da sapere",
   "h2":"Tre cose che<br><span class=\"grad\">fanno perdere il contributo</span>",
   "corpo":[
    "<b>Il de minimis.</b> Quasi tutti questi aiuti rientrano nel regime de minimis, che ha un tetto complessivo nei tre anni. Se avete già ricevuto altri contributi, controllate il Registro nazionale degli aiuti prima di contare su quello della fiera.",
    "<b>Il cumulo.</b> Lo stesso costo non si può far pagare due volte. Spesso il contributo camerale per la fiera e il voucher internazionalizzazione della stessa Camera si escludono a vicenda.",
    "<b>Le finestre brevi.</b> I bandi camerali restano aperti poche settimane e i fondi finiscono prima della scadenza. Il voucher fiere nazionale del Ministero ha chiuso a ottobre 2025 e nel 2026 non è stato riproposto. Conviene avere i preventivi pronti prima che il bando esca."]}],
 "faqtitle":"Le domande <span class=\"grad\">sui contributi.</span>",
 "faq":[
  ("Esistono contributi per partecipare alle fiere nel 2026?","Sì. Il principale è SIMEST Fiere ed Eventi, finanziamento agevolato fino a 500.000 euro con una possibile quota a fondo perduto fino al 10%, aperto per tutto il 2026. A questo si aggiungono i bandi delle Camere di Commercio, di solito 2.000-5.000 euro a fondo perduto per impresa, e le collettive regionali e ICE a quota ridotta."),
  ("Lo stand fieristico rientra nelle spese ammesse?","Nella maggior parte dei casi sì: allestimento, grafica, impianti, arredi, trasporto e montaggio sono ammessi da SIMEST e dai bandi camerali, insieme all'affitto dell'area. Conviene un preventivo a voci separate, perché alcuni bandi escludono singole voci come il catering o i gadget."),
  ("Valgono anche le fiere in Italia?","Per SIMEST sì, se la fiera è internazionale: Vinitaly, Salone del Mobile, Marmomac, EICMA e le altre fiere con espositori esteri rientrano. Molti bandi camerali invece chiedono fiere all'estero o fiere italiane con qualifica internazionale nel calendario ufficiale."),
  ("Fate voi la domanda di contributo?","No: la domanda la presentate voi, di solito con il commercialista o l'associazione di categoria. Noi prepariamo quello che serve dalla nostra parte: preventivo a voci separate, progetto dello stand, fatture con le date giuste e foto dello stand montato per la rendicontazione."),
  ("Il voucher fiere del Ministero c'è ancora?","Il voucher fiere nazionale per le PMI ha chiuso le domande il 28 ottobre 2025 e nel 2026 non risulta una nuova edizione. Restano SIMEST, i bandi camerali e quelli regionali."),
  ("Questi dati sono aggiornati?","Sono aggiornati a ottobre 2026. I bandi cambiano spesso: prima di decidere verificate sempre il testo ufficiale sul sito dell'ente, che fa fede.")],
 "ctabox":{"h2":"Avete una fiera in calendario e un bando in vista?",
  "p":"Mandateci fiera, metri quadri e scadenza del bando: vi prepariamo il progetto e un preventivo a voci separate, pronto per la domanda.",
  "btn":"Richiedi il preventivo stand"},
 "altrititle":"Pagine collegate",
 "altri":[("Allestimenti fieristici","/servizi/allestimenti-fieristici/"),
          ("Quanto costa uno stand fieristico","/quanto-costa-uno-stand-fieristico/"),
          ("Calendario fiere 2026–2027","/calendario-fiere/"),
          ("Stand per fiere all&#8217;estero","/allestimenti-fieristici-estero/"),
          ("Noleggio stand fieristici","/noleggio-stand-fieristici/"),
          ("Stand modulari","/stand-modulari/"),
          ("Come preparare una fiera","/guide/come-preparare-una-fiera/"),
          ("Bandi digitalizzazione 2026","/bandi-digitalizzazione-veneto-2026/")],
 "svc":{"name":"Allestimento stand con contributi per le fiere","type":"Allestimenti fieristici",
        "desc":"Progettazione e allestimento di stand fieristici con preventivi e documentazione adatti ai contributi SIMEST, ai bandi delle Camere di Commercio e ai bandi regionali per la partecipazione alle fiere.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Preventivo stand a voci separate per bandi","Progetto 3D dello stand","Allestimento e montaggio in fiera","Documentazione fotografica per la rendicontazione"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/bandi-digitalizzazione-veneto-2026/",
 "title":"Bandi e voucher digitalizzazione 2026 in Veneto | Danova Tech",
 "desc":"Bandi digitalizzazione 2026 per imprese venete: voucher della Camera di Commercio Treviso-Belluno, bandi regionali e iperammortamento. Cosa finanziano davvero.",
 "ogtitle":"Bandi e voucher digitalizzazione 2026 in Veneto — Danova Tech",
 "ogdesc":"Cosa c'è di aperto nel 2026 per digitalizzare un'impresa veneta, cosa si può finanziare e cosa no. Senza promesse di contributi sicuri.",
 "crumbs":[("Digitalizzazione aziendale","/digitalizzazione-aziendale/"),("Bandi 2026",None)],
 "eyebrow":"Veneto · contributi · aggiornato a ottobre 2026",
 "h1":"Bandi e voucher digitalizzazione 2026: <span class=\"grad\">cosa c'è davvero in Veneto.</span>",
 "lead":"Chi cerca un bando per la digitalizzazione trova decine di pagine che promettono il 70% a fondo perduto. La realtà del 2026 è più stretta: i fondi camerali finiscono in pochi giorni, e molti bandi finanziano macchinari e software energetici, non un sito o un gestionale da soli. Qui mettiamo in fila cosa c'è, cosa copre e quando conviene non aspettare il bando.",
 "cta1":"Parliamo del vostro progetto", "cta2":"Cosa c'è nel 2026",
 "sezioni":[
  {"id":"aperti","tipo":"cards","eyebrow":"Il quadro 2026",
   "h2":"Le misure<br><span class=\"grad\">per le imprese venete</span>",
   "corpo":[
    ("Camera di Commercio Treviso-Belluno: doppia transizione 2026","Contributo del 50% fino a 40.000 euro per impresa, spesa minima 5.000 euro, per beni e software 4.0 e soluzioni di monitoraggio energetico. Domande dall'8 luglio al 23 ottobre 2026: la dotazione di 1,4 milioni è già esaurita e le nuove domande vanno in lista d'attesa."),
    ("Regione Veneto: transizione delle imprese","Contributo fino al 30% per investimenti in digitalizzazione ed economia circolare, in alternativa finanziamento agevolato o leasing. Si rivolge a impianti, macchinari e processi produttivi più che a progetti solo software."),
    ("Iperammortamento 2026","L'agevolazione fiscale nazionale che dal 2026 ha preso il posto dei crediti Transizione 4.0 e 5.0. Il software rientra se è nell'elenco dei beni immateriali ammessi ed è collegato a beni strumentali. Non è un contributo a fondo perduto ma una maggiorazione del costo deducibile: si gestisce con il commercialista, con le comunicazioni sulla piattaforma del GSE."),
    ("Bandi delle altre Camere venete","Padova, Vicenza, Verona e Venezia Rovigo pubblicano bandi propri per la digitalizzazione, di solito una volta l'anno, con il circuito dei Punti Impresa Digitale. Percentuali e massimali cambiano a ogni edizione e le finestre durano poche settimane.")]},
  {"id":"cosa","tipo":"testo","eyebrow":"Il punto che nessuno scrive",
   "h2":"Cosa si finanzia<br><span class=\"grad\">e cosa no</span>",
   "corpo":[
    "I bandi del 2026 seguono quasi tutti gli elenchi dei beni 4.0 e 5.0. Questo significa che <b>un gestionale o un sito web da soli spesso non bastano</b>. Nel bando Treviso-Belluno 2026, per esempio, il software di gestione d'impresa è ammesso solo se acquistato insieme a una soluzione di monitoraggio dei consumi energetici.",
    "Rientrano più facilmente: software collegati a macchinari interconnessi, MES e monitoraggio della produzione, sistemi di tracciabilità, cruscotti energetici, consulenze per introdurre tecnologie 4.0 legate a quegli acquisti. Rientrano a fatica o per niente: sito vetrina, e-commerce, campagne pubblicitarie, app di marketing.",
    "Per questo, prima di progettare, leggiamo con voi il testo del bando e costruiamo il progetto in modo che le voci ammissibili siano separate da quelle che non lo sono. Se il progetto non rientra, ve lo diciamo subito: è meglio partire senza contributo che rincorrere un bando sbagliato."]},
  {"id":"come","tipo":"passi","eyebrow":"Come ci muoviamo",
   "h2":"Dal bando<br>al <span class=\"grad\">progetto finanziabile.</span>",
   "corpo":[
    ("Verifica di compatibilità","Ci mandate il bando che vi interessa, o lo cerchiamo insieme. In mezz'ora capiamo se il vostro progetto può rientrare e in quale misura."),
    ("Progetto e preventivo a voci separate","Analisi, sviluppo, licenze, formazione e consulenza su righe distinte, con la descrizione tecnica che il bando chiede: interconnessione, integrazione con i macchinari, monitoraggio."),
    ("Domanda con il vostro consulente","La domanda la presentate voi o il vostro commercialista. Noi forniamo relazione tecnica, preventivi e schede del software."),
    ("Rendicontazione","Fatture con le date giuste, documentazione del collaudo e, quando serve, dichiarazione di interconnessione del software ai sistemi aziendali.")]},
  {"id":"senza","tipo":"testo","eyebrow":"Se il bando non c'è",
   "h2":"Quando conviene<br><span class=\"grad\">non aspettare</span>",
   "corpo":[
    "Un bando copre di solito fra il 30 e il 50% della spesa. Se un processo vi costa ore ogni settimana, sei mesi di attesa per un bando che poi chiude in tre giorni possono valere più del contributo stesso.",
    "Per i progetti più piccoli esistono anche formule che non richiedono un investimento iniziale: un'applicazione web a canone mensile, per esempio, si avvia subito e si può sostituire o ampliare quando arriva un bando adatto. Trovate le cifre sul nostro <a href=\"/prezzi/\">listino prezzi</a>.",
    "Fonti ufficiali da controllare prima di decidere: <a href=\"https://www.tb.camcom.gov.it\" rel=\"noopener\" target=\"_blank\">Camera di Commercio Treviso-Belluno</a>, <a href=\"https://www.puntoimpresadigitale.camcom.it\" rel=\"noopener\" target=\"_blank\">Punto Impresa Digitale</a>, <a href=\"https://www.regione.veneto.it\" rel=\"noopener\" target=\"_blank\">Regione del Veneto</a>. Dati aggiornati a ottobre 2026."]}],
 "faqtitle":"Le domande <span class=\"grad\">sui bandi.</span>",
 "faq":[
  ("Ci sono voucher per la digitalizzazione nel 2026 in Veneto?","Sì, ma con fondi limitati. La Camera di Commercio di Treviso-Belluno ha aperto il bando doppia transizione 2026 (50% fino a 40.000 euro, domande fino al 23 ottobre 2026), con dotazione già esaurita e lista d'attesa. Le altre Camere venete e la Regione pubblicano bandi propri durante l'anno."),
  ("Un gestionale su misura è finanziabile?","Dipende dal bando. Molti bandi 2026 ammettono il software di gestione solo se collegato a beni 4.0 o a un sistema di monitoraggio energetico. Un gestionale integrato con macchinari, produzione o magazzino ha molte più probabilità di un gestionale amministrativo da solo."),
  ("Il sito web o l'e-commerce rientrano nei bandi digitalizzazione?","Nei bandi del 2026 sempre meno: la maggior parte segue gli elenchi dei beni 4.0 e 5.0, che non comprendono sito vetrina, e-commerce o pubblicità online. Alcuni bandi camerali dedicati all'e-commerce o all'internazionalizzazione escono a parte durante l'anno."),
  ("Cosa ha sostituito Transizione 5.0?","Dal 2026 l'agevolazione principale per gli investimenti in beni strumentali, anche digitali, è l'iperammortamento. Per i dettagli e per capire se il vostro investimento rientra, leggete la nostra guida alla Transizione 5.0 e parlatene con il commercialista."),
  ("Presentate voi la domanda?","No. La domanda la presenta l'impresa, di solito con il commercialista o l'associazione di categoria. Noi prepariamo la parte tecnica: progetto, preventivi separati, relazione e documentazione per la rendicontazione."),
  ("Questi dati sono aggiornati?","Sono aggiornati a ottobre 2026. I bandi cambiano spesso e il testo ufficiale dell'ente fa sempre fede.")],
 "ctabox":{"h2":"Avete un bando sotto mano e un progetto in testa?",
  "p":"Mandateci il link del bando e due righe sul progetto: vi diciamo se e come può rientrare, prima che spendiate tempo nella domanda.",
  "btn":"Verifica il tuo progetto"},
 "altrititle":"Pagine collegate",
 "altri":[("Digitalizzazione aziendale","/digitalizzazione-aziendale/"),
          ("Transizione 5.0 nel 2026","/guide/transizione-5-0/"),
          ("Software MES per la produzione","/software-mes-produzione/"),
          ("Gestionali su misura in Veneto","/gestionali-su-misura-veneto/"),
          ("Automazione processi aziendali","/automazione-processi-aziendali/"),
          ("Intelligenza artificiale per aziende","/intelligenza-artificiale-per-aziende/"),
          ("Contributi per le fiere 2026","/contributi-fiere-2026/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Progetti di digitalizzazione finanziabili con bandi","type":"Consulenza e sviluppo software per la digitalizzazione",
        "desc":"Progettazione di software, gestionali e sistemi di monitoraggio per le imprese venete, con preventivi e documentazione tecnica adatti ai bandi di digitalizzazione delle Camere di Commercio e della Regione del Veneto.",
        "area":VEN,"lingue":["Italian"],
        "catalogo":["Verifica di compatibilità con il bando","Relazione tecnica e preventivi a voci separate","Software interconnesso e monitoraggio energetico","Documentazione per la rendicontazione"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/seo-per-intelligenza-artificiale/",
 "title":"SEO per l'AI: comparire su ChatGPT e Perplexity | Danova Tech",
 "desc":"SEO per l'intelligenza artificiale: come far citare la vostra azienda da ChatGPT, Perplexity, Gemini e dalle AI Overviews di Google. Cosa funziona e cosa no.",
 "ogtitle":"SEO per l'intelligenza artificiale — Danova Tech",
 "ogdesc":"Sempre più clienti chiedono a ChatGPT invece di cercare su Google. Come fare in modo che la risposta contenga il vostro nome.",
 "crumbs":[("SEO","/servizi/seo/"),("SEO per l'AI",None)],
 "eyebrow":"GEO · AI Overviews · ChatGPT",
 "h1":"SEO per l'intelligenza artificiale: <span class=\"grad\">farsi citare da ChatGPT.</span>",
 "lead":"Una parte crescente delle ricerche non finisce più su una lista di link: finisce in una risposta scritta, da ChatGPT, Perplexity, Gemini o dal riquadro AI in cima a Google. Se in quella risposta il vostro nome non c'è, per quel cliente non esistete. La buona notizia è che le regole per entrarci somigliano molto a quelle della buona SEO, con qualche differenza che conta.",
 "cta1":"Controlliamo come vi descrive l'AI", "cta2":"Come funziona",
 "sezioni":[
  {"id":"come","tipo":"testo","eyebrow":"Come scelgono le fonti",
   "h2":"Da dove prende<br>le risposte <span class=\"grad\">un assistente AI</span>",
   "corpo":[
    "Gli assistenti AI rispondono in due modi. Il primo è la memoria del modello, costruita su testi raccolti mesi prima: lì entra chi era già citato in molte fonti affidabili. Il secondo, sempre più usato, è la ricerca in tempo reale: l'assistente cerca sul web, legge poche pagine e riassume. Le AI Overviews di Google e Perplexity funzionano quasi solo così.",
    "Per la ricerca in tempo reale valgono le basi della SEO: se Google e Bing non vi trovano, non vi trova nemmeno l'AI. Poi entra in gioco una cosa diversa: <b>l'AI cita le pagine da cui è facile estrarre una risposta</b>. Una frase chiara che risponde alla domanda, dati precisi, una fonte riconoscibile.",
    "Per la memoria del modello conta l'<b>entità</b>: quante fonti indipendenti parlano di voi, in modo coerente. Nome, sede, cosa fate, per chi. Se siti diversi vi descrivono in modo diverso, o vi confondono con un omonimo, l'AI fa lo stesso."]},
  {"id":"cosa","tipo":"cards","eyebrow":"Su cosa interveniamo",
   "h2":"Le leve<br>che <span class=\"grad\">funzionano davvero</span>",
   "corpo":[
    ("Pagine che rispondono","Una domanda per pagina, la risposta nelle prime righe, poi i dettagli. Domande frequenti scritte come le scrive un cliente, non come le scrive un ufficio marketing. È il formato che gli assistenti riprendono quasi parola per parola."),
    ("Dati strutturati e scheda dell'azienda","Schema Organization, Service, FAQ e LocalBusiness ben compilati, con partita IVA, sede, area servita e descrizione che distingue voi dagli omonimi. Più un file llms.txt che riassume chi siete per i crawler AI."),
    ("Accesso ai crawler AI","GPTBot, OAI-SearchBot, PerplexityBot, ClaudeBot, Google-Extended: molti siti li bloccano senza saperlo, da robots.txt o dal firewall. Verifichiamo che possano leggere le pagine che volete far citare."),
    ("Citazioni esterne","Google Business Profile completo, directory di settore, associazioni di categoria, articoli e casi studio sui siti dei clienti. Sono le fonti che i modelli usano per confermare che un'azienda esiste e fa quello che dice."),
    ("Bing, non solo Google","ChatGPT e Copilot si appoggiano in buona parte all'indice di Bing. Un sito ben posizionato su Google ma ignorato da Bing perde metà delle occasioni. Registriamo il sito su Bing Webmaster Tools e IndexNow."),
    ("Misura","Chiediamo agli assistenti le domande dei vostri clienti, ogni mese, e annotiamo chi viene citato. Più il traffico in arrivo da chatgpt.com e perplexity.ai in Analytics. Senza misura, la SEO per l'AI resta un atto di fede.")]},
  {"id":"onesta","tipo":"testo","eyebrow":"Cosa possiamo promettere",
   "h2":"Quello che<br><span class=\"grad\">nessuno può garantire</span>",
   "corpo":[
    "Nessuno può garantire che ChatGPT vi nomini. Le risposte cambiano da utente a utente e da un giorno all'altro, e i modelli vengono aggiornati senza preavviso. Chi vende la prima posizione su ChatGPT vende qualcosa che non controlla.",
    "Quello che si può fare è aumentare la probabilità, in modo misurabile: essere la fonte più chiara e più confermata sul vostro argomento, nella vostra zona. È lo stesso lavoro che porta clienti da Google, fatto tenendo conto di come leggono le macchine. Per questo lo facciamo dentro la consulenza SEO, non come servizio separato."]}],
 "faqtitle":"Le domande <span class=\"grad\">sulla SEO per l'AI.</span>",
 "faq":[
  ("Come si fa a comparire su ChatGPT?","Servono tre cose: un sito che i motori di ricerca, Bing compreso, indicizzano bene; pagine che rispondono in modo chiaro alle domande dei clienti; e fonti esterne coerenti che confermano chi siete. Bisogna anche verificare che il sito non blocchi i crawler di OpenAI."),
  ("Che differenza c'è fra SEO e GEO?","GEO, Generative Engine Optimization, è il nome che si usa per l'ottimizzazione verso i motori generativi come ChatGPT e Perplexity. Le basi sono le stesse della SEO; cambia il peso di alcune cose, come la chiarezza delle risposte, i dati strutturati e le citazioni esterne."),
  ("Le AI Overviews di Google mi tolgono traffico?","Su alcune ricerche informative sì: chi trova la risposta nel riquadro non clicca. Sulle ricerche commerciali, come la scelta di un fornitore, il riquadro cita poche aziende e chi viene citato riceve clic più qualificati. Conviene essere fra quelle."),
  ("Devo creare un file llms.txt?","È utile e costa poco: è un file di testo che riassume chi siete e quali pagine contano. Non è uno standard ufficiale e non sostituisce il resto, ma aiuta gli assistenti a descrivervi correttamente."),
  ("Come faccio a sapere se ChatGPT mi cita già?","Fate le domande che farebbe un vostro cliente, per esempio il servizio più la città, su ChatGPT, Perplexity e Gemini, e annotate chi compare. In Google Analytics controllate anche le visite in arrivo da chatgpt.com e perplexity.ai."),
  ("È un servizio a parte?","No, è parte della nostra consulenza SEO. Separarlo avrebbe poco senso, perché le stesse pagine e gli stessi dati lavorano per Google e per gli assistenti AI.")],
 "ctabox":{"h2":"Volete sapere cosa dice ChatGPT di voi?",
  "p":"Facciamo agli assistenti AI le domande dei vostri clienti e vi mandiamo cosa rispondono, chi citano e cosa manca al vostro sito per entrarci. Gratis.",
  "btn":"Richiedi il controllo gratuito"},
 "altrititle":"Pagine collegate",
 "altri":[("Consulenza SEO","/servizi/seo/"),
          ("Consulente SEO","/consulente-seo/"),
          ("Posizionamento sito su Google","/posizionamento-sito-google/"),
          ("Google Business Profile: la guida","/guide/google-business-profile-guida/"),
          ("Intelligenza artificiale per aziende","/intelligenza-artificiale-per-aziende/"),
          ("Chatbot aziendale","/chatbot-aziendale/"),
          ("Agenzia link building","/agenzia-link-building/"),
          ("SEO per e-commerce","/seo-per-ecommerce/")],
 "svc":{"name":"SEO per l'intelligenza artificiale","type":"Ottimizzazione per motori di ricerca e assistenti AI",
        "desc":"Ottimizzazione di sito, dati strutturati e citazioni esterne per aumentare la presenza dell'azienda nelle risposte di ChatGPT, Perplexity, Gemini, Copilot e nelle AI Overviews di Google.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Analisi della presenza negli assistenti AI","Pagine e FAQ ottimizzate per le risposte","Dati strutturati e llms.txt","Accesso ai crawler AI","Indicizzazione su Bing e IndexNow","Monitoraggio mensile delle citazioni"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/quanto-costa-google-ads/",
 "title":"Quanto costa Google Ads: budget e costo per clic | Danova Tech",
 "desc":"Quanto costa la pubblicità su Google Ads nel 2026: costo per clic per settore, budget minimo sensato, costo della gestione e come non sprecare i primi mesi.",
 "ogtitle":"Quanto costa Google Ads — Danova Tech",
 "ogdesc":"Costo per clic, budget mensile e gestione: numeri reali dal Keyword Planner e cosa fa salire o scendere la spesa.",
 "crumbs":[("Google Ads","/servizi/google-ads/"),("Quanto costa",None)],
 "eyebrow":"Pubblicità su Google · costi 2026",
 "h1":"Quanto costa Google Ads: <span class=\"grad\">budget, clic e gestione.</span>",
 "lead":"Su Google non si paga un abbonamento: si paga ogni clic, a un prezzo che decide un'asta. Per questo la domanda giusta non è quanto costa Google Ads, ma quanto costa un cliente arrivato da Google Ads. Qui trovate i costi per clic reali di alcuni settori, il budget sotto il quale i dati non bastano per decidere, e cosa si paga a parte per la gestione.",
 "cta1":"Chiedi una stima per il tuo settore", "cta2":"Le tre voci di costo",
 "sezioni":[
  {"id":"voci","tipo":"cards","eyebrow":"Le voci",
   "h2":"Tre costi,<br><span class=\"grad\">pagati a tre soggetti diversi</span>",
   "corpo":[
    ("Il budget pubblicitario","Lo pagate direttamente a Google, con la vostra carta, sull'account intestato a voi. Lo decidete voi e potete cambiarlo o fermarlo ogni giorno. Google non chiede un minimo."),
    ("La gestione delle campagne","Il compenso di chi imposta e segue le campagne: ricerca delle parole chiave, annunci, esclusioni, tracciamento delle conversioni, ottimizzazione settimanale. Di solito è una cifra mensile fissa, o fissa più una parte legata alla spesa."),
    ("La pagina di arrivo","Dove atterra chi clicca. Spesso è la voce che fa la differenza: un clic che finisce su una home generica costa come uno che finisce su una landing page fatta per quella ricerca, ma converte molto meno.")]},
  {"id":"cpc","tipo":"testo","eyebrow":"Numeri reali",
   "h2":"Quanto costa<br><span class=\"grad\">un clic, settore per settore</span>",
   "corpo":[
    "Dai dati del Keyword Planner di Google per l'Italia (agosto 2025 – luglio 2026), le offerte per comparire in cima alla pagina su ricerche di servizi per le aziende stanno in queste fasce:",
    "<b>Siti web e web agency:</b> da circa 1,60 € a 4,50 € a clic nei valori tipici, fino a 10 € nelle città più contese.",
    "<b>Software gestionali, CRM ed ERP:</b> da 2 € a 8 € a clic, con punte di 19 € su ricerche come software gestionale produzione.",
    "<b>SEO e posizionamento:</b> da 2,30 € a 6 €, fino a 25 € su posizionamento su Google.",
    "<b>Sviluppo app:</b> da 1,40 € a 6,40 €, fino a quasi 20 €.",
    "<b>Agenzie di pubblicità e lead generation:</b> da 2,70 € a 9 €, fino a 25 €.",
    "Per altri settori le cifre cambiano molto: i servizi legali, le assicurazioni e i traslochi stanno in alto; il commercio locale e la ristorazione in basso. Prima di partire ricaviamo le fasce del vostro settore e della vostra zona dallo stesso strumento, gratis."]},
  {"id":"budget","tipo":"testo","eyebrow":"Il budget minimo",
   "h2":"Sotto una certa cifra<br><span class=\"grad\">i dati non bastano</span>",
   "corpo":[
    "Un conto semplice: se un clic costa 3 € e una visita su trenta diventa una richiesta di contatto, ogni richiesta costa circa 90 €. Con 300 € al mese arrivano tre o quattro richieste: troppo poche per capire quali parole chiave funzionano e quali no.",
    "Per un'azienda di servizi in una provincia, il primo test sensato sta di solito fra 15 e 30 € al giorno per almeno due o tre mesi. Meno di così si può fare, ma su poche parole molto mirate e accettando di imparare più lentamente.",
    "Il budget si alza dopo, non prima: quando sappiamo quanto costa una richiesta e quante richieste diventano clienti, aumentare la spesa diventa un conto e non una scommessa."]},
  {"id":"spreco","tipo":"passi","eyebrow":"Dove si sprecano i soldi",
   "h2":"Gli errori<br>che <span class=\"grad\">alzano il costo</span>",
   "corpo":[
    ("Parole chiave troppo larghe","Gestionale da sola porta studenti, chi cerca un programma gratis e chi vuole un lavoro. Corrispondenza a frase o esatta e una lista di parole escluse fin dal primo giorno: gratis, corso, lavoro, stipendio, fai da te."),
    ("Nessun tracciamento delle conversioni","Senza sapere quali clic diventano chiamate o moduli, Google ottimizza per i clic. Telefonate, moduli e messaggi WhatsApp vanno misurati prima di spendere il primo euro."),
    ("Rete Display attiva per errore","Le campagne sulla rete di ricerca la includono per impostazione predefinita. Per un servizio B2B spesso porta clic economici e inutili da app e siti di giochi."),
    ("Zona troppo ampia","Se lavorate in Veneto e Friuli, mostrare gli annunci a tutta Italia raddoppia la spesa senza raddoppiare i clienti. Si parte dalla zona servita e si allarga solo se i dati lo dicono.")]}],
 "faqtitle":"Le domande <span class=\"grad\">sui costi.</span>",
 "faq":[
  ("Quanto costa fare pubblicità su Google?","Il budget pubblicitario lo decidete voi: Google non ha un minimo e si paga a clic. Nei servizi alle aziende un clic costa in genere da 1,50 € a 9 €. Per un primo test che dia dati utilizzabili servono di solito 15-30 € al giorno per due o tre mesi, più l'eventuale costo della gestione."),
  ("Quanto costa un clic su Google Ads?","Dipende dalla concorrenza sulla parola chiave. Dai dati del Keyword Planner per l'Italia: siti web 1,60-4,50 €, gestionali e software 2-8 €, SEO 2,30-6 €, app 1,40-6,40 €, con punte di 20-25 € sulle ricerche più contese."),
  ("Si paga anche se nessuno clicca?","Nelle campagne sulla rete di ricerca no: si paga solo il clic. Alcune campagne video e display possono essere pagate a visualizzazione, ma per i servizi alle aziende partiamo quasi sempre dalla rete di ricerca."),
  ("L'account Google Ads è mio?","Sì, sempre. L'account è intestato a voi, il budget lo paga la vostra carta direttamente a Google e noi abbiamo un accesso da gestori. Se un giorno smettiamo di lavorare insieme, campagne e dati restano vostri."),
  ("Meglio Google Ads o la SEO?","Non si escludono. Google Ads porta richieste da subito, finché pagate; la SEO impiega mesi, ma poi lavora senza costo a clic. Spesso usiamo Google Ads nei primi mesi anche per scoprire quali ricerche portano clienti, e poi costruiamo la SEO su quelle."),
  ("Quanto costa la gestione delle campagne?","Dipende da quante campagne, lingue e zone. Vi diamo un prezzo fisso mensile dopo la prima chiamata, separato dal budget pubblicitario, senza percentuali nascoste sulla spesa.")],
 "ctabox":{"h2":"Quanto vi costerebbe un cliente da Google?",
  "p":"Diteci cosa vendete e dove. Vi mandiamo le parole chiave del vostro settore con il costo per clic reale e un budget di partenza ragionato.",
  "btn":"Richiedi la stima gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Consulente Google Ads","/servizi/google-ads/"),
          ("Meta Ads: Facebook e Instagram","/servizi/meta-ads/"),
          ("Realizzazione landing page","/realizzazione-landing-page/"),
          ("Lead generation B2B","/lead-generation-b2b/"),
          ("Consulenza SEO","/servizi/seo/"),
          ("Quanto costa un sito web","/quanto-costa-un-sito-web/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Gestione campagne Google Ads","type":"Pubblicità sui motori di ricerca",
        "desc":"Impostazione e gestione di campagne Google Ads per aziende: ricerca parole chiave con costo per clic reale, annunci, esclusioni, tracciamento conversioni, landing page e ottimizzazione continua.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Stima del costo per clic per settore","Impostazione campagne sulla rete di ricerca","Tracciamento di chiamate, moduli e WhatsApp","Landing page dedicate","Ottimizzazione e report mensile"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/realizzazione-landing-page/",
 "title":"Realizzazione landing page per campagne | Danova Tech",
 "desc":"Realizzazione di landing page per Google Ads e Meta Ads: una pagina, un'offerta, un'azione. Veloci, misurate, collegate al CRM. Prezzo fisso dopo la prima call.",
 "ogtitle":"Realizzazione landing page — Danova Tech",
 "ogdesc":"La pagina dove atterra chi clicca l'annuncio decide quanto vi costa ogni contatto. Come la costruiamo.",
 "crumbs":[("Siti web","/servizi/siti-web-ecommerce/"),("Landing page",None)],
 "eyebrow":"Landing page · campagne · conversioni",
 "h1":"Landing page che trasformano <span class=\"grad\">i clic in richieste.</span>",
 "lead":"Chi clicca un annuncio ha in testa una domanda precisa. Se atterra sulla home del sito deve cercare da solo la risposta, e quasi sempre se ne va. Una landing page è una pagina sola, fatta per quella domanda: un'offerta, le prove che la sostengono, un modo semplice per contattarvi. Dimezzare il costo di ogni contatto, spesso, si fa qui e non nella campagna.",
 "cta1":"Parliamo della vostra campagna", "cta2":"Cosa c'è dentro",
 "sezioni":[
  {"id":"dentro","tipo":"cards","eyebrow":"Cosa c'è dentro",
   "h2":"Gli elementi<br>di una <span class=\"grad\">landing che converte</span>",
   "corpo":[
    ("Un titolo che ripete la ricerca","Se l'annuncio parla di gestionale per officine, il titolo parla di gestionale per officine. Chi arriva deve capire in tre secondi di essere nel posto giusto."),
    ("Una sola azione","Chiamare, compilare un modulo breve, scrivere su WhatsApp, prenotare una call. Una sola, ripetuta lungo la pagina. Niente menu che portano altrove."),
    ("Prove concrete","Casi studio con numeri, loghi di clienti, recensioni Google reali, foto dei lavori. Le affermazioni senza prove non convincono più nessuno."),
    ("Velocità da telefono","La maggior parte dei clic arriva da smartphone. Pagina leggera, immagini ottimizzate, caricamento sotto i due secondi: ogni secondo in più si paga in contatti persi."),
    ("Tracciamento completo","Moduli, chiamate, clic su WhatsApp ed email registrati come conversioni in Google Ads, Meta e Analytics, con il consenso cookie in regola. È quello che permette alle campagne di ottimizzare."),
    ("Collegamento al CRM","Il contatto non finisce in una casella email: arriva nel vostro CRM o gestionale, con la fonte della campagna, e parte subito la risposta automatica.")]},
  {"id":"quando","tipo":"testo","eyebrow":"Quando serve",
   "h2":"Landing page<br>o <span class=\"grad\">pagina del sito?</span>",
   "corpo":[
    "Serve una landing page quando pagate per ogni visita: campagne Google Ads, Meta Ads, LinkedIn, e-mail. Lì ogni punto percentuale di conversione in più abbassa il costo di ogni contatto.",
    "Per la SEO, invece, funzionano meglio pagine di servizio complete, collegate al resto del sito: Google premia la profondità, gli annunci premiano la concentrazione. Spesso costruiamo entrambe partendo dagli stessi contenuti.",
    "Una landing page può stare sul vostro dominio, per esempio in una cartella dedicata, oppure su un sottodominio separato. La prima strada è quasi sempre la migliore: dominio vostro, fiducia vostra, dati vostri."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lavoriamo",
   "h2":"Dalla ricerca<br>alla <span class=\"grad\">pagina misurata.</span>",
   "corpo":[
    ("Chiamata","Cosa vendete, a chi, cosa vi chiedono i clienti prima di comprare. Mezz'ora, gratuita."),
    ("Testi e struttura","Scriviamo noi i testi partendo dalle ricerche reali che le persone fanno su Google, e ve li mandiamo da approvare prima della grafica."),
    ("Sviluppo e tracciamento","Pagina veloce, responsive, con conversioni configurate e testate su Google Ads, Meta e Analytics."),
    ("Test e miglioramento","Dopo le prime settimane di traffico guardiamo i dati e proviamo varianti di titolo, offerta e modulo. Una landing page non è mai finita al primo giorno.")]}],
 "faqtitle":"Le domande <span class=\"grad\">sulle landing page.</span>",
 "faq":[
  ("Cos'è una landing page?","È una pagina web pensata per un solo obiettivo, di solito ricevere una richiesta di contatto da chi arriva da un annuncio o da una email. A differenza di una pagina normale del sito non ha menu né distrazioni: un'offerta, le prove e un modo semplice per agire."),
  ("Quanto costa una landing page?","Dipende da testi, grafica, integrazioni e numero di varianti. Vi diamo un prezzo fisso dopo la prima chiamata, compresi testi e tracciamento delle conversioni. Per un'idea dei nostri prezzi sui siti web trovate il listino nella pagina prezzi."),
  ("Fate anche le campagne?","Sì. Possiamo realizzare solo la landing page per la vostra agenzia o il vostro reparto marketing, oppure occuparci anche delle campagne Google Ads e Meta Ads. Quando seguiamo entrambe le cose, il miglioramento è più rapido perché vediamo tutti i dati."),
  ("Su che piattaforma la realizzate?","Scriviamo pagine in HTML pulito, che caricano in fretta e non dipendono da plugin. Se il vostro sito è in WordPress possiamo integrarla lì. In entrambi i casi la pagina è vostra."),
  ("Quanto tempo serve?","Dopo l'approvazione dei testi, una landing page è online in pochi giorni lavorativi. La parte più lunga è quasi sempre raccogliere prove, foto e casi studio."),
  ("Si può usare anche per una fiera?","Sì, ed è un uso che consigliamo: una pagina dedicata alla vostra presenza in fiera, con stand, novità e prenotazione dell'appuntamento, da linkare nelle email di invito e da raggiungere col QR code allo stand.")],
 "ctabox":{"h2":"State pagando clic che non diventano contatti?",
  "p":"Mandateci il link della pagina su cui atterrano i vostri annunci: vi diciamo cosa cambieremmo per primo, gratis.",
  "btn":"Richiedi l'analisi gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Quanto costa Google Ads","/quanto-costa-google-ads/"),
          ("Consulente Google Ads","/servizi/google-ads/"),
          ("Meta Ads: Facebook e Instagram","/servizi/meta-ads/"),
          ("Lead generation B2B","/lead-generation-b2b/"),
          ("Siti web ed e-commerce","/servizi/siti-web-ecommerce/"),
          ("CRM aziendale","/crm-aziendale/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Realizzazione landing page","type":"Sviluppo di pagine web per campagne pubblicitarie",
        "desc":"Progettazione, testi, sviluppo e tracciamento di landing page per campagne Google Ads, Meta Ads e email, con integrazione CRM e test di miglioramento.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Testi basati sulle ricerche reali","Pagina veloce e responsive","Tracciamento conversioni Google Ads, Meta e Analytics","Integrazione con CRM e WhatsApp","Test A/B e ottimizzazione"]},
})
