# -*- coding: utf-8 -*-
"""Pagine nuove del 24 settembre 2026 (terzo giro): applicazioni per tipo.
   Si modifica qui, poi:  python3 seo-tools/pagine-build-2.py pagine-dati-3.py"""
OGGI = "2026-09-24"
IT = [{"@type":"Country","name":"Italia"}]
PAGINE = []

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/app-per-personal-trainer/",
 "title":"App per personal trainer su misura | Danova Tech",
 "desc":"App per personal trainer con il vostro marchio: schede con video, progressi dei clienti, check-in, chat, calendario e abbonamenti. Web app o app sugli store.",
 "ogtitle":"App per personal trainer — Danova Tech",
 "ogdesc":"La vostra app, con il vostro nome sullo store: schede, video, progressi e pagamenti in un posto solo, invece di WhatsApp e fogli di calcolo.",
 "crumbs":[("App su misura","/servizi/app-su-misura/"),("Personal trainer",None)],
 "eyebrow":"Fitness e coaching",
 "h1":"App per <span class=\"grad\">personal trainer.</span>",
 "lead":"La maggior parte dei personal trainer lavora con tre strumenti: WhatsApp per parlare con i clienti, un foglio di calcolo per le schede e un'app di pagamento. Funziona finché i clienti sono dieci. Con trenta, o con il coaching online, il tempo se ne va a ricopiare, ricordare e rincorrere. Un'app vostra mette tutto in un posto, con il vostro nome sopra.",
 "cta1":"Raccontateci come lavorate", "cta2":"Cosa fa l'app",
 "sezioni":[
  {"id":"funzioni","tipo":"cards","eyebrow":"Le funzioni",
   "h2":"Cosa fa <span class=\"grad\">l'app</span>",
   "lead":"Non tutte servono dal primo giorno. Si parte da quelle che vi fanno risparmiare più tempo, di solito le prime tre.",
   "corpo":[
    ("Schede di allenamento con video","Create la scheda una volta, da computer, pescando da una libreria di esercizi con i vostri video. Il cliente la apre in palestra dal telefono, esercizio per esercizio, e segna carichi e ripetizioni mentre si allena."),
    ("Progressi del cliente","Peso, misure, foto, carichi, test periodici. Grafici semplici che il cliente capisce e che voi usate per correggere il programma, invece di chiedere ogni volta come va."),
    ("Check-in settimanale","Un breve questionario che arriva da solo ogni settimana: sonno, energia, aderenza, dolori. Per il coaching online è il momento che sostituisce la sessione di persona, e con l'app lo leggete in un minuto per cliente."),
    ("Chat e notifiche","I messaggi con il cliente restano dentro l'app, collegati alla sua scheda e ai suoi progressi. WhatsApp resta per la vita privata. Promemoria per l'allenamento e per il check-in partono da soli."),
    ("Calendario e sessioni","Il cliente prenota le sessioni di persona negli orari che aprite voi, con promemoria automatico. Pacchetti a dieci ingressi, sessioni residue e scadenze sempre visibili."),
    ("Abbonamenti e pagamenti","Pagamento mensile ricorrente o pacchetti, con carta. Chi non ha pagato lo vedete senza aprire l'estratto conto, e l'accesso ai contenuti si sospende da solo se volete.")]},
  {"id":"quale","tipo":"testo","eyebrow":"La scelta vera",
   "h2":"Piattaforma in abbonamento<br>o <span class=\"grad\">app vostra?</span>",
   "corpo":[
    "Esistono piattaforme per coach che si pagano al mese e si attivano in un'ora. Per chi comincia sono spesso la scelta giusta, e ve lo diciamo. I limiti arrivano dopo: il costo cresce con il numero di clienti, il cliente scarica l'app della piattaforma e non la vostra, e il giorno che volete cambiare portare via i dati non è sempre semplice.",
    "Un'app vostra conviene quando <b>il marchio è parte del prodotto</b>: un metodo con un nome, un programma online che vendete anche a chi non vi ha mai visto, uno studio con più trainer. Lì il cliente deve trovare sul telefono il vostro logo, non quello di un fornitore.",
    "C'è anche una via di mezzo, che proponiamo spesso: una <b>web app installabile</b>. Si apre dal browser, si aggiunge alla schermata del telefono con la vostra icona, non passa dagli store e costa una frazione di un'app nativa. Se il progetto cresce, si trasforma in app per iPhone e Android partendo dalla stessa base."]},
  {"id":"regole","tipo":"testo","eyebrow":"Da sapere prima",
   "h2":"Tre cose che<br><span class=\"grad\">nessuno vi dice</span>",
   "corpo":[
    "<b>I dati sulla salute sono dati particolari.</b> Peso, misure, infortuni e foto del corpo rientrano fra le categorie che il GDPR protegge di più. Servono un consenso esplicito, un'informativa chiara e server in Europa. Li mettiamo nel progetto dall'inizio, non dopo.",
    "<b>La dieta non la può dare il personal trainer.</b> In Italia i piani alimentari sono riservati a biologi nutrizionisti, dietisti e medici. L'app può ospitare il piano scritto dal professionista con cui collaborate e le indicazioni generali di alimentazione; non deve farvi sembrare quello che non potete essere.",
    "<b>Apple e Google hanno regole sui pagamenti.</b> Le sessioni svolte di persona si possono far pagare con il vostro sistema di pagamento; per i contenuti digitali venduti dentro un'app pubblicata sugli store valgono le loro regole e le loro commissioni. Si decide prima come vendere, perché cambia come si costruisce l'app."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Prima la versione<br>che <span class=\"grad\">usate domani.</span>",
   "corpo":[
    ("Chiamata","Ci raccontate come lavorate oggi: quanti clienti, di persona o online, cosa vi porta via più tempo. Mezz'ora, gratuita."),
    ("Prototipo","Le schermate principali, navigabili dal telefono. Le fate provare a due clienti prima di spendere per lo sviluppo."),
    ("Prima versione","Schede, progressi e check-in, con il vostro marchio. Si usa con i clienti veri mentre si costruisce il resto."),
    ("Crescita","Pagamenti, calendario, pubblicazione sugli store, nuove funzioni. Aggiunte quando servono, con il prezzo concordato prima.")]}],
 "faqtitle":"Le domande <span class=\"grad\">dei trainer.</span>",
 "faq":[
  ("Quanto costa un'app per personal trainer?","Si può partire da una web app installabile con il vostro marchio a 50 euro al mese, oppure da 750 euro una tantum, IVA inclusa. Un'app nativa pubblicata su App Store e Google Play costa di più e dipende dalle funzioni: vi diamo un prezzo fisso dopo il prototipo."),
  ("L'app sarà sugli store con il mio nome?","Sì, se scegliete l'app nativa: viene pubblicata con il vostro account sviluppatore, a vostro nome. Apple chiede un abbonamento annuale da sviluppatore e Google un pagamento una tantum: sono costi vostri e restano vostri. La web app invece non passa dagli store."),
  ("Posso caricare i miei video degli esercizi?","Sì, ed è il cuore dell'app. Caricate i video una volta nella vostra libreria e li usate in tutte le schede. Se avete già i video su YouTube o Vimeo, possiamo collegarli invece di ricaricarli."),
  ("Funziona anche per uno studio con più trainer?","Sì. Ogni trainer vede i suoi clienti, il titolare vede tutto: incassi, sessioni, clienti che non si allenano da due settimane. È una delle situazioni in cui un'app vostra conviene di più rispetto a una piattaforma che si paga a trainer."),
  ("Posso vendere programmi online a chi non conosco?","Sì: un programma di allenamento di otto o dodici settimane, acquistabile dal sito, che sblocca le schede nell'app. È il modo per guadagnare anche nelle ore in cui non siete in sala. Va progettato bene il pagamento, per le regole degli store."),
  ("I dati dei clienti di chi sono?","Vostri. Il database e il codice sono intestati a voi, e i dati si possono esportare in qualsiasi momento. Se un giorno cambiate fornitore, i vostri clienti non se ne accorgono.")],
 "ctabox":{"h2":"Quanto tempo vi porta via l'amministrazione?",
  "p":"In mezz'ora di chiamata guardiamo come lavorate e vi diciamo se vi conviene un'app vostra, una piattaforma in abbonamento o semplicemente sistemare quello che avete.",
  "btn":"Prenota la chiamata gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Sviluppo app su misura","/servizi/app-su-misura/"),
          ("Gestionale per palestre e centri fitness","/gestionale-palestra/"),
          ("App per prenotazioni e appuntamenti","/app-prenotazioni/"),
          ("App fidelizzazione clienti","/app-fidelizzazione-clienti/"),
          ("Quanto costa creare un&#8217;app","/quanto-costa-una-app/"),
          ("Sviluppo web app","/sviluppo-web-app/"),
          ("Meta Ads: Facebook e Instagram","/servizi/meta-ads/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"App per personal trainer","type":"Sviluppo di applicazioni mobile per il fitness",
        "desc":"Sviluppo di app e web app con il marchio del personal trainer: schede di allenamento con video, progressi, check-in, chat, calendario delle sessioni, abbonamenti e vendita di programmi online.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Schede di allenamento con video","Monitoraggio dei progressi","Check-in e coaching online","Calendario e pacchetti di sessioni","Abbonamenti e pagamenti","Pubblicazione su App Store e Google Play"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/gestionale-palestra/",
 "title":"Gestionale per palestre e centri fitness | Danova Tech",
 "desc":"Gestionale per palestre, box e centri fitness: abbonamenti, ingressi con QR, corsi a posti limitati, istruttori, pagamenti ricorrenti e app per i soci.",
 "ogtitle":"Gestionale palestra — Danova Tech",
 "ogdesc":"Abbonamenti, ingressi, corsi e pagamenti in un solo sistema, con l'app per i soci. Su misura quando i pacchetti pronti non bastano più.",
 "crumbs":[("App su misura","/servizi/app-su-misura/"),("Gestionale palestra",None)],
 "eyebrow":"Palestre e fitness",
 "h1":"Gestionale per palestre<br>e <span class=\"grad\">centri fitness.</span>",
 "lead":"Una palestra è un'azienda di abbonamenti che ogni giorno deve rispondere a quattro domande: chi è entrato, chi ha pagato, chi sta per andarsene e quanti posti restano nel corso delle 19. Un buon gestionale risponde da solo. Questa pagina spiega cosa deve fare, quando basta un programma pronto e quando conviene farselo costruire.",
 "cta1":"Parliamo della vostra palestra", "cta2":"Le funzioni",
 "sezioni":[
  {"id":"funzioni","tipo":"cards","eyebrow":"Le funzioni",
   "h2":"Il gestionale <span class=\"grad\">in sei pezzi</span>",
   "corpo":[
    ("Soci e abbonamenti","Mensili, trimestrali, annuali, a ingressi, famiglia, aziendali. Rinnovi e scadenze in automatico, con avviso al socio prima che l'abbonamento finisca."),
    ("Ingressi","Codice QR sul telefono, badge o collegamento al tornello. Chi ha l'abbonamento scaduto non entra, e alla reception compare il motivo invece di una discussione."),
    ("Corsi e sale","Calendario dei corsi con posti limitati, prenotazione dall'app, lista d'attesa che si scorre da sola quando qualcuno disdice. Presenze registrate per corso e per istruttore."),
    ("Pagamenti ricorrenti","Addebito automatico sulla carta o in conto, solleciti gentili a chi non ha pagato, incassi riconciliati. La reception smette di fare la cassa a fine mese."),
    ("Documenti e scadenze","Moduli di iscrizione firmati dal telefono, consensi privacy, certificati medici con la loro scadenza quando li richiedete. Tutto nella scheda del socio, niente raccoglitori."),
    ("Numeri che contano","Soci attivi, nuovi, disdette del mese, frequenza media, soci che non vengono da tre settimane. Quest'ultimo è il numero che salva gli abbonamenti, se lo guardate in tempo.")]},
  {"id":"quando","tipo":"testo","eyebrow":"Onestamente",
   "h2":"Programma pronto<br>o <span class=\"grad\">su misura?</span>",
   "corpo":[
    "Per una palestra singola con abbonamenti classici e un calendario di corsi, esistono gestionali in abbonamento che fanno bene il lavoro. Costano poco al mese e si attivano in fretta. Se siete in questa situazione ve lo diciamo al primo incontro, e vi aiutiamo a scegliere.",
    "Il su misura conviene in casi precisi: <b>più sedi</b> con abbonamenti validi ovunque e regole diverse per ognuna; un <b>modello vostro</b>, come box di functional training, piscine con corsi a turni, centri che uniscono fisioterapia e sala; <b>collegamenti</b> che i pacchetti non fanno, con il gestionale contabile, con i tornelli che avete già o con il sito che vende gli abbonamenti online.",
    "E conviene quando l'app dei soci deve essere vostra, con il vostro nome sugli store, e non l'app del fornitore con dentro altre cento palestre. Per molte catene locali è diventato un pezzo del marchio."]},
  {"id":"app","tipo":"testo","eyebrow":"L'app per i soci",
   "h2":"L'app che i soci<br><span class=\"grad\">aprono davvero</span>",
   "corpo":[
    "Un socio apre l'app della palestra per tre ragioni: entrare, prenotare un corso, vedere quando scade l'abbonamento. Se queste tre cose sono immediate, la riapre. Tutto il resto viene dopo, e le app piene di funzioni che nessuno usa sono le prime a essere cancellate.",
    "Sopra queste tre si aggiungono le cose che fanno restare i soci: la scheda del personal trainer, i progressi, le notifiche quando si libera un posto al corso preferito, la possibilità di rinnovare dall'app senza passare dalla reception. Se nella vostra palestra lavorano personal trainer, la parte che usano loro può essere la stessa della nostra app per personal trainer."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lo costruiamo",
   "h2":"Senza fermare<br><span class=\"grad\">la reception.</span>",
   "corpo":[
    ("Una mattina in palestra","Guardiamo la reception nell'ora di punta: cosa si chiede, cosa si cerca, cosa si scrive a mano. È lì che si capisce cosa serve."),
    ("Prima tappa","Soci, abbonamenti, ingressi e pagamenti. Si importano i soci dal programma attuale e si parte in un giorno di chiusura o di poca affluenza."),
    ("Seconda tappa","Corsi, prenotazioni e app per i soci, pubblicata con il vostro nome."),
    ("Terza tappa","Statistiche, campagne di rinnovo, collegamenti con contabilità, sito e tornelli.")]}],
 "faqtitle":"Le domande <span class=\"grad\">dei gestori.</span>",
 "faq":[
  ("Quanto costa un gestionale per palestra su misura?","Un gestionale su misura parte da 1.500 euro IVA inclusa per il primo modulo, con soci, abbonamenti e ingressi. L'app per i soci pubblicata sugli store e i collegamenti ai tornelli si aggiungono in base a cosa avete già. Il prezzo è fisso per tappa, deciso dopo l'analisi."),
  ("Potete importare i soci dal programma che usiamo?","Quasi sempre sì, partendo da un'esportazione in foglio di calcolo o dal database. Soci, scadenze e storico dei pagamenti si portano nel nuovo sistema; lo facciamo noi e lo verifichiamo con voi prima di spegnere il vecchio."),
  ("Funziona con i tornelli che abbiamo già?","Dipende dal modello: molti tornelli e lettori di badge accettano un comando dall'esterno, altri sono chiusi. Lo verifichiamo prima di fare il preventivo; se non si può, si usa l'ingresso con codice QR alla reception."),
  ("I soci possono pagare e rinnovare dall'app?","Sì, con carta o addebito ricorrente. Il rinnovo dall'app riduce le code alla reception e soprattutto le dimenticanze: l'avviso arriva qualche giorno prima della scadenza, con il pulsante per rinnovare."),
  ("Va bene anche per box di functional, piscine e centri danza?","Sì, ed è proprio lì che il su misura rende di più, perché hanno regole che i gestionali generici gestiscono male: turni, livelli, corsi a pacchetto, iscrizioni stagionali.")],
 "ctabox":{"h2":"Quanto vi costa la reception, ogni mese?",
  "p":"Un incontro in palestra, gratuito: guardiamo come gestite oggi soci, ingressi e pagamenti, e vi diciamo se vi basta un programma pronto o se conviene costruirlo.",
  "btn":"Fissiamo l'incontro"},
 "altrititle":"Pagine collegate",
 "altri":[("App per personal trainer","/app-per-personal-trainer/"),
          ("App per prenotazioni e appuntamenti","/app-prenotazioni/"),
          ("App fidelizzazione clienti","/app-fidelizzazione-clienti/"),
          ("Sviluppo app su misura","/servizi/app-su-misura/"),
          ("Gestionale cloud su misura","/gestionale-cloud/"),
          ("CRM aziendale","/crm-aziendale/"),
          ("Quanto costa un gestionale","/quanto-costa-un-gestionale/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Gestionale per palestre e centri fitness","type":"Sviluppo software gestionale per palestre",
        "desc":"Gestionale su misura per palestre, box e centri fitness: soci e abbonamenti, ingressi con QR o tornello, corsi a posti limitati, pagamenti ricorrenti, documenti e app per i soci con il marchio della palestra.",
        "area":IT,"lingue":["Italian"],
        "catalogo":["Gestione soci e abbonamenti","Controllo ingressi","Corsi e prenotazioni","Pagamenti ricorrenti","App per i soci","Statistiche e rinnovi"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/app-prenotazioni/",
 "title":"App per prenotazioni e appuntamenti | Danova Tech",
 "desc":"App e sistema di prenotazione su misura: calendario di persone, sale e campi, promemoria contro le assenze, caparra online, link dalla scheda Google.",
 "ogtitle":"App prenotazioni e appuntamenti — Danova Tech",
 "ogdesc":"Prenotazioni 24 ore su 24, promemoria automatici e meno assenze. Per studi, centri, campi sportivi, cantine e officine.",
 "crumbs":[("App su misura","/servizi/app-su-misura/"),("Prenotazioni",None)],
 "eyebrow":"Prenotazioni",
 "h1":"App per <span class=\"grad\">prenotazioni e appuntamenti.</span>",
 "lead":"Ogni telefonata per fissare un appuntamento è un'interruzione, e ogni appuntamento saltato senza avviso è un'ora pagata a vuoto. Un sistema di prenotazione fatto bene risolve entrambe le cose: il cliente prenota quando vuole, anche alle undici di sera, e riceve un promemoria che riduce le assenze.",
 "cta1":"Raccontateci la vostra agenda", "cta2":"Per chi funziona",
 "sezioni":[
  {"id":"chi","tipo":"cards","eyebrow":"Per chi",
   "h2":"Una logica,<br><span class=\"grad\">agende diverse</span>",
   "lead":"La tecnica è la stessa, le regole no. Ecco i casi che vediamo più spesso, e cosa hanno di particolare.",
   "corpo":[
    ("Studi professionali e sanitari","Più professionisti, prestazioni di durata diversa, pause, visite che richiedono una stanza o un macchinario. Il sistema propone solo gli orari in cui persona e stanza sono libere insieme."),
    ("Parrucchieri e centri estetici","Servizi combinati, tempi di posa, operatori preferiti. Chi prenota colore e taglio deve trovare uno slot che tiene conto di entrambi, non due appuntamenti separati."),
    ("Campi sportivi e padel","Prenotazione a ore, pagamento anticipato, divisione della quota fra i giocatori, luci e costi diversi per fascia. Il campo non prenotato alle 21 è l'incasso che si perde più spesso."),
    ("Cantine e visite guidate","Gruppi, lingue, degustazioni con posti limitati, prenotazioni che arrivano dall'estero con mesi di anticipo e pagamento al momento della prenotazione."),
    ("Officine e assistenza","Tagliandi, cambio gomme stagionale, ritiro e consegna. Il picco di ottobre e aprile si gestisce aprendo gli slot in anticipo invece di rispondere a cento telefonate."),
    ("Sale, mezzi e attrezzature","Sale riunioni, auto aziendali, attrezzature a noleggio. La prenotazione è interna, ma il problema è lo stesso: due persone che pensano di avere la stessa cosa alla stessa ora.")]},
  {"id":"assenze","tipo":"testo","eyebrow":"Il punto",
   "h2":"Il vero guadagno:<br><span class=\"grad\">meno assenze</span>",
   "corpo":[
    "Il cliente che non si presenta quasi mai lo fa per cattiveria: se ne dimentica. Per questo la funzione che rende di più non è la prenotazione online, è il <b>promemoria</b>: un messaggio il giorno prima con il pulsante per confermare o spostare. Chi sposta libera lo slot per qualcun altro; chi conferma di solito arriva.",
    "Dove le assenze pesano molto, come nei campi sportivi o nei servizi lunghi, si aggiunge la <b>caparra online</b>: una piccola somma pagata al momento della prenotazione, trattenuta solo se il cliente non disdice in tempo. È una regola che va scritta chiara nella pagina di prenotazione, e che cambia il comportamento più di qualsiasi messaggio.",
    "Il terzo pezzo è la <b>lista d'attesa</b>: quando uno slot si libera, il sistema avvisa chi lo voleva. Senza, uno slot disdetto la sera prima resta vuoto."]},
  {"id":"dove","tipo":"testo","eyebrow":"Dove prenota il cliente",
   "h2":"Dal sito, dall'app<br>o <span class=\"grad\">da Google</span>",
   "corpo":[
    "Non serve per forza un'app da scaricare. Per la maggior parte delle attività la prenotazione funziona meglio da una pagina web veloce, raggiungibile dal sito, da un link su Instagram e dalla <b>scheda Google Business Profile</b>, dove si può aggiungere il collegamento per prenotare. È lì che il cliente vi trova, ed è lì che deve poter prenotare senza cercare altro.",
    "L'app vera, installata sul telefono, conviene quando il cliente prenota spesso: la palestra, il campo da padel ogni settimana, il centro dove si fanno trattamenti a ciclo. In quel caso l'app ricorda i dati, mostra lo storico e permette di riprenotare con un tocco.",
    "Dal vostro lato, l'agenda si vede da computer e da telefono, si sincronizza con Google Calendar o Outlook se lo usate già, e le prenotazioni telefoniche si inseriscono nello stesso posto, così non esistono due agende."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Online <span class=\"grad\">in poche settimane.</span>",
   "corpo":[
    ("Le regole della vostra agenda","Durate, pause, risorse, chi può prenotare cosa, fino a quando si può disdire. Scritte insieme, perché sono loro a fare la differenza."),
    ("Pagina di prenotazione","Veloce, con il vostro marchio, collegata al sito e alla scheda Google. Si usa da subito."),
    ("Promemoria e pagamenti","Messaggi automatici, caparra o pagamento anticipato dove serve, lista d'attesa."),
    ("App e collegamenti","App per i clienti abituali, collegamento a gestionale, cassa o fatturazione quando servono.")]}],
 "faqtitle":"Le domande <span class=\"grad\">più frequenti.</span>",
 "faq":[
  ("Quanto costa un sistema di prenotazione su misura?","Una web app di prenotazione con il vostro marchio parte da 50 euro al mese oppure da 750 euro una tantum, IVA inclusa. Pagamenti online, più sedi, app sugli store e collegamenti al gestionale si aggiungono in base a cosa serve, con prezzo fisso deciso prima."),
  ("Perché non usare un servizio di prenotazione già pronto?","Spesso è la scelta giusta, e ve lo diciamo. Il su misura conviene quando le vostre regole non entrano nel prodotto pronto, quando pagate una commissione su ogni prenotazione, o quando il cliente deve prenotare da voi e non da un portale che gli mostra anche i vostri concorrenti."),
  ("I promemoria arrivano via SMS, email o WhatsApp?","Email e notifiche dell'app non hanno costi per messaggio. SMS e WhatsApp hanno un costo per invio, pagato al fornitore del servizio, e per WhatsApp servono modelli di messaggio approvati. Di solito si parte dall'email e si aggiunge il canale che i vostri clienti leggono davvero."),
  ("Si può chiedere un pagamento al momento della prenotazione?","Sì: pagamento completo, caparra o carta a garanzia addebitata solo in caso di assenza. Il denaro arriva sul vostro conto tramite il circuito di pagamento, non passa da noi."),
  ("Posso ancora prendere prenotazioni al telefono?","Certo. Le inserite nella stessa agenda, dal computer o dal telefono, e il cliente riceve lo stesso promemoria di chi ha prenotato online. L'importante è che l'agenda sia una sola.")],
 "ctabox":{"h2":"Quante ore al mese perdete al telefono?",
  "p":"In mezz'ora guardiamo come prendete oggi le prenotazioni e vi diciamo se vi basta un servizio pronto o se conviene un sistema vostro. Gratuito.",
  "btn":"Prenota la chiamata"},
 "altrititle":"Pagine collegate",
 "altri":[("Sviluppo app su misura","/servizi/app-su-misura/"),
          ("App per personal trainer","/app-per-personal-trainer/"),
          ("Gestionale per palestre","/gestionale-palestra/"),
          ("App fidelizzazione clienti","/app-fidelizzazione-clienti/"),
          ("Gestionale per studi professionali","/software-gestionale-studi-professionali/"),
          ("Guida a Google Business Profile","/guide/google-business-profile-guida/"),
          ("Sviluppo web app","/sviluppo-web-app/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"App e sistema di prenotazione su misura","type":"Sviluppo di sistemi di prenotazione online",
        "desc":"Sistemi di prenotazione e app su misura per studi, centri estetici, campi sportivi, cantine, officine e risorse interne: agenda condivisa, promemoria, caparra online, lista d'attesa e collegamento alla scheda Google.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Pagina di prenotazione online","Promemoria automatici","Caparra e pagamento anticipato","Lista d'attesa","App per i clienti","Sincronizzazione con Google Calendar e Outlook"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/app-fidelizzazione-clienti/",
 "title":"App fidelizzazione clienti e fidelity card | Danova Tech",
 "desc":"App di fidelizzazione su misura: fidelity card digitale nel wallet del telefono, punti, premi, coupon, notifiche e inviti. Dati vostri, niente cartoncini.",
 "ogtitle":"App fidelizzazione clienti — Danova Tech",
 "ogdesc":"La tessera fedeltà che il cliente non perde: nel telefono, con punti, premi e messaggi al momento giusto.",
 "crumbs":[("App su misura","/servizi/app-su-misura/"),("Fidelizzazione clienti",None)],
 "eyebrow":"Fidelizzazione",
 "h1":"App di <span class=\"grad\">fidelizzazione clienti.</span>",
 "lead":"Il cartoncino con i timbri funziona ancora, ma non vi dice niente: chi sono i clienti migliori, quanto spesso tornano, chi ha smesso di venire. Una fidelity digitale fa lo stesso lavoro dal telefono del cliente, e in più vi restituisce i numeri per decidere a chi scrivere, quando e con quale offerta.",
 "cta1":"Parliamo dei vostri clienti", "cta2":"Come funziona",
 "sezioni":[
  {"id":"funzioni","tipo":"cards","eyebrow":"Come funziona",
   "h2":"I pezzi di un programma<br><span class=\"grad\">di fedeltà</span>",
   "corpo":[
    ("Tessera nel wallet","Il cliente si iscrive con un QR alla cassa e trova la tessera nel wallet del telefono, accanto alle carte d'imbarco. Non deve scaricare niente, e la tessera non si dimentica a casa."),
    ("Punti, timbri o cashback","Il meccanismo che capiscono i vostri clienti: dieci caffè e l'undicesimo è offerto, punti che diventano premi, una percentuale restituita come credito. Uno solo, spiegato in una riga."),
    ("Premi e livelli","Premi raggiungibili, non cataloghi che nessuno completa. Per chi spende molto, un livello con vantaggi veri: priorità, anteprime, un servizio in più."),
    ("Coupon e offerte","Offerte mirate a chi non torna da un mese, a chi compie gli anni, a chi compra sempre la stessa cosa. Non la stessa promozione a tutti."),
    ("Inviti","Il cliente invita un amico con un link; quando l'amico fa il primo acquisto, entrambi ricevono qualcosa. È il canale di acquisizione più economico che esista, se il prodotto è buono."),
    ("Numeri","Iscritti, clienti attivi, frequenza media, clienti persi, effetto di ogni campagna. Il valore del programma non sono i premi: sono questi dati.")]},
  {"id":"perche","tipo":"testo","eyebrow":"Perché conviene",
   "h2":"Il cliente che torna<br><span class=\"grad\">costa meno</span>",
   "corpo":[
    "Trovare un cliente nuovo costa pubblicità, sconti di benvenuto, tempo. Farne tornare uno che vi conosce già costa un messaggio al momento giusto. È la ragione per cui supermercati, catene di caffetterie e compagnie aeree hanno tutti un programma fedeltà, e la ragione per cui ha senso anche per un negozio, un ristorante o un centro estetico.",
    "La differenza fra un programma che funziona e uno che nessuno usa sta quasi sempre in due cose: <b>quanto è facile iscriversi</b>, e <b>quanto è vicino il primo premio</b>. Se servono cinque minuti per iscriversi e sei mesi per arrivare a un premio, il cliente perde interesse alla seconda visita.",
    "Il resto si costruisce guardando i dati: dopo tre mesi si vede chi torna e chi no, e si decide dove mettere i soldi dei premi."]},
  {"id":"privacy","tipo":"testo","eyebrow":"Da fare bene",
   "h2":"Consensi separati,<br><span class=\"grad\">dati vostri</span>",
   "corpo":[
    "Per partecipare al programma basta il consenso al programma. Per ricevere offerte serve un consenso al marketing, e per usare gli acquisti per offerte personalizzate serve un consenso alla profilazione: sono tre cose diverse, e il GDPR chiede di tenerle separate. Le impostiamo così dall'inizio, con testi chiari che non spaventano il cliente.",
    "I dati dei clienti restano vostri, su server in Europa. Non vengono usati per altri negozi né venduti, a differenza di alcune app di fidelizzazione gratuite dove il prodotto siete voi."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Dalla cassa<br><span class=\"grad\">al telefono.</span>",
   "corpo":[
    ("Il meccanismo","Timbri, punti o cashback: scegliamo insieme quello che i vostri clienti capiscono al primo colpo, e il primo premio."),
    ("Tessera e iscrizione","Tessera digitale con il vostro marchio, iscrizione con QR alla cassa in meno di un minuto."),
    ("Messaggi automatici","Benvenuto, compleanno, cliente che non torna, premio vicino. Partono da soli."),
    ("Collegamenti","Cassa, e-commerce, gestionale: quando servono, i punti si caricano da soli senza passaggi alla cassa.")]}],
 "faqtitle":"Le domande <span class=\"grad\">più frequenti.</span>",
 "faq":[
  ("Quanto costa un'app di fidelizzazione?","Una fidelity digitale con il vostro marchio, tessera nel wallet e pannello di gestione parte da 50 euro al mese oppure da 750 euro una tantum, IVA inclusa. App sugli store, collegamento alla cassa o all'e-commerce e più punti vendita si preventivano a parte, con prezzo fisso."),
  ("Il cliente deve scaricare un'app?","No, se non volete. La tessera va nel wallet del telefono, Apple o Google, con una scansione. L'app vera conviene quando volete offrire di più: ordini, prenotazioni, contenuti. Si può partire dalla tessera e aggiungerla dopo."),
  ("Si collega alla cassa?","Dipende dal software di cassa: molti permettono un collegamento, altri no. Se non si può, il punto si assegna alla cassa leggendo il QR del cliente con un telefono o un tablet, in due secondi."),
  ("Funziona per più negozi?","Sì. I punti valgono in tutti i punti vendita, e vedete i numeri per negozio e complessivi. Per una piccola catena locale è spesso il primo strumento che mette in comune i clienti."),
  ("Che differenza c'è con le app di fidelizzazione gratuite?","Quelle gratuite si ripagano in altro modo: con i dati dei vostri clienti, con la pubblicità di altri negozi o con commissioni. Con un sistema vostro pagate il servizio, e i clienti restano vostri.")],
 "ctabox":{"h2":"Sapete chi sono i vostri clienti migliori?",
  "p":"In mezz'ora di chiamata guardiamo come funziona oggi la vostra clientela abituale e vi proponiamo un meccanismo semplice, con quanto costa e quando si ripaga.",
  "btn":"Prenota la chiamata gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Sviluppo app su misura","/servizi/app-su-misura/"),
          ("App per prenotazioni e appuntamenti","/app-prenotazioni/"),
          ("Gestionale per palestre","/gestionale-palestra/"),
          ("App per personal trainer","/app-per-personal-trainer/"),
          ("CRM aziendale e gestione clienti","/crm-aziendale/"),
          ("Realizzazione e-commerce","/realizzazione-ecommerce/"),
          ("Meta Ads: Facebook e Instagram","/servizi/meta-ads/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"App di fidelizzazione clienti","type":"Sviluppo di programmi fedeltà digitali",
        "desc":"Programmi fedeltà digitali su misura: tessera nel wallet del telefono, punti, timbri o cashback, premi e livelli, coupon mirati, inviti e statistiche, con consensi GDPR separati e dati di proprietà del cliente.",
        "area":IT,"lingue":["Italian"],
        "catalogo":["Fidelity card digitale nel wallet","Punti, timbri e cashback","Coupon e offerte mirate","Programma inviti","Messaggi automatici","Statistiche sui clienti"]},
})
