# -*- coding: utf-8 -*-
"""Pagine nuove del 9 ottobre 2026 (quinto giro): scelte sui volumi del Keyword Planner
   (export del 9/10/2026, cartella keywords/planner-2026-10).
   Uso:  python3 seo-tools/pagine-build-2.py pagine-dati-5.py
   ATTENZIONE: iperammortamento e AI Act contengono date e norme: ricontrollare ogni 3 mesi."""
OGGI = "2026-10-09"
IT = [{"@type":"Country","name":"Italia"}]
PAGINE = []

# --- iperammortamento 2026  (50.000 ricerche/mese) --------------------------
PAGINE.append({
 "lang":"it", "url":"/iperammortamento-2026/",
 "title":"Iperammortamento 2026: aliquote, software, scadenze",
 "desc":"Iperammortamento 2026 spiegato da una software house: aliquote 180-100-50%, quali software rientrano, interconnessione, comunicazioni al GSE e scadenze.",
 "ogtitle":"Iperammortamento 2026: cosa rientra e cosa no — Danova Tech",
 "ogdesc":"Aliquote, software agevolabili, interconnessione e procedura GSE. Con la parte che molti non dicono: un gestionale o un sito di norma non rientrano.",
 "crumbs":[("Digitalizzazione aziendale","/digitalizzazione-aziendale/"),("Iperammortamento 2026",None)],
 "eyebrow":"Legge 199/2025 · aggiornato a ottobre 2026",
 "h1":"Iperammortamento 2026: <span class=\"grad\">cosa rientra, cosa no.</span>",
 "lead":"Dal 2026 l'agevolazione per chi investe in macchinari e software 4.0 è l'iperammortamento della Legge di Bilancio 2026, al posto di Transizione 4.0 e 5.0. Non è un credito d'imposta: è una maggiorazione del costo che si deduce. Qui trovate le aliquote, quali software rientrano davvero e la procedura al GSE, spiegati da chi i software li scrive.",
 "cta1":"Verifichiamo il vostro software", "cta2":"Le aliquote",
 "sezioni":[
  {"id":"aliquote","tipo":"cards","eyebrow":"I numeri",
   "h2":"Le aliquote,<br><span class=\"grad\">per scaglioni</span>",
   "lead":"Le percentuali si applicano a scaglioni: un investimento da 3 milioni prende il 180% sui primi 2,5 milioni e il 100% sui restanti 500.000.",
   "corpo":[
    ("+180% fino a 2,5 milioni","Sulla quota di investimento fino a 2,5 milioni di euro il costo deducibile aumenta del 180%. È lo scaglione in cui ricadono quasi tutte le PMI."),
    ("+100% da 2,5 a 10 milioni","Sulla quota compresa fra 2,5 e 10 milioni di euro la maggiorazione è del 100%."),
    ("+50% da 10 a 20 milioni","Sulla quota fra 10 e 20 milioni di euro la maggiorazione scende al 50%. Oltre i 20 milioni non c'è maggiorazione."),
    ("Nessun risparmio energetico da dimostrare","È la differenza principale rispetto a Transizione 5.0: non serve più certificare una riduzione dei consumi. Restano i requisiti 4.0 e l'interconnessione documentata.")]},
  {"id":"software","tipo":"testo","eyebrow":"Il punto pratico",
   "h2":"Quali software<br><span class=\"grad\">rientrano davvero</span>",
   "corpo":[
    "I beni immateriali agevolabili sono quelli elencati negli allegati alla norma, e hanno una caratteristica in comune: <b>servono a far funzionare, coordinare o monitorare beni materiali 4.0 interconnessi</b>. Rientrano, in genere: sistemi MES per la produzione, SCADA per la supervisione degli impianti, piattaforme PLM e PDM, piattaforme IoT e cloud di fabbrica, sistemi di tracciabilità collegati alle linee, applicazioni di realtà aumentata per manutenzione e formazione.",
    "<b>Di norma non rientrano</b>: il sito web, l'e-commerce, il gestionale amministrativo, il CRM commerciale, il software di contabilità, l'app per i clienti. Sono spesso investimenti ottimi, ma hanno la loro deducibilità ordinaria. Diffidate di chi ve li presenta come agevolati.",
    "Il requisito che scarta più pratiche è l'<b>interconnessione</b>: il bene deve scambiare dati con il sistema di gestione della produzione o con la rete di fornitura, in modo documentabile. Un software MES che dialoga con le macchine e con il gestionale è interconnesso; un foglio di calcolo in rete no. Quando sviluppiamo un software di produzione, l'interconnessione la progettiamo e la documentiamo dall'inizio, perché il perito la deve poter verificare."]},
  {"id":"procedura","tipo":"passi","eyebrow":"La procedura",
   "h2":"Le tre comunicazioni<br>al <span class=\"grad\">GSE</span>",
   "lead":"Tutto passa dal portale del GSE, con accesso SPID. Servono anche una perizia asseverata sulle caratteristiche 4.0 e una certificazione contabile delle spese.",
   "corpo":[
    ("Comunicazione preventiva","Prenota le risorse indicando l'investimento previsto. La piattaforma è aperta dal 12 giugno 2026."),
    ("Comunicazione di conferma","Entro 60 giorni dall'esito positivo della preventiva, con ordini accettati e almeno il 20% del costo già pagato."),
    ("Comunicazione di completamento","Entro il 15 novembre 2028, con gli investimenti da completare entro il 31 dicembre 2028."),
    ("Perizia e certificazione","Perizia asseverata di un tecnico abilitato su caratteristiche 4.0 e interconnessione, e certificazione contabile di un revisore legale. Sono i documenti su cui si regge la pratica in caso di controllo.")]},
  {"id":"onesta","tipo":"testo","eyebrow":"Una nota onesta",
   "h2":"Prima il progetto,<br><span class=\"grad\">poi l'incentivo</span>",
   "corpo":[
    "L'iperammortamento cambia il ritorno di un investimento, non lo crea. Il beneficio segue il piano di ammortamento del bene, quindi arriva in più esercizi e non subito come accadeva con il credito d'imposta. Se un progetto ha senso solo grazie all'agevolazione, quasi sempre non ha senso.",
    "Danova Tech è una software house, non uno studio fiscale. Questa pagina riassume le fonti pubbliche: legge 199/2025, articolo 1, commi 427-436, decreto interministeriale MIMIT-MEF del 7 maggio 2026 e decreto direttoriale del 10 giugno 2026. Prima di impegnare soldi verificate la vostra posizione con il commercialista. Se invece volete sapere se un certo software può rientrare fra i beni 4.0, ve lo guardiamo noi in mezz'ora, gratis."]}],
 "faqtitle":"Le domande <span class=\"grad\">sull'iperammortamento.</span>",
 "faq":[
  ("Cos'è l'iperammortamento 2026?","È l'agevolazione per gli investimenti in beni strumentali 4.0 introdotta dalla Legge di Bilancio 2026. Permette di dedurre un costo maggiorato: +180% fino a 2,5 milioni di euro, +100% fino a 10 milioni, +50% fino a 20 milioni. Sostituisce Transizione 4.0 e 5.0."),
  ("Il software è agevolabile con l'iperammortamento?","Sì, se è fra i beni immateriali elencati negli allegati e serve a far funzionare o monitorare beni materiali 4.0 interconnessi: MES, SCADA, PLM, piattaforme IoT di fabbrica. Un gestionale amministrativo, un CRM, un sito o un e-commerce di norma non rientrano."),
  ("Serve dimostrare un risparmio energetico?","No. Era il requisito di Transizione 5.0 che bloccava molte pratiche. Nell'iperammortamento 2026 restano i requisiti 4.0 e l'interconnessione, documentati da una perizia asseverata."),
  ("Quali sono le scadenze?","La comunicazione di conferma va inviata entro 60 giorni dall'esito positivo della preventiva, con almeno il 20% del costo pagato. La comunicazione di completamento scade il 15 novembre 2028, con investimenti completati entro il 31 dicembre 2028."),
  ("Che differenza c'è con il credito d'imposta?","Il credito d'imposta si compensava subito in F24. L'iperammortamento aumenta il costo deducibile e segue il piano di ammortamento del bene, quindi il vantaggio arriva in più anni. A parità di percentuale, l'effetto sulla cassa è più lento."),
  ("Potete fare voi la pratica?","No, la pratica la seguono il commercialista e un tecnico abilitato per la perizia. Noi progettiamo e documentiamo il software in modo che caratteristiche 4.0 e interconnessione siano verificabili, e forniamo al perito schede tecniche e prove di collegamento.")],
 "ctabox":{"h2":"Il vostro software può rientrare?",
  "p":"Mandateci cosa volete realizzare o acquistare: in mezz'ora vi diciamo se ha le caratteristiche per essere un bene 4.0 e cosa serve per documentarlo.",
  "btn":"Prenota la verifica gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Transizione 5.0: cosa è cambiato","/guide/transizione-5-0/"),
          ("Software MES per la produzione","/software-mes-produzione/"),
          ("Software gestionale produzione","/software-gestionale-produzione/"),
          ("Bandi digitalizzazione 2026 in Veneto","/bandi-digitalizzazione-veneto-2026/"),
          ("Digitalizzazione aziendale","/digitalizzazione-aziendale/"),
          ("Integrazione software aziendali","/integrazione-software-aziendali/")],
 "svc":{"name":"Software 4.0 per l'iperammortamento","type":"Sviluppo software industriale",
        "desc":"Progettazione e sviluppo di software MES, monitoraggio e tracciabilità interconnessi ai macchinari, con documentazione tecnica per la perizia richiesta dall'iperammortamento 2026.",
        "area":IT,"lingue":["Italian"],
        "catalogo":["Verifica dei requisiti 4.0 del software","Software MES e monitoraggio produzione","Interconnessione con macchine e gestionale","Documentazione tecnica per la perizia"]},
})

# --- AI Act (50.000) --------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/ai-act-aziende/",
 "title":"AI Act per le aziende: obblighi e scadenze 2026 | Danova Tech",
 "desc":"AI Act spiegato alle PMI: cosa è già obbligatorio, cosa cambia con il Digital Omnibus, trasparenza dei chatbot dal 2 agosto 2026 e formazione del personale.",
 "ogtitle":"AI Act per le aziende — Danova Tech",
 "ogdesc":"Cosa deve fare una PMI che usa ChatGPT, un chatbot o un software con l'intelligenza artificiale. Scadenze aggiornate dopo il Digital Omnibus.",
 "crumbs":[("Intelligenza artificiale per aziende","/intelligenza-artificiale-per-aziende/"),("AI Act",None)],
 "eyebrow":"Regolamento UE 2024/1689 · aggiornato a ottobre 2026",
 "h1":"AI Act per le aziende: <span class=\"grad\">cosa fare davvero.</span>",
 "lead":"Il regolamento europeo sull'intelligenza artificiale riguarda anche le PMI che si limitano a usare ChatGPT o a mettere un chatbot sul sito. La buona notizia è che per la maggior parte delle aziende gli obblighi sono pochi e gestibili. Il Digital Omnibus del 2026 ha spostato in avanti le regole sui sistemi ad alto rischio, ma alcune cose valgono già oggi.",
 "cta1":"Controlliamo i vostri strumenti AI", "cta2":"Il calendario",
 "sezioni":[
  {"id":"calendario","tipo":"passi","eyebrow":"Il calendario aggiornato",
   "h2":"Le date che contano,<br><span class=\"grad\">dopo il Digital Omnibus</span>",
   "lead":"Il Regolamento (UE) 2026/1744, il cosiddetto Digital Omnibus sull'AI, è in vigore dal 27 luglio 2026 e ha modificato alcune scadenze.",
   "corpo":[
    ("2 febbraio 2025","Pratiche di AI vietate e obbligo di adottare misure per la formazione del personale che usa l'AI. Già in vigore."),
    ("2 agosto 2026","Applicazione generale del regolamento e obblighi di trasparenza: chi parla con un chatbot deve saperlo, i contenuti sintetici vanno dichiarati."),
    ("2 dicembre 2026","Marcatura tecnica dei contenuti generati per i sistemi già sul mercato e due nuovi divieti, fra cui i deepfake intimi non consensuali."),
    ("2 dicembre 2027 e 2 agosto 2028","Obblighi per i sistemi ad alto rischio: quelli dell'allegato III, per esempio selezione del personale, credito e istruzione, slittano a dicembre 2027; quelli dentro prodotti regolati ad agosto 2028.")]},
  {"id":"pmi","tipo":"cards","eyebrow":"Per una PMI tipica",
   "h2":"Cosa fare<br><span class=\"grad\">se usate l'AI in azienda</span>",
   "lead":"Una PMI che usa assistenti AI, un chatbot sul sito o un software con funzioni di AI è, per il regolamento, un deployer. Ecco cosa le serve.",
   "corpo":[
    ("Un elenco degli strumenti","Quali strumenti AI usate, chi li usa, per cosa e con quali dati. Spesso è la prima volta che l'azienda scopre quanti ne girano: è anche la base per la privacy."),
    ("Formazione documentata","L'obbligo resta, in forma più leggera: misure per sostenere la competenza di chi usa l'AI, senza un livello minimo da certificare. Una formazione breve e registrata su funzionamento, limiti ed errori tipici è la risposta proporzionata."),
    ("Chatbot dichiarato","Se sul sito o su WhatsApp risponde un assistente AI, l'utente deve capirlo in modo chiaro, non da una clausola nelle condizioni d'uso. Lo stesso per testi, immagini o video generati pubblicati come informazione."),
    ("Regole interne sull'uso","Cosa si può incollare negli assistenti e cosa no: dati dei clienti, contratti, progetti. Quali strumenti sono approvati. Mezza pagina scritta vale più di dieci riunioni."),
    ("Attenzione all'alto rischio","Se usate l'AI per scegliere candidati, valutare dipendenti o concedere credito, entrate nell'alto rischio: avete tempo fino a dicembre 2027, ma il progetto va impostato adesso."),
    ("Legge italiana sull'AI","La legge 132/2025 aggiunge regole nazionali, fra cui l'informazione ai lavoratori quando si usano sistemi di AI e l'obbligo per i professionisti di informare i clienti.")]},
  {"id":"noi","tipo":"testo","eyebrow":"Cosa facciamo noi",
   "h2":"Strumenti AI<br><span class=\"grad\">già in regola</span>",
   "corpo":[
    "Quando realizziamo un chatbot, un agente AI o un'automazione, la trasparenza la mettiamo nel progetto: l'avviso che si sta parlando con un assistente, il passaggio a una persona, i registri delle conversazioni, i dati su server europei e la possibilità di cancellarli.",
    "Possiamo anche aiutarvi a fare l'elenco degli strumenti AI in uso e a preparare la formazione interna. Per gli aspetti legali e per i sistemi ad alto rischio, invece, serve un avvocato o un consulente specializzato: siamo una software house, e questa pagina è un riassunto delle fonti pubbliche, non un parere legale."]}],
 "faqtitle":"Le domande <span class=\"grad\">sull'AI Act.</span>",
 "faq":[
  ("L'AI Act riguarda anche le piccole aziende?","Sì. Riguarda chi sviluppa sistemi di AI e anche chi li usa in azienda, compresi assistenti come ChatGPT e chatbot sul sito. Per una PMI che non usa sistemi ad alto rischio gli obblighi principali sono la formazione del personale e la trasparenza verso chi interagisce con l'AI."),
  ("Cosa ha cambiato il Digital Omnibus?","Il Regolamento (UE) 2026/1744, in vigore dal 27 luglio 2026, ha rinviato gli obblighi per i sistemi ad alto rischio al 2 dicembre 2027 e al 2 agosto 2028, ha reso più leggero l'obbligo di alfabetizzazione e ha esteso alcune semplificazioni alle imprese medio-piccole. Gli obblighi di trasparenza sono rimasti al 2 agosto 2026."),
  ("La formazione sull'AI è obbligatoria?","Resta l'obbligo di adottare misure per sostenere la competenza di chi usa l'AI per conto dell'azienda, senza dover garantire un livello minimo. In pratica: una formazione proporzionata all'uso, documentata e ripetuta quando cambiano gli strumenti."),
  ("Devo dire che sul sito risponde un chatbot?","Sì. Dal 2 agosto 2026 chi interagisce con un sistema di AI deve esserne informato in modo chiaro, salvo che sia evidente dal contesto. Il modo più semplice è un messaggio di benvenuto che lo dichiara e un pulsante per parlare con una persona."),
  ("Quali sono le sanzioni?","Per le violazioni degli obblighi di trasparenza arrivano fino a 15 milioni di euro o al 3% del fatturato mondiale, con importi ridotti per le PMI. Per le pratiche vietate le cifre sono più alte."),
  ("Mi fate voi l'adeguamento legale?","No: per il parere legale serve un avvocato. Noi rendiamo conformi gli strumenti che sviluppiamo, vi aiutiamo a censire quelli che usate e a preparare formazione e regole interne.")],
 "ctabox":{"h2":"Usate l'AI in azienda e non sapete se siete a posto?",
  "p":"Elenchiamo con voi gli strumenti AI in uso e vi diciamo cosa sistemare per primo: chatbot, regole interne, formazione. Mezz'ora, gratis.",
  "btn":"Prenota la chiamata"},
 "altrititle":"Pagine collegate",
 "altri":[("Intelligenza artificiale per aziende","/intelligenza-artificiale-per-aziende/"),
          ("Chatbot aziendale e agenti AI","/chatbot-aziendale/"),
          ("Automazioni con n8n","/automazioni-n8n/"),
          ("SEO per l&#8217;intelligenza artificiale","/seo-per-intelligenza-artificiale/"),
          ("Automazione processi aziendali","/automazione-processi-aziendali/")],
 "svc":{"name":"Strumenti di intelligenza artificiale conformi all'AI Act","type":"Consulenza e sviluppo di soluzioni AI",
        "desc":"Sviluppo di chatbot, agenti AI e automazioni con trasparenza verso l'utente, dati in Europa e registri, più supporto alle PMI per censire gli strumenti AI in uso e organizzare la formazione del personale.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Censimento degli strumenti AI in uso","Chatbot con avviso di trasparenza","Regole interne sull'uso dell'AI","Formazione del personale"]},
})

# --- n8n / automazioni (n8n 50.000, zapier 50.000, rpa 5.000) ---------------
PAGINE.append({
 "lang":"it", "url":"/automazioni-n8n/",
 "title":"Automazioni n8n per aziende: consulenza e sviluppo | Danova Tech",
 "desc":"Automazioni con n8n per aziende: colleghiamo gestionale, CRM, email, WhatsApp e AI. n8n su server europeo, alternativa a Zapier e Make senza costi a operazione.",
 "ogtitle":"Automazioni con n8n — Danova Tech",
 "ogdesc":"I lavori ripetitivi fra un software e l'altro, fatti da soli. Con n8n installato su un server vostro, in Europa.",
 "crumbs":[("Software e automazioni","/servizi/software-automazioni/"),("Automazioni n8n",None)],
 "eyebrow":"n8n · Zapier · Make · agenti AI",
 "h1":"Automazioni con n8n: <span class=\"grad\">i software parlano fra loro.</span>",
 "lead":"Ogni azienda ha qualcuno che passa ore a copiare dati da un programma all'altro: l'ordine dall'email al gestionale, il contatto dal modulo al CRM, la fattura dalla PEC alla cartella giusta. n8n è lo strumento con cui colleghiamo questi passaggi e li facciamo girare da soli, anche con l'intelligenza artificiale in mezzo quando serve leggere o decidere.",
 "cta1":"Raccontateci il lavoro ripetitivo", "cta2":"Cosa si automatizza",
 "sezioni":[
  {"id":"esempi","tipo":"cards","eyebrow":"Esempi reali",
   "h2":"Cosa si automatizza<br><span class=\"grad\">in una PMI</span>",
   "corpo":[
    ("Ordini da email a gestionale","L'ordine arriva in PDF per email. L'AI legge articoli e quantità, n8n crea la bozza d'ordine nel gestionale e la segnala a chi deve approvarla. Da venti minuti a pochi secondi per ordine."),
    ("Contatti dal sito al CRM","Il modulo del sito, la campagna Meta e il messaggio WhatsApp finiscono nello stesso CRM, con la fonte, l'assegnazione al commerciale giusto e la risposta automatica entro un minuto."),
    ("Documenti nelle cartelle giuste","Fatture, DDT e certificati estratti dalla PEC, rinominati, archiviati e registrati, con un avviso quando manca qualcosa."),
    ("Report che arrivano da soli","Ogni lunedì il riepilogo di vendite, preventivi aperti e consegne in ritardo, preso da tre programmi diversi e mandato via email o Teams."),
    ("E-commerce e magazzino","Ordini dello shop nel gestionale, giacenze aggiornate sul sito, etichette del corriere create, cliente avvisato con il tracking."),
    ("Agenti AI con le vostre regole","Assistenti che rispondono alle richieste ripetitive dei clienti usando i vostri listini e documenti, e passano a una persona quando non sono sicuri.")]},
  {"id":"perche","tipo":"testo","eyebrow":"Perché n8n",
   "h2":"n8n, Zapier o Make:<br><span class=\"grad\">cosa scegliere</span>",
   "corpo":[
    "Zapier e Make sono ottimi per partire e per automazioni semplici. Si pagano a operazione: quando le automazioni girano migliaia di volte al mese, il costo sale in fretta, e i dati passano da server fuori dal vostro controllo.",
    "<b>n8n</b> si può installare su un server vostro, in Europa, e la licenza permette l'uso interno senza costi a operazione. Collega centinaia di servizi già pronti e, quando un collegamento non esiste, si scrive in codice. Per un'azienda che manipola ordini, dati dei clienti e documenti, è la scelta che consigliamo più spesso.",
    "Non è sempre la risposta giusta: se un'automazione è il cuore del vostro lavoro, a volte conviene scriverla direttamente nel gestionale. Ve lo diciamo dopo aver visto il processo."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lavoriamo",
   "h2":"Dal lavoro manuale<br>all'<span class=\"grad\">automazione che regge.</span>",
   "corpo":[
    ("Mappatura","Guardiamo con chi fa il lavoro oggi ogni passaggio, le eccezioni e i casi strani. Le automazioni falliscono sulle eccezioni, non sul caso normale."),
    ("Prima automazione","Partiamo da quella che fa risparmiare più ore. Online in pochi giorni, con un controllo umano finché non ci fidiamo."),
    ("Installazione e sicurezza","n8n su server europeo, accessi con ruoli, credenziali cifrate, backup e registri di ogni esecuzione."),
    ("Monitoraggio","Se un'automazione fallisce, arriva un avviso e la vediamo noi prima che ve ne accorgiate voi.")]}],
 "faqtitle":"Le domande <span class=\"grad\">sulle automazioni.</span>",
 "faq":[
  ("Cos'è n8n?","È una piattaforma per automatizzare i flussi di lavoro collegando software diversi: gestionale, CRM, email, fogli di calcolo, e-commerce, servizi di intelligenza artificiale. Si può usare in cloud o installare su un server proprio."),
  ("n8n è gratis?","La versione installabile su un server proprio si può usare per i processi interni dell'azienda senza costi di licenza a operazione; esistono anche piani in cloud e enterprise a pagamento. Restano i costi del server e della realizzazione delle automazioni."),
  ("Meglio n8n o Zapier?","Zapier è più semplice per automazioni leggere. n8n conviene quando le automazioni sono tante o complesse, quando servono logica e codice personalizzati o quando volete i dati su un server vostro in Europa."),
  ("Si può collegare al nostro gestionale?","Quasi sempre sì: tramite API, database, file di scambio o email. Se il gestionale non ha collegamenti, valutiamo la strada più solida prima di promettere."),
  ("Che cos'è l'RPA e che differenza c'è?","L'RPA imita una persona che clicca sui programmi. È utile quando un software non ha alcun modo di essere collegato, ma è più fragile. Con n8n si lavora sulle API e sui dati, ed è più stabile."),
  ("Quanto costa un'automazione?","Dipende da quante sono e da quanto sono complesse. Vi diamo un prezzo fisso dopo la mappatura, e vi diciamo quante ore al mese vi fa risparmiare: se il conto non torna, ve lo diciamo.")],
 "ctabox":{"h2":"Qual è il lavoro che odiate di più?",
  "p":"Raccontateci un'attività che fate a mano ogni settimana. Vi diciamo se si può automatizzare e quante ore vi restituisce.",
  "btn":"Prenota la chiamata gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Automazione processi aziendali","/automazione-processi-aziendali/"),
          ("Integrazione software aziendali","/integrazione-software-aziendali/"),
          ("Chatbot aziendale e agenti AI","/chatbot-aziendale/"),
          ("Intelligenza artificiale per aziende","/intelligenza-artificiale-per-aziende/"),
          ("AI Act per le aziende","/ai-act-aziende/"),
          ("CRM aziendale","/crm-aziendale/")],
 "svc":{"name":"Automazioni con n8n","type":"Automazione dei processi aziendali",
        "desc":"Progettazione, installazione su server europeo e manutenzione di automazioni n8n che collegano gestionale, CRM, email, e-commerce e servizi di intelligenza artificiale.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Mappatura dei processi","Installazione n8n su server europeo","Automazioni con intelligenza artificiale","Migrazione da Zapier e Make","Monitoraggio e manutenzione"]},
})

# --- recensioni Google (5.000) ---------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/come-ottenere-recensioni-google/",
 "title":"Come ottenere recensioni Google, nel modo giusto | Danova Tech",
 "desc":"Come ottenere più recensioni Google senza violare le regole: link diretto, QR code, momento giusto e risposte. Cosa è vietato e perché contano per Maps.",
 "ogtitle":"Come ottenere recensioni Google — Danova Tech",
 "ogdesc":"Le recensioni pesano sulla posizione in Google Maps e sulla scelta del cliente. Come chiederle, come rispondere e cosa non fare mai.",
 "crumbs":[("SEO","/servizi/seo/"),("Recensioni Google",None)],
 "eyebrow":"Google Business Profile · SEO locale",
 "h1":"Come ottenere recensioni Google <span class=\"grad\">senza scorciatoie.</span>",
 "lead":"Fra due aziende vicine che fanno la stessa cosa, il cliente sceglie quasi sempre quella con più recensioni recenti. E Google fa lo stesso quando decide chi mostrare in Maps. Ottenerle non è difficile: va chiesto alle persone giuste, nel momento giusto, con un link che porta dritto al punto. Ecco come, e cosa non fare.",
 "cta1":"Sistemiamo la vostra scheda Google", "cta2":"Come chiederle",
 "sezioni":[
  {"id":"come","tipo":"passi","eyebrow":"Il metodo",
   "h2":"Come chiederle,<br><span class=\"grad\">in quattro mosse</span>",
   "corpo":[
    ("Prendete il link diretto","Dalla scheda Google Business Profile, alla voce per chiedere recensioni, Google vi dà un link breve che apre direttamente la finestra con le stelle. Niente ricerche, niente passaggi in più."),
    ("Scegliete il momento","Subito dopo un buon risultato: la consegna, il collaudo, il problema risolto. Una settimana dopo la soddisfazione è già sbiadita."),
    ("Rendetelo un'abitudine","Il link nella firma email, nel messaggio di fine lavoro, sulla fattura. Un QR code al banco, in negozio, allo stand in fiera. Funziona quello che si fa sempre, non la campagna una tantum."),
    ("Rispondete a tutte","Ringraziate chi scrive bene, con una frase che non sia copiata. Rispondete alle critiche con calma e con i fatti: chi legge giudica la risposta più della critica.")]},
  {"id":"vietato","tipo":"cards","eyebrow":"Cosa non fare",
   "h2":"Le scorciatoie<br><span class=\"grad\">che costano care</span>",
   "corpo":[
    ("Comprare recensioni","Vietato da Google e dalla legge italiana, che dal 2023 considera pratica commerciale scorretta le recensioni false o commissionate. Google le rimuove a ondate e può limitare la scheda."),
    ("Sconti in cambio di stelle","Offrire un regalo o uno sconto per una recensione è contro le regole di Google, anche se la recensione è sincera."),
    ("Chiedere solo ai contenti","Filtrare prima i clienti e mandare a Google solo chi è soddisfatto è vietato dalle norme di Google. Il link si manda a tutti."),
    ("Recensioni di dipendenti e parenti","Google le riconosce dalla posizione e dall'attività dell'account e le elimina. Rischiano di trascinare con sé anche quelle vere.")]},
  {"id":"perche","tipo":"testo","eyebrow":"Perché contano",
   "h2":"Recensioni e<br><span class=\"grad\">posizione in Maps</span>",
   "corpo":[
    "Google indica tre fattori per i risultati locali: pertinenza, distanza e prominenza. Le recensioni pesano sulla prominenza: quante sono, quanto sono recenti e cosa dicono. Una recensione che cita il servizio e la città aiuta più di cinque stelle senza testo.",
    "Le recensioni contano anche fuori da Google: gli assistenti AI come ChatGPT e Perplexity, quando consigliano un fornitore, leggono spesso le schede e le recensioni. Una scheda curata è una delle fonti più forti per essere citati.",
    "Le recensioni lavorano insieme al resto della scheda: categorie giuste, orari, foto vere, servizi descritti, post periodici. Se la scheda è incompleta, nemmeno cento recensioni la portano in cima."]}],
 "faqtitle":"Le domande <span class=\"grad\">sulle recensioni.</span>",
 "faq":[
  ("Come si ottiene il link per le recensioni Google?","Dalla gestione del profilo dell'attività su Google, alla voce per chiedere recensioni: Google genera un link breve che apre direttamente la finestra per scrivere la recensione. Si può condividere per email, WhatsApp o trasformare in QR code."),
  ("Si possono cancellare le recensioni negative?","Solo se violano le norme di Google: insulti, contenuti falsi, conflitti di interesse, recensioni non riferite a un'esperienza reale. In quel caso si segnalano dalla scheda. Una critica legittima resta, e la risposta migliore è una replica educata e concreta."),
  ("È legale chiedere recensioni ai clienti?","Sì, chiederle è legale e consigliato. È vietato offrire compensi o sconti in cambio, pubblicare recensioni false o commissionate e chiedere solo ai clienti soddisfatti."),
  ("Quante recensioni servono per salire in Google Maps?","Non c'è un numero magico: conta il confronto con le attività vicine dello stesso settore, e conta la regolarità. Qualche recensione nuova ogni mese vale più di trenta arrivate nella stessa settimana."),
  ("Conviene un QR code per le recensioni?","Sì, nei luoghi fisici: banco, negozio, cantiere, stand in fiera. Il QR code porta al link diretto e toglie al cliente la fatica di cercarvi. Sulle cartoline NFC vale lo stesso discorso."),
  ("Vi occupate voi della scheda Google?","Sì, nella consulenza SEO locale: sistemiamo la scheda, prepariamo link e QR code, impostiamo il messaggio di fine lavoro e vi aiutiamo a rispondere. Le recensioni però le devono scrivere i vostri clienti.")],
 "ctabox":{"h2":"La vostra scheda Google lavora per voi?",
  "p":"Mandateci il nome della vostra attività: vi diciamo come si posiziona in Maps rispetto ai concorrenti vicini e cosa sistemare per primo.",
  "btn":"Richiedi l'analisi gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Google Business Profile: la guida","/guide/google-business-profile-guida/"),
          ("Consulenza SEO","/servizi/seo/"),
          ("Posizionamento sito su Google","/posizionamento-sito-google/"),
          ("SEO per l&#8217;intelligenza artificiale","/seo-per-intelligenza-artificiale/"),
          ("Consulente SEO a Treviso","/consulente-seo-treviso/")],
 "svc":{"name":"Gestione recensioni e scheda Google","type":"SEO locale",
        "desc":"Ottimizzazione della scheda Google Business Profile, link e QR code per le recensioni, messaggi di richiesta e supporto nelle risposte, nel rispetto delle norme di Google e del Codice del consumo.",
        "area":IT,"lingue":["Italian"],
        "catalogo":["Ottimizzazione Google Business Profile","Link e QR code per le recensioni","Processo di richiesta recensioni","Supporto alle risposte"]},
})

# --- WMS (5.000) -----------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/software-wms/",
 "title":"Software WMS per la gestione del magazzino | Danova Tech",
 "desc":"Software WMS su misura: ubicazioni, barcode e palmari, picking guidato, lotti e scadenze, inventari rotativi, integrazione con gestionale ed e-commerce.",
 "ogtitle":"Software WMS su misura — Danova Tech",
 "ogdesc":"Quando il magazzino non sta più nella testa di chi ci lavora da vent'anni. Un WMS fatto sul vostro modo di muovere la merce.",
 "crumbs":[("Gestionali e CRM","/servizi/gestionali-crm/"),("Software WMS",None)],
 "eyebrow":"Warehouse Management System",
 "h1":"Software WMS: <span class=\"grad\">ogni pezzo, al suo posto.</span>",
 "lead":"Il gestionale sa quanti pezzi avete. Il WMS sa dove sono: in quale scaffale, in quale lotto, con quale scadenza, e qual è il giro più corto per prenderli. Serve quando il magazzino cresce, quando arrivano persone nuove o quando gli errori di spedizione cominciano a costare più del software.",
 "cta1":"Raccontateci il vostro magazzino", "cta2":"Cosa fa un WMS",
 "sezioni":[
  {"id":"funzioni","tipo":"cards","eyebrow":"Le funzioni",
   "h2":"Cosa fa<br><span class=\"grad\">un WMS</span>",
   "corpo":[
    ("Ubicazioni","Ogni scaffale, ripiano e posto pallet ha un codice. La merce in arrivo viene assegnata a un'ubicazione, e chiunque la ritrova senza chiedere."),
    ("Barcode e palmari","Carico, prelievo e spostamenti si confermano sparando il codice a barre o il QR con un palmare o con il telefono. Niente più carta, niente più errori di trascrizione."),
    ("Picking guidato","Le righe d'ordine vengono raggruppate e ordinate per percorso. Il magazziniere segue la lista sul palmare e il sistema blocca il prelievo sbagliato."),
    ("Lotti, seriali e scadenze","Tracciabilità completa per lotto o numero di serie, con logica FIFO o FEFO. Indispensabile in alimentare, farmaceutico e ricambi."),
    ("Inventari rotativi","Si conta un'area alla volta durante l'anno, senza fermare il magazzino per l'inventario di fine anno."),
    ("Integrazioni","Gestionale ed ERP, e-commerce, marketplace, corrieri per etichette e tracking. Il WMS non sostituisce il gestionale: lo completa.")]},
  {"id":"quando","tipo":"testo","eyebrow":"Su misura o pacchetto",
   "h2":"Quando serve<br><span class=\"grad\">un WMS su misura</span>",
   "corpo":[
    "Per un magazzino semplice spesso basta il modulo magazzino del gestionale che avete già. Ve lo diciamo, se è così.",
    "Un WMS su misura conviene quando il vostro modo di lavorare è parte del vantaggio: kit e distinte da preparare, conto deposito presso clienti, magazzini su più sedi, produzione che preleva e versa, merce con regole particolari. Lì un pacchetto vi costringe ad adattarvi, o a lavorare fuori dal sistema.",
    "Lo costruiamo come applicazione web che gira su computer, palmari Android e telefoni, collegata al vostro gestionale. Se il WMS è collegato ai macchinari di produzione, può anche rientrare nell'<a href=\"/iperammortamento-2026/\">iperammortamento 2026</a>: va valutato caso per caso."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Dal sopralluogo<br>al <span class=\"grad\">primo prelievo.</span>",
   "corpo":[
    ("Sopralluogo","Guardiamo il magazzino, i flussi, gli errori più frequenti e il gestionale. Mezza giornata, gratuita nel Nord-Est."),
    ("Codifica delle ubicazioni","Si decide come etichettare scaffali e posti pallet. È il lavoro più fisico, e quello che rende possibile tutto il resto."),
    ("Prima versione","Carico, ubicazioni e picking con palmare, collegati al gestionale. Si parte con una zona del magazzino, poi si estende."),
    ("Ottimizzazione","Con i dati dei primi mesi riorganizziamo le ubicazioni: gli articoli più richiesti vicino alla spedizione.")]}],
 "faqtitle":"Le domande <span class=\"grad\">sui WMS.</span>",
 "faq":[
  ("Che cos'è un WMS?","Un Warehouse Management System è il software che gestisce le operazioni fisiche del magazzino: ubicazioni, ricevimento, stoccaggio, prelievo, spedizione e inventari. A differenza del modulo magazzino del gestionale, sa dove si trova ogni articolo e guida le persone nelle operazioni."),
  ("Che differenza c'è fra WMS e gestionale di magazzino?","Il gestionale registra quantità e valori: carichi, scarichi, giacenze, costi. Il WMS gestisce lo spazio e le operazioni: dove mettere la merce, cosa prelevare, in che ordine, con quale lotto. I due lavorano insieme."),
  ("Servono palmari specifici?","Non sempre. Per volumi bassi bastano telefoni Android con la fotocamera. Per uso intenso conviene un palmare industriale con lettore laser, più robusto e veloce. Vi consigliamo i modelli in base ai volumi."),
  ("Si collega al nostro gestionale?","Sì: lo integriamo con il gestionale o l'ERP che usate, tramite API, database o scambio di file, in modo che ordini, articoli e giacenze siano sempre allineati."),
  ("Quanto tempo serve per partire?","Una prima versione con ubicazioni, barcode e picking, su una zona del magazzino, richiede di solito qualche settimana dopo il sopralluogo. La parte più lunga è etichettare gli scaffali."),
  ("Quanto costa un WMS su misura?","Dipende da volumi, numero di sedi e integrazioni. Il punto di partenza per un gestionale su misura è sul nostro listino; per il WMS vi diamo un prezzo fisso dopo il sopralluogo.")],
 "ctabox":{"h2":"Quanto vi costano gli errori di spedizione?",
  "p":"Raccontateci come lavora il vostro magazzino oggi: vi diciamo se vi serve un WMS o se basta sistemare quello che avete.",
  "btn":"Prenota il sopralluogo"},
 "altrititle":"Pagine collegate",
 "altri":[("Software gestionale magazzino","/software-gestionale-magazzino/"),
          ("App magazzino con codici a barre","/app-magazzino-codici-a-barre/"),
          ("Software trasporti e logistica","/software-gestionale-trasporti-logistica/"),
          ("E-commerce collegato al gestionale","/ecommerce-collegato-al-gestionale/"),
          ("Software MES per la produzione","/software-mes-produzione/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Software WMS su misura","type":"Sviluppo software gestionale",
        "desc":"Sviluppo di Warehouse Management System su misura con ubicazioni, barcode e palmari, picking guidato, lotti e scadenze, inventari rotativi e integrazione con gestionale, e-commerce e corrieri.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Gestione ubicazioni","Barcode e palmari","Picking guidato","Lotti, seriali e scadenze","Inventari rotativi","Integrazione con ERP ed e-commerce"]},
})

# --- portale rivenditori (5.000) -------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/portale-rivenditori-b2b/",
 "title":"Portale rivenditori B2B: ordini e listini | Danova Tech",
 "desc":"Portale rivenditori B2B su misura: listini personalizzati, disponibilità in tempo reale, ordini, documenti e garanzie, collegato al vostro gestionale.",
 "ogtitle":"Portale rivenditori B2B — Danova Tech",
 "ogdesc":"I vostri rivenditori ordinano, controllano disponibilità e scaricano documenti da soli, 24 ore su 24. E il vostro ufficio commerciale torna a vendere.",
 "crumbs":[("Siti web ed e-commerce","/servizi/siti-web-ecommerce/"),("Portale rivenditori",None)],
 "eyebrow":"B2B · rivenditori · agenti",
 "h1":"Portale rivenditori: <span class=\"grad\">la rete ordina da sola.</span>",
 "lead":"Telefonate per sapere se un articolo è disponibile, email per il listino aggiornato, ordini scritti a mano e ricopiati in ufficio. Con una rete di rivenditori, l'ufficio commerciale passa metà della giornata a rispondere invece che a vendere. Un portale riservato, collegato al gestionale, risponde da solo alle domande di tutti i giorni.",
 "cta1":"Parliamo della vostra rete", "cta2":"Cosa c'è dentro",
 "sezioni":[
  {"id":"funzioni","tipo":"cards","eyebrow":"Le funzioni",
   "h2":"Cosa trova<br><span class=\"grad\">il rivenditore</span>",
   "corpo":[
    ("Il suo listino","Ogni rivenditore vede i prezzi suoi: sconti per classe, condizioni particolari, promozioni riservate. Presi dal gestionale, mai da un PDF vecchio."),
    ("Disponibilità e tempi","Giacenza e data di arrivo prevista, articolo per articolo. La domanda più frequente al telefono smette di esserlo."),
    ("Ordini e riordini","Carrello, ordini ricorrenti, caricamento da file o da codice. L'ordine entra nel gestionale senza essere ricopiato."),
    ("Documenti","Fatture, DDT, conferme d'ordine, schede tecniche, certificazioni, manuali. Sempre aggiornati, scaricabili quando servono."),
    ("Materiale marketing","Foto, cataloghi, video, testi per il sito del rivenditore. Il vostro marchio presentato bene anche dove non ci siete."),
    ("Assistenza e garanzie","Apertura di resi e richieste di garanzia con foto e numero di serie, e stato della pratica visibile in ogni momento.")]},
  {"id":"differenza","tipo":"testo","eyebrow":"Portale o e-commerce",
   "h2":"Un portale<br><span class=\"grad\">non è un negozio online</span>",
   "corpo":[
    "Un e-commerce B2C vende a chiunque, a prezzo pubblico. Un portale rivenditori è chiuso, e ogni utente vede condizioni diverse: listini, pagamenti, minimi d'ordine, articoli riservati. La parte difficile non è la grafica, è il collegamento con il gestionale che quelle condizioni le conosce già.",
    "Per questo partiamo sempre dal gestionale: leggiamo da lì clienti, listini e giacenze, e scriviamo lì gli ordini. Il portale diventa una finestra aperta sui vostri dati, non una copia da tenere allineata a mano.",
    "Se gli agenti di commercio lavorano con la stessa rete, il portale può avere anche una parte per loro: ordini per conto del cliente, provvigioni, situazione dei pagamenti. Ne parliamo nella pagina sull'<a href=\"/app-per-agenti-di-commercio/\">app per agenti di commercio</a>."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Dal gestionale<br>al <span class=\"grad\">primo ordine online.</span>",
   "corpo":[
    ("Analisi","Come ordinano oggi i rivenditori, quali condizioni hanno, cosa chiedono più spesso al telefono, quale gestionale usate."),
    ("Collegamento al gestionale","Il lavoro più importante: clienti, listini, giacenze e ordini letti e scritti in automatico."),
    ("Pilota con pochi rivenditori","Partiamo con cinque o dieci rivenditori di fiducia, raccogliamo i commenti, correggiamo."),
    ("Apertura a tutta la rete","Inviti, guida rapida, assistenza nelle prime settimane. Il portale funziona quando i rivenditori lo usano davvero.")]}],
 "faqtitle":"Le domande <span class=\"grad\">sul portale.</span>",
 "faq":[
  ("Che cos'è un portale rivenditori?","È un'area web riservata in cui i rivenditori di un'azienda vedono il proprio listino, controllano la disponibilità, fanno ordini, scaricano documenti e materiale marketing. È collegato al gestionale, quindi i dati sono sempre aggiornati."),
  ("Con quali gestionali si collega?","Con la maggior parte dei gestionali usati dalle PMI italiane, tramite API, database o file di scambio. Prima di iniziare verifichiamo come il vostro gestionale espone i dati e ve lo diciamo con chiarezza."),
  ("Ogni rivenditore vede prezzi diversi?","Sì, ed è il punto centrale. Le condizioni di ogni rivenditore vengono lette dal gestionale: listino, sconti, pagamento, minimi d'ordine, articoli riservati."),
  ("È diverso da un e-commerce B2B?","Spesso sono la stessa cosa con nomi diversi. Parliamo di portale rivenditori quando l'accesso è riservato alla rete e le funzioni vanno oltre l'ordine: documenti, materiale marketing, garanzie, assistenza."),
  ("Funziona anche in più lingue?","Sì. Per le reti di distributori all'estero il portale può essere multilingua, con listini in valute diverse e documenti per paese."),
  ("Quanto costa un portale rivenditori?","Dipende soprattutto dall'integrazione con il gestionale e dal numero di funzioni. Vi diamo un prezzo fisso dopo l'analisi; il punto di partenza per i progetti su misura è sul nostro listino.")],
 "ctabox":{"h2":"Quante telefonate al giorno arrivano dai rivenditori?",
  "p":"Raccontateci la vostra rete e il gestionale che usate: vi diciamo come un portale cambierebbe il lavoro dell'ufficio commerciale.",
  "btn":"Prenota la chiamata gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("E-commerce B2B","/ecommerce-b2b/"),
          ("E-commerce collegato al gestionale","/ecommerce-collegato-al-gestionale/"),
          ("App per agenti di commercio","/app-per-agenti-di-commercio/"),
          ("Software preventivi e configuratore","/software-preventivi-configuratore/"),
          ("Integrazione software aziendali","/integrazione-software-aziendali/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Portale rivenditori B2B","type":"Sviluppo di portali web B2B",
        "desc":"Sviluppo di portali riservati per reti di rivenditori e distributori: listini personalizzati, disponibilità, ordini, documenti, materiale marketing, resi e garanzie, integrati con il gestionale.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Listini personalizzati per rivenditore","Disponibilità in tempo reale","Ordini integrati nel gestionale","Area documenti","Materiale marketing","Resi e garanzie"]},
})

# --- siti per hotel (sito web per hotel 500, siti web hotel 500, bid 8,82) ---
PAGINE.append({
 "lang":"it", "url":"/siti-web-per-hotel/",
 "title":"Siti web per hotel e B&B con prenotazione diretta | Danova Tech",
 "desc":"Siti web per hotel, B&B e case vacanza: prenotazione diretta senza commissioni, booking engine, multilingua, Google Hotel e SEO locale.",
 "ogtitle":"Siti web per hotel e B&B — Danova Tech",
 "ogdesc":"Ogni prenotazione che arriva dal vostro sito è una commissione che non pagate. Come costruire un sito che prenota.",
 "crumbs":[("Siti web","/servizi/siti-web-ecommerce/"),("Siti per hotel",None)],
 "eyebrow":"Hotel · B&B · case vacanza",
 "h1":"Siti web per hotel: <span class=\"grad\">più prenotazioni dirette.</span>",
 "lead":"Le OTA portano clienti, e se li fanno pagare: le commissioni dei grandi portali stanno spesso fra il 15 e il 20% del soggiorno. Molti ospiti, prima di prenotare su un portale, passano dal sito della struttura a guardare foto e prezzi. Se lì trova un sito lento o senza prenotazione, torna sul portale. Un buon sito trasforma quella visita in una prenotazione diretta.",
 "cta1":"Parliamo della vostra struttura", "cta2":"Cosa serve al sito",
 "sezioni":[
  {"id":"serve","tipo":"cards","eyebrow":"Cosa serve",
   "h2":"Gli elementi<br><span class=\"grad\">di un sito che prenota</span>",
   "corpo":[
    ("Booking engine integrato","Disponibilità e prezzi in tempo reale, prenotazione e pagamento in tre passaggi, sincronizzati con channel manager e gestionale. Integriamo il motore che usate già, o vi aiutiamo a sceglierlo."),
    ("Il miglior prezzo dichiarato","Un piccolo vantaggio per chi prenota diretto: colazione inclusa, late check-out, sconto riservato. Detto chiaramente, vicino al pulsante."),
    ("Foto e camere vere","Ogni camera con foto, metri quadri, letti, vista e servizi. È la pagina più visitata dopo la home, e quella che decide."),
    ("Multilingua vero","Inglese e tedesco per il Nord-Est, tradotti da persone, con indirizzi e titoli ottimizzati per ogni lingua. Non un traduttore automatico in un angolo."),
    ("Google Hotel e Maps","Scheda Google completa, link di prenotazione gratuiti su Google Hotel collegati al vostro booking engine, recensioni curate."),
    ("Velocità da telefono","Gran parte delle prenotazioni parte dallo smartphone. Pagine leggere, immagini ottimizzate, caricamento in meno di due secondi.")]},
  {"id":"seo","tipo":"testo","eyebrow":"Farsi trovare",
   "h2":"SEO per hotel:<br><span class=\"grad\">dove si vince davvero</span>",
   "corpo":[
    "Per hotel a Venezia o B&B a Treviso il sito di una struttura difficilmente supera i grandi portali. Si vince sulle ricerche più precise: la struttura vicino alla fiera, all'ospedale o alla cantina; quella con parcheggio, con piscina, che accetta cani; il pernottamento per l'evento di quel weekend.",
    "Per questo scriviamo pagine dedicate a eventi, fiere e motivi di viaggio della vostra zona, con informazioni utili davvero: come arrivare, dove parcheggiare, cosa vedere. Sono le pagine che portano prenotazioni dirette, e quelle che Google e gli assistenti AI citano.",
    "Usiamo anche i dati strutturati per le strutture ricettive, così Google capisce stelle, servizi, prezzi e posizione."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lavoriamo",
   "h2":"Dalle foto<br>alla <span class=\"grad\">prima prenotazione.</span>",
   "corpo":[
    ("Chiamata","Tipo di struttura, canali di vendita, booking engine e channel manager in uso, ospiti principali. Mezz'ora, gratuita."),
    ("Contenuti","Testi in italiano e lingue straniere, foto da sistemare o da rifare, pagine per eventi e motivi di viaggio."),
    ("Sviluppo e integrazione","Sito veloce, booking engine collegato, tracciamento delle prenotazioni come conversioni, scheda Google."),
    ("Dopo il lancio","Misuriamo quante prenotazioni arrivano dal sito e quanto vi fanno risparmiare in commissioni.")]}],
 "faqtitle":"Le domande <span class=\"grad\">degli albergatori.</span>",
 "faq":[
  ("Quanto costa un sito web per un hotel?","Dipende da numero di camere, lingue e integrazioni. Il nostro sito web parte dalle cifre del listino; per una struttura con booking engine e più lingue vi diamo un prezzo fisso dopo la prima chiamata. Il conto da fare è quante commissioni risparmiate con le prenotazioni dirette."),
  ("Quale booking engine usate?","Integriamo quello che avete già, collegato al vostro channel manager. Se non ne avete uno, vi aiutiamo a sceglierlo in base alla dimensione della struttura e ai canali che usate."),
  ("Il sito può sostituire Booking.com?","Di solito no, e non conviene: i portali portano clienti che non vi conoscono. Il sito serve a far prenotare direttamente chi vi ha già trovato, chi torna e chi arriva da Google, riducendo la quota di commissioni."),
  ("Fate siti anche per B&B e case vacanza?","Sì. Per le strutture piccole spesso basta un sito semplice con prenotazione o richiesta di disponibilità e la scheda Google curata. Vi proponiamo la soluzione proporzionata."),
  ("Il sito sarà in più lingue?","Sì, con traduzioni fatte da persone e pagine ottimizzate per le ricerche in ogni lingua. Per il Nord-Est consigliamo almeno inglese e tedesco."),
  ("Vi occupate anche di Google Hotel e pubblicità?","Sì: scheda Google, link di prenotazione gratuiti su Google Hotel e, se volete, campagne Google Ads e Meta Ads per le date in cui avete camere libere.")],
 "ctabox":{"h2":"Quanto pagate di commissioni all'anno?",
  "p":"Diteci quante prenotazioni arrivano dai portali: vi facciamo vedere quanto potrebbe valere spostarne una parte sul vostro sito.",
  "btn":"Prenota la chiamata gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Siti web ed e-commerce","/servizi/siti-web-ecommerce/"),
          ("Caso studio: Oasi Ponza","/lavori/oasi-ponza/"),
          ("App per prenotazioni","/app-prenotazioni/"),
          ("Web agency a Conegliano e Vittorio Veneto","/web-agency-conegliano/"),
          ("Come ottenere recensioni Google","/come-ottenere-recensioni-google/"),
          ("Quanto costa un sito web","/quanto-costa-un-sito-web/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Siti web per hotel e B&B","type":"Realizzazione siti web per strutture ricettive",
        "desc":"Realizzazione di siti web per hotel, B&B e case vacanza con booking engine integrato, multilingua, SEO locale, Google Hotel e tracciamento delle prenotazioni dirette.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Integrazione booking engine e channel manager","Sito multilingua","Pagine per eventi e motivi di viaggio","Google Hotel e scheda Google","Campagne per le date libere"]},
})

# --- siti per avvocati (sito web per avvocati 500, siti avvocati 500) -------
PAGINE.append({
 "lang":"it", "url":"/siti-web-per-avvocati/",
 "title":"Siti web per avvocati e studi legali | Danova Tech",
 "desc":"Siti web per avvocati e studi legali: chiari, sobri, nel rispetto del codice deontologico. Aree di pratica, schede dei professionisti e SEO locale.",
 "ogtitle":"Siti web per avvocati e studi legali — Danova Tech",
 "ogdesc":"Un sito che spiega cosa fate, per chi e dove, nel rispetto delle regole sull'informazione dell'avvocato.",
 "crumbs":[("Siti web","/servizi/siti-web-ecommerce/"),("Siti per avvocati",None)],
 "eyebrow":"Avvocati · studi legali · professionisti",
 "h1":"Siti web per avvocati: <span class=\"grad\">chiari, sobri, trovabili.</span>",
 "lead":"Chi cerca un avvocato su Google ha quasi sempre un problema preciso: una separazione, un licenziamento, un recupero crediti, un contratto. Vuole capire in fretta se lo studio si occupa proprio di quello, se è vicino e come contattarlo. Un sito per uno studio legale deve rispondere a queste tre domande, nel rispetto delle regole del codice deontologico.",
 "cta1":"Parliamo del vostro studio", "cta2":"Cosa serve al sito",
 "sezioni":[
  {"id":"serve","tipo":"cards","eyebrow":"Cosa serve",
   "h2":"Gli elementi<br><span class=\"grad\">di un buon sito legale</span>",
   "corpo":[
    ("Una pagina per ogni area","Diritto di famiglia, lavoro, societario, recupero crediti: una pagina ciascuna, scritta in italiano comprensibile, con le domande che i clienti fanno al primo incontro."),
    ("Schede dei professionisti","Foto, percorso, iscrizione all'albo, lingue, aree di attività. Il cliente sceglie una persona, non un logo."),
    ("Contatti protetti","Modulo con informativa privacy e consenso, che non chiede dettagli riservati prima del primo contatto. Prenotazione della consulenza, anche online."),
    ("SEO locale","Scheda Google dello studio, pagine per le sedi, presenza nelle ricerche come avvocato più materia più città. È lì che arrivano i clienti."),
    ("Articoli utili","Guide brevi su scadenze, procedure e novità normative, aggiornate. Mostrano competenza meglio di qualunque slogan, e sono le pagine che gli assistenti AI citano."),
    ("Sicurezza e privacy","Certificato, server europei, cookie in regola, aggiornamenti costanti. Per uno studio legale un sito violato è un danno di reputazione serio.")]},
  {"id":"regole","tipo":"testo","eyebrow":"Le regole",
   "h2":"Informazione<br><span class=\"grad\">e codice deontologico</span>",
   "corpo":[
    "L'avvocato può farsi conoscere, anche online, ma l'informazione deve essere veritiera, corretta, non comparativa e non equivoca, come chiede il codice deontologico forense sull'informazione professionale. Niente promesse di risultato, niente superlativi, niente nomi di clienti senza consenso.",
    "Ne teniamo conto nei testi che scriviamo con voi: descriviamo cosa fate e come, non perché siete i migliori. È anche lo stile che convince di più chi sta per affidarvi un problema importante.",
    "L'ultima parola sui contenuti spetta sempre allo studio: vi mandiamo ogni testo da approvare prima della pubblicazione."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lavoriamo",
   "h2":"Dalla prima chiamata<br>al <span class=\"grad\">sito online.</span>",
   "corpo":[
    ("Chiamata","Aree di attività, clienti tipici, sedi, cosa volete far sapere e cosa no. Mezz'ora, gratuita."),
    ("Testi","Li scriviamo noi partendo dalle ricerche reali dei clienti, e li rivedete voi riga per riga."),
    ("Sviluppo","Sito veloce e sobrio, scheda Google, modulo protetto, dati strutturati per lo studio e per i professionisti."),
    ("Dopo il lancio","Aggiornamenti di sicurezza, nuovi articoli se volete, e il numero di contatti arrivati dal sito, mese per mese.")]}],
 "faqtitle":"Le domande <span class=\"grad\">degli studi legali.</span>",
 "faq":[
  ("Un avvocato può fare pubblicità online?","Sì, l'avvocato può dare informazioni sulla propria attività anche con un sito e sui social, purché siano veritiere, corrette, non comparative e non equivoche, come previsto dal codice deontologico forense. Il sito deve informare, non promettere risultati."),
  ("Quanto costa un sito per uno studio legale?","Dipende da numero di aree, professionisti, sedi e lingue. Il punto di partenza è sul nostro listino; per uno studio con più sedi o più lingue vi diamo un prezzo fisso dopo la prima chiamata."),
  ("Scrivete voi i testi?","Sì, li scriviamo noi partendo da come i clienti cercano, e li rivedete voi: la responsabilità dei contenuti resta dello studio, e nessun testo va online senza la vostra approvazione."),
  ("Si può prenotare la consulenza dal sito?","Sì: richiesta di appuntamento, calendario con gli orari disponibili e, se lo fate, consulenza online con pagamento anticipato. Il modulo raccoglie solo i dati necessari al primo contatto."),
  ("Fate anche Google Ads per avvocati?","Sì, nel rispetto delle stesse regole sull'informazione. Sulle ricerche legali i clic costano spesso di più della media, quindi partiamo da poche parole chiave molto precise per materia e città."),
  ("Il sito è adatto anche agli assistenti AI?","Sì. Pagine chiare per materia, schede dei professionisti e dati strutturati sono le stesse informazioni che usano ChatGPT e Google quando consigliano uno studio.")],
 "ctabox":{"h2":"I clienti capiscono in un minuto cosa fa il vostro studio?",
  "p":"Mandateci l'indirizzo del sito attuale, o raccontateci lo studio: vi diciamo cosa cambieremmo per primo, gratis.",
  "btn":"Richiedi l'analisi gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Siti web ed e-commerce","/servizi/siti-web-ecommerce/"),
          ("Software gestionale studi professionali","/software-gestionale-studi-professionali/"),
          ("Consulenza SEO","/servizi/seo/"),
          ("Come ottenere recensioni Google","/come-ottenere-recensioni-google/"),
          ("Quanto costa Google Ads","/quanto-costa-google-ads/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Siti web per avvocati e studi legali","type":"Realizzazione siti web per professionisti",
        "desc":"Realizzazione di siti web per avvocati e studi legali con pagine per area di pratica, schede dei professionisti, contatti protetti, SEO locale e testi conformi alle regole sull'informazione professionale.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Pagine per area di pratica","Schede dei professionisti","Prenotazione della consulenza","SEO locale e scheda Google","Articoli e guide"]},
})
