# -*- coding: utf-8 -*-
"""Pagine nuove del 9 ottobre 2026 (sesto giro), dai volumi Keyword Planner.
   Uso:  python3 seo-tools/pagine-build-2.py pagine-dati-6.py"""
OGGI = "2026-10-09"
IT = [{"@type":"Country","name":"Italia"}]
PAGINE = []

# --- indicizzare un sito su Google (cluster ~20 varianti da 500) ---------------
PAGINE.append({
 "lang":"it", "url":"/come-indicizzare-un-sito-su-google/",
 "title":"Come indicizzare un sito su Google, passo per passo | Danova Tech",
 "desc":"Come indicizzare un sito su Google: Search Console, sitemap, controllo URL e i motivi più comuni per cui una pagina non entra nell'indice. Anche per Bing.",
 "ogtitle":"Come indicizzare un sito su Google — Danova Tech",
 "ogdesc":"Il sito è online ma su Google non c'è? Ecco i passaggi per farlo indicizzare e i controlli da fare quando una pagina non entra.",
 "crumbs":[("SEO","/servizi/seo/"),("Indicizzare un sito",None)],
 "eyebrow":"Guida pratica · Search Console",
 "h1":"Come indicizzare un sito su Google, <span class=\"grad\">passo per passo.</span>",
 "lead":"Un sito appena pubblicato non compare su Google da solo, o ci mette settimane. Indicizzare significa far sapere a Google che le pagine esistono e convincerlo a inserirle nel suo indice. Non è ancora posizionarsi, cioè comparire in alto: è il passaggio prima, e senza di questo il resto non conta.",
 "cta1":"Controlliamo il vostro sito", "cta2":"I passaggi",
 "sezioni":[
  {"id":"passi","tipo":"passi","eyebrow":"I passaggi",
   "h2":"Indicizzare un sito<br><span class=\"grad\">in cinque mosse</span>",
   "corpo":[
    ("Aggiungete il sito a Search Console","Google Search Console è gratuita. Si aggiunge la proprietà del dominio e si verifica con un record DNS o con un file sul sito. Da qui passa tutto il resto."),
    ("Inviate la sitemap","La sitemap.xml elenca le pagine del sito. Si invia nella sezione Sitemap di Search Console: Google la legge e scopre le pagine più in fretta. Molti CMS la generano da soli."),
    ("Chiedete l'indicizzazione delle pagine importanti","Con il Controllo URL si incolla l'indirizzo di una pagina e si chiede di indicizzarla. Serve per la home e le pagine principali, o dopo una modifica importante. Non serve farlo per tutte."),
    ("Collegate le pagine fra loro","Google trova le pagine seguendo i link. Una pagina che nessuna altra pagina linka è un'orfana: anche se è nella sitemap, viene considerata poco importante."),
    ("Fate lo stesso con Bing","Bing Webmaster Tools importa il sito da Search Console in un clic, e con IndexNow le pagine nuove vengono segnalate subito. Bing alimenta anche ChatGPT e Copilot, quindi conta più di quanto sembri.")]},
  {"id":"problemi","tipo":"cards","eyebrow":"Se non entra",
   "h2":"Perché una pagina<br><span class=\"grad\">non viene indicizzata</span>",
   "lead":"In Search Console, alla voce Pagine, Google dice per ogni pagina esclusa il motivo. Questi sono i più frequenti.",
   "corpo":[
    ("Tag noindex dimenticato","Molti siti in costruzione hanno l'opzione di nascondersi ai motori. Se resta attiva dopo il lancio, Google obbedisce e non indicizza niente."),
    ("Bloccata da robots.txt","Una riga sbagliata nel file robots.txt può impedire a Google di leggere intere sezioni del sito."),
    ("Canonical che punta altrove","Se la pagina dichiara che la versione principale è un'altra, Google indicizza quell'altra. Succede spesso con filtri, parametri e versioni duplicate."),
    ("Scansionata ma non indicizzata","Google l'ha letta e ha deciso che non vale la pena. Di solito il contenuto è troppo scarno o troppo simile ad altre pagine: va arricchito, non reinviato."),
    ("Rilevata ma non scansionata","Google sa che esiste ma non è ancora passato. Capita con siti nuovi o lenti: migliorano link interni, velocità e qualche link da altri siti."),
    ("Errori del server e redirect","Pagine che rispondono con errori, catene di redirect o sito lentissimo: Google rallenta la scansione per non sovraccaricare il server.")]},
  {"id":"tempi","tipo":"testo","eyebrow":"Quanto ci vuole",
   "h2":"Indicizzato<br><span class=\"grad\">non vuol dire primo</span>",
   "corpo":[
    "Per un sito nuovo, le prime pagine entrano di solito in pochi giorni o qualche settimana dall'invio della sitemap. Se dopo un mese la home non c'è, quasi sempre c'è un blocco tecnico fra quelli sopra.",
    "Una volta indicizzata, una pagina compare per le ricerche in cui Google la ritiene la risposta migliore. Arrivare in prima pagina dipende dalla qualità dei contenuti, dalla struttura del sito, dalla concorrenza e dai link: è il lavoro di <a href=\"/posizionamento-sito-google/\">posizionamento</a>.",
    "Per controllare velocemente, cercate su Google site:nomedelvostrosito.it. Il numero di risultati è indicativo, non preciso: i dati affidabili sono in Search Console."]}],
 "faqtitle":"Le domande <span class=\"grad\">sull'indicizzazione.</span>",
 "faq":[
  ("Come si indicizza un sito su Google?","Si aggiunge e verifica il sito in Google Search Console, si invia la sitemap.xml, si chiede l'indicizzazione delle pagine principali con il Controllo URL e ci si assicura che le pagine siano collegate fra loro e senza blocchi come noindex o robots.txt."),
  ("Quanto ci mette Google a indicizzare un sito?","Da qualche giorno a qualche settimana per un sito nuovo. Le pagine nuove di un sito già conosciuto entrano spesso in poche ore o giorni. Se dopo un mese non c'è niente, c'è quasi sempre un problema tecnico."),
  ("Indicizzare un sito su Google costa?","No: Google Search Console e l'invio della sitemap sono gratuiti, e nessuno può pagare Google per essere indicizzato. Si paga, eventualmente, il lavoro di chi sistema i problemi tecnici e migliora i contenuti."),
  ("Che differenza c'è fra indicizzazione e posizionamento?","Indicizzazione significa essere nell'archivio di Google. Posizionamento significa comparire in alto per le ricerche che contano. Un sito può essere tutto indicizzato e non comparire mai in prima pagina."),
  ("Perché il mio sito non compare su Google?","Le cause più comuni sono un noindex rimasto attivo, un blocco nel robots.txt, un sito troppo nuovo senza link, oppure pagine indicizzate che non si posizionano perché troppo deboli rispetto alla concorrenza. Search Console dice quale dei due casi è il vostro."),
  ("Vi occupate voi dell'indicizzazione?","Sì: è compresa nell'ottimizzazione SEO di ogni sito che realizziamo, insieme a Search Console, Bing Webmaster Tools, sitemap e dati strutturati. Possiamo controllare anche un sito fatto da altri.")],
 "ctabox":{"h2":"Il vostro sito non si trova su Google?",
  "p":"Mandateci l'indirizzo: controlliamo indicizzazione, blocchi tecnici e pagine escluse, e vi diciamo cosa sistemare. Gratis.",
  "btn":"Richiedi il controllo"},
 "altrititle":"Pagine collegate",
 "altri":[("Posizionamento sito su Google","/posizionamento-sito-google/"),
          ("Consulenza SEO","/servizi/seo/"),
          ("SEO per l&#8217;intelligenza artificiale","/seo-per-intelligenza-artificiale/"),
          ("Rifare il sito senza perdere posizioni","/guide/rifare-sito-senza-perdere-posizioni/"),
          ("Velocità del sito e Core Web Vitals","/guide/velocita-sito-web-core-web-vitals/"),
          ("Google Business Profile: la guida","/guide/google-business-profile-guida/")],
 "svc":{"name":"Indicizzazione e SEO tecnica","type":"Ottimizzazione per motori di ricerca",
        "desc":"Configurazione di Google Search Console e Bing Webmaster Tools, sitemap, IndexNow, risoluzione dei problemi di indicizzazione e SEO tecnica per siti aziendali.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Configurazione Search Console e Bing","Sitemap e IndexNow","Analisi delle pagine escluse","Correzione di noindex, canonical e robots.txt"]},
})

# --- idee stand fieristici (idee stand fiera 500 x3) -------------------------
PAGINE.append({
 "lang":"it", "url":"/idee-stand-fieristici/",
 "title":"Idee per stand fieristici che attirano visitatori | Danova Tech",
 "desc":"Idee per stand fieristici originali ed efficaci: altezza, luce, ledwall, prodotto in azione, aree per parlare, materiali sostenibili. Cosa funziona davvero in fiera.",
 "ogtitle":"Idee per stand fieristici — Danova Tech",
 "ogdesc":"Uno stand si guarda per tre secondi da lontano e poi si decide se entrare. Idee concrete per farli entrare.",
 "crumbs":[("Allestimenti fieristici","/servizi/allestimenti-fieristici/"),("Idee per stand",None)],
 "eyebrow":"Ispirazione · progettazione stand",
 "h1":"Idee per stand fieristici <span class=\"grad\">che fanno entrare la gente.</span>",
 "lead":"In un padiglione con centinaia di espositori, chi passa nel corridoio decide in pochi secondi se fermarsi. Uno stand originale non è quello più strano: è quello che si capisce da lontano, invita a entrare e, una volta dentro, rende facile parlare. Ecco le idee che usiamo più spesso, divise per obiettivo.",
 "cta1":"Progettiamo il vostro stand", "cta2":"Le idee",
 "sezioni":[
  {"id":"lontano","tipo":"cards","eyebrow":"Farsi notare",
   "h2":"Idee per farsi vedere<br><span class=\"grad\">dal fondo del corridoio</span>",
   "corpo":[
    ("Un messaggio in alto","Il marchio e una frase di cinque parole su cosa fate, sopra l'altezza delle teste. Quello che sta a un metro e mezzo da terra lo coprono i visitatori."),
    ("Luce, non solo grafica","Uno stand illuminato bene si stacca dal padiglione. Grafiche retroilluminate in tessuto, luce calda sui prodotti, nessuna zona d'ombra."),
    ("Un ledwall con un contenuto solo","Un video del prodotto in azione, senza audio e leggibile in dieci secondi. Non la presentazione aziendale di venti minuti."),
    ("Un colore che è vostro","Un colore forte e coerente, ripetuto su pareti, pavimento e divise. In fotografia e nella memoria resta più del logo.")]},
  {"id":"dentro","tipo":"cards","eyebrow":"Farli entrare e restare",
   "h2":"Idee per far entrare<br><span class=\"grad\">e far parlare</span>",
   "corpo":[
    ("Il prodotto in mano","Il macchinario che lavora, il materiale da toccare, l'assaggio, il campione da portare via. In fiera vince quello che si prova."),
    ("Stand aperto","Niente banco che fa da barriera sul fronte. Il desk sta di lato o in fondo: chi passa deve poter fare un passo dentro senza sentirsi intrappolato."),
    ("Un'area per sedersi","Un tavolo, anche piccolo, dove la conversazione diventa un preventivo. Su uno stand a isola, una saletta chiusa per i clienti importanti."),
    ("Raccogliere i contatti in digitale","Un QR code che porta a una pagina dedicata alla fiera, un tablet per i dati del visitatore, il badge letto con l'app dell'ente fiera. Il biglietto da visita nella ciotola si perde.")]},
  {"id":"budget","tipo":"testo","eyebrow":"Con budget diversi",
   "h2":"Idee anche<br><span class=\"grad\">per stand piccoli</span>",
   "corpo":[
    "Su uno stand da 9 o 12 metri quadri le idee migliori sono quelle che tolgono: una parete di fondo con una grafica forte, un solo prodotto protagonista, un desk e due sgabelli. Ogni oggetto in più rende lo spazio più piccolo.",
    "Gli stand modulari in alluminio e tessuto teso permettono un'immagine curata con un costo contenuto, e si riusano per più fiere cambiando solo la grafica. Per chi fa tre o quattro fiere l'anno sono spesso la scelta più sensata.",
    "Per un'immagine sostenibile: strutture riutilizzabili, legno certificato, grafiche in tessuto riciclabile, illuminazione LED. Funziona se è vero e se si vede, non se resta scritto su un cartello."]}],
 "faqtitle":"Le domande <span class=\"grad\">sulle idee per lo stand.</span>",
 "faq":[
  ("Come rendere originale uno stand fieristico?","Con un'idea sola, chiara da lontano: un messaggio in alto, una luce che lo stacca dal padiglione, il prodotto in azione al centro. L'originalità che funziona è quella che fa capire in tre secondi cosa fate, non quella che stupisce senza spiegare."),
  ("Come attirare visitatori allo stand?","Visibilità dall'alto, stand aperto senza barriere sul fronte, il prodotto da provare, un ledwall con un contenuto breve e un invito mandato ai clienti prima della fiera con l'appuntamento già fissato."),
  ("Cosa mettere in uno stand piccolo?","Poco: una parete di fondo con una grafica forte, un prodotto protagonista, un desk e due sgabelli. Su pochi metri quadri ogni oggetto in più toglie spazio alle persone."),
  ("Meglio uno stand su misura o modulare?","Su misura quando l'immagine è il cuore del messaggio e lo stand è grande o a isola. Modulare quando fate più fiere l'anno e volete riusare la struttura cambiando la grafica. Spesso si combinano."),
  ("Quanto prima bisogna progettare lo stand?","Per uno stand su misura almeno tre o quattro mesi prima, per avere progetto, approvazione dell'ente fiera e produzione senza fretta. Per un modulare bastano alcune settimane."),
  ("Fate voi il progetto?","Sì: partiamo dai vostri obiettivi in fiera, prepariamo il progetto con render 3D e lo realizziamo, dal materiale al montaggio.")],
 "ctabox":{"h2":"Avete una fiera in arrivo?",
  "p":"Diteci fiera, metri quadri e cosa volete ottenere: vi mandiamo un'idea di stand con render e preventivo.",
  "btn":"Richiedi il progetto"},
 "altrititle":"Pagine collegate",
 "altri":[("Allestimenti fieristici","/servizi/allestimenti-fieristici/"),
          ("Progettazione stand e render 3D","/progettazione-stand-fieristici/"),
          ("Stand fieristici piccoli","/stand-fieristici-piccoli/"),
          ("Ledwall e illuminazione","/ledwall-e-illuminazione-stand/"),
          ("Grafica per stand","/grafica-per-stand-fieristici/"),
          ("Stand ecosostenibili","/stand-fieristici-ecosostenibili/"),
          ("Come preparare una fiera","/guide/come-preparare-una-fiera/")],
 "svc":{"name":"Progettazione di stand fieristici","type":"Allestimenti fieristici",
        "desc":"Ideazione e progettazione di stand fieristici con render 3D, grafica, illuminazione, ledwall e allestimento in fiera, in Italia e all'estero.",
        "area":IT,"lingue":["Italian","English","German"],
        "catalogo":["Concept e render 3D","Grafica e illuminazione","Ledwall e contenuti video","Realizzazione e montaggio"]},
})

# --- siti per agenzie immobiliari (500) --------------------------------------
PAGINE.append({
 "lang":"it", "url":"/siti-web-per-agenzie-immobiliari/",
 "title":"Siti web per agenzie immobiliari | Danova Tech",
 "desc":"Siti web per agenzie immobiliari: annunci sincronizzati con il gestionale e i portali, ricerca per zona, valutazione online e contatti diretti, con SEO locale.",
 "ogtitle":"Siti web per agenzie immobiliari — Danova Tech",
 "ogdesc":"Gli annunci sono sui portali come quelli dei concorrenti. Il sito serve a farvi scegliere da chi vende casa.",
 "crumbs":[("Siti web","/servizi/siti-web-ecommerce/"),("Agenzie immobiliari",None)],
 "eyebrow":"Agenzie immobiliari · real estate",
 "h1":"Siti web per agenzie immobiliari: <span class=\"grad\">più incarichi, non solo annunci.</span>",
 "lead":"Chi cerca casa parte quasi sempre dai grandi portali, dove i vostri annunci stanno accanto a quelli di tutti. Chi vende casa invece sceglie l'agenzia: cerca su Google, guarda il sito, legge le recensioni. Un sito per un'agenzia immobiliare deve fare bene due lavori: mostrare gli immobili senza fatica e convincere i proprietari ad affidarvi il prossimo.",
 "cta1":"Parliamo della vostra agenzia", "cta2":"Cosa serve al sito",
 "sezioni":[
  {"id":"serve","tipo":"cards","eyebrow":"Cosa serve",
   "h2":"Gli elementi<br><span class=\"grad\">di un sito immobiliare</span>",
   "corpo":[
    ("Annunci sincronizzati","Gli immobili si caricano una volta nel gestionale immobiliare e compaiono sul sito e sui portali, aggiornati. Niente doppio lavoro, niente annunci venduti ancora online."),
    ("Ricerca semplice","Zona, prezzo, metri quadri, locali, mappa. Su telefono come su computer. Schede con foto grandi, planimetria, classe energetica e spese."),
    ("Valutazione online","Il proprietario inserisce indirizzo e caratteristiche e riceve una prima stima o una richiesta di sopralluogo. È la pagina che porta incarichi."),
    ("Pagine per zona","Quartieri e comuni che seguite, con prezzi medi, servizi e immobili disponibili. Sono le pagine che Google mostra a chi cerca agenzia immobiliare più il nome della zona."),
    ("Recensioni e risultati","Recensioni Google, immobili venduti, tempi medi di vendita. Chi affida la casa vuole prove, non slogan."),
    ("Contatti rapidi","Chiamata, WhatsApp e modulo su ogni scheda, con l'immobile già indicato nel messaggio.")]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lavoriamo",
   "h2":"Dal gestionale<br>al <span class=\"grad\">sito che porta incarichi.</span>",
   "corpo":[
    ("Chiamata","Zone, tipo di immobili, gestionale immobiliare in uso, cosa vi porta oggi gli incarichi. Mezz'ora, gratuita."),
    ("Collegamento al gestionale","Importiamo gli annunci dal gestionale che usate, con aggiornamento automatico."),
    ("Pagine e SEO locale","Pagine per zona, valutazione online, scheda Google e dati strutturati per gli immobili."),
    ("Misura","Contiamo richieste di visita e di valutazione arrivate dal sito, mese per mese.")]}],
 "faqtitle":"Le domande <span class=\"grad\">delle agenzie.</span>",
 "faq":[
  ("Il sito si collega al nostro gestionale immobiliare?","Nella maggior parte dei casi sì: i gestionali immobiliari più usati esportano gli annunci in formati standard, che il sito importa in automatico. Verifichiamo il vostro prima di iniziare."),
  ("Serve un sito se abbiamo già gli annunci sui portali?","Per chi cerca casa i portali bastano; per chi vende no. Il proprietario sceglie l'agenzia, e prima di chiamarvi guarda sito, zone che seguite e recensioni. Il sito porta incarichi, i portali portano acquirenti."),
  ("Cos'è la valutazione online?","È un modulo in cui il proprietario descrive l'immobile e riceve una prima stima o un appuntamento. Non sostituisce il sopralluogo, ma è il modo più efficace per ricevere contatti da chi vuole vendere."),
  ("Quanto costa un sito per un'agenzia immobiliare?","Dipende da collegamento al gestionale, pagine per zona e funzioni. Il punto di partenza è sul nostro listino; con integrazioni vi diamo un prezzo fisso dopo la chiamata."),
  ("Fate anche la scheda Google e le campagne?","Sì: scheda Google, recensioni e, se volete, campagne mirate ai proprietari che vogliono vendere nella vostra zona.")],
 "ctabox":{"h2":"Da dove vi arrivano gli incarichi oggi?",
  "p":"Raccontateci la vostra agenzia: vi diciamo come il sito può portare più proprietari a chiamarvi.",
  "btn":"Prenota la chiamata gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Siti web ed e-commerce","/servizi/siti-web-ecommerce/"),
          ("Siti web per hotel e B&amp;B","/siti-web-per-hotel/"),
          ("Siti web per avvocati","/siti-web-per-avvocati/"),
          ("Come ottenere recensioni Google","/come-ottenere-recensioni-google/"),
          ("CRM aziendale","/crm-aziendale/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Siti web per agenzie immobiliari","type":"Realizzazione siti web immobiliari",
        "desc":"Realizzazione di siti web per agenzie immobiliari con annunci sincronizzati dal gestionale, ricerca per zona, valutazione online, pagine per quartiere e SEO locale.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Import automatico degli annunci","Ricerca e schede immobile","Valutazione online","Pagine per zona","SEO locale e scheda Google"]},
})

# --- siti per ristoranti (siti per ristoranti 500, siti ristoranti 500) ------
PAGINE.append({
 "lang":"it", "url":"/siti-web-per-ristoranti/",
 "title":"Siti web per ristoranti: menù, prenotazioni e Google | Danova Tech",
 "desc":"Siti web per ristoranti, pizzerie e locali: menù sempre aggiornato, prenotazione del tavolo, orari, foto vere e scheda Google curata. Veloci da telefono.",
 "ogtitle":"Siti web per ristoranti — Danova Tech",
 "ogdesc":"Chi sceglie dove mangiare guarda menù, foto e orari dal telefono, in piedi, in un minuto. Il sito deve vincere quel minuto.",
 "crumbs":[("Siti web","/servizi/siti-web-ecommerce/"),("Ristoranti",None)],
 "eyebrow":"Ristoranti · pizzerie · locali",
 "h1":"Siti web per ristoranti: <span class=\"grad\">menù, tavolo, fatto.</span>",
 "lead":"Chi sceglie dove mangiare lo fa quasi sempre dal telefono, spesso a pochi minuti dalla cena. Cerca su Google Maps, apre la scheda, guarda le foto e il menù, controlla se c'è posto. Se il menù è un PDF illeggibile o il sito non si apre, sceglie il locale accanto. Un sito per un ristorante deve essere semplice, veloce e sempre aggiornato.",
 "cta1":"Parliamo del vostro locale", "cta2":"Cosa serve al sito",
 "sezioni":[
  {"id":"serve","tipo":"cards","eyebrow":"Cosa serve",
   "h2":"Le cose<br><span class=\"grad\">che contano davvero</span>",
   "corpo":[
    ("Menù in pagina, non in PDF","Piatti, prezzi e allergeni leggibili dal telefono e modificabili da voi in un minuto. Google li legge e li mostra a chi cerca un piatto preciso."),
    ("Prenotazione del tavolo","Prenotazione online collegata al sistema che usate, o una richiesta via WhatsApp con data, ora e persone già scritte. Senza passare da portali a commissione."),
    ("Orari e chiusure aggiornati","Gli stessi sul sito e sulla scheda Google, con ferie e festivi. Un orario sbagliato vale una recensione negativa."),
    ("Foto vere","Piatti, sala, dehors, persone. Poche e buone, non le foto di repertorio."),
    ("Eventi e menù speciali","Serate, menù degustazione, pranzi di lavoro, feste private: una pagina ciascuno, da condividere sui social."),
    ("Asporto e consegna","Ordine online per asporto con ritiro all'ora scelta, o il collegamento alle piattaforme di consegna che usate già.")]},
  {"id":"google","tipo":"testo","eyebrow":"Il canale principale",
   "h2":"Per un ristorante<br><span class=\"grad\">Google Maps viene prima</span>",
   "corpo":[
    "La maggior parte dei clienti nuovi arriva dalla scheda Google, non dal sito. Per questo partiamo da lì: categoria giusta, orari, foto, menù, link di prenotazione, risposte alle recensioni. Il sito sostiene la scheda e la completa.",
    "Il sito conta di più per chi organizza: cene aziendali, eventi, gruppi, turisti che pianificano. Per loro servono pagine chiare su sale, menù per gruppi e come prenotare, in italiano e in inglese se lavorate con turisti.",
    "Leggete anche come <a href=\"/come-ottenere-recensioni-google/\">ottenere più recensioni Google</a> senza scorciatoie: per un locale è la leva più forte."]}],
 "faqtitle":"Le domande <span class=\"grad\">dei ristoratori.</span>",
 "faq":[
  ("Un ristorante ha bisogno di un sito web?","Sì, anche se la scheda Google porta la maggior parte dei clienti. Il sito ospita menù aggiornato, prenotazioni dirette senza commissioni, eventi e informazioni per i gruppi, e rafforza la scheda Google stessa."),
  ("Posso aggiornare il menù da solo?","Sì: il menù si modifica da telefono o computer in pochi secondi, senza rifare un PDF. Piatti del giorno, prezzi e allergeni restano sempre allineati."),
  ("Si possono prendere prenotazioni dal sito?","Sì, con un sistema di prenotazione collegato alla vostra agenda o con richiesta via WhatsApp già compilata. Le prenotazioni dirette non pagano commissioni ai portali."),
  ("Quanto costa un sito per un ristorante?","Un sito semplice per un locale rientra nelle cifre del nostro listino, anche con la formula in abbonamento che comprende aggiornamenti e modifiche. Con ordini online o più lingue vi diamo un prezzo fisso dopo la chiamata."),
  ("Vi occupate anche della scheda Google?","Sì: sistemiamo la scheda, colleghiamo menù e prenotazioni, prepariamo il QR code per le recensioni e vi aiutiamo a rispondere.")],
 "ctabox":{"h2":"Il vostro menù si legge dal telefono?",
  "p":"Mandateci il nome del locale: guardiamo scheda Google e sito e vi diciamo cosa sistemare per primo.",
  "btn":"Richiedi l'analisi gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Siti web ed e-commerce","/servizi/siti-web-ecommerce/"),
          ("Come ottenere recensioni Google","/come-ottenere-recensioni-google/"),
          ("Siti web per hotel e B&amp;B","/siti-web-per-hotel/"),
          ("App per prenotazioni","/app-prenotazioni/"),
          ("Quanto costa un sito web","/quanto-costa-un-sito-web/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Siti web per ristoranti","type":"Realizzazione siti web per la ristorazione",
        "desc":"Realizzazione di siti web per ristoranti, pizzerie e locali con menù modificabile, prenotazione del tavolo, eventi, asporto e scheda Google curata.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Menù online modificabile","Prenotazione del tavolo","Pagine eventi e gruppi","Ordini per asporto","Scheda Google e recensioni"]},
})
