# -*- coding: utf-8 -*-
"""Pagine nuove del 24 settembre 2026 (secondo giro, dopo Search Console).
   Si modifica qui, poi:  python3 seo-tools/pagine-build-2.py
   ATTENZIONE: rigenera da zero SOLO le pagine di questo file."""
OGGI = "2026-09-24"
IT = [{"@type":"Country","name":"Italia"}]
PAGINE = []

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/software-house-veneto/",
 "title":"Software house in Veneto, a Treviso | Danova Tech",
 "desc":"Software house veneta con sede a Mansuè (TV): gestionali, app e integrazioni su misura per le aziende del Veneto. Analisi in azienda, prezzo fisso a tappe.",
 "ogtitle":"Software house in Veneto — Danova Tech",
 "ogdesc":"Dieci persone in provincia di Treviso che scrivono software per le aziende venete. Veniamo in azienda, il codice resta vostro.",
 "crumbs":[("Software house","/software-house/"),("Veneto",None)],
 "eyebrow":"Software house veneta",
 "h1":"Software house <span class=\"grad\">in Veneto.</span>",
 "lead":"Siamo a Mansuè, in provincia di Treviso, fra Oderzo e Motta di Livenza. Dieci persone che scrivono gestionali, applicazioni e collegamenti fra programmi per aziende che stanno a un'ora o due di macchina. Questa pagina non spiega cos'è una software house: spiega cosa cambia, per un'azienda veneta, averne una vicino.",
 "cta1":"Fissiamo un incontro", "cta2":"Perché vicino conta",
 "sezioni":[
  {"id":"vicino","tipo":"testo","eyebrow":"Il punto",
   "h2":"Perché la distanza<br><span class=\"grad\">conta ancora</span>",
   "corpo":[
    "Un gestionale su misura si sbaglia quasi sempre nello stesso punto: nell'analisi. Chi lo scrive non ha mai visto il magazzino, non ha parlato con chi prepara le spedizioni, non sa che il lunedì mattina l'ufficio acquisti lavora su un foglio che nessuno ha mai mostrato. Il risultato è un programma corretto sulla carta e scomodo nella realtà.",
    "Per questo la prima giornata la passiamo da voi. Non in videochiamata: in azienda, con le persone che useranno il software. È il motivo per cui lavoriamo soprattutto con aziende del Veneto e del Friuli occidentale, dove arrivare è una questione di ore e non di voli. <b>Tornare per il collaudo, per la formazione, per il primo mese di uso vero</b> costa poco a noi e cambia molto il risultato per voi.",
    "Il resto del lavoro si fa a distanza, come per tutti. Ma la differenza fra un fornitore che può venire a vedere quando qualcosa non torna e uno che può solo chiedervi uno screenshot si sente, soprattutto nei primi tre mesi."]},
  {"id":"distretti","tipo":"cards","eyebrow":"Il territorio",
   "h2":"Il Veneto non è un mercato solo:<br>è <span class=\"grad\">una somma di distretti</span>",
   "lead":"Ogni distretto ha un modo suo di lavorare, e il software deve rispettarlo. Questi sono i casi che incontriamo più spesso.",
   "corpo":[
    ("Il mobile del Livenza","Fra Motta di Livenza, Mansuè, Brugnera e Prata si lavora per commessa, con varianti di finitura infinite e contoterzisti a catena. Il gestionale deve seguire il pezzo fuori dall'azienda e riportarlo dentro, non solo contarlo in magazzino."),
    ("La meccanica vicentina e padovana","Conto lavoro, lotti, certificati di materiale, tempi ciclo. Qui il valore sta nel sapere quanto è costato davvero un ordine, e quasi sempre il dato è sparso fra tre programmi e un quaderno in officina."),
    ("L'occhialeria bellunese","Subfornitura per pochi grandi marchi, capitolati rigidi, tracciabilità del singolo componente. Serve un software che parli la lingua del committente e che esporti quello che il committente chiede, nel formato che chiede."),
    ("Lo sportsystem di Montebelluna","Taglie, colori, stagioni, campionari. Sono le varianti a far esplodere le anagrafiche, e i gestionali generici le gestiscono moltiplicando gli articoli invece di organizzarli."),
    ("Vino e agroalimentare","Dal Prosecco di Conegliano al Valpolicella, passando per il Piave: lotti, vendemmie, giacenze fiscali, schede per l'export. Tracciabilità vera, dalla vigna alla bottiglia, senza doppia registrazione."),
    ("Logistica e trasporti","Interporto di Padova, porto di Venezia, corridoio verso il Nord Europa. Le aziende di questo settore hanno quasi sempre un gestionale che funziona e dieci fogli di calcolo intorno che lo tengono in piedi.")]},
  {"id":"cosa","tipo":"testo","eyebrow":"Cosa facciamo",
   "h2":"Cosa ci chiedono <span class=\"grad\">le aziende venete</span>",
   "corpo":[
    "La richiesta più frequente non è un gestionale nuovo. È <b>far parlare fra loro programmi che già esistono</b>: il gestionale contabile che nessuno vuole cambiare, l'e-commerce, il foglio delle commesse, il sistema del corriere. Un collegamento fatto bene elimina la doppia digitazione e costa una frazione di un software nuovo.",
    "Subito dopo vengono le applicazioni per chi lavora fuori dall'ufficio: tecnici, agenti, capisquadra. Un'app che apre l'intervento, fotografa, fa firmare il cliente e manda tutto in ufficio senza che nessuno ricopi niente. Poi i gestionali veri e propri, quando l'azienda ha superato quello che un pacchetto standard riesce a fare.",
    "Quando il problema si risolve con un programma già in commercio, lo diciamo. È successo più di una volta di chiudere la prima riunione consigliando un prodotto esistente: non ci guadagniamo niente quel giorno, ma è il motivo per cui ci richiamano dopo."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lavoriamo",
   "h2":"Dal primo incontro<br>al software <span class=\"grad\">in uso.</span>",
   "corpo":[
    ("Giornata in azienda","Veniamo da voi e guardiamo il lavoro com'è fatto, non come è descritto. L'incontro è gratuito e senza impegno, anche se alla fine vi diciamo che non vi serviamo."),
    ("Proposta scritta a tappe","Ogni tappa ha un risultato che si può usare e un prezzo fisso. Potete fermarvi dopo la prima e tenere quello che è stato fatto: il codice è vostro dal primo giorno."),
    ("Sviluppo con consegne frequenti","Ogni due o tre settimane vedete qualcosa che funziona. Gli errori di analisi si scoprono lì, quando costano poco, non alla consegna finale."),
    ("Avvio affiancato","Il primo giorno di uso vero siamo in azienda. Le prime settimane sono quelle in cui un software viene adottato o abbandonato, e non le lasciamo al caso.")]}],
 "faqtitle":"Le domande che <span class=\"grad\">ci fanno al primo incontro.</span>",
 "faq":[
  ("Dove siete esattamente?","A Mansuè, in provincia di Treviso, fra Oderzo e Motta di Livenza. Da qui Treviso, Pordenone e Conegliano sono a meno di mezz'ora; Venezia, Padova e Udine intorno all'ora; Vicenza, Belluno e Verona fra un'ora e mezza e due."),
  ("Venite anche fuori dal Veneto?","Sì. Lavoriamo in tutta Italia e con clienti esteri, e buona parte del lavoro si fa a distanza. Per il Veneto e il Friuli occidentale gli incontri in azienda sono la regola; più lontano si concordano le visite nei momenti che contano, cioè analisi, collaudo e avvio."),
  ("Quanto costa un software su misura?","Un gestionale su misura parte da 1.500 euro IVA inclusa per un primo modulo, un'applicazione web pronta da personalizzare da 750 euro. Il prezzo vero dipende da quanti processi copre e da quanti programmi deve collegare: lo fissiamo dopo l'analisi, per tappe, e non cambia a lavoro in corso."),
  ("Che differenza c'è rispetto a una grande software house?","Le dimensioni. Con dieci persone parlate sempre con chi conosce il vostro progetto, e le decisioni si prendono in un giorno. Il limite è lo stesso: non siamo la scelta giusta per un ERP da duecento utenti in dieci stabilimenti, e se è il vostro caso ve lo diciamo."),
  ("Il codice sorgente resta nostro?","Sì, sempre, per contratto. Database, codice e accessi sono intestati a voi. Se un giorno volete cambiare fornitore, potete farlo senza chiederci il permesso."),
  ("Ci sono incentivi per il software nel 2026?","Alcune misure nazionali e regionali coprono l'acquisto di software e la digitalizzazione, ma cambiano spesso e hanno requisiti precisi. Prima del preventivo verifichiamo con il vostro consulente quali sono aperte e costruiamo la documentazione tecnica in modo che sia utilizzabile.")],
 "ctabox":{"h2":"Veniamo a vedere come lavorate?",
  "p":"Un incontro in azienda, gratuito, per capire dove il software vi fa perdere tempo. Se la soluzione è un programma già in commercio, ve lo diciamo lì.",
  "btn":"Fissiamo un incontro"},
 "altrititle":"Pagine collegate",
 "altri":[("Software house: cos&#8217;è e come sceglierla","/software-house/"),
          ("Software gestionale su misura in Veneto","/gestionali-su-misura-veneto/"),
          ("Sviluppo app aziendali in Veneto","/sviluppo-app-aziendali-veneto/"),
          ("Gestionale a Treviso","/gestionali-su-misura-treviso/"),
          ("Integrazione software aziendali","/integrazione-software-aziendali/"),
          ("Sviluppo software su misura","/sviluppo-software-su-misura/"),
          ("Quanto costa un gestionale","/quanto-costa-un-gestionale/"),
          ("Chi siamo","/chi-siamo/")],
 "svc":{"name":"Software house in Veneto","type":"Sviluppo software su misura",
        "desc":"Sviluppo di gestionali, applicazioni e integrazioni su misura per aziende del Veneto, con analisi in azienda, prezzo fisso per tappe e codice sorgente di proprietà del cliente.",
        "area":[{"@type":"State","name":"Veneto"},{"@type":"State","name":"Friuli-Venezia Giulia"}],"lingue":["Italian","English"],
        "catalogo":["Gestionali su misura","Applicazioni aziendali","Integrazione fra software","Automazione dei processi","Assistenza e manutenzione"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/web-agency-oderzo-motta-di-livenza/",
 "title":"Web agency a Oderzo e Motta di Livenza | Danova Tech",
 "desc":"Web agency a Mansuè, fra Oderzo e Motta di Livenza: siti web, SEO locale, e-commerce e gestionali per le aziende dell'Opitergino-Mottense. A 10 minuti.",
 "ogtitle":"Web agency Oderzo e Motta di Livenza — Danova Tech",
 "ogdesc":"Siamo a Mansuè: dieci minuti da Oderzo, dieci da Motta. Siti, SEO locale e software per le aziende della zona.",
 "crumbs":[("Siti web &amp; E-commerce","/servizi/siti-web-ecommerce/"),("Oderzo e Motta di Livenza",None)],
 "eyebrow":"Opitergino-Mottense",
 "h1":"Web agency a Oderzo<br>e <span class=\"grad\">Motta di Livenza.</span>",
 "lead":"La nostra sede è a Mansuè, a una decina di minuti da Oderzo e altrettanti da Motta di Livenza. Per le aziende della zona non siamo un'agenzia che lavora anche qui: siamo quella che sta qui. Siti web, posizionamento su Google, e-commerce e software gestionali, con un incontro di persona ogni volta che serve.",
 "cta1":"Passate da noi, o veniamo noi", "cta2":"Cosa facciamo in zona",
 "sezioni":[
  {"id":"zona","tipo":"testo","eyebrow":"La zona",
   "h2":"Un'area piccola<br>con <span class=\"grad\">aziende grandi</span>",
   "corpo":[
    "L'Opitergino-Mottense è una zona che da fuori si conosce poco e che dentro ha un tessuto produttivo fitto: il distretto del mobile che dal Livenza arriva fino a Brugnera e Prata, la meccanica di subfornitura, le cantine del Piave, il commercio di Oderzo che serve mezza provincia. Molte di queste aziende vendono in tutta Europa e hanno un sito fermo a dieci anni fa.",
    "Il motivo è quasi sempre lo stesso: il sito non è mai stato una priorità, perché i clienti arrivavano per conoscenza. Funziona finché funziona. Poi cambia una generazione negli uffici acquisti, i nuovi buyer cercano su Google, e l'azienda che produce meglio non compare.",
    "Qui il lavoro è concreto: <b>un sito che dica chiaramente cosa fate, per chi e con quali certificazioni</b>, in italiano e nelle lingue dei vostri clienti, e che venga trovato da chi cerca un fornitore come voi."]},
  {"id":"servizi","tipo":"cards","eyebrow":"Cosa facciamo",
   "h2":"Quello che ci chiedono<br><span class=\"grad\">più spesso in zona</span>",
   "corpo":[
    ("Sito aziendale multilingua","Per chi esporta, il sito in inglese e tedesco non è un'aggiunta: è il catalogo che il buyer estero guarda prima di chiedere un'offerta. Traduzioni curate, non automatiche, e pagine pensate per chi cerca un fornitore."),
    ("Scheda Google e SEO locale","Per chi lavora sul territorio, dal negozio di Oderzo all'impresa edile di Motta, la scheda Google Business Profile porta più contatti del sito. La impostiamo, la curiamo e la colleghiamo a pagine che rispondono alle ricerche di zona."),
    ("E-commerce e cataloghi B2B","Rivenditori che ordinano da un'area riservata con i loro listini, invece di mandare un'email che qualcuno ricopia. Collegato al gestionale che già usate, senza doppia digitazione."),
    ("Gestionali per il mobile","Distinte, varianti di finitura, conto lavoro verso i terzisti del distretto. Sono le cose che i gestionali generici gestiscono male, e che conosciamo perché le vediamo tutti i giorni a pochi chilometri."),
    ("App per chi lavora fuori","Rapportini, montaggi, consegne e assistenze registrate dal telefono, con foto e firma del cliente. Il capo non deve più aspettare il venerdì per sapere com'è andata la settimana."),
    ("Campagne Google e Meta","Per chi ha bisogno di contatti subito, mentre il posizionamento organico cresce. Budget sotto controllo e numeri mostrati ogni mese, compresi quelli che non vanno.")]},
  {"id":"prezzi","tipo":"testo","eyebrow":"Prezzi",
   "h2":"Prezzi scritti,<br>come <span class=\"grad\">per tutti gli altri</span>",
   "corpo":[
    "Non abbiamo un listino per chi è vicino e uno per chi è lontano. Un sito aziendale costa <b>350 euro una tantum, oppure 24,80 euro al mese</b> con dominio, hosting e modifiche compresi; l'ottimizzazione iniziale per Google e Bing costa 150 euro. Un gestionale su misura parte da 1.500 euro. Tutti i prezzi sono IVA inclusa e li trovate nella pagina dei prezzi.",
    "L'unica cosa che la vicinanza cambia è il tempo: un incontro in più non costa niente a nessuno dei due, e di solito fa risparmiare una settimana di email."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Un caffè,<br>poi <span class=\"grad\">un piano scritto.</span>",
   "corpo":[
    ("Incontro","Da noi a Mansuè o da voi in azienda. Guardiamo il sito attuale, la scheda Google e cosa cercano i vostri clienti. Mezz'ora, gratuita."),
    ("Proposta","Cosa serve, in che ordine, quanto costa e in quanto tempo. Per iscritto, con il prezzo fisso."),
    ("Lavoro","Vedete le pagine mentre le costruiamo, non solo alla fine. Testi scritti con voi, foto vere quando possibile."),
    ("Dopo la consegna","Search Console, scheda Google e statistiche restano intestati a voi. Vi facciamo vedere cosa succede nei primi mesi, anche quando i numeri sono piccoli.")]}],
 "faqtitle":"Le domande <span class=\"grad\">di chi è in zona.</span>",
 "faq":[
  ("Posso venire di persona in sede?","Sì, su appuntamento. Siamo a Mansuè: da Oderzo e da Motta di Livenza sono una decina di minuti, da Gorgo al Monticano, Meduna di Livenza, Portobuffolè e Cessalto anche meno. Se preferite veniamo noi in azienda, senza costi aggiuntivi."),
  ("Lavorate anche per negozi e piccole attività?","Sì. Per un'attività locale spesso basta un sito semplice e una scheda Google curata bene: con il sito in abbonamento a 24,80 euro al mese si parte senza anticipo. Non proponiamo progetti più grandi del necessario."),
  ("In quanto tempo si compare su Google per le ricerche di zona?","Sulle ricerche con il nome del comune, come quelle su Oderzo o Motta di Livenza, la concorrenza è bassa e i primi movimenti si vedono in qualche settimana. La scheda Google Business Profile, se è curata, porta contatti anche prima del sito."),
  ("Seguite anche aziende di Pordenone e del Portogruarese?","Sì, siamo sul confine. Brugnera, Prata, Pasiano, Sacile, Portogruaro e Annone Veneto sono a un quarto d'ora o poco più, e il distretto del mobile non si ferma al fiume."),
  ("Fate anche il gestionale, oltre al sito?","Sì, ed è spesso lì che il sito diventa utile davvero: un catalogo che prende prezzi e disponibilità dal gestionale non va aggiornato a mano. Se il gestionale che avete funziona lo colleghiamo, se non basta più lo costruiamo su misura.")],
 "ctabox":{"h2":"Siamo qui dietro l'angolo.",
  "p":"Scriveteci o chiamateci: fissiamo mezz'ora, da noi o da voi, e guardiamo insieme sito e scheda Google. Vi diciamo cosa sistemare, anche se poi decidete di farlo da soli.",
  "btn":"Fissiamo un incontro"},
 "altrititle":"Pagine collegate",
 "altri":[("Realizzazione siti web a Treviso","/realizzazione-siti-web-treviso/"),
          ("Web agency a Conegliano","/web-agency-conegliano/"),
          ("Realizzazione siti web a Pordenone","/realizzazione-siti-web-pordenone/"),
          ("Consulente SEO a Treviso","/consulente-seo-treviso/"),
          ("Gestionale a Treviso","/gestionali-su-misura-treviso/"),
          ("Guida a Google Business Profile","/guide/google-business-profile-guida/"),
          ("E-commerce B2B","/ecommerce-b2b/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Web agency a Oderzo e Motta di Livenza","type":"Realizzazione siti web e SEO locale",
        "desc":"Siti web, SEO locale, e-commerce e software gestionali per aziende di Oderzo, Motta di Livenza e dell'Opitergino-Mottense, con sede a Mansuè (TV).",
        "area":[{"@type":"City","name":"Oderzo"},{"@type":"City","name":"Motta di Livenza"},{"@type":"City","name":"Mansuè"},{"@type":"City","name":"Gorgo al Monticano"},{"@type":"City","name":"Meduna di Livenza"},{"@type":"City","name":"Portobuffolè"}],"lingue":["Italian"],
        "catalogo":["Sito web aziendale","SEO locale e Google Business Profile","E-commerce B2B","Gestionali su misura","Campagne Google e Meta"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/web-agency-conegliano/",
 "title":"Web agency a Conegliano e Vittorio Veneto | Danova Tech",
 "desc":"Siti web, SEO e software per le aziende di Conegliano, Vittorio Veneto e delle colline del Prosecco: cantine, enoturismo, meccanica. A mezz'ora da voi.",
 "ogtitle":"Web agency Conegliano — Danova Tech",
 "ogdesc":"Cantine, strutture ricettive e aziende manifatturiere della Sinistra Piave: siti multilingua, SEO e gestionali, a mezz'ora di strada.",
 "crumbs":[("Siti web &amp; E-commerce","/servizi/siti-web-ecommerce/"),("Conegliano",None)],
 "eyebrow":"Sinistra Piave",
 "h1":"Web agency a Conegliano<br>e <span class=\"grad\">Vittorio Veneto.</span>",
 "lead":"Conegliano ha due economie che vivono accanto: quella delle colline, fatta di cantine e ospitalità, e quella della pianura, fatta di meccanica, elettrodomestici e subfornitura. Hanno bisogni diversi dal web e dal software, e questa pagina li tiene separati. Siamo a mezz'ora, a Mansuè.",
 "cta1":"Parliamone", "cta2":"Cantine e ospitalità",
 "sezioni":[
  {"id":"colline","tipo":"testo","eyebrow":"Le colline",
   "h2":"Cantine e ospitalità:<br>il sito <span class=\"grad\">è la prima degustazione</span>",
   "corpo":[
    "Da quando le colline del Conegliano Valdobbiadene sono patrimonio UNESCO, chi arriva cerca online prima di partire: una cantina da visitare, un agriturismo, una degustazione il sabato mattina. La ricerca si fa in inglese e in tedesco almeno quanto in italiano, e quasi sempre dal telefono.",
    "Il sito di una cantina ha tre lavori da fare: raccontare vino e territorio senza la retorica di tutti, <b>far prenotare una visita in due tocchi</b> e vendere le bottiglie a chi è già tornato a casa. Il terzo è quello che si dimentica, ed è quello che fa fatturato a novembre, quando le visite sono finite.",
    "Per le strutture ricettive vale una regola semplice: ogni prenotazione diretta dal sito è una commissione che non si paga al portale. Un sito veloce, con disponibilità e prezzi chiari, non sostituisce i portali, ma sposta una quota di clienti sul canale che vi fa guadagnare di più."]},
  {"id":"pianura","tipo":"testo","eyebrow":"La pianura",
   "h2":"Meccanica e subfornitura:<br>meno vetrina, <span class=\"grad\">più strumenti</span>",
   "corpo":[
    "Fra Conegliano, Susegana, San Vendemiano e Vittorio Veneto lavorano molte aziende di subfornitura per grandi gruppi. Per loro il sito conta meno della capacità di rispondere in fretta a una richiesta d'offerta con i documenti giusti, e di sapere a che punto è ogni commessa.",
    "Qui il lavoro che facciamo più spesso non è il sito, ma il software: un gestionale delle commesse che dice il costo vero di un lotto, un'app per registrare le ore in reparto senza fogli, un collegamento fra il gestionale e il portale del committente che oggi qualcuno alimenta a mano ogni mattina.",
    "Il sito, per queste aziende, deve fare una cosa sola e farla bene: dire a un buyer che non vi conosce cosa sapete fare, su quali materiali, con quali macchine e con quali certificazioni. Una pagina chiara vale più di dieci pagine di presentazione."]},
  {"id":"servizi","tipo":"cards","eyebrow":"Cosa facciamo",
   "h2":"I servizi,<br><span class=\"grad\">divisi per chi li usa</span>",
   "corpo":[
    ("Sito per cantine","Multilingua, con prenotazione delle visite e negozio online collegato al magazzino. Schede dei vini leggibili da telefono, non PDF da scaricare."),
    ("Sito per strutture ricettive","Veloce, con disponibilità e richiesta di prenotazione diretta. Dati strutturati per comparire bene su Google e Maps."),
    ("Sito per aziende manifatturiere","Capacità produttive, materiali, certificazioni e un modulo di richiesta d'offerta che arriva già completo."),
    ("Gestionali e commesse","Costi reali per commessa, conto lavoro, avanzamento in reparto. Su misura, a tappe con prezzo fisso."),
    ("SEO in italiano e in inglese","Per le cantine la ricerca turistica straniera; per le aziende quella dei buyer. Due strategie diverse, non una tradotta."),
    ("Scheda Google e recensioni","Per chi riceve visitatori è il primo contatto. La impostiamo e vi spieghiamo come raccogliere recensioni vere.")]}],
 "faqtitle":"Le domande <span class=\"grad\">più frequenti.</span>",
 "faq":[
  ("Venite in sede a Conegliano?","Sì. Da Mansuè sono circa trenta-quaranta minuti, e il primo incontro lo facciamo in azienda o in cantina, gratuitamente. Vediamo come lavorate prima di proporre qualcosa."),
  ("Quanto costa il sito di una cantina?","Un sito aziendale parte da 350 euro una tantum o 24,80 euro al mese, IVA inclusa. Il negozio online e la prenotazione delle visite si aggiungono in base a quanti prodotti e lingue servono: preventivo scritto e fisso dopo il primo incontro."),
  ("Potete vendere vino online anche all'estero?","Tecnicamente sì, ma la vendita di alcolici fuori dall'Italia ha regole fiscali e di spedizione diverse per ogni Paese. Di solito si parte dall'Italia e si aggiungono i Paesi uno alla volta, con il vostro consulente per le accise."),
  ("Lavorate anche a Vittorio Veneto, Pieve di Soligo e Valdobbiadene?","Sì, tutta la Sinistra Piave e la zona collinare fino a Valdobbiadene. Per la parte di software lavoriamo anche con aziende del Bellunese."),
  ("Il sito deve essere in più lingue?","Per una cantina o una struttura sulle colline quasi sempre sì: almeno inglese e tedesco, perché una parte grande dei visitatori arriva da lì e cerca nella propria lingua. Traduciamo con persone, non con un traduttore automatico, e ogni lingua ha titoli e descrizioni pensati per le ricerche di quel Paese. Per un'azienda manifatturiera la lingua dipende dai clienti: l'inglese basta quasi sempre, il tedesco se vendete in Germania e Austria."),
  ("Serve un gestionale per una cantina?","Dipende dalle dimensioni. Sotto una certa soglia bastano il programma della contabilità e un buon foglio di cantina; oltre, con registri telematici, lotti e più canali di vendita, un collegamento fra i sistemi fa risparmiare molte ore. Ve lo diciamo francamente dopo aver visto come lavorate.")],
 "ctabox":{"h2":"Un'ora a Conegliano, senza impegno.",
  "p":"Veniamo noi: guardiamo sito, scheda Google e come arrivano oggi i vostri clienti. Vi lasciamo una lista scritta di cosa sistemare, anche se poi non lavoriamo insieme.",
  "btn":"Fissiamo l'incontro"},
 "altrititle":"Pagine collegate",
 "altri":[("Realizzazione siti web a Treviso","/realizzazione-siti-web-treviso/"),
          ("Web agency a Oderzo e Motta di Livenza","/web-agency-oderzo-motta-di-livenza/"),
          ("Gestionale agroalimentare e tracciabilità","/software-gestionale-agroalimentare/"),
          ("Gestionale per commesse","/software-gestionale-commesse/"),
          ("Realizzazione e-commerce","/realizzazione-ecommerce/"),
          ("Consulente SEO a Treviso","/consulente-seo-treviso/"),
          ("Guida a Google Business Profile","/guide/google-business-profile-guida/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Web agency a Conegliano e Vittorio Veneto","type":"Realizzazione siti web, SEO e software",
        "desc":"Siti web multilingua, SEO, e-commerce e software gestionali per cantine, strutture ricettive e aziende manifatturiere di Conegliano, Vittorio Veneto e della Sinistra Piave.",
        "area":[{"@type":"City","name":"Conegliano"},{"@type":"City","name":"Vittorio Veneto"},{"@type":"City","name":"Susegana"},{"@type":"City","name":"San Vendemiano"},{"@type":"City","name":"Pieve di Soligo"},{"@type":"City","name":"Valdobbiadene"}],"lingue":["Italian","English"],
        "catalogo":["Siti web per cantine","Siti per strutture ricettive","Siti per aziende manifatturiere","E-commerce","Gestionali per commesse","SEO in italiano e in inglese"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/software-contabilita-cantiere/",
 "title":"Software per la contabilità di cantiere | Danova Tech",
 "desc":"Contabilità di cantiere per imprese edili: SAL attivi e passivi, misure, varianti, subappalti e costi reali per cantiere. Su misura, collegata al gestionale.",
 "ogtitle":"Software contabilità di cantiere — Danova Tech",
 "ogdesc":"Quanto state guadagnando su quel cantiere, oggi, e non a fine lavori. SAL, misure, subappalti e costi in un posto solo.",
 "crumbs":[("Gestionale edilizia","/software-gestionale-edilizia/"),("Contabilità di cantiere",None)],
 "eyebrow":"Edilizia",
 "h1":"Software per la <span class=\"grad\">contabilità di cantiere.</span>",
 "lead":"In quasi tutte le imprese edili il margine di un cantiere si scopre alla fine, quando non si può più correggere niente. La contabilità di cantiere serve a saperlo mentre il cantiere è aperto: quanto è stato prodotto, quanto è stato fatturato, quanto è stato speso e quanto manca. Questa pagina spiega cosa deve fare il software, e dove un prodotto standard non basta.",
 "cta1":"Parliamo dei vostri cantieri", "cta2":"Le due contabilità",
 "sezioni":[
  {"id":"due","tipo":"testo","eyebrow":"Il punto di partenza",
   "h2":"Due contabilità<br>che <span class=\"grad\">vanno tenute insieme</span>",
   "corpo":[
    "Quando si dice contabilità di cantiere si intendono due cose diverse, ed è la prima fonte di confusione. C'è la <b>contabilità dei lavori</b>, quella del rapporto con il committente: misure, libretto, stati di avanzamento, certificati di pagamento, varianti. Negli appalti pubblici i suoi documenti sono definiti dal codice dei contratti e la tiene la direzione lavori; nei lavori privati è più libera, ma la logica è la stessa.",
    "E c'è la <b>contabilità industriale del cantiere</b>, quella interna all'impresa: ore della squadra, materiali, noli, subappalti, spese generali attribuite. Risponde a una domanda sola: su questo cantiere stiamo guadagnando o perdendo?",
    "I programmi per la direzione lavori fanno bene la prima. I gestionali contabili fanno, a fatica, la seconda. Quasi nessuno le mette una accanto all'altra, ed è proprio lì che si vede il margine: <b>SAL attivo emesso contro costi sostenuti alla stessa data</b>, cantiere per cantiere."]},
  {"id":"cosa","tipo":"cards","eyebrow":"Cosa gestisce",
   "h2":"Le funzioni <span class=\"grad\">che servono</span>",
   "corpo":[
    ("Budget dal computo","Il computo metrico estimativo diventa il budget del cantiere, voce per voce. Ogni costo che arriva dopo viene confrontato con quella voce, non con un totale generico."),
    ("SAL attivi","Stati di avanzamento verso il committente con quantità, prezzi, ritenute e anticipazioni, e la proposta di fattura pronta per il gestionale che usate già."),
    ("SAL passivi e subappalti","Lo specchio del precedente: quanto hanno prodotto i subappaltatori, quanto va pagato, cosa è trattenuto a garanzia. Con i documenti di regolarità collegati al fornitore."),
    ("Varianti e lavori extra","Ogni variante con il suo stato: richiesta, approvata, eseguita, contabilizzata. I lavori fatti e mai contabilizzati sono il margine che sparisce più spesso."),
    ("Costi dal campo","Ore squadra, materiali e noli registrati dal cantiere con l'app, attribuiti alla voce giusta senza ricopiare i rapportini in ufficio."),
    ("Margine a data","Per ogni cantiere: prodotto, fatturato, incassato, speso, previsto a finire. Un numero per riga, aggiornato ogni settimana, non a fine lavori.")]},
  {"id":"standard","tipo":"testo","eyebrow":"Onestamente",
   "h2":"Quando basta un programma<br><span class=\"grad\">e quando no</span>",
   "corpo":[
    "Se fate soprattutto lavori pubblici e il vostro problema è produrre i documenti contabili nel formato richiesto, esistono programmi specifici per la contabilità dei lavori, usati da anni da direttori lavori e imprese. Vanno bene, e non ha senso rifarli.",
    "Il su misura conviene quando il problema è l'altra metà: sapere il margine per cantiere mentre il cantiere è aperto, collegare i rapportini di campo ai costi, far parlare il programma dei SAL con il gestionale della contabilità e con il magazzino. Lì i prodotti standard si fermano, e il lavoro di collegamento lo fa ancora qualcuno in ufficio con un foglio di calcolo.",
    "Spesso la soluzione giusta è una via di mezzo: tenete il programma che avete per i documenti ufficiali, e noi costruiamo intorno il pezzo che manca, leggendo i dati da lì invece di chiedere di reinserirli."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come lo costruiamo",
   "h2":"Si parte da un cantiere,<br><span class=\"grad\">non da tutti.</span>",
   "corpo":[
    ("Analisi su un cantiere vero","Prendiamo un cantiere chiuso di recente e ricostruiamo con voi da dove arrivano i numeri. È il modo più rapido per capire dove si perdono informazioni."),
    ("Prima tappa: costi e margine","Budget dal computo, costi dal campo, margine a data. È la parte che si usa da subito e che cambia le riunioni del lunedì."),
    ("Seconda tappa: SAL e subappalti","Stati di avanzamento attivi e passivi, varianti, ritenute, collegamento alla fatturazione."),
    ("Terza tappa: collegamenti","Gestionale contabile, magazzino, programma dei documenti ufficiali. Ogni dato si inserisce una volta sola.")]}],
 "faqtitle":"Le domande <span class=\"grad\">delle imprese edili.</span>",
 "faq":[
  ("Che differenza c'è con la vostra pagina sul gestionale per l'edilizia?","Il gestionale per l'edilizia copre tutta l'impresa: preventivi, cantieri, squadre, mezzi, sicurezza. Questa pagina riguarda un pezzo solo, la contabilità e il margine del singolo cantiere, che per molte imprese è il punto da cui partire."),
  ("Sostituisce il programma della direzione lavori?","No, e di solito non conviene. Se il programma che usate produce correttamente i documenti ufficiali, lo teniamo e ne leggiamo i dati. Costruiamo la parte che manca, cioè il confronto con i costi e il margine."),
  ("Quanto costa?","Un gestionale su misura parte da 1.500 euro IVA inclusa. Una prima tappa con budget, costi dal campo e margine per cantiere sta di norma nella fascia medio-bassa delle quattro cifre; il prezzo esatto si fissa dopo l'analisi e non cambia a lavoro in corso."),
  ("Funziona anche per impiantisti e serramentisti?","Sì. Cambiano le voci del budget e le unità di misura, ma la logica di commessa, avanzamento e costi è la stessa. Per chi lavora su molti interventi piccoli invece che su pochi cantieri grandi è più adatto il gestionale delle commesse."),
  ("I capisquadra devono usare un'app?","Per avere i costi dal campo sì, ma un'app che chiede tre cose: ore, materiali, foto. Se oggi compilano un rapportino di carta, l'app richiede meno tempo, non di più. Funziona anche senza connessione.")],
 "ctabox":{"h2":"Quanto rende davvero quel cantiere?",
  "p":"Portateci i numeri di un cantiere chiuso: in un'ora vi mostriamo dove si perdono le informazioni e cosa servirebbe per saperlo prima. Gratuito.",
  "btn":"Prenota l'analisi"},
 "altrititle":"Pagine collegate",
 "altri":[("Software gestionale per edilizia","/software-gestionale-edilizia/"),
          ("Software e app gestione cantieri","/app-gestione-cantieri/"),
          ("Gestionale per commesse","/software-gestionale-commesse/"),
          ("Software controllo di gestione","/software-controllo-di-gestione/"),
          ("Software di contabilità aziendale","/software-contabilita-aziendale/"),
          ("App rapportini di lavoro","/app-rapportini-di-lavoro/"),
          ("Gestionale per impiantisti","/software-gestionale-impiantisti/"),
          ("Quanto costa un gestionale","/quanto-costa-un-gestionale/")],
 "svc":{"name":"Software per la contabilità di cantiere","type":"Sviluppo software gestionale per l'edilizia",
        "desc":"Software su misura per la contabilità di cantiere: budget dal computo metrico, SAL attivi e passivi, subappalti, varianti, costi dal campo e margine per cantiere, collegato ai gestionali esistenti.",
        "area":IT,"lingue":["Italian"],
        "catalogo":["Budget di cantiere dal computo metrico","SAL attivi e passivi","Gestione subappalti","Varianti e lavori extra","Margine per cantiere"]},
})

# ---------------------------------------------------------------------------
PAGINE.append({
 "lang":"it", "url":"/lead-generation-b2b/",
 "title":"Lead generation B2B per PMI | Danova Tech",
 "desc":"Lead generation B2B per PMI: pagine che rispondono a ricerche vere, campagne Google e Meta, moduli qualificanti e CRM collegato. Contatti misurati.",
 "ogtitle":"Lead generation B2B — Danova Tech",
 "ogdesc":"Contatti commerciali da clienti aziendali: dalla ricerca su Google alla chiamata del commerciale, misurati passo per passo.",
 "crumbs":[("Google Ads","/servizi/google-ads/"),("Lead generation B2B",None)],
 "eyebrow":"Contatti commerciali",
 "h1":"Lead generation B2B<br><span class=\"grad\">per PMI.</span>",
 "lead":"Per un'azienda che vende ad altre aziende, un contatto non vale quanto un altro: dieci richieste qualificate valgono più di cento indirizzi email. La lead generation B2B che facciamo non è una campagna, è una catena di quattro anelli, e si rompe sempre in quello che nessuno guarda.",
 "cta1":"Analizziamo la vostra catena", "cta2":"I quattro anelli",
 "sezioni":[
  {"id":"catena","tipo":"cards","eyebrow":"Come funziona",
   "h2":"Quattro anelli,<br><span class=\"grad\">uno per volta</span>",
   "corpo":[
    ("Farsi trovare","Pagine che rispondono a ricerche precise, del tipo che fa un buyer quando ha già il problema: un servizio, un materiale, una lavorazione, una zona. Posizionamento su Google per il lungo periodo, Google Ads per le ricerche che servono subito."),
    ("Convincere","Una pagina di destinazione per ogni offerta, con prezzi o fasce quando è possibile, casi reali e certificazioni. Un buyer B2B confronta tre fornitori: chi gli fa perdere meno tempo parte avanti."),
    ("Raccogliere bene","Un modulo che chiede le due o tre informazioni che servono al commerciale per capire se il contatto è buono. Non dieci campi, non un solo campo email."),
    ("Non perdere il contatto","Il modulo arriva nel CRM, non in una casella di posta condivisa. Il commerciale ha un promemoria, il responsabile vede quanti contatti sono stati richiamati e quando.")]},
  {"id":"rottura","tipo":"testo","eyebrow":"Dove si rompe",
   "h2":"Il problema, quasi sempre,<br><span class=\"grad\">è dopo il modulo</span>",
   "corpo":[
    "Quando un'azienda ci dice che le campagne non portano contatti, la prima cosa che guardiamo non sono le campagne. Guardiamo cosa succede a una richiesta arrivata dal sito: chi la riceve, dopo quanto risponde, cosa ne resta dopo un mese.",
    "Più volte abbiamo trovato richieste arrivate in una casella che nessuno controllava, o richiamate dopo una settimana, quando il buyer aveva già scelto. <b>Un contatto B2B si raffredda in fretta</b>: chi ha chiesto tre preventivi di solito lavora con chi ha risposto per primo in modo serio.",
    "Per questo il nostro lavoro comprende sempre l'ultimo anello: il collegamento del sito al CRM, o un CRM semplice se non c'è, con avvisi al commerciale e un cruscotto che mostra quanti contatti sono arrivati, quanti sono stati richiamati e quanti sono diventati offerte."]},
  {"id":"canali","tipo":"testo","eyebrow":"I canali",
   "h2":"Quali canali,<br><span class=\"grad\">e in che ordine</span>",
   "corpo":[
    "<b>Google, prima di tutto.</b> Nel B2B la maggior parte della domanda nasce da una ricerca: qualcuno ha un problema e cerca chi lo risolve. Le campagne Google Ads sulle ricerche più specifiche portano contatti in settimane; il posizionamento organico costa meno nel tempo e arriva in mesi. Di solito si usano entrambi, spostando il budget man mano che l'organico cresce.",
    "<b>Meta per ricordare, non per trovare.</b> Facebook e Instagram funzionano poco per cercare un buyer industriale da zero, ma bene per farsi rivedere da chi è già passato dal sito e non ha scritto. Budget piccolo, pubblico ristretto, messaggio diverso da quello della prima visita.",
    "<b>I contenuti che fanno lavorare il commerciale.</b> Una scheda tecnica scaricabile, un confronto fra soluzioni, un calcolatore del costo: sono le cose che un buyer gira al collega, e che fanno arrivare il vostro nome in una riunione a cui non siete invitati."]},
  {"id":"metodo","tipo":"passi","eyebrow":"Come si parte",
   "h2":"Prima si misura,<br>poi <span class=\"grad\">si spende.</span>",
   "corpo":[
    ("Analisi della catena","Da dove arrivano oggi i contatti, quanti diventano offerte, dove si perdono. Spesso il primo intervento non costa niente in pubblicità."),
    ("Tracciamento","Ogni modulo, chiamata e email dal sito misurata e attribuita al canale che l'ha portata, nel rispetto del consenso ai cookie."),
    ("Primo canale","Si parte da uno, di solito Google Ads sulle ricerche più vicine all'acquisto, con un budget definito e un obiettivo di costo per contatto."),
    ("Report mensile","Contatti, costo per contatto, contatti diventati offerte. Se un canale non funziona dopo il periodo di prova, si chiude.")]}],
 "faqtitle":"Le domande <span class=\"grad\">sulla lead generation.</span>",
 "faq":[
  ("Quanto costa la lead generation B2B?","Si divide in due voci: il nostro lavoro, cioè pagine, tracciamento, collegamento al CRM e gestione delle campagne, a prezzo fisso o mensile; e il budget pubblicitario, che pagate direttamente a Google o Meta. Vi diamo un preventivo scritto dopo l'analisi, con una stima del costo per contatto basata sui prezzi reali delle vostre parole chiave."),
  ("Comprate liste di contatti?","No. Le liste comprate nel B2B rendono poco, e l'invio di comunicazioni commerciali a chi non ha dato il consenso espone l'azienda a problemi con il GDPR. Lavoriamo solo con persone che vi hanno cercato o che hanno scelto di lasciare i propri dati."),
  ("In quanto tempo arrivano i primi contatti?","Con Google Ads sulle ricerche giuste, in genere entro le prime settimane. Con il posizionamento organico servono alcuni mesi. Un buon piano usa i due canali insieme e riduce la pubblicità quando l'organico comincia a rendere."),
  ("Serve un CRM?","Serve un posto dove i contatti non si perdono. Se avete già un CRM lo colleghiamo; se non l'avete, a volte basta uno strumento semplice, altre volte conviene costruirlo intorno al vostro modo di vendere. Ve lo diciamo dopo aver visto quanti contatti gestite."),
  ("Funziona per aziende molto di nicchia?","Spesso funziona meglio. Nelle nicchie le ricerche sono poche ma molto precise, i concorrenti sono pochi e il costo per clic è basso. Il limite è il volume: se in Italia cercano la vostra lavorazione venti persone al mese, il piano deve tenerne conto.")],
 "ctabox":{"h2":"Dove si perdono i vostri contatti?",
  "p":"In una call di mezz'ora guardiamo insieme da dove arrivano oggi le richieste e cosa ne succede dopo. Vi diciamo qual è l'anello più debole, anche se si sistema senza di noi.",
  "btn":"Prenota la call gratuita"},
 "altrititle":"Pagine collegate",
 "altri":[("Consulente Google Ads","/servizi/google-ads/"),
          ("Meta Ads: Facebook e Instagram","/servizi/meta-ads/"),
          ("CRM aziendale su misura","/crm-aziendale/"),
          ("Posizionamento su Google","/posizionamento-sito-google/"),
          ("E-commerce B2B","/ecommerce-b2b/"),
          ("Sito web aziendale","/sito-web-aziendale/"),
          ("Software preventivi e configuratore","/software-preventivi-configuratore/"),
          ("Prezzi","/prezzi/")],
 "svc":{"name":"Lead generation B2B","type":"Servizio di lead generation e marketing digitale B2B",
        "desc":"Generazione di contatti commerciali qualificati per aziende B2B: pagine di destinazione, SEO, campagne Google Ads e Meta, tracciamento delle conversioni e collegamento al CRM.",
        "area":IT,"lingue":["Italian","English"],
        "catalogo":["Analisi della catena dei contatti","Pagine di destinazione","Campagne Google Ads","Campagne Meta di remarketing","Tracciamento delle conversioni","Collegamento al CRM"]},
})
