# -*- coding: utf-8 -*-
"""Contenuti della pagina Prezzi nelle cinque lingue.
   Si modificano qui: il generatore prezzi-build.py ricostruisce le pagine."""

SITE = "https://danova-tech.com"

URLP = {'it':'/prezzi/','en':'/en/pricing/','de':'/de/preise/','fr':'/fr/tarifs/','es':'/es/precios/'}
OUT  = {'it':'prezzi','en':'en/pricing','de':'de/preise','fr':'fr/tarifs','es':'es/precios'}
DONOR= {'it':'quanto-costa-un-sito-web/index.html',
        'en':'en/how-much-does-a-website-cost/index.html',
        'de':'de/was-kostet-eine-website/index.html',
        'fr':'fr/prix-creation-site-internet/index.html',
        'es':'es/cuanto-cuesta-una-pagina-web/index.html'}
LOC   = {'it':'it-IT','en':'en-GB','de':'de-DE','fr':'fr-FR','es':'es-ES'}
OGLOC = {'it':'it_IT','en':'en_GB','de':'de_DE','fr':'fr_FR','es':'es_ES'}
LBL   = {'it':'Prezzi','en':'Pricing','de':'Preise','fr':'Tarifs','es':'Precios'}

# cifre, uguali in tutte le lingue
P = {
  'sito_mese':'24,80 €', 'sito_una':'350 €', 'seo_una':'150 €', 'sito_tot':'500 €',
  'app_mese':'50 €', 'app_una':'750 €', 'gest_da':'1.500 €',
}
NUM = {'sito_mese':'24.80','sito_una':'350.00','seo_una':'150.00','sito_tot':'500.00',
       'app_mese':'50.00','app_una':'750.00','gest_da':'1500.00'}

D = {}

# ---------------------------------------------------------------- ITALIANO
D['it'] = {
 'title':'Prezzi siti web, web app e gestionali | Danova Tech',
 'desc':'Sito web da 24,80 € al mese o 350 € una tantum (+150 € di SEO). Web app da 50 € al mese o 750 €. Gestionale aziendale da 1.500 €. Prezzi IVA inclusa.',
 'ogtitle':'Prezzi — Danova Tech',
 'ogdesc':'Sito web da 24,80 €/mese o 350 € una tantum, web app da 50 €/mese, gestionale da 1.500 €. IVA inclusa, senza costi nascosti.',
 'crumbs':[('Servizi','/servizi/'),('Prezzi',None)],
 'eyebrow':'Listino',
 'h1':'Prezzi scritti,<br><span class="grad">non sussurrati.</span>',
 'lead':'Quasi nessuna agenzia mette i prezzi sul sito. Noi sì. Qui sotto trovate quanto costa un sito web, un\'applicazione web e un gestionale aziendale, cosa c\'è dentro ogni cifra e quando conviene il canone mensile invece del pagamento unico. Tutti i prezzi sono IVA inclusa.',
 'cta1':'Richiedi un preventivo',
 'cta2':'Vai al listino',
 'cats':[
  {'id':'sito-web','eyebrow':'Sito web','h2':'Quanto costa <span class="grad">un sito web</span>',
   'intro':'Due strade, stesso sito. O lo pagate poco per volta con tutto incluso, oppure lo pagate una volta sola e resta vostro. Scegliete voi: non c\'è una versione peggiore, c\'è quella che sta meglio nei vostri conti.',
   'cards':[
    {'kind':'Opzione 1','name':'Sito in abbonamento','amt':'24,80 €','unit':'al mese',
     'badge':'Zero anticipo',
     'note':'IVA inclusa · durata minima 24 mesi · nessun costo di avvio',
     'list':['Dominio incluso e rinnovato da noi','Hosting e certificato SSL inclusi',
             'Manutenzione, backup e aggiornamenti di sicurezza','Modifiche ai testi e alle immagini comprese nel canone',
             'Assistenza via email e telefono'],
     'cta':'Parlane con noi'},
    {'kind':'Opzione 2','name':'Sito a costo chiuso','amt':'350 €','unit':'una tantum',
     'extra':'+ 150 € per l\'ottimizzazione SEO su Google e Bing','tot':'Sito + SEO: 500 € una volta sola',
     'note':'IVA inclusa · nessun canone, nessun vincolo',
     'feat':True,
     'list':['Il sito è vostro dal giorno della consegna','Dominio e hosting intestati a voi',
             'SEO per Google e Bing: 150 € una tantum','Nessuna durata minima da rispettare',
             'Manutenzione facoltativa, solo se la volete'],
     'cta':'Richiedi il preventivo'}]},
  {'id':'web-app','eyebrow':'Applicazione web','h2':'Quanto costa <span class="grad">un\'applicazione web</span>',
   'intro':'Un\'applicazione web si apre dal browser, non si installa e funziona su computer, tablet e telefono. Anche qui potete partire con un canone oppure prendere un\'applicazione già pronta e averla operativa subito.',
   'cards':[
    {'kind':'Opzione 1','name':'Web app in abbonamento','amt':'50 €','unit':'al mese',
     'note':'IVA inclusa · attivazione senza costi iniziali',
     'list':['Applicazione raggiungibile da qualsiasi browser','Hosting, backup e aggiornamenti inclusi',
             'Utenti, ruoli e permessi','Correzioni e piccole evoluzioni comprese',
             'Assistenza inclusa nel canone'],
     'cta':'Parlane con noi'},
    {'kind':'Opzione 2','name':'Web app pronta','amt':'da 750 €','unit':'una tantum',
     'note':'IVA inclusa · operativa da subito',
     'list':['Applicazione già sviluppata, non si aspettano mesi','Personalizzata con i vostri dati, colori e logo',
             'Pagamento unico, nessun canone obbligatorio','Evoluzioni successive preventivate a parte',
             'Formazione iniziale inclusa'],
     'cta':'Richiedi il preventivo'}]},
  {'id':'gestionale','eyebrow':'Gestionale aziendale','h2':'Quanto costa <span class="grad">un gestionale aziendale</span>',
   'intro':'Qui non esiste un prezzo di listino onesto, perché un gestionale si costruisce sul modo in cui lavorate. Quello che possiamo dire prima è il punto di partenza e come arriviamo alla cifra: analisi, preventivo a prezzo fisso, e da lì non si muove.',
   'cards':[
    {'kind':'Su misura','name':'Gestionale aziendale','amt':'da 1.500 €','unit':'progetto',
     'note':'IVA inclusa · cifra definita dopo l\'analisi, poi non cambia',
     'feat':True,
     'list':['Analisi dei vostri processi prima di scrivere una riga di codice','Moduli scelti su come lavorate davvero, non un pacchetto standard',
             'Migrazione dei dati da Excel o dal gestionale attuale','Formazione delle persone che lo useranno',
             'Prezzo fisso concordato prima di iniziare'],
     'cta':'Chiedi una valutazione'}]}],
 'compare':{'eyebrow':'Come scegliere','h2':'Canone mensile o <span class="grad">pagamento unico?</span>',
   'paras':[
    '<b>Il canone conviene</b> se volete partire senza mettere soldi sul tavolo all\'inizio e preferite avere dominio, hosting, manutenzione e modifiche dentro una voce sola, senza pensarci più. A 24,80 € al mese il sito è online, aggiornato e assistito, e le piccole modifiche non diventano ogni volta un preventivo.',
    '<b>Il pagamento unico conviene</b> se preferite chiudere la spesa e non avere vincoli. A 350 € il sito è vostro, con 150 € in più lo mettiamo in condizione di farsi trovare su Google e Bing, e da lì in avanti non pagate più nulla se non dominio e hosting.',
    'Una cosa la diciamo controvoglia ma la diciamo: un canone mensile alto e generico, da chiunque arrivi, spesso è il costo del sito rateizzato. Il nostro è basso apposta perché non è quello: è il servizio, non il sito nascosto dentro una rata. Se dopo 24 mesi volete passare al sito vostro, se ne parla senza drammi.']},
 'incluso':{'eyebrow':'Trasparenza','h2':'Cosa c\'è dentro il prezzo,<br>e cosa no',
   'paras':[
    'Dentro ogni cifra ci sono progettazione, sviluppo, messa online e i controlli che servono perché la pagina sia veloce e leggibile anche da telefono. Non ci sono costi di attivazione, non ci sono voci che compaiono a lavoro finito.',
    'Fuori dal prezzo restano le cose che dipendono da voi: eventuali licenze di terze parti, le fotografie professionali se le volete fatte da uno studio, la pubblicità su Google o su Meta (che è budget vostro, non nostro compenso) e le evoluzioni chieste dopo la consegna, che preventiviamo a parte e solo se le chiedete.',
    'Sui progetti più grandi — un gestionale, un\'integrazione con il vostro sistema di fatturazione — la cifra arriva dopo un\'analisi gratuita. È l\'unico modo per dare un numero che regge fino alla fine.']},
 'faq':[
  ('Quanto costa un sito web?',
   'Da noi un sito web costa 24,80 € al mese IVA inclusa, con dominio, hosting, manutenzione e modifiche compresi e una durata minima di 24 mesi; oppure 350 € una tantum se preferite pagarlo in una volta sola e averlo vostro. In questo secondo caso l\'ottimizzazione SEO per Google e Bing costa 150 € aggiuntivi, quindi 500 € in tutto.'),
  ('Cosa comprende il canone da 24,80 € al mese?',
   'Comprende il dominio, l\'hosting con certificato SSL, la manutenzione con backup e aggiornamenti di sicurezza, le modifiche ai testi e alle immagini e l\'assistenza. Non ci sono costi di avvio: si parte con la prima mensilità. La durata minima è di 24 mesi.'),
  ('Cosa sono i 150 € di SEO per Google e Bing?',
   'Sono l\'ottimizzazione iniziale del sito per i motori di ricerca: struttura delle pagine, titoli e descrizioni, dati strutturati, sitemap, registrazione su Google Search Console e Bing Webmaster Tools e invio delle pagine per l\'indicizzazione. È un lavoro una tantum e si aggiunge al sito da 350 €.'),
  ('Quanto costa un\'applicazione web?',
   'Un\'applicazione web costa 50 € al mese IVA inclusa, con hosting, aggiornamenti e assistenza inclusi, oppure a partire da 750 € una tantum se scegliete un\'applicazione già pronta, che è operativa da subito.'),
  ('Quanto costa un gestionale aziendale?',
   'Un gestionale su misura parte da 1.500 € IVA inclusa. La cifra esatta si definisce dopo un\'analisi gratuita dei vostri processi, perché dipende da quanti moduli servono, da quanti dati vanno migrati e da quali sistemi deve dialogare. Una volta dato, il prezzo è fisso e non cambia in corso d\'opera.'),
  ('I prezzi sono IVA inclusa?',
   'Sì. Tutte le cifre indicate in questa pagina sono IVA inclusa: quello che leggete è quello che pagate.'),
  ('Ci sono costi nascosti o di attivazione?',
   'No. Non chiediamo costi di attivazione, di setup o di uscita. Le uniche voci che si aggiungono sono quelle che chiedete voi dopo la consegna, e prima di farle vi arriva sempre un preventivo scritto.'),
  ('Il sito resta mio?',
   'Con il pagamento unico sì, dal giorno della consegna: dominio, hosting e contenuti sono intestati a voi. Con il canone il sito è in gestione a noi per i 24 mesi minimi, ma i contenuti restano vostri e alla scadenza potete passare al sito di proprietà senza rifare tutto da capo.'),
  ('Come si arriva al preventivo?',
   'Con una call gratuita di mezz\'ora in cui capiamo cosa vi serve. Poi vi arriva un preventivo a prezzo fisso, con dentro tutto quello che serve per andare online. Se durante la call emerge che vi basta la soluzione più piccola, ve lo diciamo.')],
 'ctabox':{'h2':'Volete la cifra sul vostro caso?',
   'p':'Mezz\'ora di call, gratuita e senza presentazioni commerciali: vi diciamo quale delle soluzioni qui sopra vi serve davvero, quanto costa e in quanto tempo va online.',
   'btn':'Richiedi un preventivo gratuito'},
 'altri':[('Quanto costa un sito web — la guida','/quanto-costa-un-sito-web/'),
          ('Quanto costa un gestionale','/quanto-costa-un-gestionale/'),
          ('Quanto costa un\'app','/quanto-costa-una-app/'),
          ('Quanto costa un e-commerce','/quanto-costa-un-ecommerce/'),
          ('Siti web &amp; E-commerce — il servizio','/servizi/siti-web-ecommerce/'),
          ('App su misura — il servizio','/servizi/app-su-misura/'),
          ('Gestionali &amp; CRM — il servizio','/servizi/gestionali-crm/'),
          ('SEO &amp; posizionamento','/servizi/seo/'),
          ('Come scegliere un\'agenzia web','/guide/come-scegliere-agenzia-web/'),
          ('Tutti i servizi','/servizi/')],
 'svc':{'name':'Realizzazione siti web, applicazioni web e gestionali a prezzo dichiarato',
        'type':'Sviluppo di siti web, applicazioni web e software gestionale',
        'desc':'Listino pubblico di Danova Tech: sito web da 24,80 € al mese o 350 € una tantum con SEO a 150 €, applicazione web da 50 € al mese o 750 € una tantum, gestionale aziendale da 1.500 €. Prezzi IVA inclusa.'},
 'offers':[
  ('Sito web in abbonamento','Sito web completo con dominio, hosting, manutenzione, aggiornamenti e modifiche inclusi. Durata minima 24 mesi.','sito_mese','MON',24),
  ('Sito web a costo chiuso','Sito web consegnato e di proprietà del cliente, pagamento unico.','sito_una',None,None),
  ('Ottimizzazione SEO per Google e Bing','Ottimizzazione iniziale per i motori di ricerca: struttura, tag, dati strutturati, sitemap e indicizzazione su Google e Bing.','seo_una',None,None),
  ('Applicazione web in abbonamento','Applicazione web con hosting, aggiornamenti e assistenza inclusi.','app_mese','MON',None),
  ('Applicazione web pronta','Applicazione web già sviluppata, personalizzata e operativa da subito.','app_una',None,None),
  ('Gestionale aziendale su misura','Software gestionale costruito sui processi dell\'azienda, con migrazione dati e formazione.','gest_da',None,None)],
}

# ---------------------------------------------------------------- ENGLISH
D['en'] = {
 'title':'Pricing: websites, web apps and ERP | Danova Tech',
 'desc':'Website from €24.80/month or €350 one-off (+€150 SEO for Google and Bing). Web app from €50/month or €750. Business ERP from €1,500. VAT included.',
 'ogtitle':'Pricing — Danova Tech',
 'ogdesc':'Website from €24.80/month or €350 one-off, web app from €50/month, custom ERP from €1,500. VAT included, no hidden costs.',
 'crumbs':[('Services','/en/services/'),('Pricing',None)],
 'eyebrow':'Price list',
 'h1':'Prices written down,<br><span class="grad">not whispered.</span>',
 'lead':'Almost no agency puts prices on its website. We do. Below you will find what a website, a web app and a business management system cost, what is inside each figure, and when a monthly fee makes more sense than paying once. All prices include VAT.',
 'cta1':'Request a quote',
 'cta2':'See the price list',
 'cats':[
  {'id':'website','eyebrow':'Website','h2':'How much does <span class="grad">a website</span> cost',
   'intro':'Two routes, same website. Either you pay a little each month with everything included, or you pay once and the site is yours. Neither is the poor relation: pick the one that fits your cash flow.',
   'cards':[
    {'kind':'Option 1','name':'Website on a monthly plan','amt':'€24.80','unit':'per month',
     'badge':'No upfront cost',
     'note':'VAT included · 24-month minimum term · no setup fee',
     'list':['Domain included and renewed by us','Hosting and SSL certificate included',
             'Maintenance, backups and security updates','Text and image changes included in the fee',
             'Support by email and phone'],
     'cta':'Talk to us'},
    {'kind':'Option 2','name':'Website at a closed price','amt':'€350','unit':'one-off',
     'extra':'+ €150 for SEO optimisation on Google and Bing','tot':'Website + SEO: €500, once',
     'note':'VAT included · no subscription, no lock-in',
     'feat':True,
     'list':['The site is yours from the day it goes live','Domain and hosting registered in your name',
             'SEO for Google and Bing: €150 one-off','No minimum term to honour',
             'Maintenance optional, only if you want it'],
     'cta':'Request a quote'}]},
  {'id':'web-app','eyebrow':'Web app','h2':'How much does <span class="grad">a web app</span> cost',
   'intro':'A web app opens in the browser, needs no installation and works on desktop, tablet and phone. Here too you can start on a monthly fee or take an application that is already built and use it straight away.',
   'cards':[
    {'kind':'Option 1','name':'Web app on a monthly plan','amt':'€50','unit':'per month',
     'note':'VAT included · no activation fee',
     'list':['Reachable from any browser','Hosting, backups and updates included',
             'Users, roles and permissions','Fixes and small improvements included',
             'Support included in the fee'],
     'cta':'Talk to us'},
    {'kind':'Option 2','name':'Ready-made web app','amt':'from €750','unit':'one-off',
     'note':'VAT included · running from day one',
     'list':['Already developed, no months of waiting','Set up with your data, colours and logo',
             'One payment, no compulsory subscription','Later developments quoted separately',
             'Initial training included'],
     'cta':'Request a quote'}]},
  {'id':'erp','eyebrow':'Business ERP','h2':'How much does <span class="grad">a business ERP</span> cost',
   'intro':'There is no honest list price here, because a management system is built around the way you work. What we can say upfront is the starting point and how we get to the number: analysis, fixed-price quote, and it does not move after that.',
   'cards':[
    {'kind':'Custom built','name':'Custom business ERP','amt':'from €1,500','unit':'per project',
     'note':'VAT included · figure set after the analysis, then fixed',
     'feat':True,
     'list':['We map your processes before writing a line of code','Modules chosen around how you actually work',
             'Data migration from Excel or your current system','Training for the people who will use it',
             'Fixed price agreed before we start'],
     'cta':'Ask for an assessment'}]}],
 'compare':{'eyebrow':'How to choose','h2':'Monthly fee or <span class="grad">one-off payment?</span>',
   'paras':[
    '<b>The monthly plan works</b> if you would rather not put money on the table at the start and prefer domain, hosting, maintenance and changes to sit in one line you never have to think about again. At €24.80 a month the site is live, updated and supported, and small changes do not turn into a quote every time.',
    '<b>Paying once works</b> if you would rather close the cost and carry no commitment. At €350 the site is yours; €150 more gets it properly set up to be found on Google and Bing, and from then on you pay nothing beyond domain and hosting.',
    'One thing we say reluctantly, but we say it: a high, vague monthly fee — from anyone — is often the price of the website spread over instalments. Ours is deliberately low because it is not that: it is the service, not the site hidden inside a payment plan. If after 24 months you want to move to owning the site, we sort it out without drama.']},
 'incluso':{'eyebrow':'Transparency','h2':'What the price includes,<br>and what it does not',
   'paras':[
    'Every figure covers design, development, going live and the checks that make the page fast and readable on a phone. There is no activation fee and no line item that appears once the work is done.',
    'Outside the price sit the things that depend on you: any third-party licences, professional photography if you want a studio to shoot it, advertising budget on Google or Meta (that is your spend, not our fee) and anything you ask for after delivery, which we quote separately and only if you ask.',
    'On larger projects — an ERP, an integration with your invoicing system — the figure comes after a free analysis. It is the only way to give a number that still holds at the end.']},
 'faq':[
  ('How much does a website cost?',
   'With us a website costs €24.80 per month including VAT, with domain, hosting, maintenance and content changes included and a 24-month minimum term; or €350 as a one-off if you prefer to pay once and own it. In that second case SEO optimisation for Google and Bing costs a further €150, so €500 in total.'),
  ('What does the €24.80 monthly fee include?',
   'It includes the domain, hosting with an SSL certificate, maintenance with backups and security updates, text and image changes, and support. There is no setup fee: you start with the first month. The minimum term is 24 months.'),
  ('What is the €150 SEO for Google and Bing?',
   'It is the initial search engine optimisation of the site: page structure, titles and descriptions, structured data, sitemap, registration on Google Search Console and Bing Webmaster Tools and submission of the pages for indexing. It is a one-off job and it is added to the €350 website.'),
  ('How much does a web app cost?',
   'A web app costs €50 per month including VAT, with hosting, updates and support included, or from €750 as a one-off if you choose a ready-made application, which is running from day one.'),
  ('How much does a business ERP cost?',
   'A custom management system starts at €1,500 including VAT. The exact figure is set after a free analysis of your processes, because it depends on how many modules you need, how much data has to be migrated and which systems it must talk to. Once given, the price is fixed and does not change during the project.'),
  ('Do the prices include VAT?',
   'Yes. Every figure on this page includes VAT: what you read is what you pay.'),
  ('Are there hidden or activation fees?',
   'No. We charge no activation, setup or exit fees. The only extras are the ones you ask for after delivery, and you always get a written quote before we do them.'),
  ('Do I own the website?',
   'With the one-off payment, yes, from the day it goes live: domain, hosting and content are in your name. On the monthly plan we manage the site for the 24-month minimum term, but the content stays yours and at the end you can move to owning it without rebuilding everything.'),
  ('How do we get to a quote?',
   'With a free half-hour call in which we work out what you need. Then you get a fixed-price quote covering everything required to go live. If it turns out the smaller option is enough for you, we say so.')],
 'ctabox':{'h2':'Want the figure for your case?',
   'p':'A free half-hour call, no sales deck: we tell you which of the options above you actually need, what it costs and how long it takes to go live.',
   'btn':'Request a free quote'},
 'altri':[('How much does a website cost — the guide','/en/how-much-does-a-website-cost/'),
          ('Websites &amp; e-commerce','/en/services/websites-ecommerce/'),
          ('Custom apps','/en/services/custom-apps/'),
          ('ERP &amp; CRM','/en/services/erp-crm/'),
          ('SEO','/en/services/seo/'),
          ('Software development company UK','/en/software-development-company-uk/'),
          ('Web design agency UK','/en/web-design-agency-uk/'),
          ('All services','/en/services/')],
 'svc':{'name':'Websites, web apps and ERP at a published price',
        'type':'Website, web application and business software development',
        'desc':'Danova Tech public price list: website from €24.80 per month or €350 one-off with SEO at €150, web app from €50 per month or €750 one-off, custom business ERP from €1,500. VAT included.'},
 'offers':[
  ('Website on a monthly plan','Complete website with domain, hosting, maintenance, updates and content changes included. 24-month minimum term.','sito_mese','MON',24),
  ('Website at a closed price','Website delivered and owned by the client, single payment.','sito_una',None,None),
  ('SEO optimisation for Google and Bing','Initial search engine optimisation: structure, tags, structured data, sitemap and indexing on Google and Bing.','seo_una',None,None),
  ('Web app on a monthly plan','Web application with hosting, updates and support included.','app_mese','MON',None),
  ('Ready-made web app','Web application already developed, customised and running from day one.','app_una',None,None),
  ('Custom business ERP','Management software built around the company processes, with data migration and training.','gest_da',None,None)],
}

# ---------------------------------------------------------------- DEUTSCH
D['de'] = {
 'title':'Preise: Website, Web-App und ERP | Danova Tech',
 'desc':'Website ab 24,80 € im Monat oder 350 € einmalig (+150 € SEO für Google und Bing). Web-App ab 50 € im Monat oder 750 €. ERP ab 1.500 €. Inkl. MwSt.',
 'ogtitle':'Preise — Danova Tech',
 'ogdesc':'Website ab 24,80 €/Monat oder 350 € einmalig, Web-App ab 50 €/Monat, ERP ab 1.500 €. Inklusive MwSt., ohne versteckte Kosten.',
 'crumbs':[('Leistungen','/de/leistungen/'),('Preise',None)],
 'eyebrow':'Preisliste',
 'h1':'Preise, die<br><span class="grad">schwarz auf weiß stehen.</span>',
 'lead':'Kaum eine Agentur schreibt ihre Preise auf die Website. Wir schon. Unten steht, was eine Website, eine Web-App und ein Warenwirtschaftssystem kosten, was in jeder Zahl enthalten ist und wann sich die Monatsgebühr gegenüber der Einmalzahlung lohnt. Alle Preise verstehen sich inklusive MwSt.',
 'cta1':'Angebot anfordern',
 'cta2':'Zur Preisliste',
 'cats':[
  {'id':'website','eyebrow':'Website','h2':'Was kostet <span class="grad">eine Website</span>',
   'intro':'Zwei Wege, dieselbe Website. Entweder Sie zahlen monatlich wenig und haben alles inklusive, oder Sie zahlen einmal und die Website gehört Ihnen. Keine der beiden Varianten ist die schlechtere: entscheidend ist, was besser in Ihre Zahlen passt.',
   'cards':[
    {'kind':'Variante 1','name':'Website im Abo','amt':'24,80 €','unit':'pro Monat',
     'badge':'Ohne Anzahlung',
     'note':'inkl. MwSt. · Mindestlaufzeit 24 Monate · keine Einrichtungsgebühr',
     'list':['Domain inklusive, Verlängerung übernehmen wir','Hosting und SSL-Zertifikat inklusive',
             'Wartung, Backups und Sicherheitsupdates','Text- und Bildänderungen in der Gebühr enthalten',
             'Support per E-Mail und Telefon'],
     'cta':'Sprechen wir darüber'},
    {'kind':'Variante 2','name':'Website zum Festpreis','amt':'350 €','unit':'einmalig',
     'extra':'+ 150 € für die SEO-Optimierung bei Google und Bing','tot':'Website + SEO: 500 €, einmalig',
     'note':'inkl. MwSt. · keine Gebühr, keine Bindung',
     'feat':True,
     'list':['Die Website gehört Ihnen ab dem Tag der Übergabe','Domain und Hosting laufen auf Ihren Namen',
             'SEO für Google und Bing: 150 € einmalig','Keine Mindestlaufzeit',
             'Wartung optional, nur wenn Sie sie wollen'],
     'cta':'Angebot anfordern'}]},
  {'id':'web-app','eyebrow':'Web-App','h2':'Was kostet <span class="grad">eine Web-App</span>',
   'intro':'Eine Web-App öffnet sich im Browser, muss nicht installiert werden und läuft auf Rechner, Tablet und Handy. Auch hier können Sie mit einer Monatsgebühr starten oder eine fertige Anwendung nehmen und sofort loslegen.',
   'cards':[
    {'kind':'Variante 1','name':'Web-App im Abo','amt':'50 €','unit':'pro Monat',
     'note':'inkl. MwSt. · keine Aktivierungsgebühr',
     'list':['Aus jedem Browser erreichbar','Hosting, Backups und Updates inklusive',
             'Benutzer, Rollen und Berechtigungen','Korrekturen und kleine Erweiterungen enthalten',
             'Support in der Gebühr enthalten'],
     'cta':'Sprechen wir darüber'},
    {'kind':'Variante 2','name':'Fertige Web-App','amt':'ab 750 €','unit':'einmalig',
     'note':'inkl. MwSt. · sofort einsatzbereit',
     'list':['Bereits entwickelt, keine Wartezeit von Monaten','Eingerichtet mit Ihren Daten, Farben und Ihrem Logo',
             'Einmalzahlung, kein Pflichtabo','Spätere Erweiterungen separat kalkuliert',
             'Einführungsschulung inklusive'],
     'cta':'Angebot anfordern'}]},
  {'id':'erp','eyebrow':'ERP / Warenwirtschaft','h2':'Was kostet <span class="grad">ein ERP-System</span>',
   'intro':'Hier gibt es keinen ehrlichen Listenpreis, weil ein Warenwirtschaftssystem auf Ihre Arbeitsweise gebaut wird. Was wir vorher sagen können, ist der Startpunkt und der Weg zur Zahl: Analyse, Festpreisangebot, und danach bewegt sich nichts mehr.',
   'cards':[
    {'kind':'Individuell','name':'ERP nach Maß','amt':'ab 1.500 €','unit':'pro Projekt',
     'note':'inkl. MwSt. · Betrag nach der Analyse, danach fix',
     'feat':True,
     'list':['Wir nehmen Ihre Prozesse auf, bevor eine Zeile Code entsteht','Module nach Ihrer tatsächlichen Arbeitsweise, kein Standardpaket',
             'Datenübernahme aus Excel oder dem bisherigen System','Schulung der Menschen, die damit arbeiten',
             'Festpreis vor Projektbeginn vereinbart'],
     'cta':'Einschätzung anfragen'}]}],
 'compare':{'eyebrow':'Entscheidungshilfe','h2':'Monatsgebühr oder <span class="grad">Einmalzahlung?</span>',
   'paras':[
    '<b>Das Abo lohnt sich</b>, wenn Sie am Anfang kein Geld binden wollen und Domain, Hosting, Wartung und Änderungen lieber in einer einzigen Position haben, über die Sie nie wieder nachdenken müssen. Für 24,80 € im Monat ist die Website online, aktuell und betreut, und kleine Änderungen werden nicht jedes Mal zu einem Angebot.',
    '<b>Die Einmalzahlung lohnt sich</b>, wenn Sie die Ausgabe abschließen und keine Bindung eingehen wollen. Für 350 € gehört die Website Ihnen, mit 150 € mehr wird sie so aufgestellt, dass Google und Bing sie finden, und danach zahlen Sie nur noch Domain und Hosting.',
    'Eines sagen wir ungern, aber wir sagen es: eine hohe, vage Monatsgebühr — von wem auch immer — ist oft der in Raten verteilte Preis der Website. Unsere ist bewusst niedrig, weil sie genau das nicht ist: sie ist die Dienstleistung, nicht die in einer Rate versteckte Website. Wenn Sie nach 24 Monaten zur eigenen Website wechseln wollen, regeln wir das ohne Drama.']},
 'incluso':{'eyebrow':'Transparenz','h2':'Was im Preis steckt<br>und was nicht',
   'paras':[
    'In jeder Zahl stecken Konzeption, Entwicklung, Veröffentlichung und die Kontrollen, die dafür sorgen, dass die Seite schnell und auch auf dem Handy gut lesbar ist. Es gibt keine Aktivierungsgebühr und keine Position, die erst nach getaner Arbeit auftaucht.',
    'Außerhalb des Preises bleibt, was von Ihnen abhängt: eventuelle Lizenzen Dritter, professionelle Fotos, wenn ein Studio sie machen soll, Werbebudget bei Google oder Meta (das ist Ihre Ausgabe, nicht unser Honorar) und alles, was Sie nach der Übergabe zusätzlich wünschen — das kalkulieren wir separat und nur auf Ihre Anfrage.',
    'Bei größeren Projekten — einem ERP, einer Anbindung an Ihre Fakturierung — kommt die Zahl nach einer kostenlosen Analyse. Nur so hält eine Zahl bis zum Schluss.']},
 'faq':[
  ('Was kostet eine Website?',
   'Bei uns kostet eine Website 24,80 € im Monat inkl. MwSt., mit Domain, Hosting, Wartung und Inhaltsänderungen und einer Mindestlaufzeit von 24 Monaten; oder 350 € einmalig, wenn Sie lieber einmal zahlen und die Website besitzen wollen. In diesem zweiten Fall kostet die SEO-Optimierung für Google und Bing zusätzlich 150 €, insgesamt also 500 €.'),
  ('Was ist in der Monatsgebühr von 24,80 € enthalten?',
   'Enthalten sind Domain, Hosting mit SSL-Zertifikat, Wartung mit Backups und Sicherheitsupdates, Text- und Bildänderungen sowie Support. Es gibt keine Einrichtungsgebühr: Sie starten mit der ersten Monatsrate. Die Mindestlaufzeit beträgt 24 Monate.'),
  ('Was sind die 150 € SEO für Google und Bing?',
   'Das ist die anfängliche Suchmaschinenoptimierung der Website: Seitenstruktur, Titel und Beschreibungen, strukturierte Daten, Sitemap, Anmeldung bei Google Search Console und Bing Webmaster Tools sowie Einreichung der Seiten zur Indexierung. Es ist eine einmalige Leistung und kommt zur Website für 350 € hinzu.'),
  ('Was kostet eine Web-App?',
   'Eine Web-App kostet 50 € im Monat inkl. MwSt., mit Hosting, Updates und Support, oder ab 750 € einmalig, wenn Sie eine fertige Anwendung wählen, die sofort einsatzbereit ist.'),
  ('Was kostet ein ERP-System?',
   'Ein individuelles Warenwirtschaftssystem beginnt bei 1.500 € inkl. MwSt. Der genaue Betrag ergibt sich nach einer kostenlosen Analyse Ihrer Prozesse, denn er hängt davon ab, wie viele Module nötig sind, wie viele Daten übernommen werden und mit welchen Systemen es sprechen muss. Einmal genannt, ist der Preis fix und ändert sich während des Projekts nicht.'),
  ('Verstehen sich die Preise inklusive MwSt.?',
   'Ja. Alle Beträge auf dieser Seite sind inklusive Mehrwertsteuer: Was Sie lesen, ist was Sie zahlen.'),
  ('Gibt es versteckte Kosten oder Aktivierungsgebühren?',
   'Nein. Wir berechnen keine Aktivierungs-, Einrichtungs- oder Ausstiegsgebühren. Zusätzlich kommen nur Leistungen, die Sie nach der Übergabe anfragen, und davor bekommen Sie immer ein schriftliches Angebot.'),
  ('Gehört die Website mir?',
   'Bei der Einmalzahlung ja, ab dem Tag der Übergabe: Domain, Hosting und Inhalte laufen auf Ihren Namen. Im Abo betreuen wir die Website für die 24 Monate Mindestlaufzeit, die Inhalte bleiben aber Ihre, und danach können Sie auf die eigene Website wechseln, ohne alles neu zu bauen.'),
  ('Wie kommen wir zum Angebot?',
   'Über ein kostenloses halbstündiges Gespräch, in dem wir klären, was Sie brauchen. Danach erhalten Sie ein Festpreisangebot mit allem, was für den Start nötig ist. Wenn sich zeigt, dass die kleinere Lösung reicht, sagen wir es Ihnen.')],
 'ctabox':{'h2':'Wollen Sie die Zahl für Ihren Fall?',
   'p':'Eine kostenlose halbe Stunde, ohne Verkaufspräsentation: Wir sagen Ihnen, welche der Varianten oben Sie wirklich brauchen, was sie kostet und wie lange es bis zum Start dauert.',
   'btn':'Kostenloses Angebot anfordern'},
 'altri':[('Was kostet eine Website — der Leitfaden','/de/was-kostet-eine-website/'),
          ('Websites &amp; E-Commerce','/de/leistungen/websites-ecommerce/'),
          ('Individuelle Apps','/de/leistungen/individuelle-apps/'),
          ('Warenwirtschaft &amp; CRM','/de/leistungen/warenwirtschaft-crm/'),
          ('SEO','/de/leistungen/seo/'),
          ('Webagentur Deutschland','/de/webagentur-deutschland/'),
          ('Individualsoftware Deutschland','/de/individualsoftware-deutschland/'),
          ('Alle Leistungen','/de/leistungen/')],
 'svc':{'name':'Websites, Web-Apps und ERP zum veröffentlichten Preis',
        'type':'Entwicklung von Websites, Webanwendungen und Unternehmenssoftware',
        'desc':'Öffentliche Preisliste von Danova Tech: Website ab 24,80 € im Monat oder 350 € einmalig mit SEO für 150 €, Web-App ab 50 € im Monat oder 750 € einmalig, individuelles ERP ab 1.500 €. Inklusive MwSt.'},
 'offers':[
  ('Website im Abo','Komplette Website mit Domain, Hosting, Wartung, Updates und Inhaltsänderungen. Mindestlaufzeit 24 Monate.','sito_mese','MON',24),
  ('Website zum Festpreis','Website übergeben und im Eigentum des Kunden, Einmalzahlung.','sito_una',None,None),
  ('SEO-Optimierung für Google und Bing','Anfängliche Suchmaschinenoptimierung: Struktur, Tags, strukturierte Daten, Sitemap und Indexierung bei Google und Bing.','seo_una',None,None),
  ('Web-App im Abo','Webanwendung mit Hosting, Updates und Support.','app_mese','MON',None),
  ('Fertige Web-App','Bereits entwickelte, angepasste und sofort einsatzbereite Webanwendung.','app_una',None,None),
  ('Individuelles ERP-System','Unternehmenssoftware, gebaut auf die Prozesse des Unternehmens, mit Datenübernahme und Schulung.','gest_da',None,None)],
}

# ---------------------------------------------------------------- FRANÇAIS
D['fr'] = {
 'title':'Tarifs : site internet, web app et ERP | Danova Tech',
 'desc':'Site internet à partir de 24,80 €/mois ou 350 € en une fois (+150 € de SEO Google et Bing). Web app dès 50 €/mois ou 750 €. ERP dès 1 500 €. TVA incluse.',
 'ogtitle':'Tarifs — Danova Tech',
 'ogdesc':'Site internet à 24,80 €/mois ou 350 € en une fois, web app dès 50 €/mois, ERP sur mesure dès 1 500 €. TVA incluse, sans frais cachés.',
 'crumbs':[('Services','/fr/services/'),('Tarifs',None)],
 'eyebrow':'Grille tarifaire',
 'h1':'Des prix écrits,<br><span class="grad">pas murmurés.</span>',
 'lead':'Presque aucune agence n\'affiche ses prix. Nous, si. Vous trouverez ci-dessous combien coûtent un site internet, une application web et un logiciel de gestion, ce que contient chaque montant et quand l\'abonnement mensuel vaut mieux que le paiement unique. Tous les prix sont TVA incluse.',
 'cta1':'Demander un devis',
 'cta2':'Voir les tarifs',
 'cats':[
  {'id':'site-internet','eyebrow':'Site internet','h2':'Combien coûte <span class="grad">un site internet</span>',
   'intro':'Deux chemins, le même site. Soit vous payez peu chaque mois avec tout compris, soit vous payez une fois et le site vous appartient. Aucune des deux n\'est le parent pauvre : choisissez celle qui tient dans votre trésorerie.',
   'cards':[
    {'kind':'Option 1','name':'Site en abonnement','amt':'24,80 €','unit':'par mois',
     'badge':'Sans apport',
     'note':'TVA incluse · durée minimale 24 mois · sans frais de mise en service',
     'list':['Nom de domaine inclus et renouvelé par nos soins','Hébergement et certificat SSL inclus',
             'Maintenance, sauvegardes et mises à jour de sécurité','Modifications de textes et d\'images comprises',
             'Assistance par e-mail et par téléphone'],
     'cta':'Parlons-en'},
    {'kind':'Option 2','name':'Site à prix fermé','amt':'350 €','unit':'en une fois',
     'extra':'+ 150 € pour l\'optimisation SEO sur Google et Bing','tot':'Site + SEO : 500 €, une seule fois',
     'note':'TVA incluse · sans abonnement, sans engagement',
     'feat':True,
     'list':['Le site est à vous dès la mise en ligne','Domaine et hébergement à votre nom',
             'SEO Google et Bing : 150 € en une fois','Aucune durée minimale à respecter',
             'Maintenance facultative, seulement si vous la voulez'],
     'cta':'Demander un devis'}]},
  {'id':'web-app','eyebrow':'Application web','h2':'Combien coûte <span class="grad">une application web</span>',
   'intro':'Une application web s\'ouvre dans le navigateur, ne s\'installe pas et fonctionne sur ordinateur, tablette et téléphone. Là aussi, vous pouvez démarrer avec un abonnement ou prendre une application déjà prête et l\'utiliser tout de suite.',
   'cards':[
    {'kind':'Option 1','name':'Application web en abonnement','amt':'50 €','unit':'par mois',
     'note':'TVA incluse · sans frais d\'activation',
     'list':['Accessible depuis n\'importe quel navigateur','Hébergement, sauvegardes et mises à jour inclus',
             'Utilisateurs, rôles et permissions','Corrections et petites évolutions comprises',
             'Assistance incluse dans l\'abonnement'],
     'cta':'Parlons-en'},
    {'kind':'Option 2','name':'Application web prête','amt':'à partir de 750 €','unit':'en une fois',
     'note':'TVA incluse · opérationnelle immédiatement',
     'list':['Déjà développée, pas de mois d\'attente','Paramétrée avec vos données, vos couleurs et votre logo',
             'Paiement unique, aucun abonnement obligatoire','Évolutions ultérieures chiffrées à part',
             'Formation initiale incluse'],
     'cta':'Demander un devis'}]},
  {'id':'erp','eyebrow':'Logiciel de gestion','h2':'Combien coûte <span class="grad">un logiciel de gestion</span>',
   'intro':'Ici, aucun prix catalogue ne serait honnête, parce qu\'un logiciel de gestion se construit sur votre façon de travailler. Ce que nous pouvons dire à l\'avance, c\'est le point de départ et la manière dont on arrive au montant : analyse, devis à prix fixe, et ensuite il ne bouge plus.',
   'cards':[
    {'kind':'Sur mesure','name':'Logiciel de gestion sur mesure','amt':'dès 1 500 €','unit':'par projet',
     'note':'TVA incluse · montant fixé après l\'analyse, puis inchangé',
     'feat':True,
     'list':['Nous cartographions vos processus avant d\'écrire une ligne de code','Modules choisis sur votre manière réelle de travailler',
             'Reprise des données depuis Excel ou votre logiciel actuel','Formation des personnes qui l\'utiliseront',
             'Prix fixe convenu avant de commencer'],
     'cta':'Demander une évaluation'}]}],
 'compare':{'eyebrow':'Comment choisir','h2':'Abonnement mensuel ou <span class="grad">paiement unique ?</span>',
   'paras':[
    '<b>L\'abonnement convient</b> si vous préférez ne rien immobiliser au départ et avoir domaine, hébergement, maintenance et modifications dans une seule ligne dont vous n\'avez plus à vous occuper. À 24,80 € par mois le site est en ligne, à jour et suivi, et les petites modifications ne deviennent pas un devis à chaque fois.',
    '<b>Le paiement unique convient</b> si vous préférez solder la dépense et ne prendre aucun engagement. À 350 € le site est à vous ; 150 € de plus le mettent en état d\'être trouvé sur Google et Bing, et ensuite vous ne payez plus que le domaine et l\'hébergement.',
    'Une chose que nous disons à contrecœur, mais nous la disons : un abonnement mensuel élevé et vague, quel qu\'en soit l\'émetteur, est souvent le prix du site étalé en mensualités. Le nôtre est volontairement bas parce qu\'il n\'est pas cela : c\'est le service, pas le site caché dans une traite. Si après 24 mois vous voulez passer au site en propriété, on s\'arrange sans drame.']},
 'incluso':{'eyebrow':'Transparence','h2':'Ce que le prix contient,<br>et ce qu\'il ne contient pas',
   'paras':[
    'Chaque montant couvre la conception, le développement, la mise en ligne et les contrôles qui rendent la page rapide et lisible aussi sur téléphone. Pas de frais d\'activation, pas de ligne qui apparaît une fois le travail terminé.',
    'Restent hors prix les éléments qui dépendent de vous : d\'éventuelles licences tierces, les photographies professionnelles si vous voulez un studio, le budget publicitaire sur Google ou Meta (c\'est votre dépense, pas notre honoraire) et tout ce que vous demandez après la livraison, que nous chiffrons à part et seulement si vous le demandez.',
    'Sur les projets plus lourds — un ERP, une intégration avec votre facturation — le montant arrive après une analyse gratuite. C\'est la seule façon de donner un chiffre qui tient jusqu\'au bout.']},
 'faq':[
  ('Combien coûte un site internet ?',
   'Chez nous, un site internet coûte 24,80 € par mois TVA incluse, avec domaine, hébergement, maintenance et modifications compris et une durée minimale de 24 mois ; ou 350 € en une fois si vous préférez payer une seule fois et en être propriétaire. Dans ce second cas, l\'optimisation SEO pour Google et Bing coûte 150 € de plus, soit 500 € au total.'),
  ('Que comprend l\'abonnement à 24,80 € par mois ?',
   'Il comprend le nom de domaine, l\'hébergement avec certificat SSL, la maintenance avec sauvegardes et mises à jour de sécurité, les modifications de textes et d\'images et l\'assistance. Aucun frais de mise en service : on démarre avec la première mensualité. La durée minimale est de 24 mois.'),
  ('Que sont les 150 € de SEO pour Google et Bing ?',
   'C\'est l\'optimisation initiale du site pour les moteurs de recherche : structure des pages, titres et descriptions, données structurées, sitemap, inscription sur Google Search Console et Bing Webmaster Tools et soumission des pages à l\'indexation. C\'est une prestation unique qui s\'ajoute au site à 350 €.'),
  ('Combien coûte une application web ?',
   'Une application web coûte 50 € par mois TVA incluse, hébergement, mises à jour et assistance compris, ou à partir de 750 € en une fois si vous choisissez une application déjà prête, opérationnelle immédiatement.'),
  ('Combien coûte un logiciel de gestion ?',
   'Un logiciel de gestion sur mesure démarre à 1 500 € TVA incluse. Le montant exact se fixe après une analyse gratuite de vos processus, car il dépend du nombre de modules, du volume de données à reprendre et des systèmes avec lesquels il doit dialoguer. Une fois donné, le prix est ferme et ne change pas en cours de projet.'),
  ('Les prix sont-ils TVA incluse ?',
   'Oui. Tous les montants de cette page sont TVA incluse : ce que vous lisez est ce que vous payez.'),
  ('Y a-t-il des frais cachés ou d\'activation ?',
   'Non. Nous ne facturons ni activation, ni mise en service, ni sortie. Les seuls suppléments sont ceux que vous demandez après la livraison, et vous recevez toujours un devis écrit avant.'),
  ('Le site m\'appartient-il ?',
   'Avec le paiement unique, oui, dès la mise en ligne : domaine, hébergement et contenus sont à votre nom. Avec l\'abonnement, nous gérons le site pendant les 24 mois minimum, mais les contenus restent les vôtres et à l\'échéance vous pouvez passer au site en propriété sans tout refaire.'),
  ('Comment arrive-t-on au devis ?',
   'Par un appel gratuit d\'une demi-heure où l\'on comprend ce qu\'il vous faut. Vous recevez ensuite un devis à prix fixe, contenant tout ce qui est nécessaire pour être en ligne. Si la solution la plus simple suffit, on vous le dit.')],
 'ctabox':{'h2':'Vous voulez le chiffre pour votre cas ?',
   'p':'Une demi-heure d\'appel, gratuite et sans présentation commerciale : on vous dit laquelle des options ci-dessus vous est vraiment utile, ce qu\'elle coûte et en combien de temps elle est en ligne.',
   'btn':'Demander un devis gratuit'},
 'altri':[('Prix d\'un site internet — le guide','/fr/prix-creation-site-internet/'),
          ('Sites web &amp; e-commerce','/fr/services/sites-web-ecommerce/'),
          ('Applications sur mesure','/fr/services/applications-sur-mesure/'),
          ('ERP &amp; CRM','/fr/services/erp-crm/'),
          ('SEO','/fr/services/seo/'),
          ('Création de site internet en France','/fr/creation-site-internet-france/'),
          ('Logiciel sur mesure France','/fr/logiciel-sur-mesure-france/'),
          ('Tous les services','/fr/services/')],
 'svc':{'name':'Sites internet, applications web et ERP à prix affiché',
        'type':'Développement de sites internet, d\'applications web et de logiciels de gestion',
        'desc':'Grille tarifaire publique de Danova Tech : site internet à 24,80 € par mois ou 350 € en une fois avec SEO à 150 €, application web dès 50 € par mois ou 750 € en une fois, logiciel de gestion sur mesure dès 1 500 €. TVA incluse.'},
 'offers':[
  ('Site internet en abonnement','Site complet avec domaine, hébergement, maintenance, mises à jour et modifications inclus. Durée minimale 24 mois.','sito_mese','MON',24),
  ('Site internet à prix fermé','Site livré et propriété du client, paiement unique.','sito_una',None,None),
  ('Optimisation SEO pour Google et Bing','Optimisation initiale pour les moteurs : structure, balises, données structurées, sitemap et indexation sur Google et Bing.','seo_una',None,None),
  ('Application web en abonnement','Application web avec hébergement, mises à jour et assistance inclus.','app_mese','MON',None),
  ('Application web prête','Application web déjà développée, personnalisée et opérationnelle immédiatement.','app_una',None,None),
  ('Logiciel de gestion sur mesure','Logiciel de gestion construit sur les processus de l\'entreprise, avec reprise des données et formation.','gest_da',None,None)],
}

# ---------------------------------------------------------------- ESPAÑOL
D['es'] = {
 'title':'Precios: páginas web, web apps y ERP | Danova Tech',
 'desc':'Página web desde 24,80 €/mes o 350 € en un pago (+150 € de SEO en Google y Bing). Web app desde 50 €/mes o 750 €. ERP a medida desde 1.500 €. IVA incluido.',
 'ogtitle':'Precios — Danova Tech',
 'ogdesc':'Página web desde 24,80 €/mes o 350 € en un pago, web app desde 50 €/mes, ERP a medida desde 1.500 €. IVA incluido, sin costes ocultos.',
 'crumbs':[('Servicios','/es/servicios/'),('Precios',None)],
 'eyebrow':'Tarifas',
 'h1':'Precios escritos,<br><span class="grad">no susurrados.</span>',
 'lead':'Casi ninguna agencia publica sus precios. Nosotros sí. Aquí abajo está cuánto cuesta una página web, una aplicación web y un software de gestión, qué incluye cada cifra y cuándo conviene la cuota mensual en lugar del pago único. Todos los precios son con IVA incluido.',
 'cta1':'Pedir presupuesto',
 'cta2':'Ver las tarifas',
 'cats':[
  {'id':'pagina-web','eyebrow':'Página web','h2':'Cuánto cuesta <span class="grad">una página web</span>',
   'intro':'Dos caminos, la misma web. O pagáis poco cada mes con todo incluido, o pagáis una sola vez y la web es vuestra. Ninguna de las dos es la versión pobre: elegid la que encaje en vuestras cuentas.',
   'cards':[
    {'kind':'Opción 1','name':'Web con cuota mensual','amt':'24,80 €','unit':'al mes',
     'badge':'Sin entrada',
     'note':'IVA incluido · permanencia mínima 24 meses · sin coste de alta',
     'list':['Dominio incluido y renovado por nosotros','Alojamiento y certificado SSL incluidos',
             'Mantenimiento, copias de seguridad y actualizaciones','Cambios de textos e imágenes incluidos en la cuota',
             'Soporte por correo y por teléfono'],
     'cta':'Hablemos'},
    {'kind':'Opción 2','name':'Web a precio cerrado','amt':'350 €','unit':'pago único',
     'extra':'+ 150 € por la optimización SEO en Google y Bing','tot':'Web + SEO: 500 €, una sola vez',
     'note':'IVA incluido · sin cuota, sin permanencia',
     'feat':True,
     'list':['La web es vuestra desde el día de la entrega','Dominio y alojamiento a vuestro nombre',
             'SEO para Google y Bing: 150 € en un pago','Sin permanencia mínima',
             'Mantenimiento opcional, solo si lo queréis'],
     'cta':'Pedir presupuesto'}]},
  {'id':'web-app','eyebrow':'Aplicación web','h2':'Cuánto cuesta <span class="grad">una aplicación web</span>',
   'intro':'Una aplicación web se abre desde el navegador, no se instala y funciona en ordenador, tableta y móvil. Aquí también podéis empezar con una cuota o llevaros una aplicación ya lista y usarla desde el primer día.',
   'cards':[
    {'kind':'Opción 1','name':'Aplicación web con cuota','amt':'50 €','unit':'al mes',
     'note':'IVA incluido · sin coste de activación',
     'list':['Accesible desde cualquier navegador','Alojamiento, copias y actualizaciones incluidos',
             'Usuarios, roles y permisos','Correcciones y pequeñas mejoras incluidas',
             'Soporte incluido en la cuota'],
     'cta':'Hablemos'},
    {'kind':'Opción 2','name':'Aplicación web lista','amt':'desde 750 €','unit':'pago único',
     'note':'IVA incluido · operativa desde el primer día',
     'list':['Ya desarrollada, sin meses de espera','Configurada con vuestros datos, colores y logotipo',
             'Un solo pago, sin cuota obligatoria','Mejoras posteriores presupuestadas aparte',
             'Formación inicial incluida'],
     'cta':'Pedir presupuesto'}]},
  {'id':'erp','eyebrow':'Software de gestión','h2':'Cuánto cuesta <span class="grad">un software de gestión</span>',
   'intro':'Aquí no existe un precio de catálogo honesto, porque un software de gestión se construye sobre vuestra forma de trabajar. Lo que sí podemos decir antes es el punto de partida y cómo llegamos a la cifra: análisis, presupuesto cerrado, y a partir de ahí no se mueve.',
   'cards':[
    {'kind':'A medida','name':'Software de gestión a medida','amt':'desde 1.500 €','unit':'por proyecto',
     'note':'IVA incluido · cifra definida tras el análisis y luego fija',
     'feat':True,
     'list':['Analizamos vuestros procesos antes de escribir una línea de código','Módulos elegidos según cómo trabajáis de verdad',
             'Migración de datos desde Excel o desde el software actual','Formación de las personas que lo van a usar',
             'Precio cerrado acordado antes de empezar'],
     'cta':'Pedir una valoración'}]}],
 'compare':{'eyebrow':'Cómo elegir','h2':'¿Cuota mensual o <span class="grad">pago único?</span>',
   'paras':[
    '<b>La cuota conviene</b> si preferís no inmovilizar dinero al principio y tener dominio, alojamiento, mantenimiento y cambios en una sola línea en la que no hay que volver a pensar. Por 24,80 € al mes la web está online, actualizada y atendida, y los cambios pequeños no se convierten cada vez en un presupuesto.',
    '<b>El pago único conviene</b> si preferís cerrar el gasto y no tener permanencia. Por 350 € la web es vuestra; con 150 € más la dejamos en condiciones de que Google y Bing la encuentren, y a partir de ahí solo pagáis dominio y alojamiento.',
    'Una cosa la decimos a regañadientes, pero la decimos: una cuota mensual alta y genérica, venga de quien venga, suele ser el precio de la web repartido en plazos. La nuestra es baja precisamente porque no es eso: es el servicio, no la web escondida dentro de una letra. Si a los 24 meses queréis pasar a la web en propiedad, se arregla sin dramas.']},
 'incluso':{'eyebrow':'Transparencia','h2':'Qué incluye el precio<br>y qué no',
   'paras':[
    'Cada cifra cubre diseño, desarrollo, publicación y las comprobaciones que hacen que la página sea rápida y legible también en el móvil. No hay coste de activación ni partidas que aparecen cuando el trabajo ya está hecho.',
    'Fuera del precio quedan las cosas que dependen de vosotros: licencias de terceros si las hay, fotografía profesional si queréis un estudio, el presupuesto de publicidad en Google o Meta (es vuestro gasto, no nuestro honorario) y lo que pidáis después de la entrega, que presupuestamos aparte y solo si lo pedís.',
    'En los proyectos más grandes —un ERP, una integración con vuestra facturación— la cifra llega después de un análisis gratuito. Es la única forma de dar un número que aguante hasta el final.']},
 'faq':[
  ('¿Cuánto cuesta una página web?',
   'Con nosotros una página web cuesta 24,80 € al mes con IVA incluido, con dominio, alojamiento, mantenimiento y cambios incluidos y una permanencia mínima de 24 meses; o 350 € en un pago único si preferís pagarla de una vez y que sea vuestra. En ese segundo caso la optimización SEO para Google y Bing cuesta 150 € más, es decir 500 € en total.'),
  ('¿Qué incluye la cuota de 24,80 € al mes?',
   'Incluye el dominio, el alojamiento con certificado SSL, el mantenimiento con copias de seguridad y actualizaciones de seguridad, los cambios de textos e imágenes y el soporte. No hay coste de alta: se empieza con la primera mensualidad. La permanencia mínima es de 24 meses.'),
  ('¿Qué son los 150 € de SEO para Google y Bing?',
   'Son la optimización inicial de la web para los buscadores: estructura de las páginas, títulos y descripciones, datos estructurados, sitemap, alta en Google Search Console y Bing Webmaster Tools y envío de las páginas a indexación. Es un trabajo de una sola vez y se suma a la web de 350 €.'),
  ('¿Cuánto cuesta una aplicación web?',
   'Una aplicación web cuesta 50 € al mes con IVA incluido, con alojamiento, actualizaciones y soporte incluidos, o desde 750 € en un pago si elegís una aplicación ya lista, que está operativa desde el primer día.'),
  ('¿Cuánto cuesta un software de gestión?',
   'Un software de gestión a medida parte de 1.500 € con IVA incluido. La cifra exacta se define tras un análisis gratuito de vuestros procesos, porque depende de cuántos módulos hagan falta, cuántos datos haya que migrar y con qué sistemas tenga que hablar. Una vez dada, el precio es cerrado y no cambia durante el proyecto.'),
  ('¿Los precios llevan el IVA incluido?',
   'Sí. Todas las cifras de esta página son con IVA incluido: lo que leéis es lo que pagáis.'),
  ('¿Hay costes ocultos o de activación?',
   'No. No cobramos activación, alta ni salida. Lo único que se suma es lo que pidáis después de la entrega, y antes recibís siempre un presupuesto por escrito.'),
  ('¿La web es mía?',
   'Con el pago único sí, desde el día de la entrega: dominio, alojamiento y contenidos van a vuestro nombre. Con la cuota gestionamos la web durante los 24 meses de permanencia mínima, pero los contenidos siguen siendo vuestros y al vencimiento podéis pasar a la web en propiedad sin rehacerlo todo.'),
  ('¿Cómo se llega al presupuesto?',
   'Con una llamada gratuita de media hora en la que entendemos qué necesitáis. Después recibís un presupuesto cerrado con todo lo necesario para estar online. Si resulta que os basta con la opción más pequeña, os lo decimos.')],
 'ctabox':{'h2':'¿Queréis la cifra de vuestro caso?',
   'p':'Media hora de llamada, gratuita y sin presentación comercial: os decimos cuál de las opciones de arriba necesitáis de verdad, cuánto cuesta y en cuánto tiempo está online.',
   'btn':'Pedir presupuesto gratuito'},
 'altri':[('Cuánto cuesta una página web — la guía','/es/cuanto-cuesta-una-pagina-web/'),
          ('Webs &amp; e-commerce','/es/servicios/webs-ecommerce/'),
          ('Apps a medida','/es/servicios/apps-a-medida/'),
          ('ERP &amp; CRM','/es/servicios/erp-crm/'),
          ('SEO','/es/servicios/seo/'),
          ('Diseño web en España','/es/diseno-web-espana/'),
          ('Software a medida España','/es/software-a-medida-espana/'),
          ('Todos los servicios','/es/servicios/')],
 'svc':{'name':'Páginas web, aplicaciones web y ERP a precio publicado',
        'type':'Desarrollo de páginas web, aplicaciones web y software de gestión',
        'desc':'Tarifas públicas de Danova Tech: página web desde 24,80 € al mes o 350 € en un pago con SEO por 150 €, aplicación web desde 50 € al mes o 750 € en un pago, software de gestión a medida desde 1.500 €. IVA incluido.'},
 'offers':[
  ('Página web con cuota mensual','Web completa con dominio, alojamiento, mantenimiento, actualizaciones y cambios incluidos. Permanencia mínima 24 meses.','sito_mese','MON',24),
  ('Página web a precio cerrado','Web entregada y en propiedad del cliente, pago único.','sito_una',None,None),
  ('Optimización SEO para Google y Bing','Optimización inicial para buscadores: estructura, etiquetas, datos estructurados, sitemap e indexación en Google y Bing.','seo_una',None,None),
  ('Aplicación web con cuota mensual','Aplicación web con alojamiento, actualizaciones y soporte incluidos.','app_mese','MON',None),
  ('Aplicación web lista','Aplicación web ya desarrollada, personalizada y operativa desde el primer día.','app_una',None,None),
  ('Software de gestión a medida','Software de gestión construido sobre los procesos de la empresa, con migración de datos y formación.','gest_da',None,None)],
}


# =====================================================================
# 20 settembre 2026 — ottimizzazione SEO del listino
# Titoli con l'anno, H1 con le parole cercate, titolo FAQ descrittivo,
# tabella riassuntiva (utile per snippet e motori di risposta AI),
# data di aggiornamento visibile e immagine social dedicata per lingua.
# A GENNAIO: aggiornare l'anno nei titoli e la data AGGIORNATO.
# =====================================================================
AGGIORNATO = '2026-09-20'
PUBBLICATO = '2026-09-19'

_X = {
 'it':{
  'title':'Prezzi siti web, app e gestionali 2026 | Danova Tech',
  'h1':'Prezzi di siti web, app e gestionali:<br><span class="grad">scritti, non sussurrati.</span>',
  'ogtitle':'Quanto costa un sito web, un\'app o un gestionale: i prezzi Danova Tech',
  'faq_h2':'Domande frequenti sui prezzi',
  'tab':{'eyebrow':'In sintesi','h2':'Il listino <span class="grad">in una tabella</span>',
         'caption':'Prezzi Danova Tech per siti web, applicazioni web e gestionali, IVA inclusa',
         'cols':['Servizio','Formula','Prezzo (IVA inclusa)','Cosa comprende'],
         'f_mese_min':'Canone mensile, minimo 24 mesi','f_mese':'Canone mensile',
         'f_una':'Pagamento unico','f_da':'Pagamento unico, a partire da',
         'prezzi':{'sito_mese':'24,80 € / mese','sito_una':'350 €','seo_una':'150 €',
                   'app_mese':'50 € / mese','app_una':'da 750 €','gest_da':'da 1.500 €'},
         'upd':'Prezzi aggiornati al <time datetime="2026-09-20">20 settembre 2026</time>.'}},
 'en':{
  'title':'Website, web app and ERP pricing 2026 | Danova Tech',
  'h1':'Website, web app and ERP pricing:<br><span class="grad">written down, not whispered.</span>',
  'ogtitle':'How much does a website, a web app or an ERP cost: Danova Tech pricing',
  'faq_h2':'Pricing FAQ',
  'tab':{'eyebrow':'At a glance','h2':'The price list <span class="grad">in one table</span>',
         'caption':'Danova Tech prices for websites, web apps and ERP systems, VAT included',
         'cols':['Service','Plan','Price (VAT incl.)','What it includes'],
         'f_mese_min':'Monthly fee, 24-month minimum','f_mese':'Monthly fee',
         'f_una':'One-off payment','f_da':'One-off, starting from',
         'prezzi':{'sito_mese':'€24.80 / month','sito_una':'€350','seo_una':'€150',
                   'app_mese':'€50 / month','app_una':'from €750','gest_da':'from €1,500'},
         'upd':'Prices updated on <time datetime="2026-09-20">20 September 2026</time>.'}},
 'de':{
  'title':'Preise 2026: Website, Web-App und ERP | Danova Tech',
  'h1':'Preise für Website, Web-App und ERP:<br><span class="grad">schwarz auf weiß.</span>',
  'ogtitle':'Was kostet eine Website, eine Web-App oder ein ERP: die Preise von Danova Tech',
  'faq_h2':'Häufige Fragen zu den Preisen',
  'tab':{'eyebrow':'Auf einen Blick','h2':'Die Preisliste <span class="grad">in einer Tabelle</span>',
         'caption':'Preise von Danova Tech für Websites, Web-Apps und ERP-Systeme, inkl. MwSt.',
         'cols':['Leistung','Modell','Preis (inkl. MwSt.)','Was enthalten ist'],
         'f_mese_min':'Monatsgebühr, Mindestlaufzeit 24 Monate','f_mese':'Monatsgebühr',
         'f_una':'Einmalzahlung','f_da':'Einmalzahlung, ab',
         'prezzi':{'sito_mese':'24,80 € / Monat','sito_una':'350 €','seo_una':'150 €',
                   'app_mese':'50 € / Monat','app_una':'ab 750 €','gest_da':'ab 1.500 €'},
         'upd':'Preise aktualisiert am <time datetime="2026-09-20">20. September 2026</time>.'}},
 'fr':{
  'title':'Tarifs 2026 : site internet, web app et ERP | Danova Tech',
  'h1':'Tarifs site internet, web app et ERP :<br><span class="grad">écrits, pas murmurés.</span>',
  'ogtitle':'Combien coûte un site internet, une web app ou un ERP : les tarifs Danova Tech',
  'faq_h2':'Questions fréquentes sur les tarifs',
  'tab':{'eyebrow':'En bref','h2':'Les tarifs <span class="grad">en un tableau</span>',
         'caption':'Tarifs Danova Tech pour sites internet, applications web et logiciels de gestion, TVA incluse',
         'cols':['Service','Formule','Prix (TVA incluse)','Ce qui est inclus'],
         'f_mese_min':'Abonnement mensuel, 24 mois minimum','f_mese':'Abonnement mensuel',
         'f_una':'Paiement unique','f_da':'Paiement unique, à partir de',
         'prezzi':{'sito_mese':'24,80 € / mois','sito_una':'350 €','seo_una':'150 €',
                   'app_mese':'50 € / mois','app_una':'dès 750 €','gest_da':'dès 1 500 €'},
         'upd':'Tarifs mis à jour le <time datetime="2026-09-20">20 septembre 2026</time>.'}},
 'es':{
  'title':'Precios 2026: páginas web, web apps y ERP | Danova Tech',
  'h1':'Precios de páginas web, apps y ERP:<br><span class="grad">escritos, no susurrados.</span>',
  'ogtitle':'Cuánto cuesta una página web, una app o un ERP: los precios de Danova Tech',
  'faq_h2':'Preguntas frecuentes sobre precios',
  'tab':{'eyebrow':'En resumen','h2':'Los precios <span class="grad">en una tabla</span>',
         'caption':'Precios de Danova Tech para páginas web, aplicaciones web y software de gestión, IVA incluido',
         'cols':['Servicio','Modalidad','Precio (IVA incluido)','Qué incluye'],
         'f_mese_min':'Cuota mensual, permanencia 24 meses','f_mese':'Cuota mensual',
         'f_una':'Pago único','f_da':'Pago único, desde',
         'prezzi':{'sito_mese':'24,80 € / mes','sito_una':'350 €','seo_una':'150 €',
                   'app_mese':'50 € / mes','app_una':'desde 750 €','gest_da':'desde 1.500 €'},
         'upd':'Precios actualizados el <time datetime="2026-09-20">20 de septiembre de 2026</time>.'}},
}
for _l, _v in _X.items():
    D[_l].update(_v)
    D[_l]['ogimg'] = '/assets/img/og-prezzi-%s.jpg' % _l
